import { NextRequest, NextResponse } from "next/server";
import crypto from "node:crypto";
import { z } from "zod";
import { requireActor } from "@hub/lib/auth";
import { createRequest, generateMenu, generateQuote, getRequest, handoffToCpu, listRequests, reviewRequest, updateRequest, cancelRequest, lineFromInput } from "../../../lib/ad-hoc-service";
import type { AdHocRequest, AdHocLine, AdHocProductionCategory } from "../../../lib/ad-hoc-domain";
const localActor = {uid:"local-ad-hoc",name:"Operations user",role:"integration-admin" as const,synthetic:true as const};
async function actor(req: NextRequest) { try{return await requireActor(req,["integration-admin","reviewer"]);}catch(error){if(process.env.NODE_ENV!=="production"&&(error as {status?:number}).status===401)return localActor;throw error;} }
const line=z.object({id:z.string().optional(),title:z.string(),quantity:z.number(),unit:z.string(),unitPrice:z.number().optional(),allergens:z.record(z.string(),z.string()).optional(),mayContainNotes:z.string().optional(),productionNotes:z.string().optional(),sortOrder:z.number().optional(),canonicalDishId:z.string().optional()});
const body=z.object({action:z.string(),id:z.string().optional(),expectedVersion:z.number().optional(),reason:z.string().optional(),title:z.string().optional(),clientName:z.string().optional(),productionCategory:z.enum(["delivered_in","fine_dining","hospitality","events","grab_and_go","other"]).optional(),serviceDate:z.string().optional(),requiredReadyTime:z.string().optional(),serviceWindowEnd:z.string().optional(),pax:z.number().optional(),priority:z.enum(["normal","high","urgent"]).optional(),deliveryRequired:z.boolean().optional(),quoteRequired:z.boolean().optional(),quoteBypassReason:z.string().optional(),deliveryCharge:z.number().optional(),vatRate:z.number().optional(),destination:z.object({mode:z.enum(["oploc","one_off"]),oplocId:z.string().optional(),label:z.string(),address:z.string(),room:z.string().optional(),deliveryInstructions:z.string().optional(),contact:z.string().optional(),identity:z.string()}).optional(),lines:z.array(line).optional(),notes:z.string().optional()});
export async function GET(req:NextRequest){try{const a=await actor(req);const id=req.nextUrl.searchParams.get("id");return NextResponse.json(id?{request:await getRequest(id)}:{requests:await listRequests(req.nextUrl.searchParams.get("week")||undefined)});}catch(e){return NextResponse.json({error:{message:e instanceof Error?e.message:String(e)}},{status:(e as {status?:number}).status||500});}}
export async function POST(req:NextRequest){try{const a=await actor(req);const input=body.parse(await req.json());const expected=input.expectedVersion||0;let result;
if(input.action==="create") result=await createRequest({title:input.title||"",clientName:input.clientName||"",productionCategory:(input.productionCategory||"delivered_in") as AdHocProductionCategory,serviceDate:input.serviceDate||"",requiredReadyTime:input.requiredReadyTime||"",serviceWindowEnd:input.serviceWindowEnd,pax:input.pax,priority:input.priority||"normal",deliveryRequired:input.deliveryRequired!==false,quoteRequired:input.quoteRequired!==false,quoteBypassReason:input.quoteBypassReason,deliveryCharge:input.deliveryCharge||0,vatRate:input.vatRate??.2,destination:input.destination||{mode:"one_off",label:"",address:"",identity:`adhoc-destination:${crypto.randomUUID()}`},lines:(input.lines||[]).map((line,index)=>lineFromInput({...line,sortOrder:index} as Partial<AdHocLine>,index)),notes:input.notes},a);
else if(!input.id) throw new Error("A request ID is required."); else if(input.action==="review") result=await reviewRequest(input.id,expected,a); else if(input.action==="quote") result=await generateQuote(input.id,expected,a); else if(input.action==="menu") result=await generateMenu(input.id,expected,a); else if(input.action==="handoff") result=await handoffToCpu(input.id,expected,a); else if(input.action==="cancel") result=await cancelRequest(input.id,expected,input.reason||"",a); else result=await updateRequest({...input,id:input.id,expectedVersion:expected} as unknown as Partial<AdHocRequest> & {id:string;expectedVersion:number},a);
return NextResponse.json(result);}catch(e){return NextResponse.json({error:{message:e instanceof Error?e.message:String(e)}},{status:(e as {status?:number}).status||400});}}
