import assert from "node:assert/strict";
import test from "node:test";
import { assertWorkflowCommand, isQuoteStale } from "../lib/booking-workflow";
import { productionOrderId } from "../lib/hospitality-booking-service";

const quote = { id: "quote:booking:test:r1", revision: 1, createdAt: "2026-07-30T12:00:00Z", createdBy: "actor", commercialVersion: 1, snapshot: {}, documentReference: "quote:booking:test:r1", stale: false };
test("review requires every structured manager check", () => { assert.doesNotThrow(() => assertWorkflowCommand({ lifecycleStatus: "New" }, { action: "review", checks: { commercialIntent: true, serviceTiming: true, deliveryContext: true, dietaryRequirements: true } })); assert.throws(() => assertWorkflowCommand({ lifecycleStatus: "New" }, { action: "review", checks: { commercialIntent: true, serviceTiming: false, deliveryContext: true, dietaryRequirements: true } })); });
test("approval requires the current non-stale quote revision", () => { const booking = { lifecycleStatus: "Quoted" as const, commercialVersion: 1, quoteState: { currentRevisionId: quote.id, revisions: [quote] } }; assert.doesNotThrow(() => assertWorkflowCommand(booking, { action: "approve", quoteRevisionId: quote.id })); assert.throws(() => assertWorkflowCommand(booking, { action: "approve", quoteRevisionId: "quote:old" })); assert.equal(isQuoteStale({ ...booking, commercialVersion: 2 }), true); });
test("completion and cancellation enforce lifecycle boundaries", () => { assert.throws(() => assertWorkflowCommand({ lifecycleStatus: "Reviewed" as const }, { action: "complete" })); assert.throws(() => assertWorkflowCommand({ lifecycleStatus: "Completed" as const }, { action: "cancel", reason: "x" })); });
test("production-order identity is deterministic for idempotent hand-off", () => { assert.equal(productionOrderId("booking:mnk:one"), productionOrderId("booking:mnk:one")); });
test("an amendment can reopen a completed or cancelled Booking while retaining commercial history", () => { const patch = { client: { name: "Host", email: "host@example.test", companyName: "Client" }, service: { eventDate: "2026-08-01", startTime: "12:00", guestCount: 10 }, order: { items: [{ itemId: "lunch", unitPrice: 9, quantity: 10 }] }, deliveryChargeRequired: true }; assert.doesNotThrow(() => assertWorkflowCommand({ lifecycleStatus: "Quoted" }, { action: "amend", reason: "Client changed delivery room.", patch })); assert.doesNotThrow(() => assertWorkflowCommand({ lifecycleStatus: "Completed" }, { action: "amend", reason: "Client amended the booking after completion.", patch })); assert.doesNotThrow(() => assertWorkflowCommand({ lifecycleStatus: "Cancelled" }, { action: "amend", reason: "Client reinstated the booking.", patch })); });
