import assert from "node:assert/strict";
import test from "node:test";
import crypto from "node:crypto";
import { db } from "../lib/firebase-admin";
import { bookingEmailStore, replayBookingEmail } from "../lib/booking-email-firestore";
import { runBookingEmailWorker } from "../lib/booking-email-outbox";
import { bookingNotificationRecord } from "../lib/booking-notifications";
import { buildMnkCanonicalBooking, executeBookingWorkflow, ingestMnkBooking, type CanonicalBooking } from "../lib/hospitality-booking-service";
import { createProductionFromApprovedBooking } from "../lib/production-domain";
import { stableDocumentId } from "../lib/canonical-editor";
import type { Actor } from "../lib/auth";
import type { CanonicalRecord } from "../lib/types";
import { GmailSendFailure, type BookingSender } from "../lib/booking-email-delivery";

test("canonical transitions atomically queue distinct lifecycle obligations; retries preserve earlier payloads", async () => {
  assert.equal(process.env.FIKA_RUNTIME_MODE || "local", "local");
  const key = `email-test-${crypto.randomUUID()}`;
  const now = new Date().toISOString();
  const menu = { canonicalId: `hospitality-menu-item:${key}`, dataHash: "test", entityType: "Hospitality Menu Item", lifecycleStatus: "published", record: { lifecycleState: "active", name: "Test lunch", unitPrice: 12, providerMappings: [{ provider: "mnk-booking-platform", sourceItemId: key }] } } as CanonicalRecord;
  const payload = { bookingId: key, siteId: `oploc:${key}`, site: key, submittedAt: now, client: { name: "Test Host", companyName: "Test", email: "host@example.test" }, event: { eventDate: "2026-10-19", startTime: "12:00", guestCount: 3 }, order: { items: [{ itemId: key, unitPrice: .01, quantity: 3, lineTotal: .01 }], netTotal: .01 } };
  const mappingRef = db.collection("integrationHubSourceMappings").doc(key);
  const oploc = `oploc:${key}`;
  await db.collection("integrationHubCanonical").doc(stableDocumentId(menu.canonicalId)).set(menu);
  await db.collection("integrationHubCanonical").doc(stableDocumentId(oploc)).set({ canonicalId: oploc, entityType: "OPLOC", lifecycleStatus: "published", publicationStatus: "published", record: { lifecycleState: "active" } });
  const actor = { uid: "test-multi-site-manager", role: "integration-admin" } as Actor;
  await mappingRef.set({ sourceIdentifier: key, sourceEntityType: "provider-location", mappingStatus: "confirmed", oplocId: oploc });
  const ingested = await ingestMnkBooking(payload);
  let booking: CanonicalBooking = ingested.booking;
  assert.equal(ingested.created, true);
  assert.equal(booking.order.netTotal, 36);
  assert.equal((await ingestMnkBooking(payload)).created, false);
  assert.equal((await db.collection("fikaBookingNotifications").where("bookingId", "==", booking.canonicalId).limit(10).get()).size, 1);
  const submitted = bookingNotificationRecord(booking, "submitted", booking.version, now);
  assert.equal((await db.collection("fikaBookingNotifications").doc(submitted.notificationId).get()).exists, true);
  const bytes = JSON.stringify((await db.collection("fikaBookingNotifications").doc(submitted.notificationId).get()).data());
  const quoted = { ...booking, lifecycleStatus: "Quoted", quoteState: { currentRevisionId: `quote:${key}`, revisions: [{ id: `quote:${key}`, revision: 1, createdAt: now, createdBy: actor.uid, commercialVersion: 1, snapshot: {}, documentReference: "mock", stale: false, pdfStatus: "saved", driveFileId: "mock-drive" }] } };
  await db.collection("fikaBookings").doc(booking.canonicalId).set(quoted);
  const handoff = await createProductionFromApprovedBooking(actor, booking.canonicalId, key);
  booking = (await db.collection("fikaBookings").doc(booking.canonicalId).get()).data() as CanonicalBooking;
  const confirmation = await db.collection("fikaBookingNotifications").doc(bookingNotificationRecord(booking, "confirmed", booking.version, booking.updatedAt).notificationId).get();
  assert.equal(confirmation.exists, true); assert.equal(confirmation.data()?.bookingVersion, booking.version);
  assert.equal(confirmation.data()?.oplocId, oploc);
  assert.equal(confirmation.data()?.outboxStatus, "pending");
  const amend = await executeBookingWorkflow(actor, booking.canonicalId, booking.version, { action: "amend", reason: "Test update", patch: { client: booking.client, service: { ...payload.event }, order: { ...booking.order, items: booking.order.items }, deliveryChargeRequired: true } });
  booking = amend.booking;
  assert.equal((await db.collection("fikaBookingNotifications").doc(bookingNotificationRecord(booking, "amended", booking.version, booking.updatedAt).notificationId).get()).exists, true);
  const cancel = await executeBookingWorkflow(actor, booking.canonicalId, booking.version, { action: "cancel", reason: "Test cancellation", notify: true });
  booking = cancel.booking;
  assert.equal((await db.collection("fikaBookingNotifications").doc(bookingNotificationRecord(booking, "cancelled", booking.version, booking.updatedAt).notificationId).get()).exists, true);
  await assert.rejects(executeBookingWorkflow(actor, booking.canonicalId, booking.version - 1, { action: "cancel", reason: "Exact retry", notify: true }));
  assert.equal(JSON.stringify((await db.collection("fikaBookingNotifications").doc(submitted.notificationId).get()).data()), bytes);
  assert.equal((await db.collection("fikaBookingNotifications").where("bookingId", "==", booking.canonicalId).limit(10).get()).size, 4);
  assert.equal(await bookingEmailStore.arm(confirmation.id, "wrong-claim", now), false);
  assert.ok(handoff.order.canonicalId);
  await mappingRef.delete();
});

test("Firestore worker CAS prevents duplicate sends, suppresses source races, and audits manual dead-letter recovery", async () => {
  assert.equal(process.env.FIKA_RUNTIME_MODE || "local", "local");
  const key = `email-worker-${crypto.randomUUID()}`;
  const booking = { canonicalId: `booking:${key}`, version: 4, commercialVersion: 2, lifecycleStatus: "Sent to CPU", service: { oplocId: `oploc:${key}`, portalSiteId: "mnk", eventDate: "2026-10-19", startTime: "12:00" }, source: { sourceBookingId: key }, client: { name: "Host", email: "host@example.test" }, order: { items: [], netTotal: 12, vatTotal: 0, grossTotal: 12 }, updatedAt: "2026-10-01T00:00:00Z" } as unknown as CanonicalBooking;
  const source = db.collection("fikaBookings").doc(booking.canonicalId);
  await source.set(booking);
  const message = bookingNotificationRecord(booking, "confirmed", 4, booking.updatedAt);
  const ref = db.collection("fikaBookingNotifications").doc(message.notificationId);
  await ref.create(message);
  // Scope candidate lookup to this fixture while exercising the actual CAS transaction adapter.
  const store = { ...bookingEmailStore, async candidates() { return [ref.id]; } };
  const sender: BookingSender = { from: "mnk@example.test", replyTo: "mnk@example.test", displayName: "MNK Catering", authenticatedAccount: "sender@example.test", verifiedSendAs: true, enabled: ["confirmed"] };
  let sends = 0;
  const deps = { sender: () => sender, token: async () => "mock", send: async () => { sends++; return "receipt"; } };
  await Promise.all([runBookingEmailWorker(store, 25, deps), runBookingEmailWorker(store, 25, deps)]);
  await runBookingEmailWorker(store, 25, deps);
  assert.equal(sends, 1); assert.equal((await ref.get()).data()?.gmailMessageId, "receipt");
  assert.equal((await ref.get()).data()?.senderEvidence?.from, sender.from);
  assert.equal((await ref.get()).data()?.senderEvidence?.authenticatedAccount, sender.authenticatedAccount);
  assert.equal((await ref.get()).data()?.nextEligibleAt, undefined);
  const saved = JSON.stringify((await ref.get()).data());
  await assert.rejects(replayBookingEmail(ref.id, "Test rejected replay", "Delivered receipt verified"));
  assert.equal(JSON.stringify((await ref.get()).data()), saved);
  const amended = bookingNotificationRecord({ ...booking, version: 5 }, "amended", 5, booking.updatedAt);
  const amendedRef = db.collection("fikaBookingNotifications").doc(amended.notificationId);
  await source.set({ ...booking, version: 5 }); await amendedRef.create(amended);
  const raceStore = { ...bookingEmailStore, async candidates() { return [amendedRef.id]; } };
  await runBookingEmailWorker(raceStore, 25, { ...deps, token: async () => { await source.update({ version: 6 }); return "mock"; } });
  assert.equal(sends, 1); assert.equal((await amendedRef.get()).data()?.outboxStatus, "dead-letter");
  await source.update({ version: 5 });
  await replayBookingEmail(amendedRef.id, "Pre-send source race verified", "Attempt log has no send barrier");
  await runBookingEmailWorker(raceStore, 25, { ...deps, send: async () => { sends++; throw new GmailSendFailure(false, false, "Unknown Gmail acceptance"); } });
  assert.equal((await amendedRef.get()).data()?.outboxStatus, "dead-letter");
  await runBookingEmailWorker(raceStore, 25, deps); assert.equal(sends, 2);
  assert.equal((await amendedRef.collection("recovery").get()).size, 1);
});
