import type { HospitalityMenuCatalogue, HospitalityMenuItem } from "./hospitality-menu-catalogue";

const sourceRows: Array<[string, string, string, number, string]> = [
  ["bloom-filter-coffee", "Bloom Filter Coffee", "Drinks", 3, "Per serving"],
  ["specialty-tea-coffee", "Specialty Tea & Coffee", "Drinks", 3.5, "Per serving"],
  ["belu-water", "Belu Water Bottle", "Drinks", 3.95, "750ml still or sparkling"],
  ["canned-drinks", "Selection of Canned Drinks", "Drinks", 1.75, "Per can"],
  ["fresh-juice", "Fresh Squeezed & Pressed Juice", "Drinks", 3, "250ml bottle"],
  ["smoothie", "Freshly Made Smoothie", "Drinks", 12, "1L bottle"],
  ["cookie-box", "Freshly Baked Cookie Box", "Sweet treats", 40, "24 mixed cookies"],
  ["tray-bake-box", "Tray Bake Box", "Sweet treats", 75, "24 pieces / 48 bites"],
  ["exotic-fruit-box", "Exotic Fruit Box", "Sweet treats", 52.5, "Serves 20"],
  ["mini-pastries", "Mini Pastries", "Breakfast", 36, "Feeds 12 people"],
  ["large-pastries", "Freshly Baked Large Pastries", "Breakfast", 42, "Box of 12"],
  ["filled-savoury-croissant", "Filled Savoury Croissant", "Breakfast", 60, "Box of 12"],
  ["vegan-savoury-croissant", "Vegan Savoury Croissant", "Breakfast", 65, "Box of 12"],
  ["bagel-box", "Bagel Box", "Breakfast", 72, "12 bagels cut in half"],
  ["power-breakfast", "Healthy Plant Power Breakfast", "Breakfast", 22, "Per person"],
  ["breakfast-pots", "Breakfast Pots", "Breakfast", 3.95, "Per pot; minimum 12 per item"],
  ["salad-protein-platter", "Salad & Protein Lunch Platter", "Lunch", 14, "Per person"],
  ["deli-sandwich-lunch", "Deli Style Sandwich Lunch", "Lunch", 9, "3 pieces per person"],
  ["individual-boxed-lunch", "Individual Boxed Lunch", "Lunch", 14.95, "Per person"],
  ["rice-paper-rolls", "Freshly Wrapped Rice Paper Rolls", "Lunch", 45, "12 wraps per platter; feeds 3"],
  ["charcuterie-box", "Grazing Box Charcuterie", "Lunch Boxes", 75, "Feeds 10"],
  ["picnic-box", "Picnic Box", "Lunch Boxes", 75, "Feeds 10"],
  ["cheese-box", "Cheese Box", "Lunch Boxes", 75, "Feeds 10"],
  ["vegan-box", "Vegan Box", "Lunch Boxes", 60, "Feeds 10"],
  ["salad-boxes", "Salad Boxes", "Salads & Sushi", 25, "Feeds 8 as a side"],
  ["deluxe-sushi-box", "Deluxe Sushi Box", "Salads & Sushi", 160, "84 pieces; feeds 8–12"],
  ["vegan-sushi-box", "Vegan Sushi Box", "Salads & Sushi", 120, "72 pieces; feeds 8–12"],
  ["fika-glow-bowl", "Fika Glow Bowl", "Bowl & Finger Food", 12.95, "Per person"],
  ["picnic-grazing-table", "Picnic Grazing Table", "Bowl & Finger Food", 24.95, "Per person; minimum 20"],
  ["grazing-sweet-table", "Grazing Sweet Table", "Bowl & Finger Food", 18.95, "Per person; minimum 20"],
  ["grazing-cups", "Grazing Cups", "Bowl & Finger Food", 12.95, "Per cup; minimum 30"],
  ["finger-food", "Finger Food", "Finger Food", 3.95, "Per piece; minimum 4 per person"],
  ["bowl-food", "Bowl Food", "Bowl & Finger Food", 30, "Three bowls per person"],
  ["hot-fork-buffet", "Hot Fork Buffet", "Bowl & Finger Food", 20, "Menu on request"],
  ["fika-canapes", "Fika Canapes", "Canapes", 30, "Six items per person; minimum 20"],
  ["corporate-dining", "Fika Corporate Dining", "Dining", 45, "Per person; minimum 12"],
  ["themed-bespoke-events", "Themed Bespoke Events", "Bespoke Events", 25, "From per person; minimum 50"],
];

const items: HospitalityMenuItem[] = sourceRows.map(([sourceItemId, name, category, unitPrice, servingInfo], index) => ({
  canonicalId: `hospitality-menu-item:cfc:${sourceItemId}`,
  source: { provider: "cfc-hospitality-brochure", sourcePath: "CFC_Hospitality Brochure_2026.pptx", sourceItemId },
  name,
  description: "Published from the CFC hospitality brochure source; confirm availability and dietary detail during review.",
  category,
  pricing: { unitPrice, currency: "GBP", basis: "per person or stated serving basis", servingInfo, vatRate: null },
  orderingConstraints: { minimumQuantity: sourceItemId === "rice-paper-rolls" ? 3 : 1, minimumGuests: null, noticeRequiredDays: category === "Bespoke Events" || category === "Dining" ? 7 : 3, serves: null, suggestionType: null, suggestionLabel: servingInfo, suggestionUnit: "serving" },
  optionGroups: [],
  dietaryInformation: [],
  allergenInformation: [],
  lifecycleState: "active",
  sortOrder: index,
}));

export const localCfcMenuCatalogue: HospitalityMenuCatalogue = {
  schemaVersion: "fika.hospitality-menu-catalogue.v1",
  generatedAt: "2026-08-05T00:00:00.000Z",
  source: { path: "CFC_Hospitality Brochure_2026.pptx", itemCount: items.length },
  categories: [...new Set(items.map((item) => item.category))].map((name) => ({ canonicalId: `hospitality-menu-category:cfc:${name.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`, name })),
  items,
  validationReport: { sourceItemCount: items.length, generatedItemCount: items.length, missingCanonicalFields: [{ field: "dietaryInformation", reason: "Not supplied as structured data by the brochure source" }, { field: "allergenInformation", reason: "Not supplied as structured data by the brochure source" }] },
};
