"use client";

import { useEffect, useMemo, useState } from "react";
import type { ProductionOrder } from "@hub/lib/production-domain";
import AllergenReviewMatrix from "../ui/AllergenReviewMatrix";
import { SignatureModal } from "../ui/LianaOrderDetail";
import { buildAllergenReviewRows, destination, orderDate } from "../../lib/production-day";
import "./page.css";

function formatDate(date: string) { return new Date(`${date}T12:00:00`).toLocaleDateString("en-GB", { weekday: "long", day: "numeric", month: "long" }); }

export default function CpuAllergenReviewPage() {
  const [orders, setOrders] = useState<ProductionOrder[]>([]); const [date, setDate] = useState(""); const [site, setSite] = useState(""); const [review, setReview] = useState("all"); const [error, setError] = useState(""); const [signing, setSigning] = useState<{ orderId: string; role: "production_chef" | "head_chef_site_manager" }>(); const [signable, setSignable] = useState<string[]>([]); const [signatureMessage, setSignatureMessage] = useState("");
  const load = async () => { const response = await fetch("/api/production?scope=all", { cache: "no-store" }); const body = await response.json(); if (!response.ok) { setError(body.error?.message || "Could not load allergen review."); return; } setOrders((body.orders || []).filter((order: ProductionOrder) => order.origin === "menu_planning")); };
  useEffect(() => { const params = new URLSearchParams(window.location.search); setDate(params.get("date") || new Date().toISOString().slice(0, 10)); void load(); }, []);
  const dayOrders = orders.filter(order => (!date || orderDate(order) === date) && (!site || order.destinationOplocId === site));
  const rows = useMemo(() => buildAllergenReviewRows(dayOrders), [dayOrders]);
  const visibleRows = rows.filter(row => review === "all" || (review === "attention" ? row.attention : review === "reviewed" ? row.reviewed && !row.attention : !row.reviewed && !row.attention));
  const sites = [...new Map(dayOrders.map(order => [order.destinationOplocId || destination(order), destination(order)])).entries()];
  const approved = rows.filter(row => row.snapshot).length; const reviewed = rows.filter(row => row.reviewed && !row.attention).length; const attention = rows.filter(row => row.attention).length;
  const sign = async (printedName: string, signatureDataUrl: string) => { if (!signing) return; const response = await fetch("/api/production-plan", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "sign-matrix", orderId: signing.orderId, role: signing.role, printedName, signatureDataUrl, attestation: "I confirm that I reviewed the CPU allergen matrix and the recorded evidence is accurate to the best of my knowledge.", actor: "production-chef" }) }); const body = await response.json(); setSignatureMessage(response.ok ? "Signature recorded in the CPU allergen review audit." : body.error?.message || "The matrix could not be signed."); setSigning(undefined); };
  return <main className="cpu-allergen-page"><header className="cpu-allergen-page-header"><div><a href="/">← CPU Production</a><small>CPU · Delivered-In lunch</small><h1>ALLERGEN REVIEW</h1><h2>{date ? formatDate(date) : "Select a production day"}</h2><p>{rows.length} dishes · {approved} approved · {reviewed ? "CPU reviewed" : "CPU review pending"}</p></div><div className="cpu-allergen-page-actions"><a href={`/?date=${date}`}>Back to production</a></div></header><section className="cpu-allergen-page-content"><div className="cpu-allergen-filters" aria-label="Allergen review filters"><label>Date<input type="date" value={date} onChange={event => setDate(event.target.value)} /></label><label>Site<select value={site} onChange={event => setSite(event.target.value)}><option value="">All sites</option>{sites.map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label><label>Review status<select value={review} onChange={event => setReview(event.target.value)}><option value="all">All statuses</option><option value="attention">Needs attention</option><option value="reviewed">CPU reviewed</option><option value="pending">Review pending</option></select></label></div><div className="cpu-allergen-page-summary"><span><strong>{rows.length}</strong> Delivered-In dishes</span><span><strong>{approved}</strong> approved</span><span className={attention ? "attention" : ""}><strong>{attention}</strong> require attention</span><span><strong>{reviewed}</strong> CPU reviewed</span></div>{error && <p role="alert">{error}</p>}<AllergenReviewMatrix rows={visibleRows} orders={dayOrders} onSaved={load} onPlanned={setSignable} /><section className="cpu-allergen-signatures"><div><small>CPU chef sign-off</small><h3>Sign the production-day allergen review</h3><p>Signatures are stored in the existing CPU production-plan audit record.</p></div>{signable.map(orderId => <div className="cpu-allergen-signature-row" key={orderId}><span>{orders.find(order => order.canonicalId === orderId)?.destinationLabel || orderId}</span><button type="button" onClick={() => setSigning({ orderId, role: "production_chef" })}>Sign as production chef</button><button type="button" onClick={() => setSigning({ orderId, role: "head_chef_site_manager" })}>Sign as head chef / site manager</button></div>)}{signatureMessage && <p role="status">{signatureMessage}</p>}</section></section>{signing && <SignatureModal role={signing.role} onCancel={() => setSigning(undefined)} onConfirm={(name, dataUrl) => void sign(name, dataUrl)} />}</main>;
}
