"use client";
import { useEffect, useState } from "react";
import { AlertTriangle, History } from "lucide-react";
import type { HubState } from "@/lib/types";

export default function ActivityAudit({ activity, refreshSession }: { activity: HubState["activity"]; refreshSession: () => Promise<boolean> }) {
  const [events, setEvents] = useState<Record<string, unknown>[]>([]), [error, setError] = useState(""), [exact, setExact] = useState(false);
  useEffect(() => { void (async () => { try { const request = () => fetch("/api/audit?limit=100", { cache: "no-store" }); let response = await request(); if (response.status === 401 && await refreshSession()) response = await request(); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message || "Governance audit could not be loaded."); setEvents(body.events); setExact(Boolean(body.exactDiffVisible)); } catch (cause) { setError((cause as Error).message); } })(); }, [refreshSession]);
  return <><section className="heading"><small>Immutable activity</small><h2>Every decision leaves evidence.</h2><p>Provider operations and governed canonical decisions remain separately traceable. Exact field changes are visible only to authorised administrators.</p></section>{error && <div className="error"><AlertTriangle />{error}</div>}<section className="panel"><h3>{events.length} governed audit events</h3><div className="list">{events.map(event => <article key={String(event.id)}><b>{String(event.action || "Governed event")}</b><span>{String(event.entityReference || "—")}</span><small>{format(event.timestamp)} · actor {String(event.actorName || event.actorId || "unknown")}</small>{exact && Boolean(event.reason) && <small>Reason: {String(event.reason)}</small>}{exact && Boolean(event.exactDiff) && <details><summary>Exact field diff</summary><pre>{JSON.stringify(event.exactDiff, null, 2)}</pre></details>}</article>)}</div>{!events.length && <div className="empty"><History /><b>No governed canonical events yet.</b></div>}</section><section className="panel"><h3>{activity.length} operational activity entries</h3><div className="list">{activity.slice().reverse().map(item => <article key={item.activityId}><b>{item.action}</b><span>{item.summary}</span><small>{format(item.timestamp)} · {item.actorName} · {item.source}</small></article>)}</div></section></>;
}
function format(value: unknown) { const date = new Date(String(value || "")); return Number.isNaN(date.valueOf()) ? "—" : date.toLocaleString(); }
