"use client";
import { useEffect, useState } from "react";
import type { CanonicalBooking } from "@/lib/hospitality-booking-service";

const statuses = ["New", "Reviewed", "Quoted", "Approved", "Completed", "Cancelled"] as const;
export default function HospitalityBookings() {
  const [bookings, setBookings] = useState<CanonicalBooking[]>([]); const [selected, setSelected] = useState<CanonicalBooking | null>(null); const [error, setError] = useState("");
  const load = async () => { const r = await fetch("/api/hospitality-bookings", { cache: "no-store" }); const j = await r.json(); if (!r.ok) throw Error(j.error?.message || "Could not load canonical Bookings."); setBookings(j.bookings); setSelected(current => j.bookings.find((booking: CanonicalBooking) => booking.canonicalId === current?.canonicalId) || null); };
  useEffect(() => { void load().catch(error => setError(error.message)); }, []);
  const change = async (status: typeof statuses[number]) => { if (!selected) return; const reason = window.prompt(`Reason for marking this Booking ${status}:`); if (!reason) return; const r = await fetch("/api/hospitality-bookings", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ canonicalId: selected.canonicalId, expectedVersion: selected.version, status, reason }) }); const j = await r.json(); if (!r.ok) { setError(j.error?.message || "Booking action failed."); return; } setSelected(j); await load(); };
  return <section className="panel"><div className="page-heading"><small>Canonical operational workspace</small><h2>Hospitality Bookings</h2><p>MNK pilot Bookings are read from the Canon. The legacy dashboard and its Sheets workflow remain an untouched compatibility path.</p></div>{error && <p className="error">{error}</p>}<div className="booking-workspace"><div className="booking-list"><h3>Upcoming and recent</h3>{bookings.length ? bookings.map(booking => <button key={booking.canonicalId} className={selected?.canonicalId === booking.canonicalId ? "selected" : ""} onClick={() => setSelected(booking)}><b>{booking.client.companyName}</b><span>{booking.service.eventDate} · {booking.service.startTime} · {booking.service.portalSiteLabel || "Unresolved portal location"}</span><small>{booking.lifecycleStatus} · £{booking.order.grossTotal.toFixed(2)} · dietary: {Object.keys(booking.dietaries).length ? "recorded" : "none"}</small></button>) : <p className="empty">No canonical MNK Bookings have been ingested yet.</p>}</div><div className="booking-detail">{selected ? <><h3>{selected.client.companyName}</h3><p><b>Contact:</b> {selected.client.name} · {selected.client.email}</p><p><b>Service:</b> {selected.service.eventDate} {selected.service.startTime} · {selected.service.guestCount} guests</p><p><b>Source:</b> MNK portal booking {selected.source.sourceBookingId}</p><h4>Order snapshot</h4><ul>{selected.order.items.map(item => <li key={`${item.itemId}-${item.lineTotal}`}>{item.quantity} × {item.itemName || item.itemId} — £{item.lineTotal.toFixed(2)}</li>)}</ul><h4>Dietary and notes</h4><pre>{JSON.stringify({ dietaries: selected.dietaries, notes: selected.notes || "" }, null, 2)}</pre><h4>Authorised workflow</h4><div className="actions">{statuses.filter(status => status !== selected.lifecycleStatus).map(status => <button key={status} onClick={() => void change(status)}>{status}</button>)}</div><details className="technical-details"><summary>Source and audit trail</summary><pre>{JSON.stringify({ source: selected.source, statusHistory: selected.statusHistory, audit: selected.audit }, null, 2)}</pre></details></> : <p className="empty">Select a canonical Booking to review its customer intent, commercial snapshot and audit trail.</p>}</div></div></section>;
}
