"use client";

import { Activity, ArrowRight, Bell, CalendarDays, ChartNoAxesCombined, ChefHat, ChevronDown, Clock3, Database, FileText, House, LayoutGrid, LogOut, Plus, Route, Settings, ShieldCheck, Star, Truck, UsersRound, type LucideIcon } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { getFikaFirebaseAuth, getFikaGoogleProvider, hasFikaFirebaseClientConfig } from "@/lib/firebase-client";
import { getRedirectResult, signInWithPopup, signInWithRedirect, signOut } from "firebase/auth";
import { validateReturnTo } from "@/lib/safe-return-to";
import { launcherGreeting } from "@/lib/launcher-greeting";
import styles from "./launcher.module.css";

type LauncherData = { principal: { displayName: string; email?: string; identityKind?: "person" | "operational"; firstName?: string }; applications: { appId: string; label: string; purpose: string; href: string }[]; canAdministerAuthmod: boolean };
type State = "loading" | "login" | "launcher" | "denied";
type AppDefinition = { appId: string; label: string; purpose: string; section: "operations" | "planning" | "administration"; icon: LucideIcon; accent: string };
const localRoles = [["integration-admin", "Administrator"], ["reviewer", "Reviewer"], ["viewer", "Viewer"]] as const;
const appDefinitions: AppDefinition[] = [
  { appId: "cpu-production", label: "CPU Production", purpose: "Production planning and kitchen workflows", section: "operations", icon: ChefHat, accent: "purple" },
  { appId: "delivered-in", label: "Delivered-In", purpose: "Delivered-in production workflow", section: "operations", icon: Truck, accent: "blue" },
  { appId: "logistics", label: "Logistics", purpose: "Deliveries, collections and dispatch", section: "operations", icon: Route, accent: "green" },
  { appId: "menu-planning", label: "Menu Planning", purpose: "Plan and publish operational menus", section: "planning", icon: CalendarDays, accent: "plum" },
  { appId: "hospitality-booking", label: "Hospitality Booking", purpose: "Hospitality booking management", section: "planning", icon: UsersRound, accent: "pink" },
  { appId: "ad-hoc-production", label: "Ad-Hoc Production", purpose: "One-off production requirements", section: "planning", icon: Plus, accent: "orange" },
  { appId: "integration-hub", label: "Integration Hub", purpose: "Data governance and integrations", section: "administration", icon: Database, accent: "purple" },
  { appId: "authmod", label: "Access Administration", purpose: "AUTHMOD access control", section: "administration", icon: ShieldCheck, accent: "purple" },
];
const favourites = ["cpu-production", "menu-planning", "delivered-in", "logistics"];
const navItems: { icon: LucideIcon; label: string; active: boolean }[] = [[House, "Home", true], [LayoutGrid, "My Apps", false], [ChartNoAxesCombined, "Activity", false], [FileText, "Reports", false], [Bell, "Alerts", false], [Settings, "Settings", false]].map(([icon, label, active]) => ({ icon: icon as LucideIcon, label: label as string, active: active as boolean }));

function today() { return new Intl.DateTimeFormat("en-GB", { weekday: "long", day: "numeric", month: "long", year: "numeric" }).format(new Date()); }

export default function Launcher() {
  const [state, setState] = useState<State>("loading"); const [data, setData] = useState<LauncherData | null>(null); const [local, setLocal] = useState<boolean | null>(null); const [localEmulatorAvailable, setLocalEmulatorAvailable] = useState(false); const [googleWorkspaceAvailable, setGoogleWorkspaceAvailable] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [returnTo, setReturnTo] = useState("/"); const firebaseConfigured = hasFikaFirebaseClientConfig();
  async function load() { try { const runtime = await fetch("/api/auth/runtime", { cache: "no-store" }); if (runtime.ok) { const config = await runtime.json() as { local?: boolean; localEmulatorAvailable?: boolean; googleWorkspaceAvailable?: boolean }; setLocal(config.local === true); setLocalEmulatorAvailable(config.localEmulatorAvailable === true); setGoogleWorkspaceAvailable(config.googleWorkspaceAvailable === true); } const session = await fetch("/api/auth/session", { cache: "no-store" }); if (session.status === 401) { setState("login"); return; } if (session.status === 403) { setState("denied"); setError("Your FIKA OS access is currently inactive or needs administrator review."); return; } if (!session.ok) throw new Error("FIKA OS could not load your session."); const launcher = await fetch("/api/launcher", { cache: "no-store" }); if (launcher.status === 401) { setState("login"); return; } if (launcher.status === 403) { setState("denied"); setError("Your FIKA OS access is currently inactive or needs administrator review."); return; } if (!launcher.ok) throw new Error("FIKA OS could not load your applications."); setData(await launcher.json()); setState("launcher"); } catch (cause) { setError((cause as Error).message); setState("login"); } }
  useEffect(() => { let destination = "/"; try { destination = validateReturnTo(new URLSearchParams(window.location.search).get("returnTo")); } catch { /* Invalid destinations fall back to the launcher. */ } setReturnTo(destination); void load(); void (async () => { try { const authInstance = getFikaFirebaseAuth(); const provider = getFikaGoogleProvider(); provider.setCustomParameters({ hd: "fikacatering.com" }); const result = await getRedirectResult(authInstance); if (result) { setBusy(true); await exchange(result.user, authInstance); } } catch { /* Missing client config is expected for local fixture mode. */ } finally { setBusy(false); } })(); }, []);
  async function exchange(user: { getIdToken(): Promise<string> }, authInstance: ReturnType<typeof getFikaFirebaseAuth>) { const idToken = await user.getIdToken(); const csrfResponse = await fetch("/api/auth/csrf", { cache: "no-store", credentials: "include" }); const csrf = await csrfResponse.json() as { csrfToken: string }; const response = await fetch("/api/auth/session", { method: "POST", headers: { "content-type": "application/json", origin: window.location.origin }, credentials: "include", body: JSON.stringify({ idToken, csrfToken: csrf.csrfToken }) }); await signOut(authInstance); if (!response.ok) { const body = await response.json().catch(() => ({})); const code = body.error?.code; if (code === "FIKA_EMAIL_NOT_ELIGIBLE") throw new Error("This Google account cannot access FIKA OS. Use your FIKA Workspace account."); if (code === "AUTHMOD_IDENTITY_NOT_FOUND") throw new Error("Your FIKA OS account has not been set up yet. Contact an administrator."); if (code === "AUTHMOD_IDENTITY_INACTIVE") throw new Error("Your FIKA OS access is currently inactive."); if (code === "AUTHMOD_EMAIL_IDENTITY_CONFLICT" || code === "AUTHMOD_EXTERNAL_IDENTITY_CONFLICT") throw new Error("Your FIKA OS account needs administrator review before you can sign in."); throw new Error("FIKA OS could not complete sign-in. Try again."); } window.location.assign(returnTo); }
  async function googleSignIn() { if (!firebaseConfigured || !googleWorkspaceAvailable) { setError(local ? "Google Workspace sign-in is not configured for this local runtime. Use a local emulator fixture or configure cloud Firebase Auth." : "FIKA OS Google sign-in is not configured. Contact an administrator."); return; } setBusy(true); setError(""); try { const authInstance = getFikaFirebaseAuth(); const provider = getFikaGoogleProvider(); provider.setCustomParameters({ hd: "fikacatering.com" }); const result = await signInWithPopup(authInstance, provider); await exchange(result.user, authInstance); } catch (cause) { const code = (cause as { code?: string }).code; if (code === "auth/popup-closed-by-user") return; if (code === "auth/popup-blocked" || code === "auth/operation-not-supported-in-this-environment") { try { await signInWithRedirect(getFikaFirebaseAuth(), getFikaGoogleProvider()); return; } catch { /* handled below */ } } setError((cause as Error).message.includes("FIKA") ? (cause as Error).message : "FIKA OS could not complete sign-in. Try again."); } finally { setBusy(false); } }
  async function localSignIn(role: string) { setBusy(true); setError(""); try { const response = await fetch("/api/auth/local-session", { method: "POST", headers: { "content-type": "application/json", origin: window.location.origin }, credentials: "include", body: JSON.stringify({ role }) }); if (!response.ok) throw new Error("Local development sign-in is unavailable."); window.location.assign(returnTo); } catch (cause) { setError((cause as Error).message); } finally { setBusy(false); } }
  async function logout() { await fetch("/api/auth/session", { method: "DELETE", credentials: "include" }); setData(null); setState("login"); }
  if (state === "loading") return <main className={styles.page}><div className={styles.loading}>Loading FIKA OS…</div></main>;
  if (state === "denied") return <main className={styles.page}><section className={styles.message}><ShieldCheck size={34} /><h1>FIKA OS</h1><p>{error}</p><a href="/">Return to sign in</a></section></main>;
  if (state === "login") return <main className={styles.page}><section className={styles.login}><div className={styles.logo}><ShieldCheck size={28} /><span>FIKA OS</span></div><h1>FIKA OS</h1><p>One place for FIKA operational systems.</p>{error && <div className={styles.error}>{error}</div>}{googleWorkspaceAvailable && firebaseConfigured && <><button className={styles.google} onClick={() => void googleSignIn()} disabled={busy}>Continue with Google <ArrowRight size={18} /></button><small>Use your FIKA Google Workspace account.</small></>}{local === true && localEmulatorAvailable && <div className={styles.local}><b>LOCAL DEVELOPMENT</b><span>Emulator sign-in</span>{localRoles.map(([role, label]) => <button key={role} onClick={() => void localSignIn(role)} disabled={busy}>{label}</button>)}</div>}</section></main>;
  return <LauncherHome data={data!} logout={logout} />;
}

function LauncherHome({ data, logout }: { data: LauncherData; logout: () => Promise<void> }) {
  const available = useMemo(() => new Map(data.applications.map(app => [app.appId, app])), [data.applications]);
  const availableApps = appDefinitions.filter(app => available.has(app.appId));
  const renderCard = (definition: AppDefinition) => { const app = definition.appId === "authmod" ? data.canAdministerAuthmod ? { href: "/authmod" } : undefined : available.get(definition.appId); const Icon = definition.icon; const content = <><div className={styles.cardIcon} data-accent={definition.accent}><Icon size={27} /></div><h3>{definition.label}</h3><p>{definition.purpose}</p><div className={styles.cardFooter}><span className={styles.cardRule} /><span className={styles.cardArrow}><ArrowRight size={19} /></span></div></>; return app ? <a className={styles.appCard} data-accent={definition.accent} href={app.href} target="_blank" rel="noopener noreferrer" key={definition.appId}>{content}</a> : <div className={`${styles.appCard} ${styles.appCardDisabled}`} data-accent={definition.accent} aria-disabled="true" key={definition.appId}>{content}</div>; };
  return <div className={styles.shell}><div className={styles.sidebar}><div className={styles.sideLogo}>FIKA<br />OS</div><nav aria-label="FIKA OS navigation">{navItems.map(({ icon: Icon, label, active }) => <button className={active ? styles.navActive : ""} key={label} type="button"><Icon size={19} /><span>{label}</span></button>)}</nav><div className={styles.botanical} aria-hidden="true"><span /><span /><span /></div><div className={styles.sideFooter}>FIKA OS<small>v0.1.0</small></div></div><section className={styles.workspace}><header className={styles.header}><div><h1>{launcherGreeting(data.principal)}</h1><p>{data.principal.identityKind === "operational" ? "Operational account" : "Integration Administrator"} · {data.principal.email || "admin@local.fika"}</p></div><div className={styles.headerTools}><div className={styles.date}><CalendarDays size={17} />{today()}</div><details className={styles.profile}><summary><span className={styles.avatar}>{data.principal.displayName.split(" ").map(value => value[0]).join("").slice(0, 2)}</span><span><b>{data.principal.displayName}</b><small>{data.principal.identityKind === "operational" ? "Operational account" : "Integration Administrator"}</small></span><ChevronDown size={16} /></summary><button type="button" onClick={() => void logout()}><LogOut size={15} /> Sign out</button></details></div></header><div className={styles.intro}>FIKA OS brings our operations, planning and data together.</div><div className={styles.contentGrid}><div className={styles.mainContent}><AppSection title="Operations">{appDefinitions.filter(app => app.section === "operations").map(renderCard)}</AppSection><div className={styles.lowerGrid}><AppSection title="Planning & Bookings">{appDefinitions.filter(app => app.section === "planning").map(renderCard)}</AppSection><AppSection title="Administration">{appDefinitions.filter(app => app.section === "administration").map(renderCard)}</AppSection></div><section className={styles.activity}><div className={styles.panelHeading}><span><Clock3 size={16} /> RECENT ACTIVITY</span></div><div className={styles.activityEmpty}>No recent activity</div></section></div><div className={styles.utility}><Favourites apps={availableApps} available={available} /><SystemStatus apps={availableApps} /></div></div><footer className={styles.brandFooter}><strong>FIKA</strong><span>Good food.<br />Better futures.</span></footer></section></div>;
}

function AppSection({ title, children }: { title: string; children: React.ReactNode }) { return <section className={styles.appSection}><h2><span />{title}</h2><div className={styles.appCards}>{children}</div></section>; }
function Favourites({ apps, available }: { apps: AppDefinition[]; available: Map<string, LauncherData["applications"][number]> }) { const rows = favourites.map(id => apps.find(app => app.appId === id)).filter(Boolean) as AppDefinition[]; return <section className={styles.utilityPanel}><h2><Star size={17} /> FAVOURITES</h2><p>Quick access to your most used apps.</p>{rows.length ? <div className={styles.favouriteRows}>{rows.map(app => { const Icon = app.icon; return <a href={available.get(app.appId)?.href} target="_blank" rel="noopener noreferrer" key={app.appId}><span className={styles.miniIcon} data-accent={app.accent}><Icon size={16} /></span><b>{app.label}</b><ArrowRight size={15} /></a>; })}</div> : <div className={styles.utilityEmpty}>No permitted favourites yet.</div>}</section>; }
function SystemStatus({ apps }: { apps: AppDefinition[] }) { return <section className={styles.utilityPanel}><h2><ShieldCheck size={17} /> SYSTEM STATUS</h2><div className={styles.statusSummary}><span />{apps.length ? "Available applications" : "No applications available"}</div><div className={styles.statusRows}>{apps.slice(0, 5).map(app => <div key={app.appId}><span /><b>{app.label}</b><small>Available</small></div>)}</div></section>; }
