"use client";
import { useEffect, useState } from "react";
import { ArrowRight, LogOut, ShieldCheck } from "lucide-react";
import { getFikaFirebaseAuth, getFikaGoogleProvider } from "@/lib/firebase-client";
import { getRedirectResult, signInWithPopup, signInWithRedirect, signOut } from "firebase/auth";
import { validateReturnTo } from "@/lib/safe-return-to";
import styles from "./launcher.module.css";

type LauncherData = { principal: { displayName: string; email?: string; identityKind?: "person" | "operational" }; applications: { appId: string; label: string; purpose: string; href: string }[]; canAdministerAuthmod: boolean };
type State = "loading" | "login" | "launcher" | "denied";
const localRoles = [["integration-admin", "Administrator"], ["reviewer", "Reviewer"], ["viewer", "Viewer"]] as const;

export default function Launcher() {
  const [state, setState] = useState<State>("loading"); const [data, setData] = useState<LauncherData | null>(null); const [local, setLocal] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [returnTo, setReturnTo] = useState("/");
  async function load() { try { const runtime = await fetch("/api/auth/runtime", { cache: "no-store" }); if (runtime.ok) setLocal((await runtime.json()).local === true); const session = await fetch("/api/auth/session", { cache: "no-store" }); if (session.status === 401) { setState("login"); return; } if (session.status === 403) { setState("denied"); setError("Your FIKA OS access is currently inactive or needs administrator review."); return; } if (!session.ok) throw new Error("FIKA OS could not load your session."); const launcher = await fetch("/api/launcher", { cache: "no-store" }); if (launcher.status === 401) { setState("login"); return; } if (launcher.status === 403) { setState("denied"); setError("Your FIKA OS access is currently inactive or needs administrator review."); return; } if (!launcher.ok) throw new Error("FIKA OS could not load your applications."); setData(await launcher.json()); setState("launcher"); } catch (cause) { setError((cause as Error).message); setState("login"); } }
  useEffect(() => { let destination = "/"; try { destination = validateReturnTo(new URLSearchParams(window.location.search).get("returnTo")); } catch { /* Invalid destinations fall back to the launcher. */ } setReturnTo(destination); void load(); void (async () => { try { const authInstance = getFikaFirebaseAuth(); const provider = getFikaGoogleProvider(); provider.setCustomParameters({ hd: "fikacatering.com" }); const result = await getRedirectResult(authInstance); if (result) { setBusy(true); await exchange(result.user, authInstance); } } catch { /* Missing client config is expected for local fixture mode. */ } finally { setBusy(false); } })(); }, []);
  async function exchange(user: { getIdToken(): Promise<string> }, authInstance: ReturnType<typeof getFikaFirebaseAuth>) { const idToken = await user.getIdToken(); const csrfResponse = await fetch("/api/auth/csrf", { cache: "no-store" }); const csrf = await csrfResponse.json() as { csrfToken: string }; const response = await fetch("/api/auth/session", { method: "POST", headers: { "content-type": "application/json", origin: window.location.origin }, body: JSON.stringify({ idToken, csrfToken: csrf.csrfToken }) }); await signOut(authInstance); if (!response.ok) { const body = await response.json().catch(() => ({})); const code = body.error?.code; if (code === "FIKA_EMAIL_NOT_ELIGIBLE") throw new Error("This Google account cannot access FIKA OS. Use your FIKA Workspace account."); if (code === "AUTHMOD_IDENTITY_NOT_FOUND") throw new Error("Your FIKA OS account has not been set up yet. Contact an administrator."); if (code === "AUTHMOD_IDENTITY_INACTIVE") throw new Error("Your FIKA OS access is currently inactive."); if (code === "AUTHMOD_EMAIL_IDENTITY_CONFLICT" || code === "AUTHMOD_EXTERNAL_IDENTITY_CONFLICT") throw new Error("Your FIKA OS account needs administrator review before you can sign in."); throw new Error("FIKA OS could not complete sign-in. Try again."); } window.location.assign(returnTo); }
  async function googleSignIn() { setBusy(true); setError(""); try { const authInstance = getFikaFirebaseAuth(); const provider = getFikaGoogleProvider(); provider.setCustomParameters({ hd: "fikacatering.com" }); const result = await signInWithPopup(authInstance, provider); await exchange(result.user, authInstance); } catch (cause) { const code = (cause as { code?: string }).code; if (code === "auth/popup-closed-by-user") return; if (code === "auth/popup-blocked" || code === "auth/operation-not-supported-in-this-environment") { try { await signInWithRedirect(getFikaFirebaseAuth(), getFikaGoogleProvider()); return; } catch { /* handled below */ } } setError((cause as Error).message.includes("FIKA") ? (cause as Error).message : "FIKA OS could not complete sign-in. Try again."); } finally { setBusy(false); } }
  async function localSignIn(role: string) { setBusy(true); setError(""); try { const response = await fetch("/api/auth/local-session", { method: "POST", headers: { "content-type": "application/json", origin: window.location.origin }, body: JSON.stringify({ role }) }); if (!response.ok) throw new Error("Local development sign-in is unavailable."); window.location.assign(returnTo); } catch (cause) { setError((cause as Error).message); } finally { setBusy(false); } }
  async function logout() { await fetch("/api/auth/session", { method: "DELETE" }); setData(null); setState("login"); }
  if (state === "loading") return <main className={styles.page}><div className={styles.loading}>Loading FIKA OS…</div></main>;
  if (state === "denied") return <main className={styles.page}><section className={styles.message}><ShieldCheck size={34} /><h1>FIKA OS</h1><p>{error}</p><a href="/">Return to sign in</a></section></main>;
  if (state === "login") return <main className={styles.page}><section className={styles.login}><div className={styles.logo}><ShieldCheck size={28} /><span>FIKA OS</span></div><h1>FIKA OS</h1><p>One place for FIKA operational systems.</p>{error && <div className={styles.error}>{error}</div>}<button className={styles.google} onClick={() => void googleSignIn()} disabled={busy}>Continue with Google <ArrowRight size={18} /></button><small>Use your FIKA Google Workspace account.</small>{local && <div className={styles.local}><b>LOCAL DEVELOPMENT</b><span>Emulator sign-in</span>{localRoles.map(([role, label]) => <button key={role} onClick={() => void localSignIn(role)} disabled={busy}>{label}</button>)}</div>}</section></main>;
  return <main className={styles.page}><header className={styles.header}><div><div className={styles.logo}><ShieldCheck size={24} /><span>FIKA OS</span></div><h1>My FIKA OS</h1><p>{data?.principal.displayName}{data?.principal.identityKind === "operational" ? " · Operational account" : data?.principal.email ? ` · ${data.principal.email}` : ""}</p></div><button className={styles.signout} onClick={() => void logout()}><LogOut size={16} /> Sign out</button></header><section className={styles.grid}>{data?.applications.map(app => <a className={styles.tile} href={app.href} key={app.appId}><div><h2>{app.label}</h2><p>{app.purpose}</p></div><span>Open <ArrowRight size={16} /></span></a>)}{data?.canAdministerAuthmod && <a className={`${styles.tile} ${styles.admin}`} href="/authmod"><div><h2>Access Administration</h2><p>AUTHMOD</p></div><span>Open <ArrowRight size={16} /></span></a>}</section>{data?.applications.length === 0 && <section className={styles.empty}><h2>You’re signed in, but no FIKA OS applications are currently assigned to this account.</h2><p>Contact a FIKA OS administrator if you need access.</p></section>}</main>;
}
