"use client";
import { useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, X } from "lucide-react";

type LegacySite = { canonicalId: string; label: string; address?: string; mappingStatus: string; mappedOplocId?: string };
type Relationship = { canonicalId: string; entityType: string; label: string; lifecycleStatus: string };
type Preview = { mappingStatus: string; target: { label: string; entityType: string } | null; generatedReason: string; additionalWrites: string[] };

export default function LegacySiteDecisionModal({ site, oplocs, refreshSession, close, saved }: { site: LegacySite; oplocs: Relationship[]; refreshSession: () => Promise<boolean>; close: () => void; saved: () => Promise<void> }) {
  const [mappingStatus, setMappingStatus] = useState<"confirmed" | "rejected" | "deferred" | "unresolved">("confirmed"), [oplocId, setOplocId] = useState(site.mappedOplocId || ""), [query, setQuery] = useState(""), [note, setNote] = useState(""), [preview, setPreview] = useState<Preview | null>(null), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  const selected = oplocs.find(oploc => oploc.canonicalId === oplocId);
  const matches = useMemo(() => oplocs.filter(oploc => `${oploc.label} ${oploc.lifecycleStatus}`.toLowerCase().includes(query.toLowerCase())).slice(0, 12), [oplocs, query]);
  async function command(action: "preview-legacy-decision" | "save-legacy-decision") { setBusy(true); setError(""); try { const body = { action, legacySourceCanonicalId: site.canonicalId, ...(mappingStatus === "confirmed" ? { oplocId } : {}), mappingStatus, decisionReason: note }; const send = () => fetch("/api/canonical-records", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); let response = await send(); if (response.status === 401 && await refreshSession()) response = await send(); const result = await response.json(); if (!response.ok) throw new Error(result.error?.message || "Legacy Site decision failed."); if (action === "preview-legacy-decision") setPreview(result); else { await saved(); close(); } } catch (cause) { setError((cause as Error).message); } finally { setBusy(false); } }
  return <div className="detail-backdrop" role="dialog" aria-modal="true" aria-labelledby="legacy-site-title" onMouseDown={event => { if (event.target === event.currentTarget) close(); }}><section className="detail-modal canonical-structured-modal"><header><div><small>Preserved source evidence</small><h2 id="legacy-site-title">Review {site.label}</h2></div><button className="icon" aria-label="Close legacy Site decision" onClick={close}><X /></button></header>
    {error && <div className="error"><AlertTriangle />{error}</div>}<div className="detail-summary"><span>{site.mappingStatus}</span>{site.address && <span>{site.address}</span>}</div>
    <label>What should happen?<select value={mappingStatus} onChange={event => { setMappingStatus(event.target.value as typeof mappingStatus); setPreview(null); if (event.target.value !== "confirmed") setOplocId(""); }}><option value="confirmed">This is an existing FIKA location</option><option value="rejected">This is not a canonical location</option><option value="deferred">Decide later</option><option value="unresolved">Leave unresolved</option></select></label>
    {mappingStatus === "confirmed" && <section className="relationship-selector"><label>Find the existing location<input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search by location name…" /></label>{selected ? <div className="relationship-selection"><b>{selected.label}</b><span>{selected.lifecycleStatus}</span><button type="button" onClick={() => { setOplocId(""); setQuery(""); setPreview(null); }}>Change selection</button></div> : query ? <div className="relationship-results" role="listbox" aria-label="Existing location results">{matches.map(oploc => <button type="button" role="option" aria-selected="false" key={oploc.canonicalId} onClick={() => { setOplocId(oploc.canonicalId); setQuery(""); setPreview(null); }}><b>{oploc.label}</b><span>{oploc.lifecycleStatus}</span></button>)}{!matches.length && <p>No accessible matching locations.</p>}</div> : <p>No location selected.</p>}</section>}
    <label>Add a note <span>(optional)</span><textarea maxLength={1000} value={note} onChange={event => { setNote(event.target.value); setPreview(null); }} placeholder="Add exceptional context not shown in the evidence." /></label>
    {preview && <section className="canonical-preview"><h3><CheckCircle2 /> Decision summary</h3><p><b>Selected action:</b> {preview.mappingStatus.replaceAll("-", " ")}</p>{preview.target && <p><b>Existing location:</b> {preview.target.label}</p>}<p><b>Audit summary:</b> {preview.generatedReason}</p><ul>{preview.additionalWrites.map(item => <li key={item}>{item}</li>)}</ul><p>The source evidence stays unchanged. Nothing is published.</p><details className="technical-details"><summary>Technical details</summary><p>{site.canonicalId}{oplocId ? ` → ${oplocId}` : ""}</p></details></section>}
    <div className="actions"><button onClick={close}>Cancel</button><button disabled={busy || (mappingStatus === "confirmed" && !oplocId)} onClick={() => void command("preview-legacy-decision")}>Preview decision</button><button className="primary" disabled={busy || !preview} onClick={() => void command("save-legacy-decision")}>Save decision</button></div>
  </section></div>;
}
