import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { errorResponse } from "@/lib/api";
import { requireActor } from "@/lib/auth";
import { assertPermission } from "@/lib/authmod";
import { acknowledgeProductionCancellation, createCpuProductionOrder, createProductionFromApprovedBooking, productionQueue, productionOrderDetail, reportProductionAllergenDiscrepancy, transitionProductionOrder, updateProductionLines, type ProductionStatus } from "@/lib/production-domain";
import { notifyCpuProjection } from "@/lib/cpu-projection-client";

const Create = z.object({ action: z.literal("create"), bookingId: z.string().min(8), idempotencyKey: z.string().trim().min(8).max(200), conversions: z.record(z.string(), z.object({ quantity: z.number().positive(), unit: z.string().trim().min(1).max(80) })).optional() }).strict();
const Transition = z.object({ action: z.literal("transition"), canonicalId: z.string().min(8), expectedVersion: z.number().int().positive(), status: z.enum(["draft", "needs_review", "accepted", "scheduled", "in_production", "partially_complete", "complete", "cancelled", "blocked", "failed", "reconciliation_required"]), reason: z.string().trim().min(3).max(1000) }).strict();
const AcknowledgeCancellation = z.object({ action: z.literal("acknowledge-cancellation"), canonicalId: z.string().min(8), expectedVersion: z.number().int().positive() }).strict();
const CpuCreate = z.object({ action: z.literal("cpu-create"), idempotencyKey: z.string().trim().min(8).max(200), clientName: z.string().trim().min(1), serviceDate: z.string(), deliveryDateTime: z.string(), requiredBy: z.string(), serviceWindow: z.object({ startTime: z.string(), endTime: z.string().optional() }), productionLocationId: z.string().optional(), destinationOplocId: z.string().optional(), requiresDelivery: z.boolean().optional(), deliveryLocation: z.string().trim().min(1), floorRoom: z.string().optional(), contact: z.string().optional(), serviceType: z.string().trim().min(1), pax: z.number().int().positive(), lines: z.array(z.object({ itemName: z.string().trim().min(1), customerQuantity: z.number().positive(), customerUnit: z.string().trim().min(1), productionQuantity: z.number().positive().optional(), productionUnit: z.string().optional(), dietary: z.record(z.string(), z.unknown()).optional(), notes: z.string().optional() }).strict()).min(1), priority: z.enum(["normal", "high", "urgent"]).optional(), sourceReference: z.string().optional(), notes: z.string().optional() }).strict();
const UpdateLines = z.object({ action: z.literal("update-lines"), canonicalId: z.string().min(8), expectedVersion: z.number().int().positive(), lines: z.array(z.object({ canonicalId: z.string().min(8), productionQuantity: z.number().positive().optional(), productionUnit: z.string().trim().optional(), actualQuantity: z.number().nonnegative().optional(), shortfallQuantity: z.number().nonnegative().optional(), substitution: z.string().optional(), wasteQuantity: z.number().nonnegative().optional(), productionInstructions: z.string().optional(), dietaries: z.record(z.string(), z.unknown()), allergenEvidenceStatus: z.enum(["confirmed", "unreviewed", "missing", "conflicting"]).optional() }).strict()).min(1) }).strict();
const AllergenDiscrepancy = z.object({ action: z.literal("report-allergen-discrepancy"), canonicalId: z.string().min(8), expectedVersion: z.number().int().positive(), note: z.string().trim().min(3) }).strict();
export async function GET(request: NextRequest) { try { const actor = await requireActor(request); assertPermission(actor, "canonical.view"); const id = request.nextUrl.searchParams.get("canonicalId"); const serviceDate = request.nextUrl.searchParams.get("serviceDate") || undefined; return NextResponse.json(id ? { order: await productionOrderDetail(id) } : { orders: await productionQueue(serviceDate) }, { headers: { "Cache-Control": "no-store, max-age=0" } }); } catch (error) { return errorResponse(error); } }
export async function POST(request: NextRequest) { try { const actor = await requireActor(request, ["integration-admin", "reviewer"]); assertPermission(actor, "canonical.edit"); const input = await request.json(); if (input?.action === "cpu-create") { const command = CpuCreate.parse(input); return NextResponse.json(await createCpuProductionOrder(actor, command, command.idempotencyKey)); } if (input?.action === "update-lines") { const command = UpdateLines.parse(input); return NextResponse.json({ order: await updateProductionLines(actor, command.canonicalId, command.expectedVersion, command.lines) }); } if (input?.action === "report-allergen-discrepancy") { const command = AllergenDiscrepancy.parse(input); return NextResponse.json(await reportProductionAllergenDiscrepancy(actor, command.canonicalId, command.expectedVersion, command.note)); } if (input?.action === "create") { const command = Create.parse(input); const result = await createProductionFromApprovedBooking(actor, command.bookingId, command.idempotencyKey, command.conversions || {}); let cpuHandoff: "delivered" | "pending" = "delivered"; if (result.order) { try { await notifyCpuProjection(result.order, "created", `cpu-projection:${result.order.canonicalId}:v${result.order.version}`); } catch { cpuHandoff = "pending"; } } return NextResponse.json({ ...result, cpuHandoff }); } if (input?.action === "acknowledge-cancellation") { const command = AcknowledgeCancellation.parse(input); return NextResponse.json({ order: await acknowledgeProductionCancellation(actor, command.canonicalId, command.expectedVersion) }); } const command = Transition.parse(input); const order = await transitionProductionOrder(actor, command.canonicalId, command.expectedVersion, command.status as ProductionStatus, command.reason); let cpuHandoff: "delivered" | "pending" = "delivered"; try { await notifyCpuProjection(order, command.status === "cancelled" ? "withdrawn" : "amended", `cpu-projection:${order.canonicalId}:v${order.version}`); } catch { cpuHandoff = "pending"; } return NextResponse.json({ order, cpuHandoff }); } catch (error) { return errorResponse(error); } }
