import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { errorResponse } from "@/lib/api";
import { requireActor } from "@/lib/auth";
import { assertPermission } from "@/lib/authmod";
import { createProductionFromApprovedBooking, productionQueue, productionOrderDetail, transitionProductionOrder, type ProductionStatus } from "@/lib/production-domain";

const Create = z.object({ action: z.literal("create"), bookingId: z.string().min(8), idempotencyKey: z.string().trim().min(8).max(200), conversions: z.record(z.string(), z.object({ quantity: z.number().positive(), unit: z.string().trim().min(1).max(80) })).optional() }).strict();
const Transition = z.object({ action: z.literal("transition"), canonicalId: z.string().min(8), expectedVersion: z.number().int().positive(), status: z.enum(["draft", "needs_review", "accepted", "scheduled", "in_production", "partially_complete", "complete", "cancelled", "blocked", "failed", "reconciliation_required"]), reason: z.string().trim().min(3).max(1000) }).strict();
export async function GET(request: NextRequest) { try { const actor = await requireActor(request); assertPermission(actor, "canonical.view"); const id = request.nextUrl.searchParams.get("canonicalId"); const serviceDate = request.nextUrl.searchParams.get("serviceDate") || undefined; return NextResponse.json(id ? { order: await productionOrderDetail(id) } : { orders: await productionQueue(serviceDate) }, { headers: { "Cache-Control": "no-store, max-age=0" } }); } catch (error) { return errorResponse(error); } }
export async function POST(request: NextRequest) { try { const actor = await requireActor(request, ["integration-admin", "reviewer"]); assertPermission(actor, "canonical.edit"); const input = await request.json(); if (input?.action === "create") return NextResponse.json(await createProductionFromApprovedBooking(actor, Create.parse(input).bookingId, Create.parse(input).idempotencyKey, Create.parse(input).conversions || {})); const command = Transition.parse(input); return NextResponse.json({ order: await transitionProductionOrder(actor, command.canonicalId, command.expectedVersion, command.status as ProductionStatus, command.reason) }); } catch (error) { return errorResponse(error); } }
