import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { errorResponse } from "@/lib/api";
import { requireActor } from "@/lib/auth";
import { assertPermission } from "@/lib/authmod";
import { acknowledgeProductionCancellation, createProductionFromApprovedBooking, productionQueue, productionQueueForWeek, productionOrderDetail, transitionProductionOrder, type ProductionStatus } from "@/lib/production-domain";
import { notifyCpuProjection } from "@/lib/cpu-projection-client";
import { notifyLogisticsProjection } from "@/lib/logistics-projection-client";

function londonBusinessDate(now = new Date()) {
  return new Intl.DateTimeFormat("en-CA", { timeZone: "Europe/London", year: "numeric", month: "2-digit", day: "2-digit" }).format(now);
}

const Create = z.object({ action: z.literal("create"), bookingId: z.string().min(8), idempotencyKey: z.string().trim().min(8).max(200), conversions: z.record(z.string(), z.object({ quantity: z.number().positive(), unit: z.string().trim().min(1).max(80) })).optional() }).strict();
const Transition = z.object({ action: z.literal("transition"), canonicalId: z.string().min(8), expectedVersion: z.number().int().positive(), status: z.enum(["draft", "needs_review", "accepted", "scheduled", "in_production", "partially_complete", "complete", "cancelled", "blocked", "failed", "reconciliation_required"]), reason: z.string().trim().min(3).max(1000) }).strict();
const AcknowledgeCancellation = z.object({ action: z.literal("acknowledge-cancellation"), canonicalId: z.string().min(8), expectedVersion: z.number().int().positive() }).strict();
export async function GET(request: NextRequest) { try { const actor = await requireActor(request); assertPermission(actor, "canonical.view"); const id = request.nextUrl.searchParams.get("canonicalId"); const serviceDate = request.nextUrl.searchParams.get("serviceDate") || londonBusinessDate(); const weekCommencing = request.nextUrl.searchParams.get("weekCommencing") || undefined; return NextResponse.json(id ? { order: await productionOrderDetail(id) } : { orders: weekCommencing ? await productionQueueForWeek(weekCommencing) : await productionQueue(serviceDate) }, { headers: { "Cache-Control": "no-store, max-age=0" } }); } catch (error) { return errorResponse(error); } }
export async function POST(request: NextRequest) { try { const actor = await requireActor(request, ["integration-admin", "reviewer"]); assertPermission(actor, "canonical.edit"); const input = await request.json(); if (input?.action === "create") { const command = Create.parse(input); const result = await createProductionFromApprovedBooking(actor, command.bookingId, command.idempotencyKey, command.conversions || {}); let cpuHandoff: "delivered" | "pending" = "delivered"; if (result.order) { try { await notifyCpuProjection(result.order, "created", `cpu-projection:${result.order.canonicalId}:v${result.order.version}`); await notifyLogisticsProjection({ serviceDate: result.order.serviceDate, sourceDomain: "cpu-production", sourceEntityId: result.order.canonicalId, sourceVersion: result.order.version, changedAt: result.order.updatedAt || result.order.createdAt, changeType: "status-changed" }); } catch { cpuHandoff = "pending"; } } return NextResponse.json({ ...result, cpuHandoff }); } if (input?.action === "acknowledge-cancellation") { const command = AcknowledgeCancellation.parse(input); return NextResponse.json({ order: await acknowledgeProductionCancellation(actor, command.canonicalId, command.expectedVersion) }); } const command = Transition.parse(input); const order = await transitionProductionOrder(actor, command.canonicalId, command.expectedVersion, command.status as ProductionStatus, command.reason); let cpuHandoff: "delivered" | "pending" = "delivered"; try { await notifyCpuProjection(order, command.status === "cancelled" ? "withdrawn" : "amended", `cpu-projection:${order.canonicalId}:v${order.version}`); await notifyLogisticsProjection({ serviceDate: order.serviceDate, sourceDomain: "cpu-production", sourceEntityId: order.canonicalId, sourceVersion: order.version, changedAt: order.updatedAt || order.createdAt, changeType: command.status === "cancelled" ? "withdrawn" : "amended" }); } catch { cpuHandoff = "pending"; } return NextResponse.json({ order, cpuHandoff }); } catch (error) { return errorResponse(error); } }
