import { productionQueue, type ProductionOrder, type ProductionStatus } from "@hub/lib/production-domain";
import type { ProductionPlan } from "../app/lib/production-plan";
import { db } from "@hub/lib/firebase-admin";

export type CpuChangeEvent = { sequence: number; serviceDate: string; entityType: "productionOrder" | "productionPlan"; entityId: string; revision: number; changeType: string; actorId: string; changedAt: string };
export type CpuProjectionOrder = { id: string; serviceDate: string; requiredBy: string; serviceWindow: ProductionOrder["serviceWindow"]; origin?: string; sourceReference?: string; destinationOplocId?: string; destinationLabel?: string; clientName?: string; serviceType?: string; pax?: number; priority: ProductionOrder["priority"]; status: ProductionStatus; workflowStatus?: ProductionStatus; productionScope?: string; quantities: Array<{ name: string; quantity: number; unit: string }>; allergenReadiness: string; planningReadiness: string; attention: string[]; version: number };
export type CpuDayProjection = { serviceDate: string; revision: number; lastChangeSequence: number; orders: CpuProjectionOrder[]; summary: { orders: number; ready: number; attention: number; planned: number; totalUnits: number }; rebuiltAt: string };
export const cpuPlans = () => db.collection("fikaCpuProductionPlansV1");
export const cpuChanges = () => db.collection("fikaCpuProductionChangesV1");
export const cpuCursor = () => db.collection("fikaCpuProductionChangeCursorV1");
export const cpuProjections = () => db.collection("fikaCpuProductionDayProjectionsV1");

export async function appendCpuChange(input: Omit<CpuChangeEvent, "sequence">) { return db.runTransaction(async (transaction) => { const ref = cpuCursor().doc("global"); const current = await transaction.get(ref); const sequence = Number(current.data()?.sequence || 0) + 1; const event = { ...input, sequence }; transaction.set(ref, { sequence }); transaction.create(cpuChanges().doc(String(sequence).padStart(20, "0")), event); return event; }); }
export async function listCpuChanges(after: number, serviceDate: string) { const snapshot = await cpuChanges().where("serviceDate", "==", serviceDate).where("sequence", ">", after).orderBy("sequence", "asc").get(); return snapshot.docs.map((doc) => doc.data() as CpuChangeEvent); }
export function buildCpuDayProjection(serviceDate: string, orders: ProductionOrder[], plans: ProductionPlan[] = [], lastChangeSequence = 0, revision = 1, now = new Date().toISOString()): CpuDayProjection {
  const planByOrder = new Map(plans.map((plan) => [plan.orderId, plan]));
  const projected = orders.filter((order) => (serviceDate === "all" || order.serviceDate === serviceDate) && !order.supersededBy && order.status !== "cancelled").map((order) => { const plan = planByOrder.get(order.canonicalId); const workflowStatus = plan?.status === "planned" ? "planned" : plan?.status === "planning" ? "planning" : order.workflowStatus; const attention = [...order.exceptions.filter((item) => item.status === "open").map((item) => item.description), ...(order.lines.some((line) => line.allergenEvidenceStatus === "missing" || line.allergenEvidenceStatus === "conflicting") ? ["Allergen evidence needs attention"] : [])]; const quantities = order.lines.map((line) => ({ name: line.itemName, quantity: line.productionQuantity ?? line.customerQuantity, unit: line.productionUnit || line.customerUnit })); return { id: order.canonicalId, serviceDate: order.serviceDate || serviceDate, requiredBy: order.requiredBy, serviceWindow: order.serviceWindow, origin: order.origin, sourceReference: order.sourceBookingId, destinationOplocId: order.destinationOplocId, destinationLabel: order.destinationLabel || order.destinationOplocId, clientName: order.clientName, serviceType: order.serviceType, pax: order.guestCount, priority: order.priority, status: order.status, workflowStatus, productionScope: order.lines.map((line) => line.workstream).filter(Boolean).join(",") || "unassigned", quantities, allergenReadiness: attention.some((item) => item.toLowerCase().includes("allergen")) ? "attention" : "ready", planningReadiness: workflowStatus === "planned" ? "planned" : order.status === "ready" || order.status === "in_production" || order.status === "complete" ? "ready" : "attention", attention, version: order.version }; });
  return { serviceDate, revision, lastChangeSequence, orders: projected, summary: { orders: projected.length, ready: projected.filter((order) => order.planningReadiness === "ready").length, attention: projected.filter((order) => order.attention.length > 0).length, planned: projected.filter((order) => order.workflowStatus === "planned").length, totalUnits: projected.reduce((sum, order) => sum + order.quantities.reduce((total, item) => total + item.quantity, 0), 0) }, rebuiltAt: now };
}

export async function rebuildCpuDayProjection(serviceDate: string, lastChangeSequence?: number) {
  const [orders, planSnapshot, previous] = await Promise.all([productionQueue(serviceDate), cpuPlans().get(), cpuProjections().doc(serviceDate).get()]);
  const plans = planSnapshot.docs.map((document) => document.data() as ProductionPlan);
  const projection = buildCpuDayProjection(serviceDate, orders, plans, lastChangeSequence ?? Number(previous.data()?.lastChangeSequence || 0), Number(previous.data()?.revision || 0) + 1);
  await cpuProjections().doc(serviceDate).set(projection);
  return projection;
}
