"use client";

import { useEffect, useMemo, useState } from "react";
import type { FulfilmentRequirement } from "../../../shared/fulfilment-requirement";
import type { DeliveryRun, DeliveryStop, MovementRequest } from "../../lib/types";
import { operationalDate } from "../../lib/date";
import { movementsForStop, selectMobileRuns } from "../../lib/planning";

type Data = { requirements: FulfilmentRequirement[]; runs: DeliveryRun[]; stops: DeliveryStop[]; movements: MovementRequest[]; oplocs: { id: string; label: string; address?: string }[]; serviceDate: string };
type View = "deliveries" | "collections" | "messages" | "more";
type DriverMessage = { id: string; title: string; body: string; meta: string };

export default function Mobile() {
  const [driver, setDriver] = useState("Franco");
  const [data, setData] = useState<Data>();
  const [view, setView] = useState<View>("deliveries");
  const [selectedStop, setSelectedStop] = useState<DeliveryStop>();
  const [issueStop, setIssueStop] = useState<DeliveryStop>();
  const [issueText, setIssueText] = useState("");
  const [issueType, setIssueType] = useState("Unable to complete");
  const [error, setError] = useState("");
  const [selectedDate, setSelectedDate] = useState(operationalDate());
  const [messages, setMessages] = useState<DriverMessage[]>([
    { id: "planner-update", title: "Planner update", body: "Your route is ready for today. Drive safe, Franco.", meta: "08:32 · Dispatch" },
    { id: "site-notice", title: "Site notice", body: "Bridgepoint reception is using the side entrance today.", meta: "Yesterday · Operations" },
  ]);
  const date = selectedDate;
  const availableDates = useMemo(() => dateOptions(), []);

  const load = async () => { try { const response = await fetch(`/api/logistics?serviceDate=${date}`, { cache: "no-store" }); const body = await response.json().catch(() => null); if (!response.ok) throw new Error(body?.error || "Logistics is temporarily unavailable."); setData(body); setError(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Logistics is temporarily unavailable."); } };
  useEffect(() => { void load(); }, [selectedDate]);

  const runs = useMemo(() => selectMobileRuns(data?.runs || [], driver, date), [data?.runs, driver, date]);
  const stops = useMemo(() => runs.flatMap((run) => run.orderedStopIds.map((id) => data?.stops.find((stop) => stop.canonicalId === id)).filter(Boolean) as DeliveryStop[]), [runs, data?.stops]);
  const deliveries = stops.filter((stop) => stop.movementType !== "collection" && stop.linkedOperation !== "collection");
  const collections = stops.filter((stop) => stop.movementType === "collection" || stop.linkedOperation === "collection");
  const completed = stops.filter((stop) => stop.status === "completed").length;
  const attention = stops.filter((stop) => stop.status === "issue" || (stop.issues || []).some((issue) => issue.status === "open")).length;
  const visibleStops = view === "collections" ? collections : deliveries;
  const nextStop = visibleStops.find((stop) => stop.status !== "completed");

  async function execute(action: string, stop: DeliveryStop, extra: Record<string, unknown> = {}) {
    const run = runs.find((item) => item.canonicalId === stop.runId); if (!run) return;
    const response = await fetch("/api/logistics", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action, by: driver, runId: run.canonicalId, expectedRunVersion: run.version, stopId: stop.canonicalId, expectedStopVersion: stop.version, ...extra }) });
    const body = await response.json().catch(() => null); if (!response.ok) { setError(body?.error || "The operation could not be completed."); return; }
    setSelectedStop(undefined); setIssueStop(undefined); setIssueText(""); await load();
  }
  const reportIssue = () => { if (issueStop && issueText.trim()) void execute("report-issue", issueStop, { issueDescription: `${issueType}: ${issueText.trim()}` }); };

  return <main className="driver-app">
    <header className="driver-hero"><div className="driver-topline"><a href="/" aria-label="Back to planner">← Planner</a><span className="driver-bell" aria-label="Notifications">♧<i /></span></div><p className="driver-eyebrow">FIKA OS · DRIVER</p><div className="driver-title-row"><h1>{view === "collections" ? "Collections" : view === "deliveries" ? "Deliveries" : view === "messages" ? "Messages" : "More"}</h1><span className="driver-live">● LIVE</span></div><div className="driver-filters"><label><span>▣</span><select aria-label="Service date" value={selectedDate} onChange={(event) => setSelectedDate(event.target.value)}>{availableDates.map((option) => <option key={option} value={option}>{formatDate(option)}</option>)}</select></label><label><span>♙</span><select aria-label="Driver" value={driver} onChange={(event) => setDriver(event.target.value)}><option>Franco</option><option>Dee</option></select></label></div></header>
    {error && <div className="driver-alert" role="alert">{error}<button onClick={() => void load()}>Retry</button></div>}
    {!data ? <section className="driver-empty">Loading your day…</section> : view === "messages" ? <Messages messages={messages} onDismiss={(id) => setMessages((current) => current.filter((message) => message.id !== id))} onClear={() => setMessages([])} /> : view === "more" ? <More driver={driver} runs={runs} /> : <>
      <section className="driver-summary" aria-label="Daily summary"><Metric icon="↘" value={deliveries.length} label="Deliveries" tone="purple" /><Metric icon="✓" value={completed} label="Completed" tone="mint" /><Metric icon="↗" value={collections.length} label="Collections" tone="blue" /><Metric icon="!" value={attention} label="Attention" tone="rose" /></section>
      <div className="driver-progress"><span>Today’s progress</span><strong>{completed} of {stops.length} tasks complete</strong><div><i style={{ width: `${stops.length ? (completed / stops.length) * 100 : 0}%` }} /></div></div>
      <nav className="task-switcher" aria-label="Task type"><button className={view === "deliveries" ? "active" : ""} onClick={() => setView("deliveries")}>Deliveries <b>{deliveries.filter((stop) => stop.status !== "completed").length}</b></button><button className={view === "collections" ? "active" : ""} onClick={() => setView("collections")}>Collections <b>{collections.filter((stop) => stop.status !== "completed").length}</b></button></nav>
      <section className="driver-list"><div className="list-heading"><div><p className="driver-section-kicker">{view === "collections" ? "RETURN LOAD" : "DELIVERY ROUTE"}</p><h2>{view === "collections" ? "Collection stops" : "Your stops"}</h2></div><span>{visibleStops.length} total</span></div>{nextStop && <div className="next-banner"><span>Next up</span><strong>{stopLabel(nextStop, data)}</strong><b>{timeFor(nextStop)}</b></div>}{visibleStops.length ? visibleStops.map((stop, index) => <StopRow key={stop.canonicalId} stop={stop} data={data} index={index} onOpen={() => setSelectedStop(stop)} />) : <div className="driver-empty compact">No {view} assigned for this day.</div>}</section>
    </>}
    <nav className="driver-bottom-nav" aria-label="Primary"><NavItem active={view === "deliveries"} icon="▦" label="Deliveries" onClick={() => setView("deliveries")} /><NavItem active={view === "collections"} icon="⌁" label="Collections" onClick={() => setView("collections")} /><NavItem active={view === "messages"} icon="□" label="Messages" onClick={() => setView("messages")} badge={messages.length ? String(messages.length) : undefined} /><NavItem active={view === "more"} icon="☰" label="More" onClick={() => setView("more")} /></nav>
    {selectedStop && data && <StopDetail stop={selectedStop} data={data} onClose={() => setSelectedStop(undefined)} onAction={execute} onIssue={() => { setIssueStop(selectedStop); setSelectedStop(undefined); }} />}{issueStop && <IssueSheet stop={issueStop} type={issueType} setType={setIssueType} text={issueText} setText={setIssueText} onClose={() => setIssueStop(undefined)} onSubmit={reportIssue} />}
  </main>;
}

function Metric({ icon, value, label, tone }: { icon: string; value: number; label: string; tone: string }) { return <div className={`driver-metric ${tone}`}><span>{icon}</span><strong>{value}</strong><small>{label}</small></div>; }
function NavItem({ active, icon, label, badge, onClick }: { active: boolean; icon: string; label: string; badge?: string; onClick: () => void }) { return <button className={active ? "active" : ""} onClick={onClick}><span>{icon}{badge && <i>{badge}</i>}</span><small>{label}</small></button>; }
function StopRow({ stop, data, index, onOpen }: { stop: DeliveryStop; data: Data; index: number; onOpen: () => void }) { const issue = stop.status === "issue" || (stop.issues || []).some((item) => item.status === "open"); return <button className={`stop-row-card ${stop.status} ${issue ? "attention" : ""}`} onClick={onOpen}><span className="stop-number">{stop.status === "completed" ? "✓" : stop.sequence || index + 1}</span><span className="stop-row-main"><span className="stop-row-meta"><b>{stop.status === "completed" ? "COMPLETED" : stop.status === "arrived" ? "CURRENT" : issue ? "ATTENTION" : index === 0 ? "UP NEXT" : "PLANNED"}</b>{stop.notes && <em>✎</em>}</span><strong>{stopLabel(stop, data)}</strong><small>{stop.movementType === "collection" ? "Collection" : "Delivery"} · {timeFor(stop)}{itemSummary(stop) ? ` · ${itemSummary(stop)}` : ""}</small></span><span className="stop-row-arrow">›</span></button>; }
function StopDetail({ stop, data, onClose, onAction, onIssue }: { stop: DeliveryStop; data: Data; onClose: () => void; onAction: (action: string, stop: DeliveryStop) => void; onIssue: () => void }) { const movement = movementsForStop(stop, data.movements)[0]; const oploc = data.oplocs.find((item) => item.id === stop.locationOplocId); const address = oploc?.address || oploc?.label || stop.locationLabelSnapshot; return <div className="sheet-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="stop-detail-sheet" role="dialog" aria-modal="true" aria-label="Stop details"><button className="sheet-close" onClick={onClose}>×</button><div className="detail-type"><span>{stop.movementType === "collection" ? "COLLECTION" : "DELIVERY"}</span><b>{statusLabel(stop.status)}</b></div><h2>{stopLabel(stop, data)}</h2><p className="detail-address">⌖ {address}</p><div className="detail-time"><span>Scheduled window</span><strong>{timeFor(stop)}</strong></div><div className="detail-block"><h3>Load summary</h3><p>{movement?.items.map((item) => `${item.quantity} ${item.unit || "items"} · ${item.description}`).join(" · ") || itemSummary(stop) || "Operational load details attached"}</p></div>{stop.notes && <div className="detail-note">✎ {stop.notes}</div>}{(stop.issues || []).filter((issue) => issue.status === "open").map((issue) => <div className="detail-issue" key={issue.id}>⚠ {issue.description}</div>)}<div className="detail-actions"><button className="navigate-action" onClick={() => window.open(`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(address)}`, "_blank")}>Navigate</button>{stop.status === "planned" && <button onClick={() => onAction("arrive-stop", stop)}>Mark arrived</button>}{stop.status === "arrived" && <button onClick={() => onAction("complete-stop", stop)}>Complete stop</button>}<button className="issue-action" onClick={onIssue}>Report issue</button></div></section></div>; }
function IssueSheet({ stop, type, setType, text, setText, onClose, onSubmit }: { stop: DeliveryStop; type: string; setType: (value: string) => void; text: string; setText: (value: string) => void; onClose: () => void; onSubmit: () => void }) { return <div className="sheet-backdrop" role="presentation"><section className="stop-detail-sheet issue-sheet" role="dialog" aria-modal="true" aria-label="Report an issue"><button className="sheet-close" onClick={onClose}>×</button><p className="driver-section-kicker">REPORT EXCEPTION</p><h2>What needs attention?</h2><p className="issue-stop-name">{stop.locationLabelSnapshot}</p><label>Issue type<select value={type} onChange={(event) => setType(event.target.value)}>{["Unable to complete", "No access", "Site closed", "Delayed", "Customer unavailable", "Partial completion", "Collection issue", "Load issue", "Other"].map((item) => <option key={item}>{item}</option>)}</select></label><label>Notes<textarea value={text} onChange={(event) => setText(event.target.value)} placeholder="Add a short note for the planner…" rows={4} /></label><button className="submit-issue" disabled={!text.trim()} onClick={onSubmit}>Submit issue</button></section></div>; }
function Messages({ messages, onDismiss, onClear }: { messages: DriverMessage[]; onDismiss: (id: string) => void; onClear: () => void }) { return <section className="secondary-screen"><div className="messages-heading"><div><p className="driver-section-kicker">INBOX</p><h2>Messages</h2></div>{messages.length > 0 && <button className="clear-messages" onClick={onClear}>Clear all</button>}</div>{messages.length ? messages.map((message) => <article className="message-card" key={message.id}><span>●</span><div><strong>{message.title}</strong><p>{message.body}</p><small>{message.meta}</small></div><button className="dismiss-message" aria-label={`Dismiss ${message.title}`} onClick={() => onDismiss(message.id)}>×</button></article>) : <div className="driver-empty compact">You’re all caught up. No new messages.</div>}</section>; }
function More({ driver, runs }: { driver: string; runs: DeliveryRun[] }) { return <section className="secondary-screen"><p className="driver-section-kicker">ACCOUNT</p><h2>More</h2><div className="more-card"><span>♙</span><div><small>Signed in as</small><strong>{driver}</strong></div></div><div className="more-card"><span>▣</span><div><small>Assigned vehicles</small><strong>{runs.map((run) => run.vehicleLabel || "Van").join(" · ") || "No vehicle assigned"}</strong></div></div><a className="planner-return" href="/">Open planner workspace →</a></section>; }
function formatDate(date: string) { return new Intl.DateTimeFormat("en-GB", { weekday: "short", day: "numeric", month: "short" }).format(new Date(`${date}T12:00:00`)); }
function dateOptions() { const start = new Date(`${operationalDate()}T12:00:00`); return Array.from({ length: 8 }, (_, index) => { const date = new Date(start); date.setDate(start.getDate() + index); return date.toISOString().slice(0, 10); }); }
function timeFor(stop: DeliveryStop) { const window = stop.plannedWindow || stop.window; return window ? `${window.startTime}${window.endTime ? ` – ${window.endTime}` : ""}` : stop.plannedArrivalTime || stop.requiredTime || "Time to confirm"; }
function itemSummary(stop: DeliveryStop) { return stop.requirementRefs.length ? `${stop.requirementRefs.length} load${stop.requirementRefs.length === 1 ? "" : "s"}` : ""; }
function stopLabel(stop: DeliveryStop, data: Data) { return data.oplocs.find((item) => item.id === stop.locationOplocId)?.label || (stop.locationLabelSnapshot.startsWith("oploc:") ? "Operational location" : stop.locationLabelSnapshot); }
function statusLabel(status: DeliveryStop["status"]) { return status === "completed" ? "Complete" : status === "arrived" ? "Current" : status === "issue" ? "Attention" : "Planned"; }
