"use client";
import { useEffect, useState } from "react";
import type { DeliveryRun, DeliveryStop, MovementRequest } from "../../lib/types";
import type { FulfilmentRequirement } from "../../../shared/fulfilment-requirement";
import { operationalDate } from "../../lib/date";
import { movementsForStop, selectMobileRun } from "../../lib/planning";
type Data={requirements:FulfilmentRequirement[];runs:DeliveryRun[];stops:DeliveryStop[];movements:MovementRequest[];oplocs:{id:string;label:string}[];serviceDate:string};
// Demo-only actor switcher. Production auth and permissions are required before real operational use.
export default function Mobile(){const [driver,setDriver]=useState("Franco");const [requestedRunId,setRequestedRunId]=useState("");const [data,setData]=useState<Data>();const [error,setError]=useState("");const date=data?.serviceDate||operationalDate();
 const load=(runId?:string)=>fetch(`/api/logistics?${runId?`runId=${encodeURIComponent(runId)}`:`serviceDate=${date}`}`,{cache:"no-store"}).then(async response=>{const body=await response.json().catch(()=>null);if(!response.ok)throw new Error(body?.error||"Logistics is temporarily unavailable. Check that Integration Hub is running, then retry.");setData(body);setError("")}).catch(cause=>setError(cause instanceof Error?cause.message:"Logistics is temporarily unavailable.")); useEffect(()=>{const runId=new URLSearchParams(window.location.search).get("run")||"";setRequestedRunId(runId);void load(runId||undefined)},[]);
 const run=selectMobileRun(data?.runs||[],driver,date,requestedRunId);const stops=run?.orderedStopIds.map(id=>data?.stops.find(stop=>stop.canonicalId===id)).filter(Boolean)as DeliveryStop[]||[];const active=stops.find(stop=>stop.status!=="completed");
 async function update(stop:DeliveryStop,status:DeliveryStop["status"]){const response=await fetch("/api/logistics",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"update-stop",by:driver,stop:{...stop,status}})});if(!response.ok){const body=await response.json().catch(()=>null);setError(body?.error||"The stop could not be updated.");return}await load(requestedRunId||undefined)}
 return <main className="mobile-shell"><header><a href="/">← Planner</a><p className="eyebrow mint">FIKA OS · DRIVER</p><h1>My run</h1><select value={driver}onChange={event=>setDriver(event.target.value)}><option>Franco</option><option>Dee</option></select></header>{error&&<div className="alert"role="alert">{error}<button className="retry"onClick={()=>void load()}>Retry</button></div>}{!run?<section className="mobile-card"><p className="eyebrow">Driver workflow</p><h2>No matching run</h2><p>{requestedRunId?"The requested run is not assigned to this operational date.":data?`No run is assigned to ${driver} for today.`:"Load the local Logistics and Integration Hub services to see today’s run."}</p></section>:<><section className="progress"><span>{run.driverLabel||driver} · {stops.filter(stop=>stop.status==="completed").length}/{stops.length} stops</span><strong>{active?active.locationLabelSnapshot:"Run complete"}</strong></section>{active&&<StopCard stop={active}requirements={data?.requirements||[]}movements={movementsForStop(active,data?.movements||[])}oplocs={data?.oplocs||[]}onUpdate={update}/>}<section className="upcoming"><p className="eyebrow">Upcoming stops</p>{stops.map(stop=><div className={stop.canonicalId===active?.canonicalId?"current":""}key={stop.canonicalId}><span>{stop.sequence}</span><strong>{stop.locationLabelSnapshot}</strong><small>{stop.status} · {stop.requiredTime||stop.window?.startTime||"—"}</small></div>)}</section></>}</main>}
function StopCard({stop,requirements,movements,oplocs,onUpdate}:{stop:DeliveryStop;requirements:FulfilmentRequirement[];movements:MovementRequest[];oplocs:{id:string;label:string}[];onUpdate:(stop:DeliveryStop,status:DeliveryStop["status"])=>void}){const label=(id?:string)=>oplocs.find(oploc=>oploc.id===id)?.label||id||"—";return <section className="next-stop"><p className="eyebrow">Next stop · {stop.status}</p><h2>{stop.locationLabelSnapshot}</h2><p className="stop-type">{stop.movementType?stop.movementType:"Fulfilment delivery"} · {stop.requiredTime||stop.window?.startTime||"Time to confirm"}</p>{movements.map(movement=><div className="movement-detail"key={movement.canonicalId}><strong>{movement.type}</strong><small>{movement.fromOplocId?`From ${label(movement.fromOplocId)} · `:""}{movement.toOplocId?`To ${label(movement.toOplocId)}`:""}</small>{movement.items.map((item,index)=><div className="mobile-item"key={`${movement.canonicalId}-${index}`}><b>{item.quantity}</b><span>{item.description}<small>{item.unit||"items"}</small></span></div>)}{movement.notes&&<p className="movement-notes">Notes: {movement.notes}</p>}</div>)}{stop.requirementRefs.flatMap(ref=>requirements.find(requirement=>requirement.canonicalId===ref.requirementId)?.lines||[]).map(line=><div className="mobile-item"key={line.canonicalId}><b>{line.quantity}</b><span>{line.displayNameSnapshot}<small>{line.unit}</small></span></div>)}<button className="navigate">Navigate ↗</button><div className="touch-actions"><button onClick={()=>void onUpdate(stop,"arrived")}>Arrived</button><button onClick={()=>void onUpdate(stop,"completed")}>Complete</button><button className="issue"onClick={()=>void onUpdate(stop,"issue")}>Report issue</button></div></section>}
