"use client";
import { useEffect, useState } from "react";
import type { DeliveryRun, DeliveryStop } from "../../lib/types";
import type { FulfilmentRequirement } from "../../../shared/fulfilment-requirement";
type Data={requirements:FulfilmentRequirement[];runs:DeliveryRun[];stops:DeliveryStop[]};

export default function Mobile(){
 const [driver,setDriver]=useState("Franco"); const [data,setData]=useState<Data>(); const [error,setError]=useState("");
 const load=()=>fetch(`/api/logistics?serviceDate=${new Date().toISOString().slice(0,10)}`,{cache:"no-store"}).then(async response=>{const body=await response.json().catch(()=>null);if(!response.ok)throw new Error(body?.error||"Logistics is temporarily unavailable. Check that Integration Hub is running, then retry.");setData(body);setError("");}).catch(cause=>setError(cause instanceof Error?cause.message:"Logistics is temporarily unavailable."));
 useEffect(()=>{void load()},[]); const run=data?.runs.find(r=>r.driverLabel===driver); const stops=run?.orderedStopIds.map(id=>data?.stops.find(s=>s.canonicalId===id)).filter(Boolean) as DeliveryStop[]||[]; const active=stops.find(s=>s.status!=="completed");
 async function update(stop:DeliveryStop,status:DeliveryStop["status"]){const response=await fetch("/api/logistics",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"update-stop",by:driver,stop:{...stop,status}})});if(!response.ok){const body=await response.json().catch(()=>null);setError(body?.error||"The stop could not be updated.");return}await load()}
 return <main className="mobile-shell"><header><a href="/">← Planner</a><p className="eyebrow mint">FIKA OS · DRIVER</p><h1>My run</h1><select value={driver} onChange={event=>setDriver(event.target.value)}><option>Franco</option><option>Dee</option></select></header>{error&&<div className="alert" role="alert">{error}<button className="retry" onClick={()=>void load()}>Retry</button></div>}{!run?<section className="mobile-card"><p className="eyebrow">Driver workflow</p><h2>No run assigned</h2><p>{data?`No run is assigned to ${driver} yet.`:"Load the local Logistics and Integration Hub services to see today’s run."}</p></section>:<><section className="progress"><span>{driver} · {stops.filter(s=>s.status==="completed").length}/{stops.length} stops</span><strong>{active?active.locationLabelSnapshot:"Run complete"}</strong></section>{active&&<section className="next-stop"><p className="eyebrow">Next stop · {active.status}</p><h2>{active.locationLabelSnapshot}</h2><p>{active.movementType||"Delivery"} · {active.requiredTime||active.window?.startTime||"Time to confirm"}</p><div className="items">{active.requirementRefs.flatMap(ref=>data?.requirements.find(r=>r.canonicalId===ref.requirementId)?.lines||[]).map(line=><div key={line.canonicalId}><b>{line.quantity}</b><span>{line.displayNameSnapshot}<small>{line.unit}</small></span></div>)}</div><button className="navigate">Navigate ↗</button><div className="touch-actions"><button onClick={()=>void update(active,"arrived")}>Arrived</button><button onClick={()=>void update(active,"completed")}>Complete</button><button className="issue" onClick={()=>void update(active,"issue")}>Report issue</button></div></section>}<section className="upcoming"><p className="eyebrow">Upcoming stops</p>{stops.map(stop=><div className={stop.canonicalId===active?.canonicalId?"current":""} key={stop.canonicalId}><span>{stop.sequence}</span><strong>{stop.locationLabelSnapshot}</strong><small>{stop.status} · {stop.requiredTime||stop.window?.startTime||"—"}</small></div>)}</section></>}</main>
}
