"use client";
import { useEffect, useMemo, useState } from "react";
import type { BeverageInnovation, BeverageVersion, IngredientLine, Lifecycle } from "@/lib/domain";
import { lifecycleLabel, lifecycleOrder } from "@/lib/domain";

const tabs = ["Overview", "Concept", "Development", "Recipe", "Method", "Costing", "Allergens", "Equipment", "Assets", "Approvals", "Rollout", "Feedback"] as const;
const nextStage: Partial<Record<Lifecycle, Lifecycle>> = { idea: "in_development", in_development: "ready_for_approval", ready_for_approval: "brand_review", brand_review: "approved", approved: "asset_generation", asset_generation: "rollout", rollout: "live", live: "review", review: "rollout", archived: "idea" };

export default function Page() {
  const [records, setRecords] = useState<BeverageInnovation[]>([]); const [selected, setSelected] = useState<BeverageInnovation>(); const [filter, setFilter] = useState<Lifecycle | "all">("all"); const [query, setQuery] = useState(""); const [showNew, setShowNew] = useState(false); const [message, setMessage] = useState("");
  const load = () => fetch("/api/beverages").then(r => r.json()).then(v => setRecords(v.records)); useEffect(() => { void load(); }, []);
  const visible = useMemo(() => records.filter(item => (filter === "all" || item.lifecycle === filter) && (!query || `${item.name} ${item.beverageType} ${item.season || ""}`.toLowerCase().includes(query.toLowerCase()))), [records, filter, query]);
  const attention = records.filter(x => x.rollouts.some(r => r.blockers.length) || x.assets.some(a => a.status === "missing") || x.versions.some(v => v.allergenStatus !== "reviewed")).length;
  return <main className="app"><header className="topbar"><a className="brand" href="#"><img src="/fika-logo-white.png" alt="FIKA"/><span>OS</span></a><div className="top-title"><small>Innovation workspace</small><strong>Beverage Innovation</strong></div><div className="role">Administrator<br/><span>local development</span></div><button className="mint" onClick={() => setShowNew(true)}>+ New concept</button></header>
    <section className="hero"><div><small>FROM IDEA TO A DRINK WORTH SERVING</small><h1>Make something<br/><em>people remember.</em></h1><p>Explore, test and launch beverages with one clear record of the concept, its versions, approvals and site readiness.</p></div><div className="hero-note"><b>{records.length}</b><span>concepts in the pipeline</span><b>{attention}</b><span>need attention</span></div></section>
    <section className="workspace"><div className="quick-grid">{[["My work", records.filter(x => ["idea", "in_development"].includes(x.lifecycle)).length, "in_development"], ["Awaiting approval", records.filter(x => ["ready_for_approval", "brand_review"].includes(x.lifecycle)).length, "brand_review"], ["Upcoming launches", records.filter(x => x.lifecycle === "rollout").length, "rollout"], ["Live drinks", records.filter(x => x.lifecycle === "live").length, "live"]].map(([label, value, stage]) => <button key={String(label)} className="quick" onClick={() => setFilter(stage as Lifecycle)}><strong>{value}</strong><span>{label}</span></button>)}</div>
      <div className="toolbar"><div><small>PIPELINE</small><h2>Drinks worth developing</h2></div><div className="filters"><input aria-label="Search beverages" placeholder="Search by name, type or season" value={query} onChange={e => setQuery(e.target.value)}/><select aria-label="Filter lifecycle" value={filter} onChange={e => setFilter(e.target.value as Lifecycle | "all")}><option value="all">All stages</option>{lifecycleOrder.map(k => <option key={k} value={k}>{lifecycleLabel[k]}</option>)}</select></div></div>
      {message && <p className="message">{message}</p>}<div className="cards">{visible.map(item => <button className="beverage-card" key={item.id} onClick={() => setSelected(item)}><div className="card-top"><span className={`stage stage--${item.lifecycle}`}>{lifecycleLabel[item.lifecycle]}</span><span>{item.beverageType}</span></div><h3>{item.name}</h3><p>{item.description}</p><div className="card-progress"><span style={{ width: `${Math.min(100, item.versions.length * 25 + (item.approvals.length ? 25 : 0) + (item.rollouts.length ? 25 : 0))}%` }}/></div><footer><span>{item.versions.length} version{item.versions.length === 1 ? "" : "s"}</span><span>{item.rollouts.length} rollout{item.rollouts.length === 1 ? "" : "s"}</span></footer></button>)}</div>{!visible.length && <div className="empty"><h3>No concepts match.</h3><p>Try another stage or create a new idea.</p></div>}</section>
    {selected && <Detail record={selected} close={() => setSelected(undefined)} refresh={async () => { await load(); const r = await fetch("/api/beverages").then(x => x.json()); setSelected(r.records.find((x: BeverageInnovation) => x.id === selected.id)); }} setMessage={setMessage}/>} {showNew && <New close={() => setShowNew(false)} refresh={load} setMessage={setMessage}/>}</main>;
}

function Detail({ record, close, refresh, setMessage }: { record: BeverageInnovation; close: () => void; refresh: () => Promise<void>; setMessage: (s: string) => void }) {
  const [tab, setTab] = useState<(typeof tabs)[number]>("Overview"); const [busy, setBusy] = useState(false); const next = nextStage[record.lifecycle];
  const move = async (to: Lifecycle) => { setBusy(true); const r = await fetch("/api/beverages", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: record.id, lifecycle: to }) }); const b = await r.json(); setBusy(false); if (!r.ok) return setMessage(b.error); setMessage(`Moved to ${lifecycleLabel[to]}.`); await refresh(); };
  const approval = async (kind: "operational" | "brand") => { setBusy(true); const r = await fetch("/api/beverages", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: record.id, action: "approval", kind, decision: "approved", actorRole: kind === "brand" ? "Marketing and brand approver" : "Coffee and beverage leadership" }) }); const b = await r.json(); setBusy(false); if (!r.ok) return setMessage(b.error); setMessage("Approval recorded."); await refresh(); };
  return <div className="backdrop"><aside className="drawer"><header><div><small>{record.id}</small><h2>{record.name}</h2><span className={`stage stage--${record.lifecycle}`}>{lifecycleLabel[record.lifecycle]}</span></div><button className="close" onClick={close}>×</button></header><nav className="drawer-tabs">{tabs.map(t => <button key={t} className={tab === t ? "active" : ""} onClick={() => setTab(t)}>{t}</button>)}</nav><div className="drawer-body"><section className="summary"><p>{record.description}</p><dl><dt>Type</dt><dd>{record.beverageType}</dd><dt>Owner</dt><dd>{record.ownerRole}</dd><dt>Season</dt><dd>{record.season || "Not set"}</dd><dt>Versions</dt><dd>{record.versions.length}</dd></dl></section>
      {tab === "Overview" && <><Panel title="Next steps"><p>Keep the record moving with explicit development, approval and rollout evidence.</p>{next && <button disabled={busy} className="purple" onClick={() => void move(next)}>Move to {lifecycleLabel[next]}</button>}</Panel><Panel title="Attention required">{record.rollouts.flatMap(r => r.blockers).concat(record.assets.filter(a => a.status === "missing").map(a => `${a.type} asset is missing`), record.versions.filter(v => v.allergenStatus !== "reviewed").map(() => "Allergen source is not yet governed")).map((x, i) => <p className="notice" key={i}>{x}</p>)}</Panel></>}
      {tab === "Concept" && <Panel title="Concept brief"><dl><dt>Flavour direction</dt><dd>{record.concept.flavourDirection || "Not set"}</dd><dt>Use case</dt><dd>{record.concept.useCase || "Not set"}</dd><dt>Service format</dt><dd>{record.concept.serviceFormat || "Not set"}</dd><dt>Seasonal context</dt><dd>{record.concept.seasonalContext || "Not set"}</dd></dl></Panel>}
      {tab === "Development" && <Panel title="Prototypes">{record.prototypes.length ? record.prototypes.map(p => <div className="list-row" key={p.id}><b>{p.name}</b><span>{p.notes}</span></div>) : <p className="muted">No prototypes recorded yet.</p>}<button className="soft" onClick={async () => { const r = await fetch("/api/beverages", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: record.id, action: "version" }) }); if (r.ok) { setMessage("New immutable version created."); await refresh(); } }}>Create next version</button></Panel>}
      {(tab === "Recipe" || tab === "Method" || tab === "Costing") && <VersionEditor record={record} refresh={refresh} setMessage={setMessage} focus={tab}/>} {tab === "Allergens" && <Panel title="Allergen evidence"><p className="muted">Allergen derivation remains pending the approved canonical ingredient source.</p>{record.versions.map(v => <div className="version" key={v.id}><b>Version {v.number}</b><p>Status: {v.allergenStatus}</p></div>)}</Panel>} {tab === "Equipment" && <Panel title="Equipment requirements">{record.versions.map(v => <div className="version" key={v.id}><b>Version {v.number}</b><p>{v.equipment.join(", ") || "No equipment recorded"}</p></div>)}</Panel>}
      {tab === "Approvals" && <Panel title="Approval history"><div className="approval-grid">{(["operational", "brand"] as const).map(kind => <div className="approval" key={kind}><b>{kind === "brand" ? "Brand approval" : "Operational approval"}</b><span>{record.approvals.find(a => a.kind === kind)?.decision || "pending"}</span><button className="soft" disabled={busy || (record.lifecycle !== "brand_review" && record.lifecycle !== "ready_for_approval")} onClick={() => void approval(kind)}>Approve</button></div>)}</div></Panel>}
      {tab === "Rollout" && <Panel title="Site rollout readiness">{record.rollouts.length ? record.rollouts.map(r => <div className="list-row" key={r.id}><b>{r.siteLabel}</b><span>{r.state}{r.blockers.length ? ` · ${r.blockers.join(", ")}` : " · no blockers"}</span></div>) : <p className="muted">No site rollout created yet.</p>}</Panel>}{tab === "Assets" && <Panel title="Asset checklist">{record.assets.map(a => <div className="list-row" key={a.id}><b>{a.type}</b><span>{a.status}</span></div>)}</Panel>}{tab === "Feedback" && <Panel title="Site feedback">{record.feedback.length ? record.feedback.map(f => <div className="list-row" key={f.id}><b>{f.siteLabel}</b><span>{f.note}</span></div>) : <p className="muted">No feedback recorded yet.</p>}</Panel>}</div><footer><button className="soft" onClick={close}>Close</button></footer></aside></div>;
}

function VersionEditor({ record, refresh, setMessage, focus }: { record: BeverageInnovation; refresh: () => Promise<void>; setMessage: (s: string) => void; focus: "Recipe" | "Method" | "Costing" }) {
  const version = record.versions.find(v => v.id === record.currentVersionId) || record.versions.at(-1); const [recipe, setRecipe] = useState(version?.recipeNotes || ""); const [method, setMethod] = useState(version?.method || ""); const [ingredients, setIngredients] = useState<IngredientLine[]>(version?.ingredients || []); const [name, setName] = useState(""); const [amount, setAmount] = useState(""); const [unit, setUnit] = useState("mL"); const [cost, setCost] = useState(""); const [saving, setSaving] = useState(false);
  if (!version) return <Panel title={focus}><p className="muted">Create a development version first.</p></Panel>;
  const add = () => { if (!name.trim()) return; setIngredients([...ingredients, { id: `${version.id}:ingredient:${Date.now()}`, name: name.trim(), amount: Number(amount) || undefined, unit, costPerUnit: Number(cost) || undefined, sourceStatus: "deferred" }]); setName(""); setAmount(""); setCost(""); };
  const total = ingredients.reduce((sum, i) => sum + (i.amount || 0) * (i.costPerUnit || 0), 0);
  const save = async () => { setSaving(true); const r = await fetch("/api/beverages", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: record.id, action: "updateVersion", versionId: version.id, recipeNotes: recipe, method, ingredients, equipment: version.equipment }) }); const b = await r.json(); setSaving(false); if (!r.ok) return setMessage(b.error); setMessage(`Version ${version.number} saved.`); await refresh(); };
  return <Panel title={`${focus} · Version ${version.number}`}><div className="editor-stack">{focus === "Recipe" && <><label>Recipe notes<textarea value={recipe} onChange={e => setRecipe(e.target.value)} rows={3}/></label><h4>Ingredients per drink</h4><div className="ingredient-add"><input aria-label="Ingredient name" placeholder="Ingredient" value={name} onChange={e => setName(e.target.value)}/><input aria-label="Ingredient amount" type="number" min="0" step="any" placeholder="Amount" value={amount} onChange={e => setAmount(e.target.value)}/><select aria-label="Ingredient unit" value={unit} onChange={e => setUnit(e.target.value)}><option>mL</option><option>g</option><option>kg</option><option>piece</option><option>dash</option><option>to taste</option></select><input aria-label="Ingredient cost" type="number" min="0" step="any" placeholder="Cost / unit" value={cost} onChange={e => setCost(e.target.value)}/><button type="button" className="soft" onClick={add}>Add</button></div>{ingredients.map((i, index) => <div className="ingredient-row" key={i.id}><b>{i.name}</b><span>{i.amount ?? "—"} {i.unit || ""}</span><span>£{((i.amount || 0) * (i.costPerUnit || 0)).toFixed(2)}</span><button type="button" className="link-danger" onClick={() => setIngredients(ingredients.filter((_, n) => n !== index))}>Remove</button></div>)}</>}{focus === "Method" && <label>Method and service guidance<textarea value={method} onChange={e => setMethod(e.target.value)} rows={8}/></label>}{focus === "Costing" && <><p className="cost-total">Estimated cost per drink <strong>£{total.toFixed(2)}</strong></p>{ingredients.length ? ingredients.map(i => <div className="ingredient-row" key={i.id}><span>{i.name}</span><span>{i.amount ?? "—"} {i.unit || ""}</span><b>£{((i.amount || 0) * (i.costPerUnit || 0)).toFixed(2)}</b></div>) : <p className="muted">Add ingredients in the Recipe tab to calculate cost.</p>}</>}<button disabled={saving} className="purple" onClick={() => void save()}>Save version</button></div></Panel>;
}

function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="panel"><h3>{title}</h3>{children}</section>; }
function New({ close, refresh, setMessage }: { close: () => void; refresh: () => Promise<void>; setMessage: (s: string) => void }) { const [name, setName] = useState(""); const [type, setType] = useState("Signature drink"); const [description, setDescription] = useState(""); const save = async (e: React.FormEvent) => { e.preventDefault(); const r = await fetch("/api/beverages", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name, beverageType: type, description }) }); const b = await r.json(); if (!r.ok) return setMessage(b.error); setMessage("Idea created — development evidence can now be added."); await refresh(); close(); }; return <div className="backdrop"><form className="drawer form" onSubmit={save}><header><div><small>New governed concept</small><h2>Start an idea</h2></div><button type="button" className="close" onClick={close}>×</button></header><div className="drawer-body"><label>Name<input required value={name} onChange={e => setName(e.target.value)} placeholder="e.g. Raspberry & Rose Iced Matcha"/></label><label>Beverage type<select value={type} onChange={e => setType(e.target.value)}><option>Signature drink</option><option>Coffee</option><option>Tea / matcha</option><option>Mocktail</option><option>Cocktail</option><option>Soft drink</option></select></label><label>Description<textarea required value={description} onChange={e => setDescription(e.target.value)} rows={4}/></label><p className="help">A concept starts as an Idea. Ingredient, allergen and performance sources remain deliberate follow-up work.</p></div><footer><button className="purple">Save idea</button><button type="button" className="soft" onClick={close}>Cancel</button></footer></form></div>; }
