export type MenuWeekStatus = "draft" | "imported" | "needs_review" | "in_review" | "approved" | "published" | "superseded" | "archived";
export type ReviewStatus = "unreviewed" | "ready" | "approved" | "ignored" | "blocked" | "archived";
export type RecipeStatus = "draft" | "active" | "under_review" | "archived";
export type MenuExceptionSeverity = "warning" | "blocking";
export type Audit = { action: string; at: string; by: string; reason?: string };
export type AllergenEvidence = { allergen: string; value: "contains" | "free_from" | "may_contain" | "unknown"; source: string; reviewedBy?: string; reviewedAt?: string; notes?: string };
export type RecipeIngredient = { name: string; quantity?: number; unit?: string; rawText?: string };
export type MenuItem = { canonicalId: string; sourceName: string; displayName: string; description?: string; preparationDescription?: string; category: string; subcategory?: string; recipeStatus?: RecipeStatus; ingredients?: RecipeIngredient[]; yield?: number; yieldUnit?: string; yieldDescription?: string; portionSize?: number; servingGuidance?: string; preparationNotes?: string; holdingStorageNotes?: string; methodSteps?: string[]; mayContainNotes?: string; sourceEvidence?: { document: string; excerpt?: string; importedAt: string }; weekId: string; dayId: string; sourceReference: { workbook: string; sheet: string; range?: string; rawValue?: unknown }; revision: number; reviewStatus: ReviewStatus; duplicateWarning?: string; allergenEvidence: AllergenEvidence[]; mayContainReviewed: boolean; audit: Audit[] };
export type SiteAllocation = { canonicalId: string; menuItemId: string; weekId: string; dayId: string; siteId?: string; sourceSiteName: string; normalisedSiteName?: string; plannedQuantity?: number; quantityUnit?: string; notes?: string; reviewStatus: ReviewStatus; audit: Audit[] };
export type MenuDay = { canonicalId: string; weekId: string; date: string; dayName: string; position: number; itemIds: string[]; notes?: string; audit: Audit[] };
export type MenuWeek = { canonicalId: string; weekCommencing: string; weekEnding: string; status: MenuWeekStatus; version: number; dayIds: string[]; itemIds: string[]; allocationIds: string[]; sourceImportId?: string; reviewer?: string; publishedBy?: string; publishedAt?: string; exceptions: MenuException[]; audit: Audit[] };
export type MenuException = { canonicalId: string; type: string; severity: MenuExceptionSeverity; status: "open" | "resolved"; affected: { weekId?: string; dayId?: string; itemId?: string; siteName?: string }; description: string; sourceEvidence?: string; createdAt: string; createdBy: string; resolvedAt?: string; resolvedBy?: string; resolutionNotes?: string; audit: Audit[] };
export type MenuSnapshot = { week: MenuWeek; days: MenuDay[]; items: MenuItem[]; allocations: SiteAllocation[] };
export function deterministicId(kind: string, ...parts: string[]) { return `${kind}:${parts.map(part => part.trim().toLowerCase().replace(/[^a-z0-9]+/g, "-")).join(":")}`; }
export function publicationBlockers(snapshot: MenuSnapshot): string[] { const blockers = snapshot.week.exceptions.filter(item => item.status === "open" && item.severity === "blocking").map(item => item.description); if (!snapshot.days.length) blockers.push("All Monday-to-Friday menu days must be present."); if (snapshot.items.some(item => item.reviewStatus !== "approved")) blockers.push("Every menu item must be approved."); if (snapshot.allocations.some(item => !item.siteId || !item.plannedQuantity || item.plannedQuantity <= 0)) blockers.push("Every site allocation needs a mapped site and positive quantity."); if (snapshot.items.some(item => item.allergenEvidence.some(evidence => evidence.value === "unknown") || !item.mayContainReviewed)) blockers.push("Allergen and may-contain evidence must be reviewed."); return blockers; }
