import * as XLSX from "xlsx";
import { deterministicId, type MenuException, type MenuItem } from "./domain";
import { titleCase } from "./text";
export type ImportReport = { workbookName: string; sheets: Array<{ name: string; rows: number; columns: number; daySignal: string | null; structure: "day-menu" | "allergen-review" | "weekly-summary" | "unknown" }>; warnings: string[]; candidates: MenuItem[]; exceptions: MenuException[] };
export function inspectWorkbook(buffer: ArrayBuffer | Uint8Array, workbookName: string, actor = "local-importer"): ImportReport {
  const workbook = XLSX.read(buffer, { type: "array", cellDates: false });
  const sheets = workbook.SheetNames.map(name => { const sheet = workbook.Sheets[name]; const rows = XLSX.utils.sheet_to_json<unknown[]>(sheet, { header: 1, defval: "" }); const text = rows.flat().map(value => String(value)).join(" "); const daySignal = /(monday|tuesday|wednesday|thursday|friday)/i.exec(text)?.[1] || null; const first = rows.slice(0, 8).flat().map(value => String(value).toLowerCase()); const structure = first.includes("product") ? (daySignal ? "day-menu" : "weekly-summary") : first.some(value => value.includes("allergen checker")) ? "allergen-review" : "unknown"; return { name, rows: rows.length, columns: Math.max(0, ...rows.map(row => row.length)), daySignal, structure: structure as "day-menu" | "allergen-review" | "weekly-summary" | "unknown" }; });
  const candidates: MenuItem[] = []; const exceptions: MenuException[] = []; const warnings: string[] = [];
  for (const sheetName of workbook.SheetNames) { const rows = XLSX.utils.sheet_to_json<unknown[]>(workbook.Sheets[sheetName], { header: 1, defval: "" }); const headerIndex = rows.findIndex(row => row.some(value => String(value).trim().toLowerCase() === "product")); if (headerIndex < 0) continue; const header = rows[headerIndex].map(value => String(value).trim()); rows.slice(headerIndex + 1).forEach((row, offset) => { const sourceLabel = String(row[0] || "").trim(); const dish = String(row[1] || "").trim(); const rawName = dish || sourceLabel; if (!rawName || !/\S/.test(rawName)) return; const displayName = titleCase(rawName); const category = sourceLabel.split(/\s+/)[0].toLowerCase() || "other"; const id = deterministicId("menu-item-import", workbookName, sheetName, String(headerIndex + offset + 2), rawName); const item: MenuItem = { canonicalId: id, sourceName: displayName, displayName, category, weekId: "menu-week:import-preview", dayId: deterministicId("menu-day", workbookName, sheetName), sourceReference: { workbook: workbookName, sheet: sheetName, range: `A${headerIndex + offset + 2}`, rawValue: { row, header } }, revision: 1, reviewStatus: "unreviewed", allergenEvidence: [], mayContainReviewed: false, audit: [{ action: "import-candidate-created", at: new Date().toISOString(), by: actor }] }; candidates.push(item); if (category === "other") warnings.push(`Unmapped category for ${displayName} on ${sheetName}.`); exceptions.push({ canonicalId: deterministicId("menu-exception", id, "allergen"), type: "missing_allergen_evidence", severity: "blocking", status: "open", affected: { itemId: id }, description: `Allergen evidence is missing for ${displayName}.`, sourceEvidence: `${sheetName}!A${headerIndex + offset + 2}`, createdAt: new Date().toISOString(), createdBy: actor, audit: [{ action: "exception-created", at: new Date().toISOString(), by: actor }] }); }); }
  return { workbookName, sheets, warnings, candidates, exceptions };
}
