import { demoSnapshot } from "@/fixtures/demo";
import { publicationBlockers, type MenuSnapshot } from "./domain";
import { normaliseDishName } from "./text";
import { normaliseDishCategory } from "./dish-categories";

let state: MenuSnapshot = structuredClone(demoSnapshot);
state.items.forEach(item => { item.category = normaliseDishCategory(item.category); });
export function getMenuSnapshot() { return structuredClone(state); }
export function runMenuCommand(command: { action: string; itemId?: string; dayId?: string; exceptionId?: string; allocationId?: string; displayName?: string; description?: string; preparationDescription?: string; category?: string; subcategory?: string; recipeStatus?: "draft" | "active" | "under_review" | "archived"; ingredients?: Array<{ name: string; quantity?: number; unit?: string; rawText?: string }>; yield?: number; yieldUnit?: string; yieldDescription?: string; portionSize?: number; servingGuidance?: string; preparationNotes?: string; holdingStorageNotes?: string; methodSteps?: string[]; mayContainNotes?: string; allergenEvidence?: MenuSnapshot["items"][number]["allergenEvidence"]; sourceEvidence?: { document: string; excerpt?: string; importedAt: string }; sourceReference?: { workbook: string; sheet: string; range?: string; rawValue?: unknown }; importedCandidate?: MenuSnapshot["items"][number]; reason?: string; siteId?: string; sourceSiteName?: string; plannedQuantity?: number; quantityUnit?: string; allergen?: string; allergenValue?: "contains" | "free_from" | "may_contain" | "unknown"; evidenceSource?: string }) {
  const now = new Date().toISOString();
  if (command.action === "create-item") {
    if (!command.displayName?.trim()) throw Object.assign(new Error("A dish name is required."), { status: 422 });
    const id = `menu-item:local:${Date.now()}`; const displayName = normaliseDishName(command.displayName); state.items.push({ canonicalId: id, sourceName: displayName, displayName, description: command.description?.trim(), preparationDescription: command.preparationDescription?.trim(), category: normaliseDishCategory(command.category), subcategory: command.subcategory?.trim() || undefined, recipeStatus: command.recipeStatus || "draft", ingredients: command.ingredients || [], yield: command.yield, yieldUnit: command.yieldUnit?.trim() || undefined, yieldDescription: command.yieldDescription?.trim() || undefined, portionSize: command.portionSize, servingGuidance: command.servingGuidance?.trim() || undefined, preparationNotes: command.preparationNotes?.trim() || undefined, holdingStorageNotes: command.holdingStorageNotes?.trim() || undefined, methodSteps: command.methodSteps?.filter(Boolean), mayContainNotes: command.mayContainNotes?.trim() || undefined, sourceEvidence: command.sourceEvidence, weekId: state.week.canonicalId, dayId: "", sourceReference: command.sourceReference || { workbook: "local", sheet: "Menu Planning" }, revision: 1, reviewStatus: "unreviewed", allergenEvidence: command.allergenEvidence || [], mayContainReviewed: false, audit: [{ action: "recipe-created", at: now, by: "local-menu-reviewer" }] });
  } else if (command.action === "import-recipe-candidate") {
    const candidate = command.importedCandidate;
    if (!candidate?.canonicalId || !candidate.displayName?.trim()) throw Object.assign(new Error("A valid recipe candidate is required."), { status: 422 });
    if (!state.items.some(item => item.canonicalId === candidate.canonicalId)) state.items.push({ ...structuredClone(candidate), category: normaliseDishCategory(candidate.category), audit: [...candidate.audit, { action: "recipe-candidate-imported", at: now, by: "local-menu-reviewer" }] });
  } else if (command.action === "approve-item") {
    const item = state.items.find(value => value.canonicalId === command.itemId); if (!item) throw Object.assign(new Error("Menu item was not found."), { status: 404 });
    item.reviewStatus = "approved"; item.audit.push({ action: "menu-item-approved", at: now, by: "local-menu-reviewer" });
  } else if (command.action === "edit-item") {
    const item = state.items.find(value => value.canonicalId === command.itemId); if (!item || !command.displayName?.trim()) throw Object.assign(new Error("A menu item name is required."), { status: 422 });
    if (state.week.status === "published") throw Object.assign(new Error("Published menus are immutable. Create a new revision first."), { status: 409 });
    Object.assign(item, { displayName: normaliseDishName(command.displayName), sourceName: normaliseDishName(command.displayName), description: command.description ?? item.description, preparationDescription: command.preparationDescription ?? item.preparationDescription, category: command.category ? normaliseDishCategory(command.category) : item.category, subcategory: command.subcategory ?? item.subcategory, ingredients: command.ingredients ?? item.ingredients, yield: command.yield ?? item.yield, yieldUnit: command.yieldUnit ?? item.yieldUnit, yieldDescription: command.yieldDescription ?? item.yieldDescription, portionSize: command.portionSize ?? item.portionSize, servingGuidance: command.servingGuidance ?? item.servingGuidance, preparationNotes: command.preparationNotes ?? item.preparationNotes, holdingStorageNotes: command.holdingStorageNotes ?? item.holdingStorageNotes, methodSteps: command.methodSteps ?? item.methodSteps, mayContainNotes: command.mayContainNotes ?? item.mayContainNotes }); item.revision += 1; item.reviewStatus = "unreviewed"; item.audit.push({ action: "menu-item-amended", at: now, by: "local-menu-reviewer", reason: command.reason });
  } else if (command.action === "duplicate-item") {
    const item = state.items.find(value => value.canonicalId === command.itemId); if (!item) throw Object.assign(new Error("Menu item was not found."), { status: 404 });
    const id = `menu-item:copy:${Date.now()}`; state.items.push({ ...structuredClone(item), canonicalId: id, displayName: `${item.displayName} (copy)`, sourceName: `${item.sourceName} (copy)`, reviewStatus: "unreviewed", audit: [{ action: "recipe-duplicated", at: now, by: "local-menu-reviewer", reason: command.reason }] });
  } else if (command.action === "archive-item") {
    const item = state.items.find(value => value.canonicalId === command.itemId); if (!item) throw Object.assign(new Error("Menu item was not found."), { status: 404 }); item.reviewStatus = "archived"; item.recipeStatus = "archived"; item.audit.push({ action: "recipe-archived", at: now, by: "local-menu-reviewer", reason: command.reason });
  } else if (command.action === "restore-item") {
    const item = state.items.find(value => value.canonicalId === command.itemId); if (!item) throw Object.assign(new Error("Menu item was not found."), { status: 404 }); item.reviewStatus = "unreviewed"; item.recipeStatus = "draft"; item.audit.push({ action: "recipe-restored", at: now, by: "local-menu-reviewer", reason: command.reason });
  } else if (command.action === "remove-from-day") {
    for (const day of state.days) day.itemIds = day.itemIds.filter(id => id !== command.itemId); state.week.itemIds = state.week.itemIds.filter(id => id !== command.itemId);
  } else if (command.action === "add-to-day") {
    const day = state.days.find(value => value.canonicalId === command.dayId); const item = state.items.find(value => value.canonicalId === command.itemId); if (!day || !item) throw Object.assign(new Error("Day or dish was not found."), { status: 404 }); if (state.week.status === "published") throw Object.assign(new Error("Published menus are immutable. Create a new revision first."), { status: 409 }); if (!day.itemIds.includes(item.canonicalId)) day.itemIds.push(item.canonicalId); if (!state.week.itemIds.includes(item.canonicalId)) state.week.itemIds.push(item.canonicalId); day.audit.push({ action: "menu-item-added", at: now, by: "local-menu-reviewer", reason: command.reason });
  } else if (command.action === "allocate-site") {
    const item = state.items.find(value => value.canonicalId === command.itemId); if (!item || !command.siteId || !command.sourceSiteName || !command.plannedQuantity || command.plannedQuantity <= 0) throw Object.assign(new Error("A dish, site and positive planned quantity are required."), { status: 422 }); if (state.week.status === "published") throw Object.assign(new Error("Published menus are immutable. Create a new revision first."), { status: 409 }); const day = state.days.find(value => value.itemIds.includes(item.canonicalId)); state.allocations.push({ canonicalId: `allocation:${item.canonicalId}:${command.siteId}:${Date.now()}`, menuItemId: item.canonicalId, weekId: state.week.canonicalId, dayId: day?.canonicalId || item.dayId, siteId: command.siteId, sourceSiteName: command.sourceSiteName, normalisedSiteName: command.sourceSiteName.trim().toLowerCase(), plannedQuantity: command.plannedQuantity, quantityUnit: command.quantityUnit || "portion", reviewStatus: "ready", audit: [{ action: "site-allocated", at: now, by: "local-menu-reviewer" }] });
  } else if (command.action === "remove-allocation") {
    const before = state.allocations.length; state.allocations = state.allocations.filter(value => value.canonicalId !== command.allocationId); if (before === state.allocations.length) throw Object.assign(new Error("Allocation was not found."), { status: 404 });
  } else if (command.action === "review-allergen") {
    const item = state.items.find(value => value.canonicalId === command.itemId); if (!item || !command.allergen || !command.allergenValue || !command.evidenceSource) throw Object.assign(new Error("Allergen, value and evidence source are required."), { status: 422 }); const existing = item.allergenEvidence.find(value => value.allergen === command.allergen); if (existing) Object.assign(existing, { value: command.allergenValue, source: command.evidenceSource, reviewedBy: "local-menu-reviewer", reviewedAt: now }); else item.allergenEvidence.push({ allergen: command.allergen, value: command.allergenValue, source: command.evidenceSource, reviewedBy: "local-menu-reviewer", reviewedAt: now }); item.mayContainReviewed = true; item.reviewStatus = "ready"; item.audit.push({ action: "allergen-evidence-reviewed", at: now, by: "local-menu-reviewer", reason: command.reason });
  } else if (command.action === "submit-review") {
    if (state.week.status === "published") throw Object.assign(new Error("Published menus are immutable."), { status: 409 }); state.week.status = "in_review"; state.week.reviewer = "local-menu-reviewer"; state.week.audit.push({ action: "menu-submitted-for-review", at: now, by: "local-menu-reviewer", reason: command.reason });
  } else if (command.action === "approve-menu") {
    const blockers = publicationBlockers(state); if (blockers.length) throw Object.assign(new Error(blockers.join(" ")), { status: 422 }); state.week.status = "approved"; state.week.reviewer = "local-menu-reviewer"; state.week.audit.push({ action: "menu-approved", at: now, by: "local-menu-reviewer", reason: command.reason });
  } else if (command.action === "new-revision") {
    if (state.week.status !== "published") throw Object.assign(new Error("A new revision can only be created from a published menu."), { status: 409 }); state.week.status = "draft"; state.week.version += 1; state.week.publishedAt = undefined; state.week.publishedBy = undefined; state.week.audit.push({ action: "menu-revision-created", at: now, by: "local-menu-reviewer" });
  } else if (command.action === "resolve-exception") {
    const exception = state.week.exceptions.find(value => value.canonicalId === command.exceptionId); if (!exception) throw Object.assign(new Error("Exception was not found."), { status: 404 });
    exception.status = "resolved"; exception.resolvedAt = now; exception.resolvedBy = "local-menu-reviewer"; exception.resolutionNotes = command.reason; exception.audit.push({ action: "menu-exception-resolved", at: now, by: "local-menu-reviewer", reason: command.reason });
  } else if (command.action === "publish") {
    const blockers = publicationBlockers(state); if (blockers.length) throw Object.assign(new Error(blockers.join(" ")), { status: 422 });
    state.week.status = "published"; state.week.publishedBy = "local-menu-reviewer"; state.week.publishedAt = now; state.week.audit.push({ action: "menu-week-published", at: now, by: "local-menu-reviewer" });
  } else { throw Object.assign(new Error("Unsupported menu command."), { status: 400 }); }
  return getMenuSnapshot();
}
