import type { DocumentData } from "firebase-admin/firestore";
import { db } from "../firebase-admin";
import type { AccessAuditEvent, AppAssignment, ApplicationRegistryEntry, AuditPage, AuthIdentity, AuthorityGrant, CustodianAssignment, DelegationRecord, ImportRecord, ImportRowResolution, LegendReference, ServicePrincipal, SiteAssignment } from "./model";
import { assertExpectedVersion, type AuthModRepository, type OplocReference } from "./repository";
const collections = { identities: "authmodIdentities", custodians: "authmodCustodianAssignments", applications: "authmodApplications", sites: "authmodSiteAssignments", apps: "authmodAppAssignments", grants: "authmodAuthorityGrants", delegations: "authmodDelegations", services: "authmodServicePrincipals", imports: "authmodImports", resolutions: "authmodImportResolutions", audits: "authmodAccessAudit" } as const;
async function readAll<T>(name: string) { return (await db.collection(name).get()).docs.map(document => document.data() as T); }
type CanonicalOploc = { canonicalId?: string; entityType?: string; lifecycleStatus?: string; publicationStatus?: string; record?: Record<string, unknown> };
function activeOploc(record: CanonicalOploc, oplocId: string) { return record.entityType === "OPLOC" && record.canonicalId === oplocId && record.lifecycleStatus !== "archived" && record.publicationStatus !== "withdrawn" && String(record.record?.lifecycleState || "active") === "active"; }
function save<T extends { version: number }>(name: string, id: string, value: T, expectedVersion?: number) {
  return db.runTransaction(async transaction => { const ref = db.collection(name).doc(id); const snapshot = await transaction.get(ref); assertExpectedVersion(snapshot.exists ? Number(snapshot.data()?.version) : undefined, expectedVersion); transaction.set(ref, value as unknown as DocumentData); });
}
export class FirestoreAuthModRepository implements AuthModRepository {
  async getIdentity(id: string) { const snapshot = await db.collection(collections.identities).doc(id).get(); return snapshot.exists ? snapshot.data() as AuthIdentity : undefined; }
  async listIdentities() { return readAll<AuthIdentity>(collections.identities); }
  async listLegendReferences(search = "", limit = 100) { const records = await readAll<{ canonicalId?: string; entityType?: string; lifecycleStatus?: string; record?: Record<string, unknown> }>("integrationHubCanonical"); const needle = search.trim().toLowerCase(); return records.filter(value => value.entityType === "Legend" && value.canonicalId && value.lifecycleStatus !== "archived" && (!needle || String(value.record?.displayName || value.record?.preferredName || value.canonicalId).toLowerCase().includes(needle))).slice(0, Math.min(limit, 200)).map(value => ({ id: value.canonicalId!, label: String(value.record?.displayName || value.record?.preferredName || value.canonicalId), active: true })); }
  async findIdentityByExternal(provider: string, uid: string) { const snapshot = await db.collection(collections.identities).where("externalProvider", "==", provider).where("externalUid", "==", uid).limit(1).get(); return snapshot.empty ? undefined : snapshot.docs[0].data() as AuthIdentity; }
  async findIdentityByEmail(email: string) { const snapshot = await db.collection(collections.identities).where("normalizedEmail", "==", email.trim().toLowerCase()).limit(1).get(); return snapshot.empty ? undefined : snapshot.docs[0].data() as AuthIdentity; }
  async findIdentityByLegend(legendId: string) { const snapshot = await db.collection(collections.identities).where("legendId", "==", legendId).limit(1).get(); return snapshot.empty ? undefined : snapshot.docs[0].data() as AuthIdentity; }
  async saveIdentity(value: AuthIdentity, expectedVersion?: number) { await save(collections.identities, value.id, value, expectedVersion); }
  async saveIdentityWithAudit(value: AuthIdentity, audit: AccessAuditEvent, expectedVersion?: number) { await db.runTransaction(async transaction => { const ref = db.collection(collections.identities).doc(value.id); const snapshot = await transaction.get(ref); assertExpectedVersion(snapshot.exists ? Number(snapshot.data()?.version) : undefined, expectedVersion); transaction.set(ref, value as unknown as DocumentData); transaction.create(db.collection(collections.audits).doc(audit.id), audit as unknown as DocumentData); }); }
  async listCustodianAssignments(operationalIdentityId: string) { const snapshot = await db.collection(collections.custodians).where("operationalIdentityId", "==", operationalIdentityId).get(); return snapshot.docs.map(document => document.data() as CustodianAssignment); }
  async saveCustodianHandover(input: { prior?: CustodianAssignment; next: CustodianAssignment; audit: AccessAuditEvent; expectedPriorVersion?: number }) { await db.runTransaction(async transaction => { const priorRef = input.prior ? db.collection(collections.custodians).doc(input.prior.id) : undefined; const priorSnapshot = priorRef ? await transaction.get(priorRef) : undefined; assertExpectedVersion(priorSnapshot?.exists ? Number(priorSnapshot.data()?.version) : undefined, input.expectedPriorVersion); if (priorRef) transaction.set(priorRef, input.prior as unknown as DocumentData); transaction.set(db.collection(collections.custodians).doc(input.next.id), input.next as unknown as DocumentData); transaction.create(db.collection(collections.audits).doc(input.audit.id), input.audit as unknown as DocumentData); }); }
  async listApplications() { return readAll<ApplicationRegistryEntry>(collections.applications); }
  async getApplication(appId: string) { const snapshot = await db.collection(collections.applications).doc(appId).get(); return snapshot.exists ? snapshot.data() as ApplicationRegistryEntry : undefined; }
  async saveApplication(value: ApplicationRegistryEntry, expectedVersion?: number) { await save(collections.applications, value.appId, value, expectedVersion); }
  async listActiveOplocs() { const records = await readAll<CanonicalOploc>("integrationHubCanonical"); return records.filter(record => record.entityType === "OPLOC" && record.canonicalId && record.lifecycleStatus !== "archived" && record.publicationStatus !== "withdrawn" && String(record.record?.lifecycleState || "active") === "active").map(record => ({ id: record.canonicalId!, label: String(record.record?.approvedName || record.canonicalId), active: true })); }
  async getActiveOploc(oplocId: string) { const snapshot = await db.collection("integrationHubCanonical").where("canonicalId", "==", oplocId).where("entityType", "==", "OPLOC").limit(1).get(); const record = snapshot.empty ? undefined : snapshot.docs[0].data() as CanonicalOploc; return record && activeOploc(record, oplocId) ? { id: oplocId, label: String(record.record?.approvedName || oplocId), active: true } : undefined; }
  async listSiteAssignments(identityId: string) { const snapshot = await db.collection(collections.sites).where("identityId", "==", identityId).get(); return snapshot.docs.map(document => document.data() as SiteAssignment); }
  async getSiteAssignment(id: string) { const snapshot = await db.collection(collections.sites).doc(id).get(); return snapshot.exists ? snapshot.data() as SiteAssignment : undefined; }
  async saveSiteAssignment(value: SiteAssignment, expectedVersion?: number) { await save(collections.sites, value.id, value, expectedVersion); }
  async saveSiteAssignmentWithAudit(value: SiteAssignment, audit: AccessAuditEvent, expectedVersion?: number) { await db.runTransaction(async transaction => { const ref = db.collection(collections.sites).doc(value.id); const snapshot = await transaction.get(ref); assertExpectedVersion(snapshot.exists ? Number(snapshot.data()?.version) : undefined, expectedVersion); transaction.set(ref, value as unknown as DocumentData); transaction.create(db.collection(collections.audits).doc(audit.id), audit as unknown as DocumentData); }); }
  async listAppAssignments(identityId: string) { const snapshot = await db.collection(collections.apps).where("identityId", "==", identityId).get(); return snapshot.docs.map(document => document.data() as AppAssignment); }
  async getAppAssignment(id: string) { const snapshot = await db.collection(collections.apps).doc(id).get(); return snapshot.exists ? snapshot.data() as AppAssignment : undefined; }
  async saveAppAssignment(value: AppAssignment, expectedVersion?: number) { await save(collections.apps, value.id, value, expectedVersion); }
  async listAuthorityGrants(subjectId: string, subjectType?: "interactive" | "service") { const query = subjectType ? db.collection(collections.grants).where("subjectId", "==", subjectId).where("subjectType", "==", subjectType) : db.collection(collections.grants).where("subjectId", "==", subjectId); const snapshot = await query.get(); return snapshot.docs.map(document => document.data() as AuthorityGrant); }
  async saveAuthorityGrant(value: AuthorityGrant, expectedVersion?: number) { await save(collections.grants, value.id, value, expectedVersion); }
  async saveAuthorityGrantWithAudit(value: AuthorityGrant, audit: AccessAuditEvent, expectedVersion?: number) { await db.runTransaction(async transaction => { const ref = db.collection(collections.grants).doc(value.id); const snapshot = await transaction.get(ref); assertExpectedVersion(snapshot.exists ? Number(snapshot.data()?.version) : undefined, expectedVersion); transaction.set(ref, value as unknown as DocumentData); transaction.create(db.collection(collections.audits).doc(audit.id), audit as unknown as DocumentData); }); }
  async getDelegation(id: string) { const snapshot = await db.collection(collections.delegations).doc(id).get(); return snapshot.exists ? snapshot.data() as DelegationRecord : undefined; }
  async listDelegations(delegateId?: string) { const query = delegateId ? db.collection(collections.delegations).where("delegateId", "==", delegateId) : db.collection(collections.delegations); const snapshot = await query.get(); return snapshot.docs.map(document => document.data() as DelegationRecord); }
  async saveDelegationWithGrant(input: { delegation: DelegationRecord; grant: AuthorityGrant; audit: AccessAuditEvent }) { await db.runTransaction(async transaction => { transaction.create(db.collection(collections.delegations).doc(input.delegation.id), input.delegation as unknown as DocumentData); transaction.create(db.collection(collections.grants).doc(input.grant.id), input.grant as unknown as DocumentData); transaction.create(db.collection(collections.audits).doc(input.audit.id), input.audit as unknown as DocumentData); }); }
  async saveStandardApplicationBundle(input: { assignment: AppAssignment; grants: AuthorityGrant[]; audit?: AccessAuditEvent; expectedAssignmentVersion?: number }) {
    await db.runTransaction(async transaction => {
      const assignmentRef = db.collection(collections.apps).doc(input.assignment.id);
      const assignmentSnapshot = await transaction.get(assignmentRef);
      assertExpectedVersion(assignmentSnapshot.exists ? Number(assignmentSnapshot.data()?.version) : undefined, input.expectedAssignmentVersion);
      transaction.set(assignmentRef, input.assignment as unknown as DocumentData);
      for (const grant of input.grants) transaction.set(db.collection(collections.grants).doc(grant.id), grant as unknown as DocumentData);
      if (input.audit) transaction.create(db.collection(collections.audits).doc(input.audit.id), input.audit as unknown as DocumentData);
    });
  }
  async revokeStandardApplicationBundle(input: { assignment: AppAssignment; grants: AuthorityGrant[]; audit?: AccessAuditEvent; expectedAssignmentVersion?: number }) {
    await db.runTransaction(async transaction => {
      const assignmentRef = db.collection(collections.apps).doc(input.assignment.id); const snapshot = await transaction.get(assignmentRef);
      assertExpectedVersion(snapshot.exists ? Number(snapshot.data()?.version) : undefined, input.expectedAssignmentVersion);
      transaction.set(assignmentRef, input.assignment as unknown as DocumentData);
      for (const grant of input.grants) transaction.set(db.collection(collections.grants).doc(grant.id), grant as unknown as DocumentData);
      if (input.audit) transaction.create(db.collection(collections.audits).doc(input.audit.id), input.audit as unknown as DocumentData);
    });
  }
  async getServicePrincipal(id: string) { const snapshot = await db.collection(collections.services).doc(id).get(); return snapshot.exists ? snapshot.data() as ServicePrincipal : undefined; }
  async listServicePrincipals() { return readAll<ServicePrincipal>(collections.services); }
  async saveServicePrincipal(value: ServicePrincipal, expectedVersion?: number) { await save(collections.services, value.id, value, expectedVersion); }
  async saveServicePrincipalWithAudit(value: ServicePrincipal, audit: AccessAuditEvent, expectedVersion?: number) { await db.runTransaction(async transaction => { const ref = db.collection(collections.services).doc(value.id); const snapshot = await transaction.get(ref); assertExpectedVersion(snapshot.exists ? Number(snapshot.data()?.version) : undefined, expectedVersion); transaction.set(ref, value as unknown as DocumentData); transaction.create(db.collection(collections.audits).doc(audit.id), audit as unknown as DocumentData); }); }
  async getImport(id: string) { const snapshot = await db.collection(collections.imports).doc(id).get(); return snapshot.exists ? snapshot.data() as ImportRecord : undefined; }
  async listImports(limit = 100) { const snapshot = await db.collection(collections.imports).orderBy("uploadedAt", "desc").limit(Math.min(limit, 200)).get(); return snapshot.docs.map(document => document.data() as ImportRecord); }
  async saveImport(value: ImportRecord, expectedVersion?: number) { await save(collections.imports, value.id, value, expectedVersion); }
  async saveImportResolution(value: ImportRowResolution, expectedVersion?: number) { await save(collections.resolutions, value.id, value, expectedVersion); }
  async listImportResolutions(importId: string) { const snapshot = await db.collection(collections.resolutions).where("importId", "==", importId).get(); return snapshot.docs.map(document => document.data() as ImportRowResolution); }
  async listAuditEvents(input: { limit?: number; cursor?: string; actorId?: string; targetId?: string } = {}): Promise<AuditPage> { const pageSize = Math.min(input.limit || 50, 200); let query: FirebaseFirestore.Query = db.collection(collections.audits); if (input.actorId) query = query.where("actorPrincipalId", "==", input.actorId); if (input.targetId) query = query.where("targetId", "==", input.targetId); if (input.cursor) query = query.where("timestamp", "<", input.cursor); query = query.orderBy("timestamp", "desc").limit(pageSize); const snapshot = await query.get(); const events = snapshot.docs.map(document => document.data() as AccessAuditEvent); return { events, ...(events.length === pageSize ? { nextCursor: events.at(-1)?.timestamp } : {}) }; }
  async appendAudit(event: AccessAuditEvent) { await db.collection(collections.audits).doc(event.id).create(event); }
}
