import crypto from "node:crypto";
import { db } from "@hub/lib/firebase-admin";
import { createCpuProductionOrder } from "@hub/lib/production-domain";
import type { Actor } from "@hub/lib/auth";
import { stableDocumentId } from "@hub/lib/canonical-editor";
import { menuHtml, quoteFor, reviewBlockers, type AdHocRequest, type AdHocLine } from "./ad-hoc-domain";
import { recordAdHocReadBudget } from "./ad-hoc-read-budget";

const collection = () => db.collection("fikaAdHocProductionRequestsV1");
const now = () => new Date().toISOString();
const actorName = (actor: Actor) => actor.name || actor.uid;
export async function listRequests(week = londonBusinessDate()) { const endExclusive = addDays(week, 7); const snap = await collection().where("serviceDate", ">=", week).where("serviceDate", "<", endExclusive).orderBy("serviceDate", "asc").limit(200).get(); recordAdHocReadBudget({ stage: "current_window_discovery", requestDocs: snap.size, serviceDateStart: week, serviceDateEndExclusive: endExclusive, knownId: false }); return snap.docs.map(doc => doc.data() as AdHocRequest); }
function addDays(date: string, days: number) { const value = new Date(`${date}T00:00:00Z`); value.setUTCDate(value.getUTCDate() + days); return value.toISOString().slice(0,10); }
function londonBusinessDate(now = new Date()) { return new Intl.DateTimeFormat("en-CA", { timeZone: "Europe/London", year: "numeric", month: "2-digit", day: "2-digit" }).format(now); }
export async function getRequest(id: string) { const snap = await collection().doc(stableDocumentId(id)).get(); recordAdHocReadBudget({ stage: "known_request_lookup", requestDocs: snap.exists ? 1 : 0, knownId: true }); return snap.exists ? snap.data() as AdHocRequest : undefined; }
export async function createRequest(input: Omit<AdHocRequest, "id"|"reference"|"version"|"createdAt"|"createdBy"|"updatedAt"|"updatedBy"|"status"|"quoteRevisions"|"audit">, actor: Actor) {
  const id = `adhoc-request:${crypto.randomUUID()}`; const timestamp = now(); const request: AdHocRequest = { ...input, id, reference: `AH-${timestamp.slice(0,10).replaceAll("-","")}-${id.slice(-6).toUpperCase()}`, version: 1, createdAt: timestamp, createdBy: actor.uid, updatedAt: timestamp, updatedBy: actor.uid, status: "DRAFT", quoteRevisions: [], audit: [{action:"request-created",at:timestamp,by:actorName(actor),version:1}] };
  await collection().doc(stableDocumentId(id)).create(request); return request;
}
export async function updateRequest(input: Partial<AdHocRequest> & { id: string; expectedVersion: number }, actor: Actor) {
  return db.runTransaction(async tx => { const ref = collection().doc(stableDocumentId(input.id)); const snap = await tx.get(ref); if (!snap.exists) throw Object.assign(new Error("Request not found."),{status:404}); const current = snap.data() as AdHocRequest; if (current.version !== input.expectedVersion) throw Object.assign(new Error("This request changed elsewhere. Refresh and review the latest version."),{status:409}); const { expectedVersion: _expectedVersion, action: _action, ...changes } = input as Partial<AdHocRequest> & { id:string; expectedVersion:number; action?:string }; const contentChanged = ["title","clientName","serviceDate","requiredReadyTime","serviceWindowEnd","destination","lines","deliveryCharge","vatRate","quoteRequired"].some(key => key in changes); const timestamp=now(); const next = { ...current, ...changes, status: contentChanged && current.status === "SENT_TO_CPU" ? "REVIEWED" as const : (changes.status || current.status), version: current.version + 1, updatedAt:timestamp, updatedBy:actor.uid, ...(contentChanged && current.currentQuoteRevisionId ? { quoteRevisions: current.quoteRevisions.map(q=>q.id===current.currentQuoteRevisionId?{...q,stale:true}:q) } : {}), audit:[...current.audit,{action:contentChanged?"request-amended":"request-updated",at:timestamp,by:actorName(actor),version:current.version+1}] }; tx.set(ref,next); return next as AdHocRequest; });
}
export async function reviewRequest(id: string, expectedVersion: number, actor: Actor) { const request=await getRequest(id); if(!request) throw Object.assign(new Error("Request not found."),{status:404}); const blockers=reviewBlockers(request); if(blockers.length) throw Object.assign(new Error(blockers.join("; ")),{status:422}); return updateRequest({id,expectedVersion,status:"REVIEWED"},actor); }
export async function generateQuote(id: string, expectedVersion: number, actor: Actor) { const request=await getRequest(id); if(!request) throw Object.assign(new Error("Request not found."),{status:404}); if(request.status!=="REVIEWED"&&request.status!=="QUOTED") throw Object.assign(new Error("Review the request before generating a quote."),{status:422}); if(reviewBlockers(request).some(item=>item.includes("price"))) throw Object.assign(new Error("Every quoted line needs a unit price."),{status:422}); const quote={...quoteFor(request,actor.uid),revision:Math.max(0,...request.quoteRevisions.map(item=>item.revision))+1}; return updateRequest({id,expectedVersion,status:"QUOTED",quoteRevisions:[...request.quoteRevisions,quote],currentQuoteRevisionId:quote.id},actor); }
export async function generateMenu(id: string, expectedVersion: number, actor: Actor) { const request=await getRequest(id); if(!request) throw new Error("Request not found."); return updateRequest({id,expectedVersion,generatedMenu:{version:request.version,generatedAt:now(),html:menuHtml(request)}},actor); }
export async function handoffToCpu(id: string, expectedVersion: number, actor: Actor) { const request=await getRequest(id); if(!request) throw new Error("Request not found."); if(request.status!=="REVIEWED"&&request.status!=="QUOTED") throw new Error("Review the request before sending it to CPU."); if(request.quoteRequired && !request.currentQuoteRevisionId) throw new Error("Generate the current quote before sending this request to CPU."); if(request.quoteRequired && request.quoteRevisions.find(q=>q.id===request.currentQuoteRevisionId)?.stale) throw new Error("The current quote is stale. Regenerate it before sending to CPU."); if(request.version!==expectedVersion) throw Object.assign(new Error("This request changed elsewhere. Refresh and review the latest version."),{status:409}); const destinationId=request.destination.oplocId||request.destination.identity; const result=await createCpuProductionOrder(actor,{clientName:request.clientName,productionCategory:request.productionCategory,serviceDate:request.serviceDate,deliveryDateTime:`${request.serviceDate}T${request.requiredReadyTime}`,requiredBy:`${request.serviceDate}T${request.requiredReadyTime}`,serviceWindow:{startTime:request.requiredReadyTime,...(request.serviceWindowEnd?{endTime:request.serviceWindowEnd}:{})},destinationOplocId:destinationId,requiresDelivery:request.deliveryRequired,deliveryLocation:request.destination.label,destinationAddress:request.destination.mode==="one_off"?{identity:request.destination.identity,label:request.destination.label,address:request.destination.address,deliveryInstructions:request.destination.deliveryInstructions,contact:request.destination.contact}:undefined,contact:request.contactName,serviceType:request.title,pax:request.pax||1,priority:request.priority,sourceReference:request.id,sourceEntityId:request.id,sourceVersion:request.version,lines:request.lines.map(line=>({itemName:line.title,customerQuantity:line.quantity,customerUnit:line.unit,productionQuantity:line.quantity,productionUnit:line.unit,dietary:line.allergens,approvedAllergenSnapshot:{allergens:line.allergens,mayContainNotes:line.mayContainNotes},notes:line.productionNotes}))},`adhoc-handoff:${request.id}:v${request.version}`); const next=await updateRequest({id,expectedVersion,status:"SENT_TO_CPU",productionOrderId:result.order.canonicalId,productionOrderVersion:result.order.version},actor); return {request:next,order:result.order,created:result.created}; }
export async function cancelRequest(id: string, expectedVersion: number, reason: string, actor: Actor) { if(!reason.trim()) throw new Error("Cancellation reason is required."); return updateRequest({id,expectedVersion,status:"CANCELLED",notes:reason},actor); }
export function lineFromInput(input: Partial<AdHocLine>, index: number): AdHocLine { return {id:input.id||`line:${crypto.randomUUID()}`,title:input.title||"",quantity:Number(input.quantity||0),unit:input.unit||"portions",unitPrice:input.unitPrice,allergens:input.allergens||{},mayContainNotes:input.mayContainNotes,productionNotes:input.productionNotes,sortOrder:index,canonicalDishId:input.canonicalDishId}; }
