import crypto from "node:crypto";
import { parseCanonical, type CanonicalEntityType } from "./schemas";
import type { Actor } from "./auth";
import { validateCanonicalId } from "./canonical-identities";
import { normaliseAddressValues } from "./address";

export type EditableEntityType = "OPLOC" | "Address" | "Legend" | "Employment" | "Operational Assignment" | "Operational Capability" | "Capability Enablement";
export type InlineAddressInput = { canonicalId: string; expectedVersion?: number; values: Record<string, unknown>; decisionReason: string; allowDistinctDuplicate?: boolean };
export type CanonicalEditorInput = { entityType: EditableEntityType; canonicalId: string; expectedVersion?: number; values: Record<string, unknown>; decisionReason: string; legacySourceCanonicalId?: string; allowDistinctDuplicate?: boolean; inlineAddress?: InlineAddressInput };

export function buildCanonicalRecord(input: CanonicalEditorInput, actor: Actor, previous?: Record<string, unknown>) {
  validateId(input.entityType, input.canonicalId); if (input.decisionReason.trim().length < 10) throw new Error("A decision reason of at least 10 characters is required.");
  const now = new Date().toISOString(); const base = previous ? { ...structuredClone(previous), version: Number(previous.version) + 1, updatedAt: now, updatedBy: actor.uid } : { schemaVersion: "0.1.0", version: 1, createdAt: now, createdBy: actor.uid, updatedAt: now, updatedBy: actor.uid, active: true, externalIdentities: [], provenanceIds: [], ownership: { providerOwned: {}, fikaOwned: { humanDecisions: [] } } };
  let record: Record<string, unknown>;
  if (input.entityType === "OPLOC") record = buildOploc(input, actor, base, previous, now);
  else if (input.entityType === "Address") record = buildAddress(input, actor, base, now);
  else if (input.entityType === "Legend") record = { ...base, entityType: "Legend", canonicalId: input.canonicalId, displayName: requiredText(input.values.displayName, "Approved name"), ...optional("preferredName", input.values.preferredName), ...optional("workEmail", input.values.workEmail) };
  else if (input.entityType === "Employment") record = { ...base, entityType: "Employment", canonicalId: input.canonicalId, legendId: requiredId(input.values.legendId, "Legend"), employmentState: requiredText(input.values.employmentState, "Employment state"), ...optional("startDate", input.values.startDate), ...optional("terminationDate", input.values.terminationDate), ...optional("contractualJobTitle", input.values.contractualJobTitle), ...optionalNumber("contractHours", input.values.contractHours) };
  else if (input.entityType === "Operational Assignment") record = { ...base, entityType: "Operational Assignment", canonicalId: input.canonicalId, legendId: requiredId(input.values.legendId, "Legend"), oplocId: requiredId(input.values.oplocId, "OPLOC"), assignmentRole: requiredText(input.values.assignmentRole, "Assignment role"), designation: input.values.designation, effectiveFrom: requiredText(input.values.effectiveFrom, "Effective from"), ...optional("effectiveTo", input.values.effectiveTo), lifecycleState: input.values.lifecycleState || "active", evidenceReferences: Array.isArray(input.values.evidenceReferences) ? input.values.evidenceReferences.map(String).filter(Boolean) : [], decisionReason: input.decisionReason, approvedBy: actor.uid, approvedAt: now };
  else if (input.entityType === "Operational Capability") record = { ...base, entityType: "Operational Capability", canonicalId: input.canonicalId, capabilityName: requiredText(input.values.capabilityName, "Capability name"), owningDomainId: requiredId(input.values.owningDomainId, "Owning domain"), businessPurpose: requiredText(input.values.businessPurpose, "Business purpose"), ...optional("eligibilitySummary", input.values.eligibilitySummary), lifecycleState: input.values.lifecycleState || "active", effectiveFrom: requiredText(input.values.effectiveFrom, "Effective from"), ...optional("effectiveTo", input.values.effectiveTo), decisionReason: input.decisionReason, approvedBy: actor.uid, approvedAt: now };
  else record = { ...base, entityType: "Capability Enablement", canonicalId: input.canonicalId, capabilityId: requiredId(input.values.capabilityId, "Operational Capability"), oplocId: requiredId(input.values.oplocId, "OPLOC"), state: input.values.state || "enabled", businessOwnerRoleId: requiredId(input.values.businessOwnerRoleId, "Business owner role"), effectiveFrom: requiredText(input.values.effectiveFrom, "Effective from"), ...optional("effectiveTo", input.values.effectiveTo), ...optional("configurationReferenceId", input.values.configurationReferenceId), decisionReason: input.decisionReason, approvedBy: actor.uid, approvedAt: now };
  preserveHumanDecision(record, actor, input.decisionReason, now);
  const parsed = parseCanonical(input.entityType as CanonicalEntityType, record); if (!parsed.success) { const issue = parsed.error.issues[0]; const path = issue?.path.map(String).join(".") || "record"; throw new Error(`Schema validation failed at ${path}: ${issue?.message || "Review this value."}`); }
  return record;
}

export function editorPreview(input: CanonicalEditorInput, actor: Actor, previous?: Record<string, unknown>) { const proposed = buildCanonicalRecord(input, actor, previous); const changes = diff(previous || {}, proposed); const address = input.entityType === "Address"; return { entityType: input.entityType, canonicalId: input.canonicalId, operation: previous ? "update" : "create", lifecycleAfterSave: address ? "published" : "needs-review", publicationAfterSave: address ? "published" : "unpublished", changes, proposed, additionalWrites: input.legacySourceCanonicalId ? ["Create confirmed legacy-source mapping to this OPLOC", "Preserve legacy source record unchanged", "Create audit event and revision"] : [address ? "Record automatic Address approval and publication with the authenticated actor" : "Create audit event and revision"] }; }
export function diff(before: Record<string, unknown>, after: Record<string, unknown>) { return [...new Set([...Object.keys(before), ...Object.keys(after)])].filter(key => JSON.stringify(before[key]) !== JSON.stringify(after[key])).map(field => ({ field, previousValue: before[field], newValue: after[field] })); }
export function stableDocumentId(value: string) { return crypto.createHash("sha256").update(value).digest("hex"); }
export function editableEntityType(value: string): value is EditableEntityType { return ["OPLOC", "Address", "Legend", "Employment", "Operational Assignment", "Operational Capability", "Capability Enablement"].includes(value); }

function buildOploc(input: CanonicalEditorInput, actor: Actor, base: Record<string, unknown>, previous: Record<string, unknown> | undefined, now: string) {
  const type = input.values.primaryLocationType; if (type !== "Site" && type !== "Venue") throw new Error("Location Type must be Site or Venue.");
  const effectiveFrom = requiredText(input.values.locationTypeEffectiveFrom, "Location Type effective date"); const current = previous?.primaryLocationType;
  let history = Array.isArray(previous?.locationTypeHistory) ? structuredClone(previous.locationTypeHistory) as Record<string, unknown>[] : [];
  if (!previous || current !== type) { history = history.map(item => item.effectiveTo ? item : { ...item, effectiveTo: `${effectiveFrom}T00:00:00.000Z` }); history.push({ assignmentId: `location-type:${crypto.randomUUID()}`, locationType: type, effectiveFrom: `${effectiveFrom}T00:00:00.000Z`, approvedBy: actor.uid, approvedAt: now, reason: input.decisionReason }); }
  const previousAliases = Array.isArray(previous?.aliases) ? previous.aliases as { alias?: unknown; recordedAt?: unknown; sourceReference?: unknown }[] : [];
  const aliases = Array.isArray(input.values.aliases) ? input.values.aliases.map(value => String(value).trim()).filter(Boolean).map(alias => previousAliases.find(item => item.alias === alias) || { alias, recordedAt: now }) : previousAliases;
  const lifecycleState = input.values.lifecycleState || "active";
  return { ...base, entityType: "OPLOC", canonicalId: input.canonicalId, approvedName: requiredText(input.values.approvedName, "Approved name"), primaryLocationType: type, locationTypeHistory: history, lifecycleState, ...(lifecycleState === "merged" ? { mergedIntoOplocId: requiredId(input.values.mergedIntoOplocId, "Surviving OPLOC") } : {}), aliases, ...optional("addressReference", input.values.addressReference) };
}
function buildAddress(input: CanonicalEditorInput, actor: Actor, base: Record<string, unknown>, now: string) { const normalised = normaliseAddressValues(input.values); return { ...base, entityType: "Address", canonicalId: input.canonicalId, addressId: input.canonicalId, addressLine1: requiredText(normalised.addressLine1, "Address line 1"), ...optional("addressLine2", normalised.addressLine2), ...optional("addressLine3", normalised.addressLine3), locality: requiredText(normalised.locality, "Town or city"), ...optional("region", normalised.region), ...optional("postalCode", normalised.postalCode), countryCode: requiredText(normalised.countryCode, "Country"), lifecycleState: normalised.lifecycleState || "active", approvalState: "approved", evidenceReferences: normalised.evidenceReferences || [], decisionReason: input.decisionReason, approvedBy: actor.uid, approvedAt: now }; }
function preserveHumanDecision(record: Record<string, unknown>, actor: Actor, reason: string, timestamp: string) { const ownership = record.ownership as { providerOwned: Record<string, unknown>; fikaOwned: Record<string, unknown> }; const decisions = Array.isArray(ownership.fikaOwned.humanDecisions) ? ownership.fikaOwned.humanDecisions : []; ownership.fikaOwned.humanDecisions = [...decisions, { actorId: actor.uid, timestamp, reason }]; }
function validateId(type: EditableEntityType, id: string) { validateCanonicalId(type, id); }
function requiredText(value: unknown, label: string) { const text = String(value || "").trim(); if (!text) throw new Error(`${label} is required.`); return text; }
function requiredId(value: unknown, label: string) { const text = requiredText(value, label); if (!text.includes(":")) throw new Error(`${label} must use a stable canonical ID.`); return text; }
function optional(key: string, value: unknown) { const text = String(value || "").trim(); return text ? { [key]: text } : {}; }
function optionalNumber(key: string, value: unknown) { const text = String(value ?? "").trim(); if (!text) return {}; const number = Number(text); if (!Number.isFinite(number) || number < 0) throw new Error(`${key} must be zero or a positive number.`); return { [key]: number }; }
