import type { FulfilmentRequirement } from "../../shared/fulfilment-requirement";
import type { DeliveryRun, DeliveryStop, MovementRequest, PlanningItem } from "./types";

export const plannedRequirementIds = (stops: DeliveryStop[]) => new Set(stops.flatMap(stop => stop.requirementRefs.map(ref => ref.requirementId)));
export function isNewlyPlannable(requirement: FulfilmentRequirement, stops: DeliveryStop[]) { return requirement.status !== "withdrawn" && !plannedRequirementIds(stops).has(requirement.canonicalId); }
export function planningAttention(requirement: FulfilmentRequirement, ref?: { requirementId:string; sourceVersion:number }) { if (!ref) return undefined; if (requirement.status === "withdrawn") return "WITHDRAWN — remove from plan"; if (requirement.status === "amended" || requirement.sourceVersion !== ref.sourceVersion) return "AMENDED — review source changes"; return undefined; }
export function combineStop(stops: DeliveryStop[], input: { locationOplocId:string; locationLabel:string; requirement?:FulfilmentRequirement; movement?:MovementRequest; runId:string; by:string; now?:string }) {
  const now = input.now || new Date().toISOString(); const existing = stops.find(stop => stop.runId === input.runId && stop.locationOplocId === input.locationOplocId && stop.status !== "completed");
  if (input.requirement && !isNewlyPlannable(input.requirement, stops)) throw new Error(input.requirement.status === "withdrawn" ? "Withdrawn work cannot be newly planned." : "This requirement is already planned.");
  if (!existing) return { ...({ canonicalId:`stop:${input.runId}:${input.locationOplocId}:${Date.now()}`, runId:input.runId, sequence:stops.length + 1, locationOplocId:input.locationOplocId, locationLabelSnapshot:input.locationLabel, requirementRefs: input.requirement ? [{ requirementId:input.requirement.canonicalId, sourceVersion:input.requirement.sourceVersion }] : [], movementRequestId:input.movement?.canonicalId, movementType:input.movement?.type, requiredTime:input.requirement?.readyAt || input.movement?.requiredTime, window:input.requirement?.requiredDeliveryWindow || input.movement?.window, status:"planned", createdAt:now, updatedAt:now, version:1, audit:[{action:"stop-created",at:now,by:input.by,version:1}] } as DeliveryStop) };
  const next = { ...existing, requirementRefs: input.requirement ? [...existing.requirementRefs, { requirementId:input.requirement.canonicalId, sourceVersion:input.requirement.sourceVersion }] : existing.requirementRefs, movementRequestId: input.movement?.canonicalId || existing.movementRequestId, updatedAt:now, version:existing.version + 1, audit:[...existing.audit,{action:"work-combined",at:now,by:input.by,version:existing.version + 1}] };
  return next;
}
export function orderedTransferStops(stops: DeliveryStop[]) { return [...stops].sort((a,b) => (a.movementType === "collection" ? -1 : 0) - (b.movementType === "collection" ? -1 : 0) || a.sequence - b.sequence).map((stop,index) => ({...stop,sequence:index + 1})); }
export function runsForDriver<T extends { driverLabel?: string }>(runs: T[], driver: string) { return runs.filter(run => run.driverLabel === driver); }
export const asPlanningItems = (requirements: FulfilmentRequirement[], movements: MovementRequest[]): PlanningItem[] => [...requirements.map(requirement => ({kind:"fulfilment" as const, requirement})), ...movements.map(movement => ({kind:"movement" as const, movement}))];
