import type { FulfilmentRequirement } from "../../shared/fulfilment-requirement";
import type { DeliveryRun, DeliveryStop, MovementRequest, PlanningItem } from "./types";

export const plannedRequirementIds = (stops: DeliveryStop[]) => new Set(stops.flatMap(stop => stop.requirementRefs.map(ref => ref.requirementId)));
export const plannedMovementIds = (stops: DeliveryStop[]) => new Set(stops.flatMap(stop => stop.movementRequestIds || (stop.movementRequestId ? [stop.movementRequestId] : [])));
export function isNewlyPlannable(requirement: FulfilmentRequirement, stops: DeliveryStop[]) { return requirement.status !== "withdrawn" && !plannedRequirementIds(stops).has(requirement.canonicalId); }
export function planningAttention(requirement: FulfilmentRequirement, ref?: { requirementId:string; sourceVersion:number }) { if (!ref) return undefined; if (requirement.status === "withdrawn") return "WITHDRAWN — remove from plan"; if (requirement.status === "amended" || requirement.sourceVersion !== ref.sourceVersion) return "AMENDED — review source changes"; return undefined; }
export function chooseTargetRun(runs: DeliveryRun[], selectedRunId?: string) { if (selectedRunId && runs.some(run => run.canonicalId === selectedRunId)) return selectedRunId; return runs.length === 1 ? runs[0].canonicalId : undefined; }
export function selectMobileRun(runs: DeliveryRun[], driver: string, serviceDate: string, requestedRunId?: string) { return runs.find(run => run.serviceDate === serviceDate && requestedRunId && run.canonicalId === requestedRunId) || runs.find(run => run.serviceDate === serviceDate && !requestedRunId && run.driverLabel === driver); }
export function movementsForStop(stop: DeliveryStop, movements: MovementRequest[]) { const ids=stop.movementRequestIds || (stop.movementRequestId ? [stop.movementRequestId] : []); return ids.map(id=>movements.find(movement=>movement.canonicalId===id)).filter(Boolean) as MovementRequest[]; }
export function isUnplannedRequirement(requirement: FulfilmentRequirement, stops: DeliveryStop[]) { return !plannedRequirementIds(stops).has(requirement.canonicalId); }
export function isUnplannedMovement(movement: MovementRequest, stops: DeliveryStop[]) { return !plannedMovementIds(stops).has(movement.canonicalId); }
export function combineStop(stops: DeliveryStop[], input: { locationOplocId:string; locationLabel:string; requirement?:FulfilmentRequirement; movement?:MovementRequest; runId:string; by:string; now?:string }) {
  const now = input.now || new Date().toISOString(); const existing = stops.find(stop => stop.runId === input.runId && stop.locationOplocId === input.locationOplocId && stop.status !== "completed");
  if (input.requirement && !isNewlyPlannable(input.requirement, stops)) throw new Error(input.requirement.status === "withdrawn" ? "Withdrawn work cannot be newly planned." : "This requirement is already planned.");
  if (input.movement && plannedMovementIds(stops).has(input.movement.canonicalId)) throw new Error("This movement is already planned.");
  if (!existing) return { ...({ canonicalId:`stop:${input.runId}:${input.locationOplocId}:${Date.now()}`, runId:input.runId, sequence:stops.length + 1, locationOplocId:input.locationOplocId, locationLabelSnapshot:input.locationLabel, requirementRefs: input.requirement ? [{ requirementId:input.requirement.canonicalId, sourceVersion:input.requirement.sourceVersion }] : [], movementRequestIds: input.movement ? [input.movement.canonicalId] : [], movementType:input.movement?.type, requiredTime:input.requirement?.readyAt || input.movement?.requiredTime, window:input.requirement?.requiredDeliveryWindow || input.movement?.window, status:"planned", createdAt:now, updatedAt:now, version:1, audit:[{action:"stop-created",at:now,by:input.by,version:1}] } as DeliveryStop) };
  const movementIds = input.movement ? Array.from(new Set([...(existing.movementRequestIds || []), ...(existing.movementRequestId ? [existing.movementRequestId] : []), input.movement.canonicalId])) : (existing.movementRequestIds || []);
  return { ...existing, requirementRefs: input.requirement ? [...existing.requirementRefs, { requirementId:input.requirement.canonicalId, sourceVersion:input.requirement.sourceVersion }] : existing.requirementRefs, movementRequestIds:movementIds, movementType:input.movement?.type || existing.movementType, updatedAt:now, version:existing.version + 1, audit:[...existing.audit,{action:"work-combined",at:now,by:input.by,version:existing.version + 1}] };
}
export function orderedTransferStops(stops: DeliveryStop[]) { return [...stops].sort((a,b) => (a.movementType === "collection" ? -1 : 0) - (b.movementType === "collection" ? -1 : 0) || a.sequence - b.sequence).map((stop,index) => ({...stop,sequence:index + 1})); }
export function assignMovementStops(stops: DeliveryStop[], runId: string, movement: MovementRequest, labels: { from?: string; to?: string }, by: string) { const scoped=stops.filter(stop=>stop.runId===runId); const newStops=movement.type === "transfer" ? [combineStop(scoped,{locationOplocId:movement.fromOplocId||"",locationLabel:labels.from||"",movement:{...movement,type:"collection"},runId,by}),combineStop(scoped,{locationOplocId:movement.toOplocId||"",locationLabel:labels.to||"",movement:{...movement,type:"delivery"},runId,by})] : [combineStop(scoped,{locationOplocId:movement.toOplocId||movement.fromOplocId||"",locationLabel:labels.to||labels.from||"",movement,runId,by})]; const byId=new Map(scoped.map(stop=>[stop.canonicalId,stop])); newStops.forEach(stop=>byId.set(stop.canonicalId,stop)); return orderedTransferStops([...byId.values()]); }
export function runsForDriver<T extends { driverLabel?: string; serviceDate?: string }>(runs: T[], driver: string, serviceDate?: string) { return runs.filter(run => run.driverLabel === driver && (!serviceDate || run.serviceDate === serviceDate)); }
export const asPlanningItems = (requirements: FulfilmentRequirement[], movements: MovementRequest[]): PlanningItem[] => [...requirements.map(requirement => ({kind:"fulfilment" as const, requirement})), ...movements.map(movement => ({kind:"movement" as const, movement}))];
