import type { FulfilmentRequirement } from "../../shared/fulfilment-requirement";
import type { DeliveryRun, DeliveryStop, LogisticsDayProjection, MovementRequest } from "./types";
import type { PlannerDay, PlannerLine, PlannerWorkGroup } from "./planner-read-model";

export function projectionToDashboardData(projection: LogisticsDayProjection) {
  const now = new Date().toISOString();
  const projectedRuns = projection.runs.length ? projection.runs : [{ canonicalId: `projection-run:${projection.serviceDate}`, status: "planned" as const, driverId: undefined, driverLabel: undefined, vehicleLabel: "Van 1" }];
  const runs = projectedRuns.map((projectedRun, runIndex) => {
    const deliveryLoads = projection.deliveryLoads.filter((load) => load.runId === projectedRun.canonicalId || (!load.runId && runIndex === 0));
    const collectionLoads = projection.deliveryLoads.filter((load) => load.collectionRequired && (load.collectionRunId === projectedRun.canonicalId || (!load.collectionRunId && runIndex === 0)));
    const loadEntries = [...deliveryLoads.map((load) => ({ load, lane: "delivery" as const })), ...collectionLoads.map((load) => ({ load, lane: "collection" as const }))];
    const run: DeliveryRun = { canonicalId: projectedRun.canonicalId, serviceDate: projection.serviceDate, status: projectedRun.status, driverId: projectedRun.driverId, driverLabel: projectedRun.driverLabel, vehicleLabel: projectedRun.vehicleLabel, orderedStopIds: loadEntries.map(({ load, lane }) => `projection-stop:${lane}:${load.id}`), version: projection.revision, createdAt: now, updatedAt: now, audit: [] };
    const stops: DeliveryStop[] = loadEntries.map(({ load, lane }, index) => { const collection = lane === "collection"; const stopId = `projection-stop:${lane}:${load.id}`; const scheduledTime = collection ? load.collectionScheduledTime : load.scheduledTime; const scheduledEnd = collection ? load.collectionScheduledEnd : load.scheduledEnd; return ({ canonicalId: stopId, runId: run.canonicalId, sequence: index + 1, locationOplocId: collection ? load.originOplocId : load.destinationOplocId, locationLabelSnapshot: collection ? "CPU production" : load.destinationLabelSnapshot || load.destinationOplocId, requirementRefs: load.jobs.map((job) => ({ requirementId: job.id, sourceVersion: 1 })), movementRequestIds: [], ...(scheduledTime ? { requiredTime: scheduledTime, ...(scheduledEnd ? { plannedWindow: { startTime: scheduledTime, endTime: scheduledEnd } } : { plannedArrivalTime: scheduledTime }) } : {}), loaded: Boolean(load.loaded), status: load.status === "delivered" ? "completed" : "planned", movementType: collection ? "collection" as const : "delivery" as const, linkedStopId: `projection-stop:delivery:${load.id}`, linkedOperation: collection ? "collection" as const : "delivery" as const, createdAt: now, updatedAt: now, version: projection.revision, audit: [] } as DeliveryStop); });
    return { run, stops };
  });
  const line = (job: { id: string; sourceId: string; totalUnits: number }): PlannerLine => ({ lineKey: `projection:${job.id}`, displayName: job.sourceId, unit: "unit", quantity: job.totalUnits, requirementRefs: [job.id], sourceLineRefs: [] });
  const workGroups: PlannerWorkGroup[] = projection.planningQueue.map((job) => ({ groupKey: `projection-job:${job.id}`, serviceDate: projection.serviceDate, destinationOplocId: job.destinationOplocId || "", destinationLabel: job.destinationLabelSnapshot || job.destinationOplocId || "Unknown destination", ...(job.requestedWindow ? { deliveryWindow: job.requestedWindow } : {}), requiredTimes: job.requestedWindow?.startTime ? [job.requestedWindow.startTime] : [], requirementRefs: [{ requirementId: job.id, sourceVersion: 1, sourceDomain: job.sourceType as FulfilmentRequirement["sourceDomain"], sourceEntityId: job.sourceId, status: "ready_for_planning" }], requirementCount: 1, sourceLabels: [job.sourceType], combinedLines: [line(job)], unitBreakdown: [{ unit: "unit", quantity: job.totalUnits }], readiness: "READY", attention: [], planningState: "unplanned", collectionRequired: false }));
  for (const load of projection.deliveryLoads.filter((item) => item.collectionRequired && !item.collectionScheduledTime)) {
    const runId = load.collectionRunId || load.runId || projectedRuns[0]?.canonicalId;
    const collectionStopId = `projection-stop:collection:${load.id}`;
    workGroups.push({ groupKey: `projection-collection:${load.id}`, serviceDate: projection.serviceDate, destinationOplocId: load.originOplocId, destinationLabel: "CPU production", requiredTimes: [], requirementRefs: load.jobs.map((job) => ({ requirementId: job.id, sourceVersion: 1, sourceDomain: job.sourceType as FulfilmentRequirement["sourceDomain"], sourceEntityId: job.sourceId, status: "ready_for_planning", runId, stopId: collectionStopId })), requirementCount: load.jobCount, sourceLabels: Array.from(new Set(load.jobs.map((job) => job.sourceType))), combinedLines: load.jobs.map((job) => line(job)), unitBreakdown: [{ unit: "unit", quantity: load.totalUnits }], readiness: "READY", attention: ["Collection timing required"], planningState: "partially_planned", collectionRequired: true });
  }
  const plannerRuns = runs.map(({ run, stops }) => {
    const scheduledStopCount = stops.filter((stop) => Boolean(stop.requiredTime)).length;
    const needsTimeStopCount = stops.length - scheduledStopCount;
    return { runId: run.canonicalId, serviceDate: run.serviceDate, driver: run.driverLabel, vehicle: run.vehicleLabel, status: run.status, operationalStatus: run.status === "dispatched" ? "dispatched" as const : "planned" as const, returnToCpuRequired: false, returnReady: false, completedCollections: projection.summary.collectedJobs, remainingCollections: 0, version: run.version, stopCount: stops.length, scheduledStopCount, needsTimeStopCount, completedStops: stops.filter((stop) => stop.status === "completed").length, openIssueCount: 0, readiness: { ready: projection.exceptions.length === 0, blockers: projection.exceptions }, nextStop: undefined, stops: stops.map((stop) => ({ stopId: stop.canonicalId, sequence: stop.sequence, destination: { id: stop.locationOplocId, label: stop.locationLabelSnapshot }, requiredTime: stop.requiredTime, plannedArrivalTime: stop.plannedArrivalTime, plannedWindow: stop.plannedWindow, loaded: stop.loaded, requirementCount: stop.requirementRefs.length, movementCount: 0, movementTypes: [], sourceLabels: [], combinedLines: [], unitBreakdown: [], attention: [], status: stop.status, lane: stop.movementType === "collection" ? "collection" as const : "delivery" as const, linkedStopId: stop.linkedStopId, linkedOperation: stop.linkedOperation, operationalStatus: stop.status === "completed" ? "delivered" as const : "scheduled" as const })) };
  });
  const allStops = runs.flatMap(({ stops }) => stops);
  const scheduledStops = allStops.filter((stop) => Boolean(stop.requiredTime)).length;
  const needsTimeStops = allStops.length - scheduledStops;
  const planner: PlannerDay = { serviceDate: projection.serviceDate, workGroups, movements: [], runs: plannerRuns, summary: { requirements: projection.planningQueue.length + projection.summary.assignedJobs, destinations: new Set([...projection.planningQueue.map((job) => job.destinationOplocId), ...projection.deliveryLoads.map((load) => load.destinationOplocId)]).size, unplanned: projection.planningQueue.length, partiallyPlanned: 0, planned: projection.summary.assignedJobs, attention: projection.exceptions.length, movements: 0, loads: projection.deliveryLoads.length, deliveries: projection.deliveryLoads.length, collections: 0, transfers: 0, assignedWork: projection.summary.assignedJobs, scheduledStops, needsTime: needsTimeStops }, upstreamHealth: { fulfilment: { available: true }, oplocs: { available: true }, enrichment: { available: true } } };
  return { requirements: [] as FulfilmentRequirement[], runs: runs.map(({ run }) => run), stops: allStops, movements: [] as MovementRequest[], oplocs: [], serviceDate: projection.serviceDate, fetchedAt: projection.rebuiltAt, planner };
}
