import type { FulfilmentRequirement } from "../../shared/fulfilment-requirement";
import type { DeliveryRun, DeliveryStop, LogisticsDayProjection, MovementRequest } from "./types";
import type { PlannerDay, PlannerLine, PlannerWorkGroup } from "./planner-read-model";

export function projectionToDashboardData(projection: LogisticsDayProjection) {
  const now = new Date().toISOString();
  const projectedRuns = projection.runs.length ? projection.runs : [{ canonicalId: `projection-run:${projection.serviceDate}`, status: "planned" as const, driverId: undefined, driverLabel: undefined, vehicleLabel: "Van 1" }];
  const runs = projectedRuns.map((projectedRun, runIndex) => {
    const loads = projection.deliveryLoads.filter((load) => load.runId === projectedRun.canonicalId || (!load.runId && runIndex === 0));
    const run: DeliveryRun = { canonicalId: projectedRun.canonicalId, serviceDate: projection.serviceDate, status: projectedRun.status, driverId: projectedRun.driverId, driverLabel: projectedRun.driverLabel, vehicleLabel: projectedRun.vehicleLabel, orderedStopIds: loads.map((load) => `projection-stop:${load.id}`), version: projection.revision, createdAt: now, updatedAt: now, audit: [] };
    const stops: DeliveryStop[] = loads.map((load, index) => ({ canonicalId: `projection-stop:${load.id}`, runId: run.canonicalId, sequence: index + 1, locationOplocId: load.destinationOplocId, locationLabelSnapshot: load.destinationLabelSnapshot || load.destinationOplocId, requirementRefs: load.jobs.map((job) => ({ requirementId: job.id, sourceVersion: 1 })), movementRequestIds: [], requiredTime: load.scheduledTime, plannedArrivalTime: load.scheduledTime, status: load.status === "delivered" ? "completed" : "planned", createdAt: now, updatedAt: now, version: projection.revision, audit: [] }));
    return { run, stops };
  });
  const line = (job: { id: string; sourceId: string; totalUnits: number }): PlannerLine => ({ lineKey: `projection:${job.id}`, displayName: job.sourceId, unit: "unit", quantity: job.totalUnits, requirementRefs: [job.id], sourceLineRefs: [] });
  const workGroups: PlannerWorkGroup[] = projection.planningQueue.map((job) => ({ groupKey: `projection-job:${job.id}`, serviceDate: projection.serviceDate, destinationOplocId: job.destinationOplocId || "", destinationLabel: job.destinationLabelSnapshot || job.destinationOplocId || "Unknown destination", ...(job.requestedWindow ? { deliveryWindow: job.requestedWindow } : {}), requiredTimes: job.requestedWindow?.startTime ? [job.requestedWindow.startTime] : [], requirementRefs: [{ requirementId: job.id, sourceVersion: 1, sourceDomain: job.sourceType as FulfilmentRequirement["sourceDomain"], sourceEntityId: job.sourceId, status: "ready_for_planning" }], requirementCount: 1, sourceLabels: [job.sourceType], combinedLines: [line(job)], unitBreakdown: [{ unit: "unit", quantity: job.totalUnits }], readiness: "READY", attention: [], planningState: "unplanned", collectionRequired: false }));
  const plannerRuns = runs.map(({ run, stops }) => {
    const scheduledStopCount = stops.filter((stop) => Boolean(stop.requiredTime)).length;
    const needsTimeStopCount = stops.length - scheduledStopCount;
    return { runId: run.canonicalId, serviceDate: run.serviceDate, driver: run.driverLabel, vehicle: run.vehicleLabel, status: run.status, operationalStatus: run.status === "dispatched" ? "dispatched" as const : "planned" as const, returnToCpuRequired: false, returnReady: false, completedCollections: projection.summary.collectedJobs, remainingCollections: 0, version: run.version, stopCount: stops.length, scheduledStopCount, needsTimeStopCount, completedStops: stops.filter((stop) => stop.status === "completed").length, openIssueCount: 0, readiness: { ready: projection.exceptions.length === 0, blockers: projection.exceptions }, nextStop: undefined, stops: stops.map((stop) => ({ stopId: stop.canonicalId, sequence: stop.sequence, destination: { id: stop.locationOplocId, label: stop.locationLabelSnapshot }, requiredTime: stop.requiredTime, plannedArrivalTime: stop.plannedArrivalTime, requirementCount: stop.requirementRefs.length, movementCount: 0, movementTypes: [], sourceLabels: [], combinedLines: [], unitBreakdown: [], attention: [], status: stop.status, lane: "delivery" as const, operationalStatus: stop.status === "completed" ? "delivered" as const : "scheduled" as const })) };
  });
  const allStops = runs.flatMap(({ stops }) => stops);
  const scheduledStops = allStops.filter((stop) => Boolean(stop.requiredTime)).length;
  const needsTimeStops = allStops.length - scheduledStops;
  const planner: PlannerDay = { serviceDate: projection.serviceDate, workGroups, movements: [], runs: plannerRuns, summary: { requirements: projection.planningQueue.length + projection.summary.assignedJobs, destinations: new Set([...projection.planningQueue.map((job) => job.destinationOplocId), ...projection.deliveryLoads.map((load) => load.destinationOplocId)]).size, unplanned: projection.planningQueue.length, partiallyPlanned: 0, planned: projection.summary.assignedJobs, attention: projection.exceptions.length, movements: 0, loads: projection.deliveryLoads.length, deliveries: projection.deliveryLoads.length, collections: 0, transfers: 0, assignedWork: projection.summary.assignedJobs, scheduledStops, needsTime: needsTimeStops }, upstreamHealth: { fulfilment: { available: true }, oplocs: { available: true }, enrichment: { available: true } } };
  return { requirements: [] as FulfilmentRequirement[], runs: runs.map(({ run }) => run), stops: allStops, movements: [] as MovementRequest[], oplocs: [], serviceDate: projection.serviceDate, fetchedAt: projection.rebuiltAt, planner };
}
