"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { useSearchParams } from "next/navigation";
import type { RollingSnapshot, RollingEntry } from "@/lib/rolling-menu-types";
import { ROLLING_SLOTS } from "@/lib/rolling-menu-types";
import { clearMenuPlanningCache, getCachedWeek, putCachedWeek, type CachedMenuWeek } from "@/lib/menu-week-cache";
import { loadCachedCatalogue, type CachedCatalogueEntry, type CatalogueManifest } from "@/lib/menu-catalogue-cache";
export type Dish = { id: string; name: string; category?: string; description?: string; usage?: string[]; allergenEvidence?: Array<{ allergen: string; value: "contains" | "free_from" | "may_contain" | "unknown" }>; mayContainReviewed?: boolean };
export type PublicationDayState = { currentPublicationDayId?: string; currentVersion?: number; currentContentHash?: string; hasCurrentPublication: boolean; hasUnpublishedChanges: boolean; legacy: boolean; status: "published" | "draft" | "legacy" };
const titleCase = (value: string) => value.trim().toLocaleLowerCase().replace(/(^|[\s\-/&])([a-z])/g, (_, prefix: string, letter: string) => `${prefix}${letter.toUpperCase()}`);
const weekCache = new Map<string, CachedMenuWeek>();
let cacheIdentity = "";
let catalogueCache: Promise<Dish[]> | undefined;
const readJson = async (response: Response) => { const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error?.message || `Menu could not be loaded (HTTP ${response.status}).`); return body; };
const toDish = (entry: CachedCatalogueEntry): Dish => { const item = entry.item as Record<string, unknown> | undefined; return { id: String(entry.id), name: titleCase(String(entry.displayName ?? entry.name ?? "")), category: entry.category ? String(entry.category) : undefined, description: item?.description ? String(item.description) : undefined, allergenEvidence: Array.isArray(item?.allergenEvidence) ? item.allergenEvidence as Dish["allergenEvidence"] : [], mayContainReviewed: item?.mayContainReviewed === true }; };
const fetchCatalogue = async () => { const response = await fetch("/api/catalogue", { cache: "no-store" }); const body = await readJson(response); return { entries: (body.entries || []) as CachedCatalogueEntry[], categories: body.categories || [], identity: response.headers.get("x-fika-menu-identity") || undefined, manifest: body.manifest as CatalogueManifest | undefined }; };
const fetchCatalogueManifest = async () => { const response = await fetch("/api/catalogue?manifest=true", { cache: "no-store" }); return await readJson(response) as CatalogueManifest; };
const loadCatalogue = (onUpdate?: (dishes: Dish[]) => void) => catalogueCache ||= loadCachedCatalogue(fetchCatalogue, entries => onUpdate?.(entries.map(toDish)), fetchCatalogueManifest).then(entries => entries.map(toDish));
export function useRollingData(options: { loadCatalogue?: boolean } = {}) {
  const shouldLoadCatalogue = options.loadCatalogue !== false;
  const [snapshot, setSnapshot] = useState<RollingSnapshot>(); const [weeks, setWeeks] = useState<Array<{ id: string; weekCommencing: string }>>([]); const weeksRef = useRef(weeks); const [dishes, setDishes] = useState<Dish[]>([]); const [publicationState, setPublicationState] = useState<Record<string, PublicationDayState>>({}); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const params = useSearchParams(); const [requestedWeek, setRequestedWeek] = useState(() => params.get("week"));
  const applyCached = useCallback((cached: CachedMenuWeek, source: "memory" | "indexeddb") => { weekCache.set(cached.weekId, cached); setSnapshot(cached.snapshot); setPublicationState(cached.publicationState); setError(""); console.info("Menu Planning week cache timing", { source, cacheHit: true, renderMs: 0 }); }, []);
  const fetchWeek = useCallback(async (weekId?: string) => { const query = weekId ? `?weekId=${encodeURIComponent(weekId)}` : ""; const started = performance.now(); const response = await fetch(`/api/rolling-menu${query}`, { cache: "no-store" }); const body = await readJson(response); console.info("Menu Planning week cache timing", { source: "server", fullWeekFetchMs: performance.now() - started }); return { ...body, identity: response.headers.get("x-fika-menu-identity") || "" }; }, []);
  const revalidateWeek = useCallback(async (weekId: string, cached: CachedMenuWeek) => { try { const started = performance.now(); const summaryBody = await readJson(await fetch("/api/rolling-menu?summariesOnly=true", { cache: "no-store" })); const summary = (summaryBody.weeks || []).find((item: { id: string }) => item.id === weekId); console.info("Menu Planning week cache timing", { source: "server", summaryVersionCheckMs: performance.now() - started, cacheVersion: cached.version, serverVersion: summary?.version }); if (summary && Number(summary.version) === cached.version) return; const body = await fetchWeek(weekId); if (body.snapshot?.week?.id) { const value: CachedMenuWeek = { weekId: body.snapshot.week.id, weekCommencing: body.snapshot.week.weekCommencing, version: Number(body.snapshot.week.version || 0), snapshot: body.snapshot, publicationState: body.publicationState || {}, cachedAt: Date.now(), identity: cacheIdentity || "local" }; weekCache.set(value.weekId, value); if (cacheIdentity) await putCachedWeek(value); setSnapshot(value.snapshot); setPublicationState(value.publicationState); } } catch { /* Background revalidation must not blank a visible cached week. */ } }, [fetchWeek]);
  const load = useCallback(async (weekId?: string) => { try {
    const availableWeeks = weeksRef.current;
    const target = weekId || (requestedWeek ? availableWeeks.find(item => item.id === requestedWeek || item.weekCommencing === requestedWeek)?.id : undefined);
    let cached = target ? weekCache.get(target) : undefined;
    if (!cached && target && cacheIdentity) cached = await getCachedWeek(target, cacheIdentity);
    if (cached) { applyCached(cached, weekCache.has(target!) ? "memory" : "indexeddb"); void revalidateWeek(target!, cached); return; }
    const body = await fetchWeek(target); const identity = typeof body.identity === "string" ? body.identity : "";
    if (identity && cacheIdentity && identity !== cacheIdentity) { weekCache.clear(); await clearMenuPlanningCache(); }
    if (identity) cacheIdentity = identity;
    const next: CachedMenuWeek = { weekId: body.snapshot.week.id, weekCommencing: body.snapshot.week.weekCommencing, version: Number(body.snapshot.week.version || 0), snapshot: body.snapshot, publicationState: body.publicationState || {}, cachedAt: Date.now(), identity: cacheIdentity || "local" }; weekCache.set(next.weekId, next); if (cacheIdentity) await putCachedWeek(next); setError(""); setSnapshot(next.snapshot); weeksRef.current = body.weeks || availableWeeks; setWeeks(weeksRef.current); setPublicationState(next.publicationState);
    const index = (body.weeks || availableWeeks).findIndex((item: { id: string }) => item.id === next.snapshot?.week?.id); for (const neighbor of [(body.weeks || availableWeeks)[index - 1], (body.weeks || availableWeeks)[index + 1]]) if (neighbor && !weekCache.has(neighbor.id)) void fetchWeek(neighbor.id).then(prefetched => { if (prefetched.snapshot?.week?.id) { const value: CachedMenuWeek = { weekId: prefetched.snapshot.week.id, weekCommencing: prefetched.snapshot.week.weekCommencing, version: Number(prefetched.snapshot.week.version || 0), snapshot: prefetched.snapshot, publicationState: prefetched.publicationState || {}, cachedAt: Date.now(), identity: cacheIdentity || "local" }; weekCache.set(value.weekId, value); if (cacheIdentity) void putCachedWeek(value); } }).catch(() => undefined);
  } catch (cause) { setError(cause instanceof Error ? cause.message : "Menu could not be loaded."); } }, [applyCached, fetchWeek, revalidateWeek, requestedWeek]);
  useEffect(() => { void load(requestedWeek || undefined); }, [load, requestedWeek]);
  useEffect(() => { const onPopState = () => setRequestedWeek(new URLSearchParams(window.location.search).get("week")); window.addEventListener("popstate", onPopState); return () => window.removeEventListener("popstate", onPopState); }, []);
  useEffect(() => { const onLogout = () => { cacheIdentity = ""; catalogueCache = undefined; weekCache.clear(); window.sessionStorage.removeItem("fika-menu-identity"); void clearMenuPlanningCache(); }; window.addEventListener("fika-logout", onLogout); return () => window.removeEventListener("fika-logout", onLogout); }, []);
  useEffect(() => { if (shouldLoadCatalogue) void loadCatalogue(setDishes).then(setDishes).catch((cause: Error) => setError(cause.message)); }, [shouldLoadCatalogue]);
  const selectWeek = useCallback((weekId: string) => { const target = weeksRef.current.find(item => item.id === weekId); if (!target) return; const url = new URL(window.location.href); url.searchParams.set("week", target.weekCommencing); url.searchParams.delete("day"); window.history.pushState({}, "", url); setRequestedWeek(target.weekCommencing); }, []);
  useEffect(() => { const onSelect = (event: Event) => { const weekId = (event as CustomEvent<string>).detail; selectWeek(weekId); }; window.addEventListener("menu-week-select", onSelect); return () => window.removeEventListener("menu-week-select", onSelect); }, [selectWeek]);
  const command = useCallback(async (action: string, extra: Record<string, unknown> = {}) => { setMessage("Saving…"); const response = await fetch("/api/rolling-menu", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action, ...extra }) }); const body = await response.json(); if (!response.ok) { setError(body.error?.message || "Could not save."); setMessage(""); return false; } setError(""); setSnapshot(body.snapshot); setWeeks(body.weeks || []); setPublicationState(body.publicationState || {}); const value = body.snapshot?.week?.id ? { weekId: body.snapshot.week.id, weekCommencing: body.snapshot.week.weekCommencing, version: Number(body.snapshot.week.version || 0), snapshot: body.snapshot, publicationState: body.publicationState || {}, cachedAt: Date.now(), identity: cacheIdentity || "local" } as CachedMenuWeek : undefined; if (value) { weekCache.set(value.weekId, value); if (cacheIdentity) void putCachedWeek(value); } setMessage("Saved"); window.setTimeout(() => setMessage(""), 1200); return true; }, []);
  return { snapshot, setSnapshot, weeks, dishes, publicationState, message, error, setError, load, selectWeek, command };
}
export const slotLabel = (slot: string) => slot.replace(/^SALAD \d+$/, "Salad").replace("COLD PROTEIN", "Cold protein").replace("HOT VEG VEGAN", "Hot veg / vegan").replace("HOT MEAT", "Hot meat").replace(/^EXTRAS \d+$/, "Side").replace("SOUP", "Soup");
export const groupedSlots = (snapshot: RollingSnapshot) => { const slots = Array.from(new Set([...ROLLING_SLOTS, ...(snapshot.week.customSlots || []), ...snapshot.entries.map(entry => entry.slot)])).filter(slot => !snapshot.week.removedSlots?.includes(slot)); const groups: Array<[string, string[]]> = [["SALADS", slots.filter(slot => slot.startsWith("SALAD "))], ["COLD", slots.filter(slot => slot === "COLD PROTEIN")], ["HOT", slots.filter(slot => ["SOUP", "HOT MEAT", "HOT VEG VEGAN"].includes(slot))], ["SIDES", slots.filter(slot => slot.startsWith("EXTRAS ") || !["COLD PROTEIN", "SOUP", "HOT MEAT", "HOT VEG VEGAN"].includes(slot) && !slot.startsWith("SALAD "))]]; return groups.filter(([, values]) => values.length); };
export function patchEntry(entry: RollingEntry, patch: Record<string, unknown>) { return { action: "update-entry", weekId: entry.id.split(":entry:")[0], entryId: entry.id, patch }; }
