"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { useSearchParams } from "next/navigation";
import type { RollingSnapshot, RollingEntry, RollingWeek } from "@/lib/rolling-menu-types";
import { ROLLING_SLOTS } from "@/lib/rolling-menu-types";
import { clearMenuPlanningCache, createVersionedCacheWriter, getCachedWeek, getCachedWeekSelection, putCachedWeek, putCachedWeekSelection, type CachedMenuWeek } from "@/lib/menu-week-cache";
import { catalogueManifestFromResponse, loadCachedCatalogue, type CachedCatalogueEntry, type CatalogueManifest } from "@/lib/menu-catalogue-cache";
import { recordDataAccess } from "@fika/server-shared/data-source-meter-client";
export type Dish = { id: string; name: string; category?: string; description?: string; usage?: string[]; allergenEvidence?: Array<{ allergen: string; value: "contains" | "free_from" | "may_contain" | "unknown" }>; mayContainReviewed?: boolean };
export type WeekSummary = Pick<RollingWeek, "id" | "weekCommencing" | "entryIds" | "version">;
export type PublicationDayState = { currentPublicationId?: string; currentPublicationDayId?: string; currentVersion?: number; currentContentHash?: string; hasCurrentPublication: boolean; hasUnpublishedChanges: boolean; legacy: boolean; status: "published" | "draft" | "legacy" };
const titleCase = (value: string) => value.trim().toLocaleLowerCase().replace(/(^|[\s\-/&])([a-z])/g, (_, prefix: string, letter: string) => `${prefix}${letter.toUpperCase()}`);
const weekCache = new Map<string, CachedMenuWeek>();
let cacheIdentity = typeof window !== "undefined" ? window.sessionStorage.getItem("fika-menu-identity") || "" : "";
let catalogueCache: Promise<Dish[]> | undefined;
const weekCacheWriter = createVersionedCacheWriter<CachedMenuWeek>(putCachedWeek);
function persistCachedWeek(value: CachedMenuWeek, generation = weekCacheWriter.currentGeneration()) { if (!cacheIdentity || value.identity !== cacheIdentity) return Promise.resolve(); return weekCacheWriter.enqueue(value.weekId, value.version, value, generation); }
const readJson = async (response: Response) => { const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error?.message || `Menu could not be loaded (HTTP ${response.status}).`); return body; };
const toDish = (entry: CachedCatalogueEntry): Dish => { const item = entry.item as Record<string, unknown> | undefined; return { id: String(entry.id), name: titleCase(String(entry.displayName ?? entry.name ?? "")), category: entry.category ? String(entry.category) : undefined, description: item?.description ? String(item.description) : undefined, allergenEvidence: Array.isArray(item?.allergenEvidence) ? item.allergenEvidence as Dish["allergenEvidence"] : [], mayContainReviewed: item?.mayContainReviewed === true }; };
const fetchCatalogue = async () => { const response = await fetch("/api/catalogue", { cache: "no-store" }); const body = await readJson(response); return { entries: (body.entries || []) as CachedCatalogueEntry[], categories: body.categories || [], identity: response.headers.get("x-fika-menu-identity") || undefined, manifest: body.manifest ? catalogueManifestFromResponse(body.manifest as CatalogueManifest & { package?: { contentHash?: string } }) : undefined }; };
const fetchCatalogueManifest = async () => { const response = await fetch("/api/catalogue?manifest=true", { cache: "no-store" }); return await readJson(response) as CatalogueManifest; };
const loadCatalogue = (onUpdate?: (dishes: Dish[]) => void) => { if (catalogueCache) { void catalogueCache.then(entries => recordDataAccess({ app: "menu-planning", operation: "catalogue.memory", source: "MEMORY", documents: entries.length, cacheHit: true })); } return catalogueCache ||= loadCachedCatalogue(fetchCatalogue, entries => onUpdate?.(entries.map(toDish)), fetchCatalogueManifest).then(entries => entries.map(toDish)); };
export function useRollingData(options: { loadCatalogue?: boolean } = {}) {
  const shouldLoadCatalogue = options.loadCatalogue !== false;
  const [snapshot, setSnapshot] = useState<RollingSnapshot>(); const [weeks, setWeeks] = useState<WeekSummary[]>([]); const weeksRef = useRef(weeks); const [dishes, setDishes] = useState<Dish[]>([]); const [publicationState, setPublicationState] = useState<Record<string, PublicationDayState>>({}); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const operationRef = useRef(0); const appliedVersionsRef = useRef(new Map<string, number>());
  const params = useSearchParams(); const [requestedWeek, setRequestedWeek] = useState(() => params.get("week"));
  const applyCached = useCallback((cached: CachedMenuWeek, source: "memory" | "indexeddb") => { const applied = appliedVersionsRef.current.get(cached.weekId); if (applied !== undefined && cached.version < applied) return; appliedVersionsRef.current.set(cached.weekId, cached.version); weekCache.set(cached.weekId, cached); const cachedWeeks = cached.weeks?.length ? cached.weeks : [{ id: cached.weekId, weekCommencing: cached.weekCommencing, entryIds: cached.snapshot.week.entryIds, version: cached.version }]; weeksRef.current = cachedWeeks; setWeeks(cachedWeeks); setSnapshot(cached.snapshot); setPublicationState(cached.publicationState); setError(""); if (source === "memory") recordDataAccess({ app: "menu-planning", operation: "week.memory", source: "MEMORY", documents: 1, cacheHit: true }); console.info("Menu Planning week cache timing", { source, cacheHit: true, renderMs: 0 }); }, []);
  const fetchWeek = useCallback(async (weekId?: string, snapshotOnly = false) => { const query = weekId ? `?weekId=${encodeURIComponent(weekId)}${snapshotOnly ? "&snapshotOnly=true" : ""}` : ""; const started = performance.now(); const response = await fetch(`/api/rolling-menu${query}`, { cache: "no-store" }); const body = await readJson(response); console.info("Menu Planning week cache timing", { source: "server", fullWeekFetchMs: performance.now() - started }); return { ...body, identity: response.headers.get("x-fika-menu-identity") || "" }; }, []);
  const revalidateWeek = useCallback(async (weekId: string, cached: CachedMenuWeek, operation: number, generation: number) => { try { const started = performance.now(); const summaryBody = await readJson(await fetch(`/api/rolling-menu?summariesOnly=true&weekId=${encodeURIComponent(weekId)}`, { cache: "no-store" })); const summary = summaryBody.week as { id: string; version: number } | null | undefined; console.info("Menu Planning week cache timing", { source: "server", weekHeadVersionCheckMs: performance.now() - started, cacheVersion: cached.version, serverVersion: summary?.version }); if (operation !== operationRef.current || (summary && Number(summary.version) <= cached.version)) return; const body = await fetchWeek(weekId); if (operation !== operationRef.current || body.snapshot?.week?.id !== weekId) return; if (body.snapshot?.week?.id) { const value: CachedMenuWeek = { weekId: body.snapshot.week.id, weekCommencing: body.snapshot.week.weekCommencing, version: Number(body.snapshot.week.version || 0), snapshot: body.snapshot, publicationState: body.publicationState || {}, weeks: body.weeks || [], cachedAt: Date.now(), identity: cacheIdentity || "local" }; const applied = appliedVersionsRef.current.get(value.weekId); if (applied !== undefined && value.version < applied) return; appliedVersionsRef.current.set(value.weekId, value.version); weekCache.set(value.weekId, value); if (cacheIdentity) { await persistCachedWeek(value, generation); await putCachedWeekSelection({ weekId: value.weekId, weekCommencing: value.weekCommencing, identity: cacheIdentity, selectedAt: Date.now() }); } if (operation !== operationRef.current) return; weeksRef.current = value.weeks || []; setWeeks(weeksRef.current); setSnapshot(value.snapshot); setPublicationState(value.publicationState); } } catch { /* Background revalidation must not blank a visible cached week. */ } }, [fetchWeek]);
  const load = useCallback(async (weekId?: string) => { const operation = ++operationRef.current; const generation = weekCacheWriter.currentGeneration(); try {
    const availableWeeks = weeksRef.current;
    let target = weekId || (requestedWeek ? availableWeeks.find(item => item.id === requestedWeek || item.weekCommencing === requestedWeek)?.id : undefined);
    if (!target && cacheIdentity) { const selected = await getCachedWeekSelection(cacheIdentity); if (selected && (!requestedWeek || selected.weekId === requestedWeek || selected.weekCommencing === requestedWeek)) target = selected.weekId; }
    let cached = target ? weekCache.get(target) : undefined;
    if (!cached && target && cacheIdentity) cached = await getCachedWeek(target, cacheIdentity);
    if (operation !== operationRef.current) return;
    if (cached) { applyCached(cached, weekCache.has(target!) ? "memory" : "indexeddb"); if (cacheIdentity) void putCachedWeekSelection({ weekId: cached.weekId, weekCommencing: cached.weekCommencing, identity: cacheIdentity, selectedAt: Date.now() }); void revalidateWeek(target!, cached, operation, generation); return; }
    const body = await fetchWeek(target); if (operation !== operationRef.current) return; const identity = typeof body.identity === "string" ? body.identity : "";
    if (identity && cacheIdentity && identity !== cacheIdentity) { weekCacheWriter.invalidate(); weekCache.clear(); await clearMenuPlanningCache(); }
    if (identity) cacheIdentity = identity;
    const next: CachedMenuWeek = { weekId: body.snapshot.week.id, weekCommencing: body.snapshot.week.weekCommencing, version: Number(body.snapshot.week.version || 0), snapshot: body.snapshot, publicationState: body.publicationState || {}, weeks: body.weeks || [], cachedAt: Date.now(), identity: cacheIdentity || "local" }; appliedVersionsRef.current.set(next.weekId, next.version); weekCache.set(next.weekId, next); if (cacheIdentity) { await persistCachedWeek(next, generation); await putCachedWeekSelection({ weekId: next.weekId, weekCommencing: next.weekCommencing, identity: cacheIdentity, selectedAt: Date.now() }); } if (operation !== operationRef.current) return; setError(""); setSnapshot(next.snapshot); weeksRef.current = body.weeks || availableWeeks; setWeeks(weeksRef.current); setPublicationState(next.publicationState);
    const governedWeeks = [...(body.weeks || availableWeeks)].sort((a: { weekCommencing: string }, b: { weekCommencing: string }) => a.weekCommencing.localeCompare(b.weekCommencing)); const index = governedWeeks.findIndex((item: { id: string }) => item.id === next.snapshot?.week?.id); for (const neighbor of [governedWeeks[index - 1], governedWeeks[index + 1]]) if (neighbor && !weekCache.has(neighbor.id)) void fetchWeek(neighbor.id, true).then(prefetched => { if (prefetched.snapshot?.week?.id) { const value: CachedMenuWeek = { weekId: prefetched.snapshot.week.id, weekCommencing: prefetched.snapshot.week.weekCommencing, version: Number(prefetched.snapshot.week.version || 0), snapshot: prefetched.snapshot, publicationState: prefetched.publicationState || {}, weeks: prefetched.weeks || [], cachedAt: Date.now(), identity: cacheIdentity || "local" }; const applied = appliedVersionsRef.current.get(value.weekId); if (applied === undefined || value.version >= applied) { appliedVersionsRef.current.set(value.weekId, value.version); weekCache.set(value.weekId, value); if (cacheIdentity) void persistCachedWeek(value, generation); } } }).catch(() => undefined);
  } catch (cause) { setError(cause instanceof Error ? cause.message : "Menu could not be loaded."); } }, [applyCached, fetchWeek, revalidateWeek, requestedWeek]);
  useEffect(() => { void load(requestedWeek || undefined); }, [load, requestedWeek]);
  useEffect(() => { const onPopState = () => setRequestedWeek(new URLSearchParams(window.location.search).get("week")); window.addEventListener("popstate", onPopState); return () => window.removeEventListener("popstate", onPopState); }, []);
  useEffect(() => { const onLogout = () => { cacheIdentity = ""; catalogueCache = undefined; weekCache.clear(); weekCacheWriter.invalidate(); operationRef.current += 1; window.sessionStorage.removeItem("fika-menu-identity"); void clearMenuPlanningCache(); }; window.addEventListener("fika-logout", onLogout); return () => window.removeEventListener("fika-logout", onLogout); }, []);
  useEffect(() => { if (shouldLoadCatalogue) void loadCatalogue(setDishes).then(setDishes).catch((cause: Error) => setError(cause.message)); }, [shouldLoadCatalogue]);
  const selectWeek = useCallback((weekId: string) => { const target = weeksRef.current.find(item => item.id === weekId); if (!target) return; operationRef.current += 1; const url = new URL(window.location.href); url.searchParams.set("week", target.weekCommencing); url.searchParams.delete("day"); window.history.pushState({}, "", url); setRequestedWeek(target.weekCommencing); if (cacheIdentity) void putCachedWeekSelection({ weekId: target.id, weekCommencing: target.weekCommencing, identity: cacheIdentity, selectedAt: Date.now() }); }, []);
  useEffect(() => { const onSelect = (event: Event) => { const weekId = (event as CustomEvent<string>).detail; selectWeek(weekId); }; window.addEventListener("menu-week-select", onSelect); return () => window.removeEventListener("menu-week-select", onSelect); }, [selectWeek]);
  const command = useCallback(async (action: string, extra: Record<string, unknown> = {}) => { const operation = ++operationRef.current; const generation = weekCacheWriter.currentGeneration(); setMessage("Saving…"); try { const response = await fetch("/api/rolling-menu", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action, ...extra }) }); const body = await response.json().catch(() => ({})); if (operation !== operationRef.current) return false; if (!response.ok) { setError(body.error?.message || "Could not save."); setMessage(""); return false; } setError(""); setSnapshot(body.snapshot); setWeeks(body.weeks || []); weeksRef.current = body.weeks || []; setPublicationState(body.publicationState || {}); const value = body.snapshot?.week?.id ? { weekId: body.snapshot.week.id, weekCommencing: body.snapshot.week.weekCommencing, version: Number(body.snapshot.week.version || 0), snapshot: body.snapshot, publicationState: body.publicationState || {}, weeks: body.weeks || [], cachedAt: Date.now(), identity: cacheIdentity || "local" } as CachedMenuWeek : undefined; if (value) { appliedVersionsRef.current.set(value.weekId, value.version); weekCache.set(value.weekId, value); if (cacheIdentity) { void persistCachedWeek(value, generation); void putCachedWeekSelection({ weekId: value.weekId, weekCommencing: value.weekCommencing, identity: cacheIdentity, selectedAt: Date.now() }); } } setMessage(action === "batch-update-entries" ? "Changes saved" : "Saved"); window.setTimeout(() => setMessage(""), 1200); return true; } catch (cause) { if (operation !== operationRef.current) return false; setError(cause instanceof Error ? cause.message : "Could not save. Please try again."); setMessage(""); return false; } }, []);
  return { snapshot, setSnapshot, weeks, dishes, publicationState, message, error, setError, load, selectWeek, command };
}
export const slotLabel = (slot: string) => slot.replace(/^SALAD \d+$/, "Salad").replace("COLD PROTEIN", "Cold protein").replace("HOT VEG VEGAN", "Hot veg / vegan").replace("HOT MEAT", "Hot meat").replace(/^EXTRAS \d+$/, "Side").replace("SOUP", "Soup");
export const groupedSlots = (snapshot: RollingSnapshot) => { const slots = Array.from(new Set([...ROLLING_SLOTS, ...(snapshot.week.customSlots || []), ...snapshot.entries.map(entry => entry.slot)])).filter(slot => !snapshot.week.removedSlots?.includes(slot)); const groups: Array<[string, string[]]> = [["SALADS", slots.filter(slot => slot.startsWith("SALAD "))], ["COLD", slots.filter(slot => slot === "COLD PROTEIN")], ["HOT", slots.filter(slot => ["SOUP", "HOT MEAT", "HOT VEG VEGAN"].includes(slot))], ["SIDES", slots.filter(slot => slot.startsWith("EXTRAS ") || !["COLD PROTEIN", "SOUP", "HOT MEAT", "HOT VEG VEGAN"].includes(slot) && !slot.startsWith("SALAD "))]]; return groups.filter(([, values]) => values.length); };
export function patchEntry(entry: RollingEntry, patch: Record<string, unknown>) { return { action: "update-entry", weekId: entry.id.split(":entry:")[0], entryId: entry.id, patch }; }
