"use client";

import { Fragment, useEffect, useRef, useState, type CSSProperties, type KeyboardEvent } from "react";
import Link from "next/link";
import type { AllergenMap, AllergenState, RollingEntry, RollingSnapshot, RollingSlot, RollingWeek } from "@/lib/rolling-menu-types";
import { ROLLING_SLOTS } from "@/lib/rolling-menu-types";
import { rankDishPickerItems, similarDishNames, type DishPickerItem } from "@/lib/dish-picker";
import { CANONICAL_DISH_CATEGORIES, categoryForSlot } from "@/lib/dish-categories";

const ALLERGENS = ["no_key_allergens", "peanuts", "tree_nuts", "gluten", "sesame", "molluscs", "fish", "soya", "celery", "shellfish", "eggs", "milk", "mustard", "lupin", "sulphites"];
const display = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, c => c.toUpperCase());
const titleCase = (value: string) => value.trim().toLocaleLowerCase().replace(/(^|[\s\-/&])([a-z])/g, (_, prefix: string, letter: string) => `${prefix}${letter.toUpperCase()}`);
const slotDisplay = (slot: string) => slot.replace("HOT VEG VEGAN", "Hot Veg / Vegan").replace(/^SALAD \d+$/, "Salad").replace(/^EXTRAS \d+$/, "Side").replace("COLD PROTEIN", "Cold Protein").replace("HOT MEAT", "Hot Meat").replace("SOUP", "Soup");
const configuredSlots = (snapshot: RollingSnapshot) => Array.from(new Set([...ROLLING_SLOTS, ...(snapshot.week.customSlots || []), ...snapshot.entries.map(entry => entry.slot)]));
const optionalEmptySlots = new Set(["SALAD 5", "SALAD 6", "EXTRAS 1", "EXTRAS 2", "EXTRAS 3", "EXTRAS 4", "EXTRAS 5", "EXTRAS 6"]);
const visibleSlots = (snapshot: RollingSnapshot) => configuredSlots(snapshot).filter(slot => !snapshot.week.removedSlots?.includes(slot) && (!optionalEmptySlots.has(slot) || snapshot.entries.some(entry => entry.slot === slot) || snapshot.week.customSlots?.includes(slot)));
const nextSuggestedSlot = (snapshot: RollingSnapshot, category = "SALAD") => { const slots = configuredSlots(snapshot); const numbers = slots.map(slot => new RegExp(`^${category} (\\d+)$`).exec(slot)?.[1]).filter(Boolean).map(Number); return `${category} ${(numbers.length ? Math.max(...numbers) : 0) + 1}`; };
type OplocOption = { canonicalId: string; label: string };
const OTHER_OPLOC = "__other__";
let latestCatalogue: DishPickerItem[] = [];

export default function RollingMenuWorkspace() {
  const [snapshot, setSnapshot] = useState<RollingSnapshot>();
  const [weeks, setWeeks] = useState<RollingWeek[]>([]);
  const [dayId, setDayId] = useState("");
  const [editing, setEditing] = useState<string>();
  const [allergenEntry, setAllergenEntry] = useState<RollingEntry>();
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  const [showMore, setShowMore] = useState(false);
  const [catalogue, setCatalogue] = useState<DishPickerItem[]>([]);
  const [oplocs, setOplocs] = useState<OplocOption[]>([]);
  const [newDish, setNewDish] = useState<{ dayId: string; slot: string; entry?: RollingEntry }>();
  const [slotModalOpen, setSlotModalOpen] = useState(false);
  const [weekDialog, setWeekDialog] = useState<{ action: "create-week" | "duplicate-week"; title: string; initial?: string }>();
  const [clearEntry, setClearEntry] = useState<RollingEntry>();
  const [removeSlot, setRemoveSlot] = useState<string>();
  const [undoAction, setUndoAction] = useState<{ label: string; entryId: string; patch: Record<string, unknown> }>();
  const fileRef = useRef<HTMLInputElement>(null);

  const load = async (weekId?: string) => {
    const response = await fetch(`/api/rolling-menu${weekId ? `?weekId=${encodeURIComponent(weekId)}` : ""}`, { cache: "no-store" });
    const body = await response.json();
    if (!response.ok) { setError(body.error?.message || "Menu could not be loaded."); return; }
    setSnapshot(body.snapshot); setWeeks(body.weeks || []); setDayId(current => current || body.snapshot.days[0]?.id || "");
  };
  useEffect(() => { void load(); }, []);
  useEffect(() => { void fetch("/api/catalogue", { cache: "no-store" }).then(response => response.json()).then(body => setCatalogue((body.entries || []).map((entry: Record<string, unknown>) => { const item = entry.item as Record<string, unknown> | undefined; return { id: String(entry.id), name: titleCase(String(entry.displayName ?? entry.name ?? "")), category: entry.category ? String(entry.category) : undefined, subcategory: entry.subcategory ? String(entry.subcategory) : undefined, description: item?.description ? String(item.description) : undefined, allergenEvidence: Array.isArray(item?.allergenEvidence) ? item.allergenEvidence as DishPickerItem["allergenEvidence"] : [], mayContainReviewed: item?.mayContainReviewed === true }; }))).catch(() => undefined); }, []);
  useEffect(() => { void fetch("/api/oplocs", { cache: "no-store" }).then(response => response.json()).then(body => setOplocs(body.oplocs || [])).catch(() => setOplocs([])); }, []);
  useEffect(() => { latestCatalogue = catalogue; }, [catalogue]);

  const command = async (action: string, extra: Record<string, unknown> = {}) => {
    setMessage("Saving...");
    const response = await fetch("/api/rolling-menu", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action, ...extra }) });
    const body = await response.json();
    if (!response.ok) { setError(body.error?.message || "Command failed."); setMessage(""); return false; }
    setError(""); setSnapshot(body.snapshot); setWeeks(body.weeks || []); setMessage("Saved"); window.setTimeout(() => setMessage(""), 1200); return true;
  };
  const selectDish = async (dayId: string, slot: string, entry: RollingEntry | undefined, item: DishPickerItem) => {
    const ok = entry
      ? await command("update-entry", { weekId: snapshot?.week.id, entryId: entry.id, patch: { itemId: item.id, itemLabel: item.name } })
      : await command("create-entry", { weekId: snapshot?.week.id, dayId, slot, itemId: item.id, itemLabel: item.name });
    return ok;
  };
  const clearDish = async (entry: RollingEntry) => {
    const restore = { itemId: entry.itemId || "", itemLabel: entry.itemLabel, allocations: entry.allocations, portions: entry.portions, allergens: entry.allergens, mayContainNotes: entry.mayContainNotes || "" };
    const ok = await command("update-entry", { weekId: snapshot?.week.id, entryId: entry.id, patch: { itemId: "", itemLabel: "", allocations: [], portions: 0, allergens: {}, mayContainNotes: "" } });
    if (ok) setUndoAction({ label: `Restore ${titleCase(entry.itemLabel)}`, entryId: entry.id, patch: restore });
  };

  if (!snapshot) return <main style={styles.shell}><div style={styles.loading}>Loading menu planning…</div></main>;
  const day = snapshot.days.find(item => item.id === dayId) || snapshot.days[0];
  if (!day) return null;
  const slots = visibleSlots(snapshot);
  const entries = snapshot.entries.filter(item => item.dayId === day.id);
  const portions = snapshot.entries.reduce((sum, item) => sum + item.portions, 0);
  const destinations = new Set(snapshot.entries.flatMap(item => item.allocations.map(allocation => allocation.destinationLabel))).size;
  const reviewed = snapshot.entries.filter(item => Object.keys(item.allergens).length).length;
  const summary = { portions, destinations, reviewed, needsReview: snapshot.entries.length - reviewed };

  return <main style={styles.shell}>
    <header style={styles.header}><div><div style={styles.brand}>FIKA OS <span>/</span> Menu Planning</div><h1 style={styles.title}>Delivered-In Menus</h1></div><div style={styles.headerRight}><span style={styles.user}>Menu planner</span><button style={styles.secondary} aria-expanded={showMore} aria-haspopup="menu" onClick={() => setShowMore(value => !value)}>Menu ▾</button></div></header>
    {showMore && <div role="menu" style={styles.moreMenu}><Link role="menuitem" style={styles.moreLink} href="/">Delivered-In Menus</Link><Link role="menuitem" style={styles.moreLink} href="/catalogue">Dish Library</Link><Link role="menuitem" style={styles.moreLink} href="/dishes/new">Create dish</Link><button style={styles.moreAction} onClick={() => fileRef.current?.click()}>Import historical workbook</button><input ref={fileRef} type="file" accept=".xlsx,.xls" hidden onChange={async event => { const file = event.target.files?.[0]; if (!file) return; const response = await fetch("/api/rolling-menu/import", { method: "POST", headers: { "content-type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "x-workbook-name": file.name }, body: await file.arrayBuffer() }); const body = await response.json(); if (!response.ok) setError(body.error?.message || "Import failed."); else { setSnapshot(body.snapshot); setWeeks(body.weeks || []); setDayId(body.snapshot.days[0]?.id || ""); setMessage("Imported"); } }} /></div>}
    {error && <div style={styles.error}>{error}</div>}
    <section style={styles.weekBar}><button style={styles.iconButton} onClick={() => { const index = weeks.findIndex(item => item.id === snapshot.week.id); const previous = weeks[index - 1]; if (previous) void load(previous.id); }}>‹</button><button style={styles.weekTitle} onClick={() => setWeekDialog({ action: "create-week", title: "Create week", initial: snapshot.week.weekCommencing })}>WC {new Date(`${snapshot.week.weekCommencing}T00:00:00Z`).toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" }).toUpperCase()}</button><button style={styles.iconButton} onClick={() => { const index = weeks.findIndex(item => item.id === snapshot.week.id); const next = weeks[index + 1]; if (next) void load(next.id); }}>›</button><span style={styles.statusBadge}>{display(snapshot.week.status)}</span><button style={styles.primary} onClick={() => void command("publish", { weekId: snapshot.week.id })}>Publish week</button><button style={styles.secondary} onClick={() => setWeekDialog({ action: "duplicate-week", title: "Duplicate week" })}>Duplicate</button><button style={styles.secondary} onClick={() => setWeekDialog({ action: "create-week", title: "Start blank week" })}>Start blank</button></section>
    <div style={styles.saveState}>{message || (snapshot.week.status === "published" ? "Published week" : "Draft changes are saved locally")}{undoAction && <button style={styles.undoButton} onClick={async () => { const action = undoAction; const ok = await command("update-entry", { weekId: snapshot.week.id, entryId: action.entryId, patch: action.patch }); if (ok) setUndoAction(undefined); }}>{undoAction.label} · Undo</button>}</div>
    <section style={styles.summary}>{[`${snapshot.days.filter(item => item.entryIds.length).length} days`, `${summary.portions.toLocaleString()} planned portions`, `${summary.destinations} destinations`, `${summary.reviewed} allergens verified · ${summary.needsReview} need review`].map(item => <span key={item}>{item}</span>)}</section>
    <WeeklyPlanner snapshot={snapshot} slots={slots} items={catalogue} history={snapshot.entries} onSelect={selectDish} onClear={(dayId, slot, entry) => entry && void clearDish(entry)} onCreate={(nextDayId, slot, entry) => setNewDish({ dayId: nextDayId, slot, entry })} onAddSlot={() => setSlotModalOpen(true)} onRemoveSlot={slot => setRemoveSlot(slot)} />
    <section style={styles.dayNav}>{snapshot.days.slice(0, 5).map(item => { const count = snapshot.entries.filter(entry => entry.dayId === item.id).reduce((sum, entry) => sum + entry.portions, 0); const needs = snapshot.entries.some(entry => entry.dayId === item.id && !Object.keys(entry.allergens).length); return <button key={item.id} aria-pressed={item.id === day.id} style={item.id === day.id ? styles.dayActive : styles.day} onClick={() => setDayId(item.id)}><strong>{item.dayName.slice(0, 3).toUpperCase()} {item.date.slice(8)}</strong><span>{count} portions</span><i aria-label={needs ? "Needs allergen review" : "Allergens reviewed"} style={{ ...styles.dot, background: needs ? "#e5a31b" : "#44dcb2" }} /></button>; })}</section>
    <section style={styles.panel}><div style={styles.panelHeading}><div><div style={styles.kicker}>DAILY MENU</div><h2>{day.dayName}, {new Date(`${day.date}T00:00:00Z`).toLocaleDateString("en-GB", { day: "2-digit", month: "long", year: "numeric" })}</h2><p>{entries.length ? `${entries.length} menu slots · ${entries.reduce((sum, item) => sum + item.allocations.reduce((total, allocation) => total + allocation.quantity, 0), 0)} planned portions · ${entries.filter(item => Object.values(item.allergens).some(state => state !== "clear")).length}/${entries.length} allergens reviewed` : "No dishes planned yet"}</p></div></div><div style={styles.table}><div style={styles.tableHeader}><span>Slot</span><span>Dish</span><span>Destinations</span><span>Total</span><span>Allergens</span><span>Actions</span></div>{slots.map(slot => { const entry = entries.find(item => item.slot === slot); return <DailyRow key={slot} slot={slot as RollingSlot} entry={entry} items={catalogue} history={snapshot.entries} oplocs={oplocs} onSelect={item => void selectDish(day.id, slot, entry, item)} onCreate={() => setNewDish({ dayId: day.id, slot, entry })} onDestinationSave={patch => entry && void command("update-entry", { weekId: snapshot.week.id, entryId: entry.id, patch })} onAllergens={() => entry && setAllergenEntry(entry)} onClear={() => entry && setClearEntry(entry)} />; })}</div></section>
    <footer style={styles.footer}>Source evidence remains attached to imported rows. Drafts do not appear in chef views.</footer>
    {allergenEntry && <AllergenDrawer entry={allergenEntry} onClose={() => setAllergenEntry(undefined)} onSave={patch => { void command("update-entry", { weekId: snapshot.week.id, entryId: allergenEntry.id, patch }); setAllergenEntry(undefined); }} />}
    {slotModalOpen && <AddMenuSlotModal snapshot={snapshot} onClose={() => setSlotModalOpen(false)} onSave={async slot => { const ok = await command("add-menu-slot", { weekId: snapshot.week.id, slot }); if (ok) setSlotModalOpen(false); }} />}
    {weekDialog && <WeekDateModal title={weekDialog.title} initial={weekDialog.initial} onClose={() => setWeekDialog(undefined)} onSave={async weekCommencing => { const ok = await command(weekDialog.action, { ...(weekDialog.action === "duplicate-week" ? { weekId: snapshot.week.id } : {}), weekCommencing }); if (ok) setWeekDialog(undefined); }} />}
    {clearEntry && <ConfirmModal title="Clear menu slot?" message={`Remove ${titleCase(clearEntry.itemLabel)} from ${slotDisplay(clearEntry.slot)}?`} onClose={() => setClearEntry(undefined)} onConfirm={() => { const entry = clearEntry; setClearEntry(undefined); void clearDish(entry); }} />}
    {removeSlot && <ConfirmModal title="Remove empty menu row?" message={`Remove the empty ${slotDisplay(removeSlot)} row from this week?`} confirmLabel="Remove row" onClose={() => setRemoveSlot(undefined)} onConfirm={() => { const slot = removeSlot; setRemoveSlot(undefined); void command("remove-menu-slot", { weekId: snapshot.week.id, slot }); }} />}
    {newDish && <CreateDishDrawer slot={newDish.slot as RollingSlot} items={catalogue} onClose={() => setNewDish(undefined)} onUseExisting={async item => { const ok = newDish.entry ? await command("update-entry", { weekId: snapshot.week.id, entryId: newDish.entry.id, patch: { itemId: item.id, itemLabel: item.name } }) : await command("create-entry", { weekId: snapshot.week.id, dayId: newDish.dayId, slot: newDish.slot, itemId: item.id, itemLabel: item.name }); if (ok) setNewDish(undefined); }} onSave={async payload => { const response = await fetch("/api/menu", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "create-item", displayName: titleCase(payload.name), category: titleCase(payload.category), description: payload.description, preparationNotes: payload.notes, allergenEvidence: payload.allergenEvidence }) }); const body = await response.json(); if (!response.ok) { setError(body.error?.message || "Dish could not be created."); return; } const created = body.snapshot?.items?.find((candidate: Record<string, unknown>) => String(candidate.displayName || "").toLowerCase() === payload.name.toLowerCase()) || body.snapshot?.items?.at(-1); if (!created?.canonicalId) { setError("Dish was created but could not be assigned to this slot."); return; } const item = { id: String(created.canonicalId), name: titleCase(String(created.displayName || payload.name)), category: created.category ? String(created.category) : payload.category }; setCatalogue(current => current.some(existing => existing.id === item.id) ? current : [...current, item]); const ok = newDish.entry ? await command("update-entry", { weekId: snapshot.week.id, entryId: newDish.entry.id, patch: { itemId: item.id, itemLabel: item.name } }) : await command("create-entry", { weekId: snapshot.week.id, dayId: newDish.dayId, slot: newDish.slot, itemId: item.id, itemLabel: item.name }); if (ok) setNewDish(undefined); }} />}
  </main>;
}

function WeeklyPlanner({ snapshot, slots, items, history, onSelect, onClear, onCreate, onAddSlot, onRemoveSlot }: { snapshot: RollingSnapshot; slots: string[]; history: RollingEntry[]; items: DishPickerItem[]; onSelect: (dayId: string, slot: string, entry: RollingEntry | undefined, item: DishPickerItem) => Promise<boolean>; onClear: (dayId: string, slot: string, entry?: RollingEntry) => void; onCreate: (dayId: string, slot: string, entry?: RollingEntry) => void; onAddSlot: () => void; onRemoveSlot: (slot: string) => void }) {
  const weekdays = snapshot.days.slice(0, 5);
  return <section style={styles.overview}><div style={styles.kicker}>Weekly Planner</div><div style={styles.weeklyGrid}><div style={styles.weeklyHeader}>Slot</div>{weekdays.map(day => <div key={day.id} style={styles.weeklyHeader}>{day.dayName.slice(0, 3).toUpperCase()} {day.date.slice(8)}</div>)}{slots.map(slot => { const occupied = snapshot.entries.some(entry => entry.slot === slot && entry.itemLabel.trim()); return <Fragment key={slot}><div style={styles.weeklySlotWrap}><strong style={styles.weeklySlot}>{slotDisplay(slot)}</strong>{!occupied && <button type="button" style={styles.removeRowButton} onClick={() => onRemoveSlot(slot)} aria-label={`Remove empty ${slotDisplay(slot)} row`}>×</button>}</div>{weekdays.map(day => { const entry = snapshot.entries.find(item => item.dayId === day.id && item.slot === slot); return <DishSelector key={`${day.id}-${slot}`} slot={slot} entry={entry} items={items} history={history} compact onSelect={item => onSelect(day.id, slot, entry, item)} onClear={() => onClear(day.id, slot, entry)} onCreate={() => onCreate(day.id, slot, entry)} ariaLabel={`${slotDisplay(slot)} for ${day.dayName}`} />; })}</Fragment>; })}</div><button style={styles.addSlotButton} onClick={onAddSlot}>＋ Add menu slot</button></section>;
}

function AddMenuSlotModal({ snapshot, onClose, onSave }: { snapshot: RollingSnapshot; onClose: () => void; onSave: (slot: string) => Promise<void> }) {
  const [category, setCategory] = useState("SALAD");
  const [customSlot, setCustomSlot] = useState("");
  const suggested = category === "CUSTOM" ? "" : nextSuggestedSlot(snapshot, category);
  const submit = () => { const slot = category === "CUSTOM" ? customSlot.trim().toUpperCase().replace(/\s+/g, " ") : suggested; if (slot) void onSave(slot); };
  return <div style={styles.modalBackdrop} role="dialog" aria-modal="true" aria-label="Add menu slot"><section style={styles.slotModal}><button style={styles.close} onClick={onClose} aria-label="Close">×</button><div style={styles.kicker}>MENU COMPOSITION</div><h2>Add menu slot</h2><p>Choose the governed slot type to add. Salad and Side rows are shown without numbering.</p><label style={styles.field}>Slot category<select value={category} onChange={event => setCategory(event.target.value)}><option value="SALAD">Salad</option><option value="EXTRAS">Side</option><option value="CUSTOM">Create new category / slot</option></select></label>{category === "CUSTOM" && <label style={styles.field}>New category or slot<input autoFocus value={customSlot} onChange={event => setCustomSlot(event.target.value)} placeholder="e.g. Dessert" /></label>}{category !== "CUSTOM" && <div style={styles.slotPreview}>New slot: <strong>{category === "SALAD" ? "Salad" : "Side"}</strong></div>}<div style={styles.modalActions}><button style={styles.secondary} onClick={onClose}>Cancel</button><button style={styles.primary} disabled={category === "CUSTOM" && !customSlot.trim()} onClick={submit}>Add menu slot</button></div></section></div>;
}

function WeekDateModal({ title, initial = "", onClose, onSave }: { title: string; initial?: string; onClose: () => void; onSave: (value: string) => Promise<void> }) {
  const [value, setValue] = useState(initial);
  return <div style={styles.modalBackdrop} role="dialog" aria-modal="true" aria-label={title}><section style={styles.slotModal}><button style={styles.close} onClick={onClose} aria-label="Close">×</button><div style={styles.kicker}>MENU WEEK</div><h2>{title}</h2><label style={styles.field}>Week commencing<input autoFocus type="date" value={value} onChange={event => setValue(event.target.value)} /></label><div style={styles.modalActions}><button style={styles.secondary} onClick={onClose}>Cancel</button><button style={styles.primary} disabled={!value} onClick={() => void onSave(value)}>Continue</button></div></section></div>;
}

function ConfirmModal({ title, message, confirmLabel = "Clear slot", onClose, onConfirm }: { title: string; message: string; confirmLabel?: string; onClose: () => void; onConfirm: () => void }) {
  return <div style={styles.modalBackdrop} role="dialog" aria-modal="true" aria-label={title}><section style={styles.slotModal}><button style={styles.close} onClick={onClose} aria-label="Close">×</button><div className="kicker" style={styles.kicker}>CONFIRM ACTION</div><h2>{title}</h2><p>{message}</p><div style={styles.modalActions}><button style={styles.secondary} onClick={onClose}>Cancel</button><button style={styles.actionMenuItemDanger} onClick={onConfirm}>{confirmLabel}</button></div></section></div>;
}

function DailyRow({ slot, entry, items, history, oplocs, onSelect, onCreate, onDestinationSave, onAllergens, onClear }: { slot: RollingSlot; entry?: RollingEntry; items: DishPickerItem[]; history: RollingEntry[]; oplocs: OplocOption[]; onSelect: (item: DishPickerItem) => void; onCreate: () => void; onDestinationSave: (patch: Record<string, unknown>) => void; onAllergens: () => void; onClear?: () => void }) {
  const [editing, setEditing] = useState(false);
  const [actions, setActions] = useState(false);
  const [selectorRequest, setSelectorRequest] = useState(0);
  const [allocations, setAllocations] = useState(entry?.allocations || []);
  useEffect(() => setAllocations(entry?.allocations || []), [entry?.id, entry?.allocations]);
  const total = allocations.reduce((sum, item) => sum + item.quantity, 0);
  const summary = allocations.map(item => `${item.destinationLabel} ${item.quantity}`).join(" · ");
  const dish = entry ? latestCatalogue.find(item => item.id === entry.itemId || item.name.toLowerCase() === entry.itemLabel.toLowerCase()) : undefined;
  const active = dish?.allergenEvidence?.filter(evidence => evidence.value === "contains" || evidence.value === "may_contain") || [];
  const fallback = entry ? Object.entries(entry.allergens || {}).filter(([, state]) => state !== "clear").map(([allergen, state]) => ({ allergen, value: state })) : [];
  const declared = (active.length ? active : fallback).filter(item => item.allergen !== "no_key_allergens");
  const verified = Boolean(entry && Object.keys(entry.allergens || {}).length) || Boolean(dish?.mayContainReviewed === true && !dish.allergenEvidence?.some(evidence => evidence.value === "unknown"));
  const allergenContent = !entry ? "—" : <><span style={styles.allergenNames}>{declared.length ? declared.map(({ allergen, value }) => <span style={styles.allergenChip} key={allergen}>{display(allergen)}{value === "may_contain" ? " · MC" : ""}</span>) : <span style={styles.noAllergens}>No declared allergens</span>}</span><span style={verified ? styles.verified : styles.needs}>{verified ? "Verified ✓" : "Not verified ⚠"}</span></>;
  const save = () => { onDestinationSave({ allocations, portions: total }); setEditing(false); };
  if (editing && entry) return <div style={styles.row}><strong style={styles.slot}>{slotDisplay(slot)}</strong><div style={styles.dish}><DishSelector slot={slot} entry={entry} items={items} history={history} onSelect={onSelect} onCreate={onCreate} /></div><div style={styles.destinationWrap}><div style={styles.destinationEditor} role="dialog" aria-label="Edit destinations">{allocations.map((allocation, index) => { const governed = oplocs.some(oploc => oploc.canonicalId === allocation.destinationId); const selected = governed ? allocation.destinationId! : OTHER_OPLOC; return <div style={styles.destinationEditRow} key={`${allocation.destinationId || "one-off"}-${index}`}><select style={styles.destinationName} aria-label="Destination" value={selected} onChange={event => setAllocations(current => current.map((item, i) => i === index ? event.target.value === OTHER_OPLOC ? { ...item, destinationId: undefined } : { ...item, destinationId: event.target.value, destinationLabel: oplocs.find(oploc => oploc.canonicalId === event.target.value)?.label || item.destinationLabel } : item))}><option value="">Choose OPLOC…</option>{oplocs.map(oploc => <option key={oploc.canonicalId} value={oploc.canonicalId}>{oploc.label}</option>)}<option value={OTHER_OPLOC}>Other — one-off destination</option></select>{selected === OTHER_OPLOC && <input style={styles.destinationName} aria-label="One-off destination" value={allocation.destinationLabel} onChange={event => setAllocations(current => current.map((item, i) => i === index ? { ...item, destinationLabel: event.target.value, destinationId: undefined } : item))} placeholder="Enter destination" />}<input style={styles.destinationInput} aria-label="Portions" type="number" min={0} value={allocation.quantity} onChange={event => setAllocations(current => current.map((item, i) => i === index ? { ...item, quantity: Number(event.target.value) || 0 } : item))} /><button style={styles.removeDestination} onClick={() => setAllocations(current => current.filter((_, i) => i !== index))}>×</button></div>; })}<button style={styles.addDestination} onClick={() => setAllocations(current => [...current, { destinationLabel: "", quantity: 0 }])}>＋ Add destination</button><div style={styles.popoverActions}><button style={styles.secondary} onClick={() => setEditing(false)}>Cancel</button><button style={styles.primary} onClick={save}>Save</button></div></div></div><strong style={styles.total}>{total}</strong><button style={styles.allergens} onClick={onAllergens}>{allergenContent}</button><div style={styles.actions} /></div>;
  return <div style={styles.row}><strong style={styles.slot}>{slotDisplay(slot)}</strong><div style={styles.dish}><DishSelector slot={slot} entry={entry} items={items} history={history} openRequest={selectorRequest} onSelect={onSelect} onClear={() => onClear?.()} onCreate={onCreate} /></div><div style={styles.destinationWrap}><button style={styles.destinationSummary} onClick={() => entry && setEditing(value => !value)} disabled={!entry}>{summary || "No destinations"}</button>{editing && entry && <div style={styles.destinationEditor} role="dialog" aria-label="Edit destinations">{allocations.map((allocation, index) => <div style={styles.destinationEditRow} key={`${allocation.destinationLabel}-${index}`}><input style={styles.destinationName} aria-label="Destination" value={allocation.destinationLabel} onChange={event => setAllocations(current => current.map((item, i) => i === index ? { ...item, destinationLabel: event.target.value } : item))} /><input style={styles.destinationInput} aria-label="Portions" type="number" min={0} value={allocation.quantity} onChange={event => setAllocations(current => current.map((item, i) => i === index ? { ...item, quantity: Number(event.target.value) || 0 } : item))} /><button style={styles.removeDestination} onClick={() => setAllocations(current => current.filter((_, i) => i !== index))}>×</button></div>)}<button style={styles.addDestination} onClick={() => setAllocations(current => [...current, { destinationLabel: "New destination", quantity: 0 }])}>＋ Add destination</button><div style={styles.popoverActions}><button style={styles.secondary} onClick={() => setEditing(false)}>Cancel</button><button style={styles.primary} onClick={save}>Save</button></div></div>}</div><strong style={styles.total}>{entry ? total : 0}</strong><button style={styles.allergens} onClick={onAllergens} disabled={!entry}>{allergenContent}</button><div style={styles.actions}>{entry && <><button aria-label={`Actions for ${entry.itemLabel}`} style={styles.actionButton} onClick={() => setActions(value => !value)}>⋯</button>{actions && <div style={styles.actionMenu} role="menu"><button style={styles.actionMenuItem} onClick={() => { setActions(false); setSelectorRequest(value => value + 1); }}>Change dish</button><button style={styles.actionMenuItem} onClick={() => { setActions(false); setSelectorRequest(value => value + 1); }}>Edit dish</button><button style={styles.actionMenuItem} onClick={() => setEditing(true)}>Edit destinations</button><button style={styles.actionMenuItem} onClick={onAllergens}>Review allergens</button><button style={styles.actionMenuItemDanger} onClick={() => { setActions(false); onClear?.(); }}>Clear slot</button></div>}</>}</div></div>;
}

function DishSelector({ slot, entry, items, history, onSelect, onClear, onCreate, compact = false, ariaLabel, openRequest = 0 }: { slot: string; entry?: RollingEntry; items: DishPickerItem[]; history: RollingEntry[]; onSelect: (item: DishPickerItem) => void | Promise<boolean>; onClear?: () => void; onCreate: () => void; compact?: boolean; ariaLabel?: string; openRequest?: number }) {
  const [open, setOpen] = useState(false);
  const [query, setQuery] = useState("");
  const [highlighted, setHighlighted] = useState(0);
  const rootRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);
  const ranked = rankDishPickerItems(items, query, slot).map(item => { const matches = history.filter(value => value.itemId === item.id || value.itemLabel.toLowerCase() === item.name.toLowerCase()); return { ...item, usageCount: matches.length, lastServed: matches.map(value => value.date).sort().at(-1) }; });
  const currentId = entry?.itemId || items.find(item => item.name.toLowerCase() === entry?.itemLabel.toLowerCase())?.id;
  const openSelector = () => { setOpen(true); setQuery(""); setHighlighted(0); window.setTimeout(() => inputRef.current?.focus(), 0); };
  const closeSelector = () => { setOpen(false); setQuery(""); };
  useEffect(() => { if (!open) return; const handleOutside = (event: MouseEvent) => { if (!rootRef.current?.contains(event.target as Node)) closeSelector(); }; document.addEventListener("mousedown", handleOutside); return () => document.removeEventListener("mousedown", handleOutside); }, [open]);
  useEffect(() => { if (openRequest > 0) openSelector(); }, [openRequest]);
  useEffect(() => setHighlighted(0), [query]);
  const select = async (item: DishPickerItem) => { await onSelect(item); closeSelector(); };
  const handleKeyDown = (event: KeyboardEvent) => { if (event.key === "Escape") { event.preventDefault(); closeSelector(); } else if (event.key === "ArrowDown") { event.preventDefault(); setHighlighted(index => Math.min(index + 1, Math.max(ranked.length - 1, 0))); } else if (event.key === "ArrowUp") { event.preventDefault(); setHighlighted(index => Math.max(index - 1, 0)); } else if (event.key === "Enter" && ranked[highlighted]) { event.preventDefault(); void select(ranked[highlighted]); } };
  return <div ref={rootRef} style={styles.selectorRoot}><button type="button" style={compact ? styles.selectorButtonCompact : styles.selectorButton} aria-label={ariaLabel || (entry ? `Change dish, ${titleCase(entry.itemLabel)}` : `Select dish for ${slotDisplay(slot)}`)} aria-expanded={open} aria-haspopup="listbox" onClick={() => open ? closeSelector() : openSelector()} onKeyDown={event => { if ((event.key === "Enter" || event.key === " ") && !open) { event.preventDefault(); openSelector(); } }}>{entry ? titleCase(entry.itemLabel) : "Select dish…"} <span aria-hidden="true">▾</span></button>{open && <div style={styles.selectorPopover} role="dialog" aria-label={`Select dish for ${slotDisplay(slot)}`}><input ref={inputRef} autoComplete="off" style={styles.selectorSearch} value={query} onChange={event => setQuery(event.target.value)} onKeyDown={handleKeyDown} placeholder="Search dishes" aria-label="Search dishes" /><div style={styles.selectorResults} role="listbox">{ranked.map((item, index) => <button type="button" role="option" aria-selected={item.id === currentId} key={item.id} style={{ ...styles.selectorOption, ...(index === highlighted ? styles.selectorOptionActive : {}) }} onMouseEnter={() => setHighlighted(index)} onClick={() => void select(item)}><span><strong>{item.name}</strong><small style={styles.selectorOptionSmall}>{item.category || "Uncategorised"}</small></span>{item.id === currentId && <span aria-label="Selected">✓</span>}</button>)}</div>{!ranked.length && <p style={styles.selectorEmpty}>No matching reusable dishes.</p>}{entry && onClear && <button type="button" style={styles.selectorClear} onClick={() => { closeSelector(); onClear(); }}>Clear selected dish</button>}<button type="button" style={styles.selectorCreate} onClick={() => { closeSelector(); onCreate(); }}>＋ Create new dish</button></div>}</div>;
}

function CreateDishDrawer({ slot, items, onClose, onUseExisting, onSave }: { slot: RollingSlot; items: DishPickerItem[]; onClose: () => void; onUseExisting: (item: DishPickerItem) => void; onSave: (payload: { name: string; category: string; description: string; notes: string; allergenEvidence: Array<{ allergen: string; value: "contains" | "may_contain"; source: string; reviewedBy: string; reviewedAt: string }> }) => void }) {
  const [name, setName] = useState(""); const [category, setCategory] = useState<string>(categoryForSlot(slot)); const [description, setDescription] = useState(""); const [notes, setNotes] = useState(""); const [states, setStates] = useState<AllergenMap>({});
  const similar = name.trim() ? similarDishNames(items, name) : [];
  const toggle = (key: string) => setStates(current => { const next = current[key] === "contains" ? "may_contain" : current[key] === "may_contain" ? "clear" : "contains"; const result = { ...current, [key]: next as AllergenState }; if (next === "clear") delete result[key]; return result; });
  const submit = () => { if (!name.trim()) return; const reviewedAt = new Date().toISOString(); onSave({ name: titleCase(name), category: titleCase(category) || "Other", description: description.trim(), notes: notes.trim(), allergenEvidence: Object.entries(states).filter(([, value]) => value !== "clear").map(([allergen, value]) => ({ allergen, value: value === "contains" ? "contains" : "may_contain", source: "menu-planning", reviewedBy: "Menu planner", reviewedAt })) }); };
  return <div style={styles.overlay}><aside style={styles.drawer} role="dialog" aria-modal="true" aria-label="Create reusable dish"><button style={styles.close} onClick={onClose}>×</button><div className="kicker" style={styles.kicker}>NEW REUSABLE DISH</div><h2>Create dish</h2><p>Save a reusable menu item for this slot. Recipes and costing can be added later.</p><div style={styles.formGrid}><label style={styles.field}>Name<input autoFocus spellCheck value={name} onBlur={() => setName(titleCase(name))} onChange={event => setName(event.target.value)} /></label><label style={styles.field}>Category<select value={category} onChange={event => setCategory(event.target.value)}>{CANONICAL_DISH_CATEGORIES.map(option => <option key={option} value={option}>{option}</option>)}</select></label></div><label style={styles.field}>Description<textarea spellCheck value={description} onChange={event => setDescription(event.target.value)} /></label><label style={styles.field}>Notes<textarea spellCheck value={notes} onChange={event => setNotes(event.target.value)} /></label><div style={styles.kicker}>ALLERGENS</div><div style={styles.allergenGrid}>{ALLERGENS.filter(key => key !== "no_key_allergens").map(key => <button type="button" key={key} style={{ ...styles.allergenOption, ...(states[key] ? styles.allergenSelected : {}) }} onClick={() => toggle(key)}><span>{states[key] === "contains" ? "✓" : states[key] === "may_contain" ? "MC" : ""}</span>{display(key)}</button>)}</div>{similar.length > 0 && <div style={styles.warning}><strong>Similar existing dish</strong><p>{similar.map(item => item.name).join(", ")}</p><div style={styles.inlineActions}><button style={styles.secondary} onClick={() => onUseExisting(similar[0])}>Use existing</button><button style={styles.primary} onClick={submit}>Create anyway</button></div></div>}<div style={styles.drawerActions}><button style={styles.secondary} onClick={onClose}>Cancel</button>{similar.length === 0 && <button style={styles.primary} onClick={submit}>Save dish</button>}</div></aside></div>;
}

function AllergenDrawer({ entry, onClose, onSave }: { entry: RollingEntry; onClose: () => void; onSave: (patch: { allergens: AllergenMap; mayContainNotes?: string }) => void }) {
  const [states, setStates] = useState<AllergenMap>(entry.allergens || {}); const [notes, setNotes] = useState(entry.mayContainNotes || "");
  const toggle = (key: string) => setStates(current => { if (key === "no_key_allergens") return { no_key_allergens: current.no_key_allergens === "contains" ? "clear" : "contains" }; const next = current[key] === "contains" ? "may_contain" : current[key] === "may_contain" ? "clear" : "contains"; const result = { ...current, [key]: next as AllergenState }; if (next !== "clear") delete result.no_key_allergens; return result; });
  return <div style={styles.overlay}><aside style={styles.drawer} role="dialog" aria-modal="true" aria-label="Edit allergens"><button style={styles.close} onClick={onClose}>×</button><div style={styles.kicker}>ALLERGEN REVIEW</div><h2>{titleCase(entry.itemLabel)}</h2><p>Click a status to cycle clear → contains → may contain.</p><div style={styles.allergenGrid}>{ALLERGENS.map(key => <button key={key} style={{ ...styles.allergenOption, ...(states[key] && states[key] !== "clear" ? styles.allergenSelected : {}) }} onClick={() => toggle(key)}><span>{states[key] === "contains" ? "✓" : states[key] === "may_contain" ? "MC" : ""}</span>{display(key)}</button>)}</div><label style={styles.noteLabel}>May contain details<textarea spellCheck value={notes} onChange={event => setNotes(event.target.value)} /></label><div style={styles.drawerActions}><button style={styles.secondary} onClick={onClose}>Cancel</button><button style={styles.primary} onClick={() => onSave({ allergens: states, mayContainNotes: notes })}>Save allergens</button></div></aside></div>;
}
 
const styles: Record<string, CSSProperties> = {
  shell: { minHeight: "100vh", background: "#f7f6fb", color: "#261345", padding: "20px clamp(18px,4vw,64px)", fontFamily: "Gilroy, Arial, sans-serif" },
  loading: { maxWidth: 900, margin: "20vh auto", background: "white", padding: 32, borderRadius: 12 },
  header: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 24, marginBottom: 16 },
  brand: { fontSize: 13, fontWeight: 800, letterSpacing: ".08em", color: "#5336cb" }, title: { margin: "5px 0 0", fontSize: 30, letterSpacing: "-.03em" }, headerRight: { display: "flex", gap: 12, alignItems: "center" }, user: { color: "#746887", fontSize: 13 },
  weekBar: { display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap", background: "white", border: "1px solid #ded8ed", borderRadius: 12, padding: 10 }, iconButton: { border: "1px solid #d7cdec", background: "white", color: "#4527ba", borderRadius: 8, fontSize: 22, width: 40, height: 38, cursor: "pointer" }, weekTitle: { border: 0, background: "transparent", color: "#2b185b", fontWeight: 900, fontSize: 16, padding: "8px 10px", cursor: "pointer" },
  primary: { background: "#4930c7", color: "white", border: 0, borderRadius: 8, padding: "10px 14px", fontWeight: 800, cursor: "pointer" }, secondary: { background: "#efebfc", color: "#4527ba", border: 0, borderRadius: 8, padding: "10px 12px", fontWeight: 800, cursor: "pointer" }, statusBadge: { marginLeft: "auto", background: "#e8f9f2", color: "#16745f", borderRadius: 999, padding: "7px 12px", fontWeight: 800, fontSize: 13 }, saveState: { minHeight: 20, color: "#6f647f", fontSize: 12, textAlign: "right", marginTop: 6 },
  summary: { display: "flex", gap: 10, flexWrap: "wrap", color: "#675b78", fontSize: 14, padding: "12px 0" }, dayNav: { display: "flex", gap: 8, alignItems: "stretch", overflowX: "auto", marginBottom: 14 }, day: { position: "relative", minWidth: 120, display: "grid", gap: 4, background: "white", border: "1px solid #ded8ed", borderRadius: 10, color: "#5f5371", textAlign: "left", padding: "10px 12px", cursor: "pointer" }, dayActive: { position: "relative", minWidth: 120, display: "grid", gap: 4, background: "#4930c7", border: "1px solid #4930c7", borderRadius: 10, color: "white", textAlign: "left", padding: "10px 12px", cursor: "pointer" }, dot: { display: "block", width: 7, height: 7, borderRadius: "50%", marginTop: 5 },
  overviewToggle: { background: "#efebfc", color: "#4527ba", border: 0, borderRadius: 8, padding: "10px 12px", fontWeight: 800, cursor: "pointer", marginLeft: "auto" }, overview: { background: "white", border: "1px solid #ded8ed", borderRadius: 12, padding: 16, marginBottom: 14, overflowX: "auto" }, kicker: { color: "#5437c9", fontWeight: 900, fontSize: 11, letterSpacing: ".13em" }, overviewGrid: { display: "grid", gridTemplateColumns: "150px repeat(5,minmax(130px,1fr))", minWidth: 820, gap: 1, marginTop: 12 }, overviewDay: { border: 0, background: "#f0edfb", padding: 9, fontWeight: 900, color: "#3f258f", cursor: "pointer" }, overviewCell: { border: 0, background: "#faf9fd", textAlign: "left", padding: "9px 8px", color: "#44365c", cursor: "pointer", whiteSpace: "normal" },
  panel: { background: "white", border: "1px solid #ded8ed", borderRadius: 12, padding: "18px clamp(12px,2vw,24px)" }, panelHeading: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 18, flexWrap: "wrap", marginBottom: 14 }, panelHeadingTitle: { margin: "4px 0", fontSize: 24 }, panelHeadingText: { margin: 0, color: "#766c84", fontSize: 13 }, readiness: { background: "#f0edfb", color: "#4930c7", padding: "9px 12px", borderRadius: 8, fontWeight: 800, fontSize: 13 },
  table: { overflowX: "auto" }, tableHeader: { display: "grid", gridTemplateColumns: "minmax(88px,.7fr) minmax(250px,2.3fr) minmax(190px,1.5fr) 70px minmax(170px,1.5fr) 42px", gap: 10, minWidth: 980, color: "#594c6f", fontWeight: 900, fontSize: 12, padding: "9px 8px", borderBottom: "2px solid #4930c7" }, row: { display: "grid", gridTemplateColumns: "minmax(88px,.7fr) minmax(250px,2.3fr) minmax(190px,1.5fr) 70px minmax(170px,1.5fr) 42px", gap: 10, minWidth: 980, alignItems: "center", padding: "9px 8px", borderBottom: "1px solid #ece8f3" }, slot: { color: "#7d7190", fontSize: 12, fontWeight: 700 }, dish: { minWidth: 0 }, readValue: { background: "transparent", border: 0, padding: 0, textAlign: "left", color: "#261345", fontWeight: 900, fontSize: 15, cursor: "pointer", whiteSpace: "normal" }, dishInput: { width: "100%", border: "1px solid #bdb2d7", borderRadius: 6, padding: "8px 9px", font: "inherit" },
  addDish: { display: "flex", flexDirection: "column", gap: 3 }, addDishSpan: { color: "#948ba0", fontSize: 11 }, addDishButton: { border: "1px dashed #b8ace0", background: "#faf9fd", color: "#4930c7", borderRadius: 8, padding: "10px 12px", fontWeight: 800, cursor: "pointer", textAlign: "left" }, suggestions: { position: "absolute", background: "white", border: "1px solid #d8d0e7", zIndex: 2, boxShadow: "0 8px 20px #28155922" }, suggestion: { display: "block", border: 0, background: "white", padding: "8px 10px", textAlign: "left", width: "100%", cursor: "pointer" }, destinations: { display: "flex", gap: 7, flexWrap: "wrap", alignItems: "center" }, destinationChip: { border: "1px solid #d8d0e7", background: "#f7f5fb", color: "#55466f", borderRadius: 999, padding: "5px 8px", cursor: "pointer", fontSize: 11 }, destinationLabel: { display: "inline-flex", alignItems: "center", gap: 5, background: "#f7f5fb", borderRadius: 6, padding: "4px 6px", fontSize: 11, color: "#6d617c" }, destinationInput: { width: 48, border: "1px solid #d1c9df", borderRadius: 4, padding: 4, background: "white" }, total: { color: "#2b185b", fontSize: 15 }, allergens: { border: 0, background: "transparent", padding: 0, display: "flex", gap: 4, flexWrap: "wrap", textAlign: "left", cursor: "pointer" }, allergenChip: { background: "#eeeafb", borderRadius: 999, color: "#4b3591", padding: "4px 7px", fontSize: 11 }, needs: { color: "#a36a00", fontWeight: 800 },
  footer: { color: "#81778e", fontSize: 12, padding: "15px 0" }, moreMenu: { position: "absolute", right: 60, top: 70, zIndex: 3, background: "white", border: "1px solid #ded8ed", borderRadius: 8, boxShadow: "0 8px 24px #26134522", padding: 8 }, error: { background: "#fff0f2", border: "1px solid #e5afbd", color: "#8e2044", borderRadius: 8, padding: "10px 12px", marginBottom: 10 }, overlay: { position: "fixed", inset: 0, zIndex: 10, background: "#23104466", display: "flex", justifyContent: "flex-end" }, drawer: { width: "min(480px, 100%)", height: "100%", overflowY: "auto", background: "white", padding: 28, boxShadow: "-8px 0 30px #21103933" }, picker: { width: "min(520px, 100%)", height: "100%", overflowY: "auto", background: "white", padding: 28, boxShadow: "-8px 0 30px #21103933" }, pickerSearch: { width: "100%", border: "1px solid #cfc5e3", borderRadius: 8, padding: "11px 12px", font: "inherit", margin: "12px 0" }, pickerList: { display: "grid", gap: 8, marginBottom: 16 }, pickerItem: { border: "1px solid #ded8ed", background: "white", borderRadius: 8, padding: "11px 12px", textAlign: "left", cursor: "pointer", display: "grid", gap: 3 }, createDishButton: { background: "#4930c7", color: "white", border: 0, borderRadius: 8, padding: "10px 14px", fontWeight: 800, cursor: "pointer" }, formGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 }, field: { display: "grid", gap: 5, color: "#4930c7", fontWeight: 800, margin: "10px 0" }, warning: { background: "#fff5dc", border: "1px solid #edc36c", color: "#785000", borderRadius: 8, padding: 12, marginTop: 12 }, inlineActions: { display: "flex", gap: 8, flexWrap: "wrap" }, close: { float: "right", border: 0, background: "#f0edfb", borderRadius: "50%", width: 34, height: 34, fontSize: 22, color: "#4930c7", cursor: "pointer" }, allergenGrid: { display: "grid", gridTemplateColumns: "repeat(2,1fr)", gap: 8, margin: "20px 0" }, allergenOption: { display: "flex", gap: 8, alignItems: "center", border: "1px solid #ded8ed", borderRadius: 7, background: "white", color: "#3d3153", padding: "9px 10px", textAlign: "left", cursor: "pointer" }, allergenSelected: { background: "#eeeafb", borderColor: "#4930c7", color: "#3f258f", fontWeight: 800 }, noteLabel: { display: "grid", gap: 5, fontWeight: 800, color: "#4930c7" }, noteTextarea: { minHeight: 84, border: "1px solid #d1c9df", borderRadius: 7, padding: 8, font: "inherit" }, drawerActions: { display: "flex", justifyContent: "flex-end", gap: 8, marginTop: 24 }
};

Object.assign(styles, {
  destinationWrap: { position: "relative", minWidth: 0 },
  destinationSummary: { border: 0, background: "transparent", color: "#55466f", padding: "5px 0", textAlign: "left", fontSize: 12, cursor: "pointer", whiteSpace: "normal" },
  destinationEditor: { position: "absolute", zIndex: 4, left: 0, top: "100%", width: 300, background: "white", border: "1px solid #d8d0e7", borderRadius: 8, padding: 10, boxShadow: "0 8px 22px #26134522" },
  destinationEditRow: { display: "flex", gap: 5, marginBottom: 6 },
  destinationName: { flex: 1, minWidth: 0, border: "1px solid #d1c9df", borderRadius: 4, padding: 5 },
  removeDestination: { border: 0, background: "transparent", color: "#a52042", cursor: "pointer" },
  addDestination: { border: 0, background: "#efebfc", color: "#4527ba", borderRadius: 6, padding: "6px 8px", fontWeight: 800, cursor: "pointer" },
  popoverActions: { display: "flex", justifyContent: "flex-end", gap: 6, marginTop: 8 },
  verified: { color: "#178260", fontWeight: 900 },
  warningMark: { color: "#a36a00", fontWeight: 900 },
  actions: { position: "relative", display: "flex", justifyContent: "flex-end" },
  actionButton: { border: 0, background: "#efebfc", color: "#4527ba", borderRadius: 6, width: 30, height: 30, fontSize: 18, cursor: "pointer" },
  actionMenu: { position: "absolute", right: 0, top: "100%", zIndex: 5, background: "white", border: "1px solid #d8d0e7", borderRadius: 8, padding: 5, minWidth: 150, boxShadow: "0 8px 20px #26134522" },
  actionMenuItem: { display: "block", width: "100%", border: 0, background: "white", color: "#3f258f", textAlign: "left", padding: "7px 8px", cursor: "pointer" },
  actionMenuItemDanger: { display: "block", width: "100%", border: 0, background: "white", color: "#a52042", textAlign: "left", padding: "7px 8px", cursor: "pointer" },
  moreLink: { display: "block", color: "#4527ba", textDecoration: "none", padding: "7px 9px", fontSize: 13, fontWeight: 800 },
  moreAction: { display: "block", width: "100%", border: 0, background: "white", color: "#4527ba", textAlign: "left", padding: "7px 9px", fontWeight: 800, cursor: "pointer" },
} as Record<string, CSSProperties>);

Object.assign(styles, {
  readValue: { background: "#faf9fd", border: "1px solid #d8d0e7", borderRadius: 8, padding: "7px 9px", textAlign: "left", color: "#261345", fontWeight: 900, fontSize: 13, cursor: "pointer", whiteSpace: "normal", width: "100%" },
  addDishButton: { border: "1px solid #d8d0e7", background: "#faf9fd", color: "#4930c7", borderRadius: 8, padding: "7px 9px", fontWeight: 800, fontSize: 13, cursor: "pointer", textAlign: "left", width: "100%" },
  allergenNames: { display: "flex", gap: 4, flexWrap: "wrap" },
  noAllergens: { color: "#675b78", fontSize: 11 },
  weeklyGrid: { display: "grid", gridTemplateColumns: "minmax(150px,1.15fr) repeat(5,minmax(180px,1fr))", minWidth: 1050, gap: 1, marginTop: 12, overflow: "visible" },
  weeklyHeader: { position: "sticky", top: 0, zIndex: 2, background: "#f0edfb", color: "#3f258f", padding: "9px 8px", fontWeight: 900, fontSize: 12 },
  weeklySlot: { background: "#faf9fd", color: "#594c6f", padding: "10px 8px", fontSize: 12, alignSelf: "stretch", display: "flex", alignItems: "center" },
  weeklySlotWrap: { background: "#faf9fd", display: "flex", alignItems: "stretch" },
  removeRowButton: { alignSelf: "center", margin: "0 6px 0 auto", border: 0, background: "transparent", color: "#9a8eaa", cursor: "pointer", fontSize: 18, lineHeight: 1, padding: 4 },
  undoButton: { marginLeft: 10, border: 0, background: "transparent", color: "#4930c7", fontWeight: 800, cursor: "pointer" },
  addSlotButton: { marginTop: 12, background: "#efebfc", color: "#4527ba", border: 0, borderRadius: 8, padding: "8px 10px", fontWeight: 800, cursor: "pointer" },
  modalBackdrop: { position: "fixed", inset: 0, zIndex: 30, background: "#23104466", display: "grid", placeItems: "center", padding: 18 },
  slotModal: { position: "relative", width: "min(480px, 100%)", background: "white", border: "1px solid #ded8ed", borderRadius: 12, padding: 22, boxShadow: "0 16px 42px #26134544" },
  slotPreview: { background: "#f0edfb", color: "#4527ba", borderRadius: 8, padding: "10px 12px", marginTop: 8 },
  modalActions: { display: "flex", justifyContent: "flex-end", gap: 8, marginTop: 20 },
  selectorRoot: { position: "relative", minWidth: 0, width: "100%" },
  selectorButton: { background: "#faf9fd", border: "1px solid #d8d0e7", borderRadius: 8, padding: "7px 9px", textAlign: "left", color: "#261345", fontWeight: 900, fontSize: 13, cursor: "pointer", whiteSpace: "normal", width: "100%" },
  selectorButtonCompact: { background: "#faf9fd", border: "1px solid #e1dced", borderRadius: 6, padding: "7px 8px", textAlign: "left", color: "#261345", fontWeight: 800, fontSize: 12, cursor: "pointer", whiteSpace: "normal", width: "100%", minHeight: 38 },
  selectorPopover: { position: "absolute", left: 0, top: "calc(100% + 4px)", zIndex: 20, width: "min(330px, 32vw)", minWidth: 250, background: "white", border: "1px solid #d8d0e7", borderRadius: 8, padding: 8, boxShadow: "0 10px 24px #26134530" },
  selectorSearch: { width: "100%", border: "1px solid #cfc5e3", borderRadius: 6, padding: "8px 9px", font: "inherit", marginBottom: 7 },
  selectorResults: { display: "grid", gap: 3, maxHeight: 260, overflowY: "auto" },
  selectorOption: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 8, border: 0, borderRadius: 6, background: "white", color: "#261345", padding: "7px 8px", textAlign: "left", cursor: "pointer", width: "100%" },
  selectorOptionActive: { background: "#f0edfb" },
  selectorOptionSmall: { display: "block", color: "#766c84", fontSize: 11, marginTop: 2 },
  selectorEmpty: { color: "#766c84", fontSize: 12, padding: "6px 4px", margin: 0 },
  selectorCreate: { width: "100%", marginTop: 7, border: 0, borderTop: "1px solid #ece8f3", padding: "8px 4px 2px", background: "white", color: "#4930c7", fontWeight: 800, textAlign: "left", cursor: "pointer" },
  selectorClear: { width: "100%", marginTop: 7, border: 0, borderTop: "1px solid #ece8f3", padding: "8px 4px 2px", background: "white", color: "#9a3151", fontWeight: 800, textAlign: "left", cursor: "pointer" },
} as Record<string, CSSProperties>);
