"use client";

import { useEffect, useState } from "react";
import MenuPlanningShell from "./menu-planning-shell";
import { groupedSlots, slotLabel, useRollingData, type Dish } from "./planner-data";
import PlanningContextNav from "./planning-context-nav";
import { rankDishPickerItems } from "@/lib/dish-picker";
import { categoryForSlot } from "@/lib/dish-categories";

export default function WeekPlanner() {
  const { snapshot, weeks, dishes, message, error, command } = useRollingData();
  const [query, setQuery] = useState(""); const [picker, setPicker] = useState<{ dayId: string; slot: string }>();
  if (!snapshot) return <MenuPlanningShell section="Week Planner"><div className="menu-loading">Loading Week Planner…</div></MenuPlanningShell>;
  const choose = async (dish: Dish) => { if (!picker) return; const entry = snapshot.entries.find(item => item.dayId === picker.dayId && item.slot === picker.slot); await command(entry ? "update-entry" : "create-entry", entry ? { weekId: snapshot.week.id, entryId: entry.id, patch: { itemId: dish.id, itemLabel: dish.name } } : { weekId: snapshot.week.id, dayId: picker.dayId, slot: picker.slot, itemId: dish.id, itemLabel: dish.name }); setPicker(undefined); };
  const createDish = async (name: string) => { const response = await fetch("/api/catalogue", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "create-dish", displayName: name, category: categoryForSlot(picker?.slot || "") }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message || body.error || "The dish could not be created."); const item = body.item as { canonicalId: string; displayName: string; category: string }; await choose({ id: item.canonicalId, name: item.displayName, category: item.category }); };
  return <MenuPlanningShell section="Week Planner"><section className="workspace-intro planner-intro"><small>Delivered-In</small><h2>Week Planner</h2><p>{snapshot.entries.filter(entry => entry.itemLabel.trim()).length} dishes planned</p></section><PlanningContextNav weeks={weeks} currentWeek={snapshot.week.id} /><div className="planner-toolbar"><span className={`status status--${snapshot.week.status}`}>{snapshot.week.status.replaceAll("_", " ")}</span>{message && <span role="status">{message}</span>}</div>{error && <div className="menu-error" role="alert">{error}</div>}<section className="workspace-panel week-planner-panel"><div className="week-matrix" role="table" aria-label="Weekly menu matrix"><div className="week-matrix-corner">Menu slot</div>{snapshot.days.slice(0, 5).map(day => <div className="week-matrix-day" key={day.id}>{day.dayName.slice(0, 3).toUpperCase()}<small>{new Date(`${day.date}T00:00:00Z`).getUTCDate()}</small></div>)}{groupedSlots(snapshot).map(([group, slots]) => <div className="week-matrix-group" key={group}><span>{group}</span>{slots.map(slot => <div className="week-matrix-row" key={slot}><strong>{slotLabel(slot)}</strong>{snapshot.days.slice(0, 5).map(day => { const entry = snapshot.entries.find(item => item.dayId === day.id && item.slot === slot); return <div className="week-menu-cell" key={day.id}><button className="week-menu-cell-button" onClick={() => { setQuery(""); setPicker({ dayId: day.id, slot }); }}>{entry?.itemLabel || "+ Select dish"}</button>{entry && <button className="week-menu-clear" aria-label={`Clear ${entry.itemLabel}`} onClick={() => void command("update-entry", { weekId: snapshot.week.id, entryId: entry.id, patch: { itemId: "", itemLabel: "", allocations: [], portions: 0 } })}>×</button>}</div>; })}</div>)}</div>)}</div></section>{picker && <DishPicker dishes={dishes} query={query} setQuery={setQuery} slot={picker.slot} onChoose={choose} onCreate={createDish} onClose={() => setPicker(undefined)} />}</MenuPlanningShell>;
}

function DishPicker({ dishes, query, setQuery, slot, onChoose, onCreate, onClose }: { dishes: Dish[]; query: string; setQuery: (value: string) => void; slot: string; onChoose: (dish: Dish) => void; onCreate: (name: string) => Promise<void>; onClose: () => void }) {
  const filtered = rankDishPickerItems(dishes, query, slot); const [creating, setCreating] = useState(false); const [name, setName] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); const canCreate = Boolean(query.trim()) && filtered.length === 0;
  useEffect(() => { const closeOnEscape = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); }; window.addEventListener("keydown", closeOnEscape); return () => window.removeEventListener("keydown", closeOnEscape); }, [onClose]);
  const saveNewDish = async () => { if (!name.trim()) return; setSaving(true); setError(""); try { await onCreate(name); } catch (cause) { setError(cause instanceof Error ? cause.message : "The dish could not be created."); setSaving(false); } };
  return <div className="modal-backdrop" onMouseDown={event => { if (event.target === event.currentTarget) onClose(); }}><aside className="dish-picker" role="dialog" aria-modal="true" aria-labelledby="dish-picker-title"><header><div><small>{slotLabel(slot)}</small><h3 id="dish-picker-title">Select dish</h3></div><button type="button" className="modal-close" onClick={onClose} aria-label="Close dish picker">Close</button></header><p className="dish-picker-category">Showing {slotLabel(slot).toLocaleLowerCase()} dishes only</p>{!creating ? <><input autoFocus value={query} onChange={event => setQuery(event.target.value)} placeholder={`Search ${slotLabel(slot).toLocaleLowerCase()} dishes`} /><div className="dish-picker-list">{filtered.map(dish => <button key={dish.id} onClick={() => onChoose(dish)}><strong>{dish.name}</strong><small>{dish.category || "Uncategorised"}{dish.usage?.length ? ` · used for ${dish.usage.join(", ")}` : ""}</small></button>)}{!filtered.length && <p className="dish-picker-empty">No {slotLabel(slot).toLocaleLowerCase()} dishes match your search.</p>}</div>{canCreate && <button type="button" className="dish-picker-create" onClick={() => { setName(query.trim()); setCreating(true); }}>＋ Create “{query.trim()}” as a new {slotLabel(slot).toLocaleLowerCase()} dish</button>}</> : <div className="dish-picker-create-form"><label>New {slotLabel(slot).toLocaleLowerCase()} dish name<input autoFocus value={name} onChange={event => setName(event.target.value)} placeholder="Type a dish title" /></label>{error && <p className="menu-error" role="alert">{error}</p>}<div><button type="button" className="button button-soft" onClick={() => setCreating(false)}>Back to search</button><button type="button" className="button button-mint" disabled={saving || !name.trim()} onClick={() => void saveNewDish()}>{saving ? "Creating…" : "Create and add to planner"}</button></div></div>}</aside></div>;
}
