"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import MenuPlanningShell from "../menu-planning-shell";
import type { RollingSnapshot } from "@/lib/rolling-menu-types";
import type { DishResolution } from "@/lib/legacy-week-importer";
import { clearImportSession, loadImportSession, saveImportSession, type ImportSession } from "@/lib/import-session";

type Report = { fileName: string; weekCommencing?: string; status: "valid" | "needs_attention"; error?: string; recognisedEntries?: number };
type Option = { id: string; name: string };
type Decision = DishResolution & { workbookCount?: number; canonicalId?: string; remember?: boolean; ignored?: boolean };
type Conflict = { weekCommencing: string; status: string };
type ProgressState = { phase: "checking" | "importing" | "checked" | "success" | "error"; total: number; completed: number; current: string; weeks: number; days: number; dishes: number; matched: number; review: number; error?: string };

function ProgressModal({ progress, onClose }: { progress: ProgressState; onClose: () => void }) {
  const checking = progress.phase === "checking";
  const importing = progress.phase === "importing";
  const checked = progress.phase === "checked";
  const finished = progress.phase === "success";
  const percentage = finished || checked ? 100 : progress.total ? Math.round((progress.completed / progress.total) * 100) : 8;
  const title = checking ? "Checking your workbooks" : importing ? "Importing menu weeks" : checked ? "Workbooks checked" : finished ? "Import complete" : "Import could not be completed";
  return <div className="import-progress-backdrop" role="presentation"><section className="import-progress-modal" role="dialog" aria-modal="true" aria-labelledby="import-progress-title" aria-describedby="import-progress-status">
    <div className={`import-progress-icon import-progress-icon-${progress.phase}`} aria-hidden="true">{finished ? "✓" : progress.phase === "error" ? "!" : "…"}</div>
    <h2 id="import-progress-title">{title}</h2>
    {progress.phase === "error" ? <p id="import-progress-status" role="alert">{progress.error || "We could not finish this import."}{progress.current ? ` Affected workbook or week: ${progress.current}.` : ""}</p> : finished ? <><p id="import-progress-status" role="status">{progress.completed} menu week{progress.completed === 1 ? "" : "s"} imported as planning source. 0 new Dish Library items were created.</p><dl className="import-progress-stats"><div><dt>Menu weeks imported</dt><dd>{progress.completed}</dd></div><div><dt>Menu days imported</dt><dd>{progress.days}</dd></div><div><dt>Dish mappings used</dt><dd>{progress.matched}</dd></div><div><dt>New dishes</dt><dd>0 created</dd></div></dl></> : checked ? <><p id="import-progress-status" role="status">Ready for your review: {progress.weeks} menu week{progress.weeks === 1 ? "" : "s"}, {progress.days} menu days and {progress.dishes} unique dish names found.</p><dl className="import-progress-stats"><div><dt>Matched automatically</dt><dd>{progress.matched}</dd></div><div><dt>Need review</dt><dd>{progress.review}</dd></div></dl></> : <>
      <p id="import-progress-status" className="import-progress-status">{checking ? `Checking workbook ${Math.min(progress.completed + 1, progress.total)} of ${progress.total}` : `Importing week ${Math.min(progress.completed + 1, progress.total)} of ${progress.total}`}</p>
      <div className="import-progress-track" role="progressbar" aria-valuemin={0} aria-valuemax={100} aria-valuenow={percentage} aria-label={`${percentage}% complete`}><span style={{ width: `${percentage}%` }} /></div>
      <dl className="import-progress-stats">{checking ? <><div><dt>Files checked</dt><dd>{progress.completed} / {progress.total}</dd></div><div><dt>Menu weeks found</dt><dd>{progress.weeks}</dd></div><div><dt>Menu days parsed</dt><dd>{progress.days}</dd></div><div><dt>Unique dish names</dt><dd>{progress.dishes}</dd></div><div><dt>Matched automatically</dt><dd>{progress.matched}</dd></div><div><dt>Need review</dt><dd>{progress.review}</dd></div></> : <><div><dt>Weeks imported</dt><dd>{progress.completed} / {progress.total}</dd></div><div><dt>Remaining weeks</dt><dd>{Math.max(progress.total - progress.completed, 0)}</dd></div><div><dt>New Dish Library items</dt><dd>0 created</dd></div></>}</dl>
      <p className="import-progress-current">Current workbook/week: <strong>{progress.current || "Preparing…"}</strong></p>
    </>}
    {(finished || checked || progress.phase === "error") && <div className="import-progress-footer">{finished && <button type="button" className="import-progress-close import-progress-secondary" onClick={() => { window.location.href = progress.current ? `/?week=${progress.current}` : "/"; }}>View Week Planner</button>}<button type="button" className="import-progress-close" onClick={onClose}>{finished || checked ? "Close" : "Close and review"}</button></div>}
    {(checking || importing) && <p className="import-progress-lock">Please keep this window open while we {checking ? "check the workbooks" : "save the planning weeks"}.</p>}
  </section></div>;
}

export default function ImportMenuWeekPage() {
  const [files, setFiles] = useState<File[]>([]); const [reports, setReports] = useState<Report[]>([]); const [snapshots, setSnapshots] = useState<RollingSnapshot[]>([]); const [resolutions, setResolutions] = useState<Decision[]>([]); const [catalogue, setCatalogue] = useState<Option[]>([]); const [overrides, setOverrides] = useState<Record<string, string>>({}); const [conflicts, setConflicts] = useState<Conflict[]>([]); const [resume, setResume] = useState<ImportSession>(); const [filter, setFilter] = useState("all"); const [search, setSearch] = useState(""); const [openSource, setOpenSource] = useState<string>(); const [undo, setUndo] = useState<Decision[]>(); const [bulkConfirmation, setBulkConfirmation] = useState<{ action: "accept" | "ignore"; count: number }>(); const [dragging, setDragging] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [progress, setProgress] = useState<ProgressState>(); const inputRef = useRef<HTMLInputElement>(null);
  useEffect(() => { const preventNavigation = (event: DragEvent) => event.preventDefault(); window.addEventListener("dragover", preventNavigation); window.addEventListener("drop", preventNavigation); return () => { window.removeEventListener("dragover", preventNavigation); window.removeEventListener("drop", preventNavigation); }; }, []);
  useEffect(() => { void loadImportSession().then(setResume).catch(() => undefined); }, []);
  const reviewCount = resolutions.filter(item => !item.canonicalId && !item.ignored).length; const resolvedCount = resolutions.filter(item => item.canonicalId || item.ignored).length; const workbookIssueCount = reports.filter(report => report.status !== "valid").length; const attention = workbookIssueCount > 0 || reports.length !== files.length;
  const visible = useMemo(() => resolutions.filter(item => filter === "all" || (filter === "matched" ? Boolean(item.canonicalId) : filter === "review" ? !item.canonicalId && !item.ignored : filter === "needs-dish" ? !item.canonicalId && !item.suggestions.length && !item.ignored : Boolean(item.ignored))), [filter, resolutions]);
  const filteredCatalogue = useMemo(() => catalogue.filter(item => item.name.toLocaleLowerCase().includes(search.toLocaleLowerCase())).slice(0, 80), [catalogue, search]); const filterCounts = { all: resolutions.length, review: reviewCount, "needs-dish": resolutions.filter(item => !item.canonicalId && !item.suggestions.length && !item.ignored).length, matched: resolutions.filter(item => Boolean(item.canonicalId)).length, ignored: resolutions.filter(item => Boolean(item.ignored)).length };
  useEffect(() => { if (!snapshots.length || busy) return; void saveImportSession({ savedAt: Date.now(), files: files.map(file => ({ name: file.name, size: file.size, lastModified: file.lastModified, type: file.type })), reports: reports as unknown as Array<Record<string, unknown>>, snapshots, resolutions: resolutions as unknown as Array<Record<string, unknown>>, overrides, conflicts: conflicts as unknown as Array<Record<string, unknown>> }).catch(() => undefined); }, [busy, conflicts, files, overrides, reports, resolutions, snapshots]);
  const preview = async (nextFiles: File[], nextOverrides = overrides) => { setBusy(true); setResume(undefined); setError(""); setProgress({ phase: "checking", total: nextFiles.length, completed: 0, current: nextFiles[0]?.name || "", weeks: 0, days: 0, dishes: 0, matched: 0, review: 0 }); try { const form = new FormData(); nextFiles.forEach(file => form.append("files", file)); form.append("weekDates", JSON.stringify(nextOverrides)); const response = await fetch("/api/rolling-menu/import", { method: "POST", body: form }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message || "The workbooks could not be checked."); const nextReports = body.files || []; const nextSnapshots = body.snapshots || []; const nextResolutions = body.resolutions || []; setFiles(nextFiles); setReports(nextReports); setSnapshots(nextSnapshots); setResolutions(nextResolutions); setConflicts(body.conflicts || []); setCatalogue(body.catalogue || []); setProgress({ phase: "checked", total: nextFiles.length, completed: nextFiles.length, current: nextReports[nextReports.length - 1]?.fileName || nextFiles[nextFiles.length - 1]?.name || "", weeks: nextSnapshots.length, days: nextSnapshots.reduce((count: number, snapshot: RollingSnapshot) => count + snapshot.days.length, 0), dishes: nextResolutions.length, matched: nextResolutions.filter((item: Decision) => Boolean(item.canonicalId)).length, review: nextResolutions.filter((item: Decision) => !item.canonicalId && !item.ignored).length }); } catch (cause) { const reason = cause instanceof Error ? cause.message : "The workbooks could not be checked."; setError(reason); setProgress(current => current ? { ...current, phase: "error", error: reason } : undefined); } finally { setBusy(false); } };
  const addFiles = (incoming: File[]) => { const accepted = incoming.filter(file => /\.xlsx?$/i.test(file.name)); const next = [...files, ...accepted.filter(file => !files.some(existing => existing.name === file.name && existing.size === file.size))]; if (next.length) void preview(next); else setError("Choose one or more Excel files (.xlsx or .xls)."); };
  const removeFile = (name: string) => { const next = files.filter(file => file.name !== name); setFiles(next); if (next.length) void preview(next); else { setReports([]); setSnapshots([]); setResolutions([]); setConflicts([]); void clearImportSession(); } };
  const chooseDate = (name: string, date: string) => { const next = { ...overrides, [name]: date }; setOverrides(next); void preview(files, next); }; const choose = (sourceName: string, canonicalId: string) => setResolutions(current => current.map(item => item.sourceName === sourceName ? { ...item, canonicalId, canonicalName: catalogue.find(option => option.id === canonicalId)?.name, ignored: false, remember: true } : item)); const ignore = (sourceName: string) => setResolutions(current => current.map(item => item.sourceName === sourceName ? { ...item, ignored: true, canonicalId: undefined } : item));
  const applyBulk = (action: "accept" | "ignore") => { const target = visible.filter(item => action === "accept" ? !item.canonicalId && item.suggestions.length > 0 : !item.canonicalId && !item.ignored); if (target.length) setBulkConfirmation({ action, count: target.length }); };
  const confirmBulk = () => { if (!bulkConfirmation) return; const { action } = bulkConfirmation; const target = visible.filter(item => action === "accept" ? !item.canonicalId && item.suggestions.length > 0 : !item.canonicalId && !item.ignored); setUndo(resolutions); setResolutions(current => current.map(item => target.some(value => value.sourceName === item.sourceName) ? action === "accept" ? { ...item, canonicalId: item.suggestions[0].id, canonicalName: item.suggestions[0].name, remember: true } : { ...item, ignored: true } : item)); setBulkConfirmation(undefined); };
  const commit = async () => { if (busy) return; if (!snapshots.length || reviewCount || attention) { setError(reviewCount ? `${reviewCount} dish names still need a decision. Review or ignore these dishes before importing.` : `${workbookIssueCount || 1} workbooks need attention. Resolve the workbook issues before importing.`); return; } const total = snapshots.length; const days = snapshots.reduce((count, snapshot) => count + snapshot.days.length, 0); setBusy(true); setError(""); setProgress({ phase: "importing", total, completed: 0, current: snapshots[0]?.week.weekCommencing || "the first selected week", weeks: total, days, dishes: resolutions.length, matched: resolutions.filter(item => Boolean(item.canonicalId)).length, review: 0 }); try { const response = await fetch("/api/rolling-menu/import", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "commit", snapshots, resolutions }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message || "The menu weeks could not be imported."); await clearImportSession().catch(() => undefined); setMessage(`Imported ${total} menu week${total === 1 ? "" : "s"} as planning source. Your Dish Library was not changed.`); setFiles([]); setReports([]); setSnapshots([]); setResolutions([]); setConflicts([]); setProgress(current => current ? { ...current, phase: "success", completed: total, days, current: snapshots[total - 1]?.week.weekCommencing || current.current } : current); } catch (cause) { const reason = cause instanceof Error ? cause.message : "The menu weeks could not be imported."; setError(reason); setProgress(current => current ? { ...current, phase: "error", error: reason } : undefined); } finally { setBusy(false); } };
  const restoreSession = () => { if (!resume) return; setFiles(resume.files.map(file => new File([], file.name, { type: file.type, lastModified: file.lastModified }))); setReports(resume.reports as Report[]); setSnapshots(resume.snapshots); setResolutions(resume.resolutions as Decision[]); setOverrides(resume.overrides); setConflicts(resume.conflicts as Conflict[]); setResume(undefined); }; const discardSession = () => { void clearImportSession(); setResume(undefined); };
  const filters: Array<[string, string]> = [["all", "All"], ["review", "Needs review"], ["needs-dish", "Needs a dish"], ["matched", "Matched"], ["ignored", "Ignored"]];

  return <MenuPlanningShell section="Planner">{progress && <ProgressModal progress={progress} onClose={() => setProgress(undefined)} />}{bulkConfirmation && <div className="import-confirm-backdrop" role="presentation"><section className="import-confirm-modal" role="dialog" aria-modal="true" aria-labelledby="bulk-confirm-title"><h2 id="bulk-confirm-title">{bulkConfirmation.action === "ignore" ? `Ignore ${bulkConfirmation.count} dish names?` : `Accept ${bulkConfirmation.count} suggested matches?`}</h2><p>{bulkConfirmation.action === "ignore" ? "These dishes will not be added to the imported menu weeks." : "Use the suggested existing Dish Library match for these names."}</p><div className="import-progress-footer"><button type="button" className="import-secondary-action" onClick={() => setBulkConfirmation(undefined)}>Cancel</button><button type="button" className="import-submit" onClick={confirmBulk}>{bulkConfirmation.action === "ignore" ? `Ignore ${bulkConfirmation.count} dishes` : `Accept ${bulkConfirmation.count} matches`}</button></div></section></div>}<main className="import-menu-week"><p className="import-eyebrow">MENU PLANNING</p><h1>Import menu weeks</h1><p className="import-lede">Upload Brian&apos;s weekly menu spreadsheets. We&apos;ll match dishes to your existing Dish Library before anything is added.</p>
    {resume && <section className="import-resume" role="status"><div><strong>Resume import review</strong><span>{resume.snapshots.length} menu weeks · {resume.resolutions.filter(item => !item.canonicalId && !item.ignored).length} dishes still need review</span></div><div><button type="button" onClick={restoreSession}>Resume</button><button type="button" className="import-secondary-action" onClick={discardSession}>Discard saved import</button></div></section>}
    {!files.length && <section className={`import-dropzone${dragging ? " is-dragging" : ""}`} onDragEnter={event => { event.preventDefault(); setDragging(true); }} onDragOver={event => event.preventDefault()} onDragLeave={() => setDragging(false)} onDrop={event => { event.preventDefault(); setDragging(false); addFiles([...event.dataTransfer.files]); }}><button type="button" onClick={() => inputRef.current?.click()}>Choose Excel files</button><input ref={inputRef} type="file" accept=".xlsx,.xls" multiple hidden onChange={event => addFiles([...(event.target.files || [])])} /><p>or drag and drop files here</p><small>Select one or many .xlsx or .xls workbooks.</small></section>}
    {files.length > 0 && <><section className="import-workbooks"><div className="import-section-heading"><h2>Selected workbooks</h2><button type="button" className="import-secondary-action" onClick={() => inputRef.current?.click()}>Add more files</button></div><input ref={inputRef} type="file" accept=".xlsx,.xls" multiple hidden onChange={event => addFiles([...(event.target.files || [])])} /><div>{reports.map(report => <div className="import-workbook-row" key={report.fileName}><strong>{report.fileName}</strong><span>{report.weekCommencing || "Week date needed"}</span><span className={report.status === "valid" ? "import-status-success" : "import-status-warning"}>{report.status === "valid" ? "Valid" : "Needs attention"}</span>{report.error && <small>{report.error}</small>}{!report.weekCommencing && <input type="date" aria-label={`Choose week date for ${report.fileName}`} onChange={event => chooseDate(report.fileName, event.target.value)} />}<button type="button" className="import-tertiary-action" onClick={() => removeFile(report.fileName)}>Remove</button></div>)}</div></section>
      {snapshots.length > 0 && <><section className="import-summary"><div><strong>{snapshots.length}</strong><span>menu weeks</span></div><div><strong>{resolutions.length}</strong><span>dish names</span></div><div><strong>{resolvedCount}</strong><span>resolved</span></div><div><strong>{reviewCount}</strong><span>need review</span></div><div className="import-summary-progress"><span style={{ width: `${resolutions.length ? Math.round((resolvedCount / resolutions.length) * 100) : 0}%` }} /></div></section>
        <div className="import-review-toolbar"><div className="import-filter-row">{filters.map(([value, label]) => <button className={filter === value ? "is-active" : ""} key={value} onClick={() => setFilter(value)}>{label} <span>{filterCounts[value as keyof typeof filterCounts]}</span></button>)}<span className="import-visible-count">{visible.length} shown</span></div><div className="import-bulk-row"><button className="import-bulk-primary" onClick={() => applyBulk("accept")} disabled={!visible.some(item => !item.canonicalId && item.suggestions.length)}>Accept {visible.filter(item => !item.canonicalId && item.suggestions.length).length} suggested matches</button><button className="import-bulk-subtle" onClick={() => applyBulk("ignore")} disabled={!visible.some(item => !item.canonicalId && !item.ignored)}>Ignore {visible.filter(item => !item.canonicalId && !item.ignored).length} shown</button>{undo && <button className="import-tertiary-action" onClick={() => { setResolutions(undo); setUndo(undefined); }}>Undo last bulk action</button>}</div></div>
        <div className="import-review-table"><div className="import-review-header"><span>Source dish</span><span>Match</span><span>Used</span><span>Status / action</span></div>{visible.map(item => <div className="import-review-row" key={item.sourceName}><strong>{item.sourceName}</strong><span>{item.canonicalId ? <span className="import-status-success">{item.canonicalName}</span> : item.ignored ? <span className="import-status-warning">Ignored</span> : item.suggestions[0]?.name || "No match found"}</span><span>{item.occurrences}×<small>{item.workbookCount || 1} week{(item.workbookCount || 1) === 1 ? "" : "s"}</small></span><span className="import-review-actions">{item.canonicalId ? <span className="import-status-success">Matched</span> : item.ignored ? <span className="import-status-warning">Ignored</span> : <>{item.suggestions[0] && <button className="import-action-primary" onClick={() => choose(item.sourceName, item.suggestions[0].id)}>Use match</button>}<button className="import-action-secondary" onClick={() => setOpenSource(openSource === item.sourceName ? undefined : item.sourceName)}>{item.suggestions[0] ? "Choose another" : "Choose dish"}</button><button className="import-action-tertiary" onClick={() => ignore(item.sourceName)}>Ignore</button></>}</span>{openSource === item.sourceName && !item.canonicalId && !item.ignored && <span className="import-dish-search"><input aria-label={`Search Dish Library for ${item.sourceName}`} placeholder="Search Dish Library" value={search} onChange={event => setSearch(event.target.value)} /><select aria-label={`Choose existing dish for ${item.sourceName}`} defaultValue="" onChange={event => event.target.value && choose(item.sourceName, event.target.value)}><option value="">Choose an existing dish</option>{filteredCatalogue.map(option => <option key={option.id} value={option.id}>{option.name}</option>)}</select></span>}</div>)}</div>
        <section className="import-ready"><h2>{reviewCount ? `${reviewCount} dish names still need a decision` : workbookIssueCount ? `${workbookIssueCount} workbooks need attention` : "Ready to import"}</h2><p>{reviewCount ? "Review or ignore these dishes before importing." : workbookIssueCount ? "Resolve the workbook issues before importing." : `${snapshots.length} weeks · ${resolvedCount} dish names resolved · 0 new dishes`}</p><p><strong>Your Dish Library will not be changed.</strong></p>{reviewCount && <button type="button" className="import-secondary-action" onClick={() => setFilter("review")}>Show unresolved dishes</button>}{workbookIssueCount > 0 && <div className="import-conflict-group"><strong>Workbook issues</strong>{reports.filter(report => report.status !== "valid").map(report => <div key={report.fileName}><span>{report.fileName}</span><small>{report.error || "Review this workbook before importing."}</small></div>)}</div>}{conflicts.length > 0 && <div className="import-conflict-group"><strong>Already in Menu Planning</strong>{conflicts.map(conflict => <div key={conflict.weekCommencing}><span>WC {conflict.weekCommencing} — {conflict.status}</span><small>Existing weeks are never overwritten. Remove this workbook before importing.</small></div>)}</div>}<button className="import-submit" disabled={Boolean(reviewCount) || attention || busy} onClick={() => void commit()}>{busy ? "Preparing import…" : `Import ${snapshots.length} menu weeks`}</button></section></>}
    </>}
    {error && <p role="alert" className="import-error">{error}</p>}{message && <p role="status" className="import-message">{message}</p>}
  </main></MenuPlanningShell>;
}
