const assert = require('node:assert/strict');
const test = require('node:test');
const path = require('node:path');
const { setup, jobs, loads, run, execute, lifecycle, nativeExecute, depart } = require('./helpers/execution-fixture.cjs');
const ok = result => assert.equal(result.response.status, 200, JSON.stringify(result.body));
const projection = f => f.records.get('fikaLogisticsDayProjectionsV1/' + f.date);
const stop = (f, lane) => f.load(path.resolve(__dirname, '../lib/projection-dashboard-adapter.ts')).projectionToDashboardData(projection(f)).stops.find(s => s.canonicalId.startsWith('projection-stop:' + lane + ':'));
test('fresh projected-only run readies and dispatches only after all delivery jobs loaded', async () => {
  const f = await setup(); ok(await lifecycle(f, 'mark-run-ready')); assert.equal((await lifecycle(f, 'dispatch-run')).response.status, 422);
  ok(await execute(f, 'mark-subload-loaded', 'delivery', { jobId: jobs(f)[0].id })); assert.equal(jobs(f)[0].deliveryStatus, 'loaded'); assert.equal(jobs(f)[1].deliveryStatus, 'pending'); assert.equal(loads(f)[0].loaded, false);
  ok(await execute(f, 'mark-subload-loaded', 'delivery', { jobId: jobs(f)[1].id })); assert.equal(loads(f)[0].loaded, true); ok(await lifecycle(f, 'dispatch-run')); assert.equal(loads(f)[0].status, 'dispatched'); assert.equal(run(f).status, 'dispatched');
});
test('arrival and partial delivery preserve other subloads and collection independently', async () => {
  const f = await setup({ collection: true }); await depart(f); ok(await execute(f, 'arrive-stop')); assert.equal(stop(f, 'delivery').status, 'arrived');
  ok(await execute(f, 'mark-subload-delivered', 'delivery', { jobId: jobs(f)[0].id })); assert.equal(jobs(f)[1].deliveryStatus, 'loaded'); assert.notEqual(loads(f)[0].status, 'delivered'); assert.notEqual(stop(f, 'delivery').status, 'completed');
  ok(await execute(f, 'mark-subload-delivered', 'delivery', { jobId: jobs(f)[1].id })); assert.equal(loads(f)[0].status, 'delivered'); assert.notEqual(stop(f, 'collection').status, 'completed'); assert.equal(run(f).returnToCpuPending, undefined);
  ok(await execute(f, 'arrive-stop', 'collection')); ok(await execute(f, 'mark-subload-collected', 'collection', { jobId: jobs(f)[0].id })); assert.equal(jobs(f)[1].collectionStatus, 'awaiting'); assert.equal(stop(f, 'collection').status, 'arrived');
  ok(await execute(f, 'mark-subload-collected', 'collection', { jobId: jobs(f)[1].id })); assert.equal(stop(f, 'collection').status, 'completed'); assert.equal(jobs(f)[0].deliveryStatus, 'delivered'); assert.equal(run(f).returnToCpuPending, true); ok(await lifecycle(f, 'confirm-returned-to-cpu')); assert.equal(run(f).status, 'completed');
});
for (const native of [false, true]) for (const status of ['planned', 'ready']) for (const invalid of ['unloaded', 'withdrawn', 'newer']) test(`${native ? 'native' : 'projected'} ${status} dispatch rejects ${invalid}`, async () => {
  const f = await setup({ native, count: native ? 1 : 2 }); if (status === 'ready') ok(await lifecycle(f, 'mark-run-ready'));
  if (invalid === 'withdrawn') f.requirements[0].status = 'withdrawn'; if (invalid === 'newer') f.requirements[0].sourceVersion++;
  if (invalid !== 'unloaded') { const result = native ? await nativeExecute(f, 'mark-stop-loaded') : await execute(f, 'mark-stop-loaded'); if (invalid === 'newer' || invalid === 'withdrawn') assert.ok([200, 409].includes(result.response.status)); }
  const before = structuredClone([...f.records]); assert.notEqual((await lifecycle(f, 'dispatch-run')).response.status, 200); assert.deepEqual([...f.records], before);
});
for (const native of [false, true]) for (const returnRequired of [true, false]) test(`${native ? 'native' : 'projected'} final issue resolution applies return policy ${returnRequired}`, async () => {
  const f = await setup({ native, count: 1 }); f.records.get('fikaLogisticsDeliveryRunsV1/r1').returnToCpuRequired = returnRequired; await depart(f, native);
  const act = (action, extra = {}) => native ? nativeExecute(f, action, extra) : execute(f, action, 'delivery', extra);
  ok(await act('report-issue', { issueDescription: 'Access delay' })); ok(await act('complete-stop', { confirmDirect: true })); assert.equal(run(f).status, 'dispatched'); assert.equal(Boolean(run(f).returnToCpuPending), false);
  const issue = native ? f.records.get('fikaLogisticsDeliveryStopsV1/native').issues[0] : loads(f)[0].deliveryExecution.issues[0]; ok(await act('resolve-issue', { issueId: issue.id })); assert.equal(run(f).status, returnRequired ? 'dispatched' : 'completed'); assert.equal(Boolean(run(f).returnToCpuPending), returnRequired);
});
for (const lane of ['delivery', 'collection']) test('whole ' + lane + ' undo restores prior partial progress exactly', async () => {
  const f = await setup({ collection: true }); await depart(f);
  ok(await execute(f, lane === 'delivery' ? 'mark-subload-delivered' : 'mark-subload-collected', lane, { jobId: jobs(f)[0].id })); const before = jobs(f);
  ok(await execute(f, 'complete-stop', lane, { confirmDirect: true })); ok(await execute(f, 'undo-completion', lane));
  for (const job of jobs(f)) { const prior = before.find(j => j.id === job.id); assert.equal(job.deliveryStatus, prior.deliveryStatus); assert.equal(job.collectionStatus, prior.collectionStatus); } assert.equal(Boolean(run(f).returnToCpuPending), false);
});
test('wrong lane, foreign job and stale job/load versions fail without writes', async () => {
  const f = await setup({ collection: true }); const before = structuredClone([...f.records]);
  for (const [action, lane, extra, status] of [['mark-stop-loaded', 'collection', {}, 422], ['mark-subload-loaded', 'delivery', { jobId: 'foreign' }, 422], ['mark-subload-loaded', 'delivery', { jobId: jobs(f)[0].id, expectedJobVersions: { [jobs(f)[0].id]: 0 } }, 409], ['mark-stop-loaded', 'delivery', { expectedLoadVersions: { [loads(f)[0].id]: 0 } }, 409]]) { assert.equal((await execute(f, action, lane, extra)).response.status, status); assert.deepEqual([...f.records], before); }
});
test('merged whole loading is atomic and individual loading mutates only its own aggregate', async () => {
  const f = await setup({ merged: true }); const original = loads(f); const otherJob = jobs(f)[1]; ok(await execute(f, 'mark-subload-loaded', 'delivery', { jobId: jobs(f)[0].id })); assert.equal(jobs(f)[1].deliveryStatus, 'pending'); assert.equal(loads(f).find(l => l.id === otherJob.activeLoadId).version, original.find(l => l.id === otherJob.activeLoadId).version);
  const versions = Object.fromEntries(loads(f).map(l => [l.id, l.version])); versions[loads(f)[1].id] = 0; const before = structuredClone([...f.records]); assert.equal((await execute(f, 'mark-stop-loaded', 'delivery', { expectedLoadVersions: versions })).response.status, 409); assert.deepEqual([...f.records], before); ok(await execute(f, 'mark-stop-loaded')); assert.ok(loads(f).every(l => l.loaded));
});
test('projected issues persist by lane and resolving one leaves the other open', async () => {
  const f = await setup({ collection: true }); await depart(f); ok(await execute(f, 'report-issue', 'delivery', { issueDescription: 'Delivery issue' })); ok(await execute(f, 'report-issue', 'collection', { issueDescription: 'Collection issue' }));
  assert.equal(stop(f, 'delivery').issues[0].description, 'Delivery issue'); assert.equal(stop(f, 'collection').issues[0].description, 'Collection issue'); ok(await execute(f, 'resolve-issue', 'delivery', { issueId: stop(f, 'delivery').issues[0].id })); assert.equal(stop(f, 'collection').issues[0].status, 'open');
});
test('shared merged issue remains visible after grouping splits', async () => {
  const f = await setup({ merged: true }); await depart(f); ok(await execute(f, 'report-issue', 'delivery', { issueDescription: 'Shared exception' })); assert.equal(loads(f)[0].deliveryExecution.issues[0].id, loads(f)[1].deliveryExecution.issues[0].id);
  ok(await execute(f, 'mark-subload-delivered', 'delivery', { jobId: jobs(f)[0].id })); assert.equal(projection(f).deliveryLoads.length, 2); assert.ok(loads(f).every(l => l.deliveryExecution.issues[0].status === 'open'));
});
test('projected group omission fails closed', async () => { const f = await setup({ merged: true }); assert.equal((await execute(f, 'mark-stop-loaded', 'delivery', { loadIds: [loads(f)[0].id] })).response.status, 409); });
test('delivery run waits only for its own collection legs', async () => { const f = await setup({ count: 1, collection: true }); f.records.get('fikaLogisticsDeliveryLoadsV1/' + loads(f)[0].id).collectionRunId = 'r2'; await depart(f); ok(await execute(f, 'complete-stop', 'delivery', { confirmDirect: true })); assert.equal(run(f).returnToCpuPending, true); assert.equal(jobs(f)[0].collectionStatus, 'awaiting'); });
for (const native of [false, true]) test('return and explicit completion reject outstanding ' + (native ? 'native' : 'projected') + ' work', async () => { const f = await setup({ native, count: 1 }); await depart(f, native); f.records.get('fikaLogisticsDeliveryRunsV1/r1').returnToCpuPending = true; assert.equal((await lifecycle(f, 'confirm-returned-to-cpu')).response.status, 422); assert.equal((await lifecycle(f, 'complete-run')).response.status, 422); });
test('required collection without timing blocks dispatch', async () => { const f = await setup({ collection: true }); delete f.records.get('fikaLogisticsDeliveryLoadsV1/' + loads(f)[0].id).collectionScheduledTime; ok(await execute(f, 'mark-stop-loaded')); assert.equal((await lifecycle(f, 'dispatch-run')).response.status, 422); });
test('mixed run requires native and projected delivery loading', async () => { const f = await setup({ count: 1 }); f.seed('fikaLogisticsDeliveryStopsV1', 'native', { canonicalId: 'native', runId: 'r1', sequence: 1, locationOplocId: 'site:native', locationLabelSnapshot: 'Native movement', requirementRefs: [], movementRequestIds: [], plannedArrivalTime: '12:00', status: 'planned', loaded: false, version: 1, audit: [], createdAt: 'now', updatedAt: 'now' }); ok(await execute(f, 'mark-stop-loaded')); assert.equal((await lifecycle(f, 'dispatch-run')).response.status, 422); ok(await nativeExecute(f, 'mark-stop-loaded')); ok(await lifecycle(f, 'dispatch-run')); });
for (const action of ['mark-run-ready', 'dispatch-run']) test('vehicle-authorised operator can ' + action + ' after historical driver revocation', async () => { const f = await setup(); f.deactivateDriver(); if (action === 'dispatch-run') ok(await execute(f, 'mark-stop-loaded')); const historical = run(f).driverId; ok(await lifecycle(f, action)); assert.equal(run(f).driverId, historical); });
for (const invalid of ['cancelled', 'withdrawn', 'destination']) test('projected execution rejects ' + invalid + ' source authority', async () => { const f = await setup(); if (invalid === 'cancelled') f.records.get('fikaLogisticsDeliveryLoadsV1/' + loads(f)[0].id).status = 'cancelled'; else f.records.get('fikaLogisticsJobsV1/' + jobs(f)[0].id)[invalid === 'withdrawn' ? 'sourceStatus' : 'destinationOplocId'] = invalid === 'withdrawn' ? 'withdrawn' : 'other'; const before = structuredClone([...f.records]); assert.equal((await execute(f, 'mark-stop-loaded')).response.status, 409); assert.deepEqual([...f.records], before); });
test('execution and collection defer reject before dispatch safely', async () => { const f = await setup({ collection: true }); assert.equal((await execute(f, 'arrive-stop')).response.status, 422); assert.equal((await execute(f, 'defer-collection', 'collection')).response.status, 422); });
test('native undo clears completed/return state without changing projected progress', async () => { const f = await setup({ native: true, count: 1 }); await depart(f, true); ok(await nativeExecute(f, 'complete-stop', { confirmDirect: true })); assert.equal(run(f).returnToCpuPending, true); ok(await nativeExecute(f, 'undo-completion')); assert.equal(run(f).returnToCpuPending, false); assert.equal(run(f).status, 'dispatched'); });
test('unauthorized vehicle execution fails closed', async () => { const f = await setup(); f.principal.permittedVehicleIds = ['van2']; assert.equal((await execute(f, 'mark-stop-loaded')).response.status, 403); });

test('collection completion before delivery preserves loaded delivery state and blocks return', async () => { const f = await setup({ collection: true }); await depart(f); ok(await execute(f, 'complete-stop', 'collection', { confirmDirect: true })); assert.ok(jobs(f).every(job => job.deliveryStatus === 'loaded')); assert.equal(loads(f)[0].status, 'dispatched'); assert.equal(Boolean(run(f).returnToCpuPending), false); assert.equal((await lifecycle(f, 'confirm-returned-to-cpu')).response.status, 422); });
test('whole delivery completion needs loading and explicit arrival/direct confirmation', async () => { const f = await setup(); f.records.get('fikaLogisticsDeliveryRunsV1/r1').status = 'dispatched'; assert.equal((await execute(f, 'complete-stop', 'delivery', { confirmDirect: true })).response.status, 422); f.records.get('fikaLogisticsDeliveryRunsV1/r1').status = 'planned'; await depart(f); assert.equal((await execute(f, 'complete-stop')).response.status, 422); ok(await execute(f, 'arrive-stop')); assert.equal((await execute(f, 'arrive-stop')).response.status, 422); ok(await execute(f, 'complete-stop')); });
test('post-dispatch loading and foreign run execution fail', async () => { const f = await setup(); await depart(f); assert.equal((await execute(f, 'mark-stop-loaded')).response.status, 422); assert.equal((await execute(f, 'arrive-stop', 'delivery', { runId: 'r2', expectedRunVersion: run(f, 'r2').version })).response.status, 422); });
test('undo cannot overwrite a job mutated after whole completion', async () => { const f = await setup({ collection: true }); await depart(f); ok(await execute(f, 'complete-stop', 'delivery', { confirmDirect: true })); f.records.get('fikaLogisticsJobsV1/' + jobs(f)[0].id).version++; const before = structuredClone([...f.records]); assert.equal((await execute(f, 'undo-completion')).response.status, 409); assert.deepEqual([...f.records], before); });
test('source reconciliation preserves delivery execution authority', async () => { const f = await setup(); ok(await execute(f, 'mark-subload-loaded', 'delivery', { jobId: jobs(f)[0].id })); const version = jobs(f)[0].version; f.requirements[0].sourceVersion++; f.requirements[0].lines[0].quantity++; await f.materialisation.reconcileLogisticsDay(f.date, 'Operator'); assert.equal(jobs(f)[0].deliveryStatus, 'loaded'); assert.equal(jobs(f)[0].version, version + 1); });
test('adding/removing pending jobs recomputes persisted load aggregates', async () => { const f = await setup({ count: 1 }); ok(await execute(f, 'mark-stop-loaded')); const req = { ...f.requirements[0], canonicalId: 'req:new', sourceEntityId: 'order:new' }; f.requirements.push(req); await f.materialisation.reconcileLogisticsDay(f.date, 'Operator'); const job = jobs(f).find(job => job.requirementId === req.canonicalId); const prior = loads(f)[0]; ok(await f.post({ action: 'assign-job-to-load', jobId: job.id, expectedJobVersion: job.version, expectedLoadVersions: { [prior.id]: prior.version }, targetRunId: 'r1', scheduledTime: '10:30' })); assert.equal(loads(f)[0].loaded, false); const current = jobs(f).find(j => j.id === job.id), load = loads(f)[0]; ok(await f.post({ action: 'remove-job-from-load', jobId: job.id, expectedJobVersion: current.version, expectedLoadVersion: load.version })); assert.equal(loads(f)[0].loaded, true); });
test('withdrawal recomputes the remaining loaded aggregate', async () => { const f = await setup(); ok(await execute(f, 'mark-subload-loaded', 'delivery', { jobId: jobs(f)[0].id })); f.requirements[1].status = 'withdrawn'; f.requirements[1].sourceVersion++; await f.materialisation.reconcileLogisticsDay(f.date, 'Operator'); assert.equal(loads(f)[0].loaded, true); });
for (const native of [false, true]) test('completed run undo reopens safely after CPU return; native=' + native, async () => { const f = await setup({ native, count: 1 }); await depart(f, native); ok(native ? await nativeExecute(f, 'complete-stop', { confirmDirect: true }) : await execute(f, 'complete-stop', 'delivery', { confirmDirect: true })); ok(await lifecycle(f, 'confirm-returned-to-cpu')); assert.equal(run(f).status, 'completed'); ok(native ? await nativeExecute(f, 'undo-completion') : await execute(f, 'undo-completion')); assert.equal(run(f).status, 'dispatched'); assert.equal(run(f).returnedToCpuAt, undefined); assert.equal(run(f).returnToCpuPending, false); });
test('open projected issue blocks both return and explicit complete-run', async () => { const f = await setup(); await depart(f); ok(await execute(f, 'report-issue', 'delivery', { issueDescription: 'Blocked access' })); ok(await execute(f, 'complete-stop', 'delivery', { confirmDirect: true })); f.records.get('fikaLogisticsDeliveryRunsV1/r1').returnToCpuPending = true; assert.equal((await lifecycle(f, 'confirm-returned-to-cpu')).response.status, 422); assert.equal((await lifecycle(f, 'complete-run')).response.status, 422); });

for (const stale of [false, true]) test('shared issue resolution after split is atomic; stale other copy=' + stale, async () => {
  const f = await setup({ merged: true }); await depart(f); ok(await execute(f, 'report-issue', 'delivery', { issueDescription: 'Shared access exception' })); ok(await execute(f, 'mark-subload-delivered', 'delivery', { jobId: jobs(f)[0].id }));
  const selected = loads(f)[0]; const versions = Object.fromEntries(loads(f).map(load => [load.id, load.version])); if (stale) versions[loads(f)[1].id] = 0;
  const before = structuredClone([...f.records]); const result = await f.post({ action: 'resolve-issue', runId: 'r1', expectedRunVersion: run(f).version, stopId: 'projection-stop:delivery:' + selected.id, loadIds: [selected.id], expectedLoadVersions: versions, issueId: selected.deliveryExecution.issues[0].id });
  if (stale) { assert.equal(result.response.status, 409); assert.deepEqual([...f.records], before); } else { ok(result); assert.ok(loads(f).every(load => load.deliveryExecution.issues[0].status === 'resolved')); }
});

for (const action of ['mark-subload-delivered', 'complete-stop']) test('native ' + action + ' cannot bypass dispatch/loading', async () => { const f = await setup({ native: true, count: 1 }); assert.equal((await nativeExecute(f, action, { requirementId: 'req:0', confirmDirect: true })).response.status, 422); f.records.get('fikaLogisticsDeliveryRunsV1/r1').status = 'dispatched'; assert.equal((await nativeExecute(f, action, { requirementId: 'req:0', confirmDirect: true })).response.status, 422); });
test('native collection per-subload completion stays independent', async () => { const f = await setup({ native: true, count: 1 }); const stop = f.records.get('fikaLogisticsDeliveryStopsV1/native'); stop.movementType = 'collection'; stop.linkedOperation = 'collection'; assert.equal((await nativeExecute(f, 'mark-stop-loaded')).response.status, 422); ok(await lifecycle(f, 'dispatch-run')); ok(await nativeExecute(f, 'mark-subload-collected', { requirementId: 'req:0' })); assert.deepEqual(f.records.get('fikaLogisticsDeliveryStopsV1/native').collectedRequirementIds, ['req:0']); assert.equal(f.records.get('fikaLogisticsDeliveryStopsV1/native').deliveredRequirementIds, undefined); assert.equal(run(f).returnToCpuPending, true); });

test('native exact undo survives Firestore-style omission of undefined snapshot fields', async () => { const f = await setup({ native: true, count: 1 }); await depart(f, true); ok(await nativeExecute(f, 'complete-stop', { confirmDirect: true })); const key = 'fikaLogisticsDeliveryStopsV1/native'; f.records.set(key, JSON.parse(JSON.stringify(f.records.get(key)))); ok(await nativeExecute(f, 'undo-completion')); assert.deepEqual(f.records.get(key).deliveredRequirementIds, []); assert.equal(f.records.get(key).loaded, true); assert.notEqual(f.records.get(key).status, 'completed'); });

test('fresh draft projected-only assignment plans the run once and can become Ready', async () => { const f = await setup({ draft: true }); assert.equal(run(f).status, 'planned'); assert.equal(run(f).version, 3); assert.deepEqual(run(f).orderedStopIds, []); assert.equal([...f.records.keys()].some(key => key.startsWith('fikaLogisticsDeliveryStopsV1/')), false); ok(await lifecycle(f, 'mark-run-ready')); assert.equal(run(f).status, 'ready'); });
