import assert from "node:assert/strict";
import { test } from "node:test";
import { applyLogisticsChange, buildLogisticsDayProjection } from "../lib/logistics-projection";
import type { DeliveryLoad, LogisticsAssignment, LogisticsChangeEvent, LogisticsJob } from "../lib/types";

const job = (id: string, time = "11:30"): LogisticsJob => ({ id, sourceType: "cpu-production", sourceId: id, serviceDate: "2026-08-24", originOplocId: "oploc:cpu", destinationOplocId: "oploc:mnk", requestedWindow: { startTime: time }, productionReadiness: "ready", collectionStatus: "awaiting", contents: [{ description: "Lunch", quantity: 10, unit: "portion" }], createdAt: "now", updatedAt: "now", version: 1, audit: [] });
const load = (id: string, time: string): DeliveryLoad => ({ id, serviceDate: "2026-08-24", originOplocId: "oploc:cpu", destinationOplocId: "oploc:mnk", scheduledTime: time, status: "planned", createdAt: "now", updatedAt: "now", version: 1, audit: [] });
const assignment = (jobId: string, loadId: string): LogisticsAssignment => ({ jobId, loadId, assignedAt: "now", assignedBy: "test", audit: [] });
const event = (sequence: number, entityId = "a"): LogisticsChangeEvent => ({ sequence, entityType: "assignment", entityId, relatedEntityId: "load:1", changeType: "job-assigned", revision: sequence, changedAt: "now", actorId: "test" });

test("initial projection is compact and job/load based", () => { const projection = buildLogisticsDayProjection({ serviceDate: "2026-08-24", jobs: [job("a"), job("b", "14:00")], loads: [load("load:1", "11:30")], assignments: [assignment("a", "load:1")] }); assert.equal(projection.planningQueue.length, 1); assert.equal(projection.deliveryLoads[0].jobCount, 1); assert.equal(projection.summary.assignedJobs, 1); });
test("same-destination loads at the same time merge while retaining their source load ids", () => { const first = load("load:1", "11:30"); const second = load("load:2", "11:30"); const projection = buildLogisticsDayProjection({ serviceDate: "2026-08-24", jobs: [job("a"), job("b")], loads: [first, second], assignments: [assignment("a", first.id), assignment("b", second.id)] }); assert.equal(projection.deliveryLoads.length, 1); assert.deepEqual(projection.deliveryLoads[0].loadIds, [first.id, second.id]); assert.equal(projection.deliveryLoads[0].jobCount, 2); });
test("replay is idempotent and cursor is monotonic", () => { const base = buildLogisticsDayProjection({ serviceDate: "2026-08-24", jobs: [job("a")], loads: [load("load:1", "11:30")], assignments: [] }); const once = applyLogisticsChange(base, event(2), { serviceDate: "2026-08-24", jobs: [job("a")], loads: [load("load:1", "11:30")], assignments: [assignment("a", "load:1")] }); const duplicate = applyLogisticsChange(once, event(2), { serviceDate: "2026-08-24", jobs: [job("a")], loads: [load("load:1", "11:30")], assignments: [assignment("a", "load:1")] }); assert.equal(once.deliveryLoads[0].jobCount, 1); assert.equal(duplicate, once); });
test("moving a job changes only the projected load membership", () => { const a = job("a"); const first = load("load:1", "11:30"); const second = load("load:2", "14:00"); const before = buildLogisticsDayProjection({ serviceDate: a.serviceDate, jobs: [a], loads: [first, second], assignments: [assignment("a", first.id)] }); const after = applyLogisticsChange(before, event(3), { serviceDate: a.serviceDate, jobs: [a], loads: [first, second], assignments: [assignment("a", second.id)] }); assert.equal(after.deliveryLoads.find((item) => item.id === first.id), undefined); assert.equal(after.deliveryLoads.find((item) => item.id === second.id)?.jobCount, 1); });
test("orphaned empty loads are not shown as operational work", () => { const projection = buildLogisticsDayProjection({ serviceDate: "2026-08-24", jobs: [], loads: [load("load:orphan", "07:00")], assignments: [] }); assert.equal(projection.deliveryLoads.length, 0); assert.equal(projection.summary.loads, 0); });
