import assert from "node:assert/strict";
import { test } from "node:test";
import { combineStop, isNewlyPlannable, orderedTransferStops, planningAttention, runsForDriver } from "../lib/planning";
import type { DeliveryStop } from "../lib/types";
import type { FulfilmentRequirement } from "../../shared/fulfilment-requirement";

const requirement = (sourceDomain: FulfilmentRequirement["sourceDomain"], id: string, status: FulfilmentRequirement["status"] = "ready_for_planning", sourceVersion = 1): FulfilmentRequirement => ({ canonicalId:`req:${id}`, entityType:"Fulfilment Requirement", schemaVersion:"0.1.0", version:sourceVersion, sourceDomain, sourceEntityId:id, sourceVersion, destinationOplocId:"oploc:one", destinationLabelSnapshot:"One Angel Court", serviceDate:"2026-08-20", lines:[{canonicalId:`line:${id}`,sourceLineId:`line:${id}`,displayNameSnapshot:`${sourceDomain} item`,quantity:2,unit:"portion",sortOrder:0}], status, createdAt:"now",createdBy:"test",updatedAt:"now",updatedBy:"test",audit:[],idempotencyKey:`${id}:${sourceVersion}` });
const stop = (refs: {requirementId:string;sourceVersion:number}[]): DeliveryStop => ({canonicalId:"stop:1",runId:"run:1",sequence:1,locationOplocId:"oploc:one",locationLabelSnapshot:"One Angel Court",requirementRefs:refs,status:"planned",createdAt:"now",updatedAt:"now",version:1,audit:[]});

test("central requirements render regardless of source domain", () => assert.equal(new Set([requirement("cpu-production","cpu"),requirement("menu-planning","menu"),requirement("grab-and-go","grab")].map(r=>r.sourceDomain)).size, 3));
test("same destination combines and duplicate assignment is rejected", () => { const first=combineStop([], {locationOplocId:"oploc:one",locationLabel:"One Angel Court",requirement:requirement("cpu-production","a"),runId:"run:1",by:"Franco"}); const combined=combineStop([first], {locationOplocId:"oploc:one",locationLabel:"One Angel Court",requirement:requirement("menu-planning","b"),runId:"run:1",by:"Franco"}); assert.equal(combined.canonicalId,first.canonicalId); assert.equal(combined.requirementRefs.length,2); assert.throws(()=>combineStop([combined], {locationOplocId:"oploc:one",locationLabel:"One Angel Court",requirement:requirement("cpu-production","a"),runId:"run:1",by:"Franco"})); });
test("withdrawn work cannot be newly planned", () => { const withdrawn=requirement("grab-and-go","gone","withdrawn"); assert.equal(isNewlyPlannable(withdrawn,[]),false); assert.throws(()=>combineStop([], {locationOplocId:"oploc:one",locationLabel:"One Angel Court",requirement:withdrawn,runId:"run:1",by:"Franco"})); });
test("newer and amended upstream requirements are visibly flagged", () => { const ref={requirementId:"req:a",sourceVersion:1}; assert.equal(planningAttention(requirement("cpu-production","a","ready_for_planning",2),ref),"AMENDED — review source changes"); assert.equal(planningAttention(requirement("cpu-production","a","amended",1),ref),"AMENDED — review source changes"); assert.equal(planningAttention(requirement("cpu-production","a","withdrawn",2),ref),"WITHDRAWN — remove from plan"); });
test("movement types are represented as planning work", () => { const movement={canonicalId:"move:delivery",entityType:"Movement Request" as const,type:"delivery" as const,serviceDate:"2026-08-20",toOplocId:"oploc:one",items:[{description:"Crates",quantity:3}],createdBy:"Franco",status:"open" as const,version:1,createdAt:"now",updatedAt:"now",audit:[]}; const planned=combineStop([], {locationOplocId:"oploc:one",locationLabel:"One Angel Court",movement,runId:"run:1",by:"Franco"}); assert.equal(planned.movementRequestId,"move:delivery"); });
test("collection is ordered before delivery and drivers only see their runs", () => { const base={runId:"run:1",locationOplocId:"oploc:one",locationLabelSnapshot:"One",requirementRefs:[],status:"planned" as const,createdAt:"now",updatedAt:"now",version:1,audit:[]}; const ordered=orderedTransferStops([{...base,canonicalId:"drop",sequence:1,movementType:"delivery",movementRequestId:"move:1"},{...base,canonicalId:"pickup",sequence:2,movementType:"collection",movementRequestId:"move:1"}]); assert.deepEqual(ordered.map(stop=>stop.canonicalId),["pickup","drop"]); assert.deepEqual(runsForDriver([{driverLabel:"Franco"},{driverLabel:"Dee"},{driverLabel:"Franco"}],"Dee"),[{driverLabel:"Dee"}]); });
