import assert from "node:assert/strict";
import { test } from "node:test";
import { buildPlannerDay, movementQueueState, workGroupQueueState } from "../lib/planner-read-model";
import type { DeliveryRun, DeliveryStop, MovementRequest } from "../lib/types";
import type { FulfilmentRequirement } from "../../shared/fulfilment-requirement";

const requirement = (id:string, sourceDomain:FulfilmentRequirement["sourceDomain"], window?:{startTime:string;endTime?:string}, status:FulfilmentRequirement["status"]="ready_for_planning", sourceVersion=1):FulfilmentRequirement => ({ canonicalId:`req:${id}`, entityType:"Fulfilment Requirement", schemaVersion:"0.1.0", version:sourceVersion, sourceDomain, sourceEntityId:`source:${id}`, sourceVersion, destinationOplocId:"oploc:haleon", destinationLabelSnapshot:"Haleon", serviceDate:"2026-08-24", ...(window ? {requiredDeliveryWindow:window} : {}), lines:[{canonicalId:`line:${id}:1`,sourceLineId:`source-line:${id}`,canonicalItemId:id === "same" ? "dish:same" : undefined,displayNameSnapshot:id === "same" ? "Same dish" : id,quantity:2,unit:id === "items" ? "item" : "portion",sortOrder:0}], status, createdAt:"now", createdBy:"test", updatedAt:"now", updatedBy:"test", audit:[], idempotencyKey:id });
const run = (id:string):DeliveryRun => ({canonicalId:id,serviceDate:"2026-08-24",status:"planned",driverLabel:"Franco",orderedStopIds:[],version:3,createdAt:"now",updatedAt:"now",audit:[]});
const stop = (id:string, runId:string, refs:DeliveryStop["requirementRefs"], movementRequestIds:string[]=[], timing?:{requiredTime?:string;window?:{startTime:string;endTime?:string};plannedArrivalTime?:string;plannedWindow?:{startTime:string;endTime?:string}}):DeliveryStop => ({canonicalId:id,runId,sequence:1,locationOplocId:"oploc:haleon",locationLabelSnapshot:"Haleon",requirementRefs:refs, movementRequestIds, movementType:movementRequestIds.length ? "delivery" : undefined,status:"planned",createdAt:"now",updatedAt:"now",version:1,audit:[],...timing});
const movement = (id:string,type:MovementRequest["type"]="transfer"):MovementRequest => ({canonicalId:id,entityType:"Movement Request",type,serviceDate:"2026-08-24",fromOplocId:"oploc:from",toOplocId:"oploc:haleon",items:[{description:"Hot cupboard",quantity:2,unit:"item"},{description:"Portioned lunch",quantity:4,unit:"portion"}],notes:"Loading bay",createdBy:"Franco",status:"open",version:1,createdAt:"now",updatedAt:"now",audit:[]});
const health = {fulfilment:{available:true},oplocs:{available:true},enrichment:{available:true}};
const base = (requirements:FulfilmentRequirement[], runs:DeliveryRun[]=[], stops:DeliveryStop[]=[], movements:MovementRequest[]=[]) => buildPlannerDay({serviceDate:"2026-08-24",requirements,runs,stops,movements,oplocs:[{id:"oploc:haleon",label:"Haleon"},{id:"oploc:from",label:"Loading Bay"}],health});

test("same destination and window groups mixed Menu, Grab & Go and CPU work",()=>{const day=base([requirement("menu","menu-planning",{startTime:"10:15",endTime:"10:45"}),requirement("grab","grab-and-go",{startTime:"10:15",endTime:"10:45"}),requirement("cpu","cpu-production",{startTime:"10:15",endTime:"10:45"})],[ ],[],[]);assert.equal(day.workGroups.length,1);assert.equal(day.workGroups[0].requirementCount,3);assert.deepEqual(day.workGroups[0].sourceLabels,["Menu Planning","Grab & Go","CPU Production"])});
test("different windows and no-window work stay in predictable separate groups",()=>{const day=base([requirement("a","menu-planning",{startTime:"10:00",endTime:"10:30"}),requirement("b","grab-and-go",{startTime:"11:00",endTime:"11:30"}),requirement("c","cpu-production"),requirement("d","cpu-production")]);assert.equal(day.workGroups.length,3);assert.equal(day.workGroups.filter(group=>!group.deliveryWindow).length,1)});
test("hospitality production enrichment changes only the human source label",()=>{const item=requirement("hospitality","cpu-production");const day=buildPlannerDay({serviceDate:"2026-08-24",requirements:[item],runs:[],stops:[],movements:[],oplocs:[],health,production:[{canonicalId:item.sourceEntityId,origin:"hospitality_booking",clientName:"Haleon",guestCount:40}]});assert.deepEqual(day.workGroups[0].sourceLabels,["Hospitality"]);assert.equal(day.workGroups[0].productionContext?.guestCount,40)});
test("enrichment failure leaves core work available",()=>{const day=buildPlannerDay({serviceDate:"2026-08-24",requirements:[requirement("cpu","cpu-production")],runs:[],stops:[],movements:[],oplocs:[],health:{...health,enrichment:{available:false,error:"CPU unavailable"}},production:[]});assert.equal(day.workGroups.length,1);assert.equal(day.upstreamHealth.enrichment.available,false)});
test("combined lines aggregate safe identity and unit only",()=>{const same=requirement("same","menu-planning");const same2={...requirement("same-2","grab-and-go"),lines:[{...same.lines[0],canonicalId:"line:2",sourceLineId:"source:2",quantity:3}]};const mixedUnit={...requirement("items","cpu-production"),lines:[{...same.lines[0],canonicalId:"line:3",sourceLineId:"source:3",canonicalItemId:"dish:same",displayNameSnapshot:"Same dish",quantity:7,unit:"item"}]};const day=base([same,same2,mixedUnit]);assert.equal(day.workGroups[0].combinedLines.length,2);assert.deepEqual(day.workGroups[0].unitBreakdown,[{unit:"portion",quantity:5},{unit:"item",quantity:7}])});
test("pending, amended and withdrawn work creates explicit attention states",()=>{const day=base([requirement("pending","menu-planning",undefined,"pending"),requirement("amended","grab-and-go",undefined,"amended"),requirement("withdrawn","cpu-production",undefined,"withdrawn")]);assert.equal(day.workGroups[0].readiness,"ATTENTION");assert.ok(day.workGroups[0].attention.some(item=>item.includes("Withdrawn")));assert.ok(day.workGroups[0].attention.some(item=>item.includes("Amended")))});
test("planned and partially planned group state exposes run and stop references",()=>{const a=requirement("a","menu-planning");const b=requirement("b","grab-and-go");const runOne=run("run:1");runOne.orderedStopIds=["stop:1"];const day=base([a,b],[runOne],[stop("stop:1","run:1",[{requirementId:a.canonicalId,sourceVersion:a.sourceVersion}])]);assert.equal(day.workGroups[0].planningState,"partially_planned");assert.equal(day.workGroups[0].requirementRefs.find(ref=>ref.requirementId===a.canonicalId)?.stopId,"stop:1");assert.equal(day.summary.partiallyPlanned,1)});
test("run summaries resolve stop contents, warnings and source labels",()=>{const item=requirement("a","menu-planning",undefined,"amended");const current=run("run:1");current.orderedStopIds=["stop:1"];const day=base([item],[current],[stop("stop:1","run:1",[{requirementId:item.canonicalId,sourceVersion:1}])]);assert.equal(day.runs[0].stops[0].requirementCount,1);assert.deepEqual(day.runs[0].stops[0].sourceLabels,["Menu Planning"]);assert.ok(day.runs[0].stops[0].attention.length)});
test("movement view retains transfer semantics and assignment context",()=>{const item=movement("movement:1");const current=run("run:1");current.orderedStopIds=["stop:1"];const day=base([],[current],[stop("stop:1","run:1",[],[item.canonicalId])],[item]);assert.equal(day.movements[0].type,"transfer");assert.equal(day.movements[0].planningState,"partially_planned");assert.equal(day.movements[0].from?.label,"Loading Bay");assert.equal(day.movements[0].assignedStops[0].sequence,1)});
test("assigned timed work is scheduled while assigned untimed work stays in the planning queue",()=>{const timed=requirement("timed","menu-planning",{startTime:"10:00",endTime:"10:30"});const untimed=requirement("untimed","grab-and-go");const current=run("run:1");current.orderedStopIds=["stop:timed","stop:untimed"];const day=base([timed,untimed],[current],[stop("stop:timed","run:1",[{requirementId:timed.canonicalId,sourceVersion:1}],[],{plannedWindow:{startTime:"10:00",endTime:"10:30"}}),stop("stop:untimed","run:1",[{requirementId:untimed.canonicalId,sourceVersion:1}])]);assert.equal(workGroupQueueState(day.workGroups.find(group=>group.requirementRefs.some(ref=>ref.requirementId===timed.canonicalId))!,day.runs),"scheduled");assert.equal(workGroupQueueState(day.workGroups.find(group=>group.requirementRefs.some(ref=>ref.requirementId===untimed.canonicalId))!,day.runs),"needs_time");assert.equal(day.runs[0].scheduledStopCount,1);assert.equal(day.runs[0].needsTimeStopCount,1);assert.equal(day.summary.scheduledStops,1);assert.equal(day.summary.needsTime,1)});
test("unassigned and attention work remain queue-visible and untimed movements receive no schedule",()=>{const unassigned={...requirement("unassigned","menu-planning"),destinationOplocId:"oploc:other",destinationLabelSnapshot:"Other"};const amended=requirement("amended-queue","grab-and-go",undefined,"amended");const current=run("run:1");current.orderedStopIds=["stop:amended","stop:movement"];const item=movement("movement:untimed");const day=base([unassigned,amended],[current],[stop("stop:amended","run:1",[{requirementId:amended.canonicalId,sourceVersion:1}]),stop("stop:movement","run:1",[],[item.canonicalId])],[item]);assert.equal(workGroupQueueState(day.workGroups.find(group=>group.requirementRefs.some(ref=>ref.requirementId===unassigned.canonicalId))!,day.runs),"unassigned");assert.equal(workGroupQueueState(day.workGroups.find(group=>group.requirementRefs.some(ref=>ref.requirementId===amended.canonicalId))!,day.runs),"attention");assert.equal(movementQueueState(day.movements[0],day.runs),"needs_time");assert.equal(day.runs[0].needsTimeStopCount,2)});
