import { addApproval, cloneVersion, transition, updateVersion as updateVersionRecord, type BeverageInnovation, type ApprovalDecision, type ApprovalKind, type Lifecycle, type IngredientLine } from "./domain";
const now = "2026-08-10T09:00:00Z";
const seed: BeverageInnovation[] = [
  { id:"beverage:summer-strawberry-matcha", name:"Summer Strawberry Matcha", description:"A bright seasonal matcha concept for FIKA sites.", beverageType:"Signature drink", season:"Summer 2026", lifecycle:"in_development", ownerRole:"Beverage developer", concept:{ flavourDirection:"Fresh strawberry, creamy matcha", useCase:"Summer refreshment", serviceFormat:"Iced", seasonalContext:"Summer 2026" }, versions:[{ id:"beverage:summer-strawberry-matcha:version:1", number:1, status:"prototype", recipeNotes:"Matcha, coconut, strawberry and ice.", method:"Build over ice and finish with strawberry.", ingredients:[{id:"ingredient:matcha",name:"Matcha",sourceStatus:"deferred"},{id:"ingredient:strawberry",name:"Strawberry",sourceStatus:"deferred"}], equipment:["Shaker","Iced cup"], allergenStatus:"awaiting_canonical_source", allergens:[], createdAt:now, createdByRole:"Beverage developer"}], currentVersionId:"beverage:summer-strawberry-matcha:version:1", prototypes:[{id:"beverage:summer-strawberry-matcha:prototype:1",name:"First kitchen trial",notes:"Balance strawberry sweetness against matcha.",createdAt:now}], rollouts:[], approvals:[], assets:[{id:"asset:summer-strawberry-matcha:photo",type:"photo",status:"missing"},{id:"asset:summer-strawberry-matcha:guide",type:"service_guide",status:"missing"}], feedback:[], audit:[{at:now,action:"created",actorRole:"Beverage developer"}] },
  { id:"beverage:autumn-spiced-cold-brew", name:"Autumn Spiced Cold Brew", description:"A warming seasonal cold brew direction for review.", beverageType:"Coffee", season:"Autumn 2026", lifecycle:"brand_review", ownerRole:"Beverage developer", concept:{flavourDirection:"Coffee, cinnamon and orange",useCase:"Autumn menu",serviceFormat:"Cold brew"}, versions:[], prototypes:[], rollouts:[], approvals:[{id:"approval:autumn:ops",kind:"operational",decision:"approved",actorRole:"Coffee and beverage leadership",createdAt:now}], assets:[{id:"asset:autumn:photo",type:"photo",status:"ready"}],feedback:[],audit:[{at:now,action:"created",actorRole:"Beverage developer"}] },
  { id:"beverage:house-citrus-spritz", name:"House Citrus Spritz", description:"Approved concept awaiting a site-ready rollout plan.", beverageType:"Mocktail", season:"All year", lifecycle:"rollout", ownerRole:"Beverage developer", concept:{useCase:"Events and hospitality",serviceFormat:"Spritz"}, versions:[], prototypes:[], rollouts:[{id:"rollout:house-citrus:mnk",oplocId:"oploc:mnk",siteLabel:"MNK",state:"blocked",blockers:["Equipment confirmation required"],readiness:{equipment:false,ingredients:"deferred",training:false,assets:true}}],approvals:[{id:"approval:house:ops",kind:"operational",decision:"approved",actorRole:"Coffee and beverage leadership",createdAt:now},{id:"approval:house:brand",kind:"brand",decision:"approved",actorRole:"Marketing and brand approver",createdAt:now}],assets:[],feedback:[],audit:[{at:now,action:"created",actorRole:"Beverage developer"}] },
];
const cocktailSource = "Cocktails Drinks Recipe.pptx";
const cocktailImportedAt = "2026-08-12T09:00:00Z";
const cocktailRecipes: Array<{ key: string; name: string; ingredients: string[]; method: string; equipment: string }> = [
  { key: "espresso-martini", name: "Espresso Martini", ingredients: ["50 mL vodka", "25 mL coffee liqueur", "25 mL cold espresso", "3 coffee beans for garnish"], method: "Shaker & double strain. Shake cold espresso, vodka and coffee liqueur vigorously with ice, then double strain into a chilled coupe. Garnish with coffee beans.", equipment: "Shaker; double strainer; coupe" },
  { key: "elderflower-fizz", name: "Elderflower Fizz", ingredients: ["50 mL purple gin", "12.5 mL lime juice", "12.5 mL elderflower liqueur", "5–6 mint leaves", "Elderflower tonic"], method: "Build and stir. Add lime, elderflower liqueur and gin to an iced wine glass. Clap the mint, add it to the glass, stir gently and top with elderflower tonic.", equipment: "Wine glass; bar spoon" },
  { key: "mojito", name: "Mojito", ingredients: ["6–7 mint leaves", "3–4 lime wedges", "50 mL rum", "12.5–25 mL brown sugar syrup", "Soda water"], method: "Build and stir. Muddle lime, clap the mint, then shake with rum, syrup and ice. Pour into an iced hi-ball and top with soda water.", equipment: "Shaker; muddler; hi-ball" },
  { key: "strawberry-basil-lemonade", name: "Strawberry Basil Lemonade", ingredients: ["3 strawberries", "6 oz lemonade", "3–4 basil leaves", "Lemon wheel and basil sprig for garnish"], method: "Shake and double strain. Muddle the strawberries, clap the basil, add lemonade and ice, shake for 30–60 seconds and double strain over ice.", equipment: "Shaker; double strainer; rocks or cocktail glass" },
  { key: "butterfly-passion-cooler", name: "Butterfly Passion Cooler", ingredients: ["12 mL lime juice", "12.5 mL passionfruit juice", "12.5 mL simple syrup", "Butterfly pea tea"], method: "Build. Stir lime, passionfruit juice and syrup in a cocktail glass. Add ice and top gently with butterfly pea tea to create a gradient.", equipment: "Cocktail glass; bar spoon" },
];
const importedCocktails: BeverageInnovation[] = cocktailRecipes.map((recipe) => {
  const id = `beverage:${recipe.key}`;
  const versionId = `${id}:version:1`;
  return { id, name: recipe.name, description: `${recipe.name} recipe imported from the cocktail recipe source deck.`, beverageType: "Cocktail / mocktail", season: "Source recipe", lifecycle: "in_development", ownerRole: "Beverage developer", concept: { serviceFormat: "Cocktail service", useCase: "Beverage innovation catalogue", notes: "Imported as source evidence for deliberate review." }, versions: [{ id: versionId, number: 1, status: "prototype", recipeNotes: recipe.ingredients.join("; "), method: recipe.method, ingredients: recipe.ingredients.map((name, index) => ({ id: `${versionId}:ingredient:${index + 1}`, name, sourceStatus: "deferred" as const })), equipment: [recipe.equipment], allergenStatus: "awaiting_canonical_source", allergens: [], createdAt: cocktailImportedAt, createdByRole: "Beverage developer" }], currentVersionId: versionId, prototypes: [], rollouts: [], approvals: [], assets: [], feedback: [], audit: [{ at: cocktailImportedAt, action: "imported:cocktails-drinks-recipe", actorRole: "Beverage developer" }], sourceEvidence: { fileName: cocktailSource, importedAt: cocktailImportedAt, sourceKey: recipe.key } };
});
const byName = new Map<string, BeverageInnovation>();
for (const record of [...seed, ...importedCocktails]) byName.set(record.name.trim().toLocaleLowerCase(), record);
let records = structuredClone([...byName.values()]);
export function listBeverages(){return structuredClone(records)}
export function getBeverage(id:string){return structuredClone(records.find(x=>x.id===id))}
export function createBeverage(input: Pick<BeverageInnovation,"name"|"description"|"beverageType">){const id=`beverage:${input.name.toLowerCase().replace(/[^a-z0-9]+/g,"-")}`;if(records.some(x=>x.id===id))throw new Error("A beverage with this name already exists.");const record:BeverageInnovation={...input,id,lifecycle:"idea",ownerRole:"Beverage developer",concept:{},versions:[],prototypes:[],rollouts:[],approvals:[],assets:[],feedback:[],audit:[{at:new Date().toISOString(),action:"created",actorRole:"Beverage developer"}]};records=[...records,record];return structuredClone(record)}
export function setLifecycle(id:string,lifecycle:Lifecycle){const record=records.find(x=>x.id===id);if(!record)throw new Error("Beverage not found.");const next=transition(record,lifecycle);records=records.map(x=>x.id===id?next:x);return structuredClone(next)}
export function recordApproval(id:string,kind:ApprovalKind,decision:ApprovalDecision,actorRole:string,notes?:string){const record=records.find(x=>x.id===id);if(!record)throw new Error("Beverage not found.");const next=addApproval(record,kind,decision,actorRole,notes);records=records.map(x=>x.id===id?next:x);return structuredClone(next)}
export function createVersion(id:string){const record=records.find(x=>x.id===id);if(!record)throw new Error("Beverage not found.");const next=cloneVersion(record);records=records.map(x=>x.id===id?next:x);return structuredClone(next)}
export function updateVersion(id:string, versionId:string, patch:{recipeNotes:string;method:string;ingredients:IngredientLine[];equipment:string[]}){const record=records.find(x=>x.id===id);if(!record)throw new Error("Beverage not found.");const next=updateVersionRecord(record,versionId,patch);records=records.map(x=>x.id===id?next:x);return structuredClone(next)}
