"use client";

import { useEffect, useMemo, useState } from "react";
import type { GrabAndGoOrder, GrabAndGoProduct } from "../lib/grab-and-go";
import { productsForDeliveryDate } from "../lib/grab-and-go";
import { cacheGrabAndGoCatalogue, grabAndGoCatalogueManifestMatches, readCachedGrabAndGoCatalogue } from "./lib/grab-and-go-catalogue-indexeddb";

type DeliveryDate = { date: string; rotationWeek: number; weekday: string; cutoff: string };
type Data = { catalogue: GrabAndGoProduct[]; catalogueStale?: boolean; deliveryDates: DeliveryDate[]; orders: Array<GrabAndGoOrder & { editable: boolean }>; suggestedLinesByDate: Record<string, Array<{ productId: string; quantity: number }>>; cutoffHour: number };
type Quantities = Record<string, Record<string, number>>;
const displayDate = (value: string) => new Date(`${value}T00:00:00Z`).toLocaleDateString("en-GB", { weekday: "long", day: "numeric", month: "long", timeZone: "UTC" });
const displayDateShort = (value: string) => new Date(`${value}T00:00:00Z`).toLocaleDateString("en-GB", { day: "numeric", month: "long", timeZone: "UTC" });
async function fetchCatalogueManifest(oplocId: string) { const response = await fetch(`/api/delivered-in/grab-and-go/catalogue?manifest=1&oplocId=${encodeURIComponent(oplocId)}`, { cache: "no-store" }); const body = await response.json(); if (!response.ok || !body.manifest) throw new Error("The current Grab & Go catalogue is unavailable."); return body.manifest; }
async function fetchCataloguePackage(oplocId: string) { const response = await fetch(`/api/delivered-in/grab-and-go/catalogue?oplocId=${encodeURIComponent(oplocId)}`, { cache: "no-store" }); const body = await response.json(); if (!response.ok || !body.catalogue || !body.manifest) throw new Error("The current Grab & Go catalogue is unavailable."); return body as { catalogue: { schemaVersion: 1; products: GrabAndGoProduct[] }; manifest: import("@fika/server-shared/read-package").ReadPackageManifest }; }

export default function GrabAndGoView({ oplocId, accountScope }: { oplocId: string; accountScope: string }) {
  const [data, setData] = useState<Data>(); const [quantities, setQuantities] = useState<Quantities>({}); const [busyDate, setBusyDate] = useState(""); const [error, setError] = useState("");
  const load = async () => { try {
    const cached = await readCachedGrabAndGoCatalogue(accountScope);
    let catalogue: GrabAndGoProduct[]; let catalogueStale = false;
    try {
      const manifest = await fetchCatalogueManifest(oplocId);
      if (cached && grabAndGoCatalogueManifestMatches(cached.manifest, manifest)) catalogue = cached.catalogue.products;
      else { const packageValue = await fetchCataloguePackage(oplocId); catalogue = packageValue.catalogue.products; await cacheGrabAndGoCatalogue(accountScope, packageValue.catalogue, packageValue.manifest); }
    } catch (catalogueError) {
      if (!cached) throw catalogueError;
      catalogue = cached.catalogue.products; catalogueStale = true;
    }
    const response = await fetch(`/api/delivered-in/grab-and-go?oplocId=${encodeURIComponent(oplocId)}`, { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error("Unavailable"); setData({ ...body, catalogue, catalogueStale }); const next: Quantities = {}; for (const date of body.deliveryDates.slice(0, 2) as DeliveryDate[]) { const existing = (body.orders as Array<GrabAndGoOrder>).find(order => order.deliveryDate === date.date); const lines: Array<{ productId: string; quantity: number }> = existing?.lines || body.suggestedLinesByDate?.[date.date] || []; next[date.date] = Object.fromEntries(lines.map(line => [line.productId, line.quantity])); } setQuantities(next); setError("");
  } catch { setError("The ordering catalogue is temporarily unavailable. Please check back shortly."); } };
  useEffect(() => { void load(); }, [oplocId, accountScope]);
  const dates = useMemo(() => data?.deliveryDates.slice(0, 2) || [], [data]);
  const basketTotal = dates.reduce((sum, date) => sum + Object.values(quantities[date.date] || {}).reduce((dayTotal, quantity) => dayTotal + quantity, 0), 0);
  const save = async (date: string, action: "submit" | "amend" | "cancel") => { const existing = data?.orders.find(order => order.deliveryDate === date); setBusyDate(date); setError(""); try { const response = await fetch("/api/delivered-in/grab-and-go", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ oplocId, deliveryDate: date, action, expectedVersion: existing?.version, lines: Object.entries(quantities[date] || {}).map(([productId, quantity]) => ({ productId, quantity })) }) }); if (!response.ok) throw new Error("Unable to save order"); await load(); } catch { setError("We couldn’t save that order. Please check your quantities and try again."); } finally { setBusyDate(""); } };
  if (!data) return <section className="content"><div className="empty-state"><p>{error || "Loading Grab & Go…"}</p></div></section>;
  return <section className="content grab-and-go-content"><header className="grab-hero"><div><p className="eyebrow">CPU-owned catalogue</p><h1>Grab &amp; Go ordering</h1><p>Plan your next Monday and Wednesday deliveries together.<br />Previous-week quantities are copied into a draft when available.</p>{data.catalogueStale && <p className="grab-copy-note">Using the last verified catalogue while the current package is unavailable.</p>}</div><div className="grab-hero-facts"><Fact icon="◷" label="Ordering cut-off" value={`${data.cutoffHour}:00 the day before`} /><Fact icon="▦" label="Delivery days" value="Mon & Wed" /><Fact icon="⟳" label="Rotation week" value={`Week ${dates[0]?.rotationWeek || "—"}`} /></div></header>{error && <p className="grab-error" role="alert">{error}</p>}<div className="grab-layout"><div className="grab-order-board">{dates.map(date => <GrabAndGoDay key={date.date} data={data} date={date} quantities={quantities[date.date] || {}} busy={busyDate === date.date} onQuantity={(productId, quantity) => setQuantities(current => ({ ...current, [date.date]: { ...current[date.date], [productId]: quantity } }))} onSave={action => void save(date.date, action)} />)}</div><GrabSidebar dates={dates} quantities={quantities} total={basketTotal} onReview={() => document.querySelector(".grab-order-board")?.scrollIntoView({ behavior: "smooth", block: "start" })} cutoffHour={data.cutoffHour} /></div></section>;
}

function Fact({ icon, label, value }: { icon: string; label: string; value: string }) { return <div className="grab-fact"><span className="grab-fact-icon">{icon}</span><div><span>{label}</span><strong>{value}</strong></div></div>; }
function GrabSidebar({ dates, quantities, total, onReview, cutoffHour }: { dates: DeliveryDate[]; quantities: Quantities; total: number; onReview: () => void; cutoffHour: number }) { return <aside className="grab-sidebar"><section className="basket-card"><header><h2><span aria-hidden="true">♧</span> Your basket</h2><span className="basket-pill">{total} items</span></header><div className="basket-total"><span>Total items</span><strong>{total}</strong></div><div className="basket-days">{dates.map(date => <div key={date.date}><strong>{date.weekday} {displayDateShort(date.date)}</strong><span>{Object.values(quantities[date.date] || {}).reduce((sum, quantity) => sum + quantity, 0)} items</span></div>)}</div><button className="primary-button basket-review" type="button" onClick={onReview}>Review quantities <span>→</span></button><p className="basket-note">Submit each delivery order below when your quantities are ready.</p></section><section className="support-card"><h3><span className="support-icon green">⌁</span> Ordering help</h3><a href="#how-it-works"><span><strong>How it works</strong><small>Simple steps to place your order</small></span><b>›</b></a><a href="mailto:food@fika.co.uk"><span><strong>Need help?</strong><small>Contact the FIKA Food team</small></span><b>›</b></a></section><section className="support-card"><h3><span className="support-icon">▣</span> Delivery information</h3><div className="delivery-info"><p><span className="status-dot" />Delivery window <strong>07:00 – 10:30</strong></p><p><span>◷</span>Ordering cut-off <strong>{cutoffHour}:00 the day before</strong></p></div></section></aside>; }

function GrabAndGoDay({ data, date, quantities, busy, onQuantity, onSave }: { data: Data; date: DeliveryDate; quantities: Record<string, number>; busy: boolean; onQuantity: (productId: string, quantity: number) => void; onSave: (action: "submit" | "amend" | "cancel") => void }) {
  const existing = data.orders.find(order => order.deliveryDate === date.date); const editable = Boolean(!existing || existing.editable); const products = productsForDeliveryDate(data.catalogue, date.date); const grouped = { grab_250ml: products.filter(product => product.category === "grab_250ml"), stacking_salad_750ml: products.filter(product => product.category === "stacking_salad_750ml") }; const itemCount = Object.values(quantities).reduce((sum, quantity) => sum + quantity, 0); const copied = !existing && Boolean(data.suggestedLinesByDate[date.date]);
  const productRows = (items: GrabAndGoProduct[]) => <div className="grab-product-list">{items.map(product => <div className="grab-product-row" key={product.productId}><span className="product-mark" aria-hidden="true">✦</span><strong>{product.name}</strong><QuantityStepper product={product} quantity={quantities[product.productId] || 0} editable={editable} onQuantity={onQuantity} /></div>)}</div>;
  return <article className="grab-day-board"><header className="grab-day-header"><div><div className="grab-day-title"><p className="eyebrow">{date.weekday}</p><span className={editable ? "open-status" : "closed-status"}>{editable ? "Open now" : "Read-only"}</span></div><h2>{displayDate(date.date).toUpperCase()}</h2><div className="grab-day-meta"><span>⟳ &nbsp;Rotation week {date.rotationWeek}</span><i>·</i><span>Order by {data.cutoffHour}:00 the day before</span></div></div></header>{existing && <div className="grab-order-status">{existing.status === "cancelled" ? "Previous order cancelled" : existing.editable ? "Order submitted · quantities can be amended" : "Order submitted · read-only after cut-off"}</div>}{copied && <div className="grab-copy-note">Draft copied from last week’s {date.weekday} order. Check quantities before submitting.</div>}<section className="grab-section"><header><h3>250ml Pots</h3><span>{grouped.grab_250ml.length} products</span></header>{productRows(grouped.grab_250ml)}</section><section className="grab-section"><header><h3>750ml Pots</h3><span>{grouped.stacking_salad_750ml.length} products</span></header>{productRows(grouped.stacking_salad_750ml)}</section><footer className="grab-order-actions"><strong>{itemCount} items</strong><div>{existing?.status === "submitted" && existing.editable && <button className="secondary-button" disabled={busy} onClick={() => onSave("cancel")}>Cancel order</button>}{editable && <button className="primary-button" disabled={busy || itemCount === 0} onClick={() => onSave(existing?.status === "submitted" ? "amend" : "submit")}>{busy ? "Saving…" : existing?.status === "submitted" ? "Amend order" : "Submit order"} <span>→</span></button>}</div></footer></article>;
}
function QuantityStepper({ product, quantity, editable, onQuantity }: { product: GrabAndGoProduct; quantity: number; editable: boolean; onQuantity: (productId: string, quantity: number) => void }) { return <div className="grab-quantity"><button type="button" aria-label={`Decrease ${product.name}`} disabled={!editable || !quantity} onClick={() => onQuantity(product.productId, Math.max(0, quantity - 1))}>−</button><output aria-label={`${quantity} ${product.name}`}>{quantity}</output><button type="button" aria-label={`Increase ${product.name}`} disabled={!editable} onClick={() => onQuantity(product.productId, quantity + 1)}>+</button></div>; }
