"use client";

import { useEffect, useMemo, useState } from "react";
import type { GrabAndGoOrder, GrabAndGoProduct } from "../lib/grab-and-go";
import { productsForDeliveryDate } from "../lib/grab-and-go";

type DeliveryDate = { date: string; rotationWeek: number; weekday: string; cutoff: string };
type Data = { catalogue: GrabAndGoProduct[]; deliveryDates: DeliveryDate[]; orders: Array<GrabAndGoOrder & { editable: boolean }>; suggestedLinesByDate: Record<string, Array<{ productId: string; quantity: number }>>; cutoffHour: number };
type Quantities = Record<string, Record<string, number>>;
const money = (value?: number) => value === undefined ? "" : `£${value.toFixed(2)}`;
const displayDate = (value: string) => new Date(`${value}T00:00:00Z`).toLocaleDateString("en-GB", { weekday: "long", day: "numeric", month: "long", timeZone: "UTC" });

export default function GrabAndGoView({ oplocId }: { oplocId: string }) {
  const [data, setData] = useState<Data>(); const [quantities, setQuantities] = useState<Quantities>({}); const [busyDate, setBusyDate] = useState(""); const [error, setError] = useState("");
  const load = async () => { try { const response = await fetch(`/api/delivered-in/grab-and-go?oplocId=${encodeURIComponent(oplocId)}`, { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message || "Grab & Go could not be loaded."); setData(body); const next: Quantities = {}; for (const date of body.deliveryDates.slice(0, 2) as DeliveryDate[]) { const existing = (body.orders as Array<GrabAndGoOrder>).find(order => order.deliveryDate === date.date); const lines: Array<{ productId: string; quantity: number }> = existing?.lines || body.suggestedLinesByDate?.[date.date] || []; next[date.date] = Object.fromEntries(lines.map(line => [line.productId, line.quantity])); } setQuantities(next); setError(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Grab & Go could not be loaded."); } };
  useEffect(() => { void load(); }, [oplocId]);
  const dates = useMemo(() => data?.deliveryDates.slice(0, 2) || [], [data]);
  const save = async (date: string, action: "submit" | "amend" | "cancel") => { const existing = data?.orders.find(order => order.deliveryDate === date); setBusyDate(date); setError(""); try { const response = await fetch("/api/delivered-in/grab-and-go", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ oplocId, deliveryDate: date, action, expectedVersion: existing?.version, lines: Object.entries(quantities[date] || {}).map(([productId, quantity]) => ({ productId, quantity })) }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message || "The Grab & Go order could not be saved."); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "The Grab & Go order could not be saved."); } finally { setBusyDate(""); } };
  if (!data) return <section className="content"><div className="empty-state"><p>Loading Grab & Go…</p></div></section>;
  return <section className="content grab-and-go-content"><header className="section-heading"><p className="eyebrow">CPU-owned catalogue · {oplocId}</p><h2>Grab & Go ordering</h2><p>Plan your next Monday and Wednesday deliveries together. Previous-week quantities are copied into a draft when available.</p></header>{error && <p className="error" role="alert">{error}</p>}<div className="grab-order-board">{dates.map(date => <GrabAndGoDay key={date.date} data={data} date={date} quantities={quantities[date.date] || {}} busy={busyDate === date.date} onQuantity={(productId, quantity) => setQuantities(current => ({ ...current, [date.date]: { ...current[date.date], [productId]: quantity } }))} onSave={action => void save(date.date, action)} />)}</div></section>;
}

function GrabAndGoDay({ data, date, quantities, busy, onQuantity, onSave }: { data: Data; date: DeliveryDate; quantities: Record<string, number>; busy: boolean; onQuantity: (productId: string, quantity: number) => void; onSave: (action: "submit" | "amend" | "cancel") => void }) {
  const existing = data.orders.find(order => order.deliveryDate === date.date); const editable = Boolean(!existing || existing.editable); const products = productsForDeliveryDate(data.catalogue, date.date); const grouped = { grab_250ml: products.filter(product => product.category === "grab_250ml"), stacking_salad_750ml: products.filter(product => product.category === "stacking_salad_750ml") }; const itemCount = Object.values(quantities).reduce((sum, quantity) => sum + quantity, 0); const copied = !existing && Boolean(data.suggestedLinesByDate[date.date]);
  const productRows = (items: GrabAndGoProduct[]) => <div className="grab-product-list">{items.map(product => <div className="grab-product-row" key={product.productId}><div><strong>{product.name}</strong>{product.price !== undefined && <small>{money(product.price)} each</small>}</div><div className="grab-quantity"><button type="button" aria-label={`Decrease ${product.name}`} disabled={!editable || !quantities[product.productId]} onClick={() => onQuantity(product.productId, Math.max(0, (quantities[product.productId] || 0) - 1))}>−</button><output>{quantities[product.productId] || 0}</output><button type="button" aria-label={`Increase ${product.name}`} disabled={!editable} onClick={() => onQuantity(product.productId, (quantities[product.productId] || 0) + 1)}>+</button></div></div>)}</div>;
  return <article className="grab-day-board"><header className="grab-day-header"><div><p className="eyebrow">{date.weekday}</p><h3>{displayDate(date.date)}</h3></div><div className="grab-day-meta"><strong>{itemCount} items</strong><span>Rotation week {date.rotationWeek}</span><small>Orders close at {data.cutoffHour}:00 the day before</small></div></header>{existing && <div className="grab-order-status">Order {existing.orderId} · version {existing.version} · {existing.status === "cancelled" ? "cancelled" : existing.editable ? "amendable" : "read-only after cutoff"}</div>}{copied && <div className="grab-copy-note">Draft copied from last week’s {date.weekday} order. Check quantities before submitting.</div>}<div className="grab-day-sections"><section className="grab-section"><header><div><p className="eyebrow">250ml pots</p><h4>Grab n Go · 250ml</h4></div><span>{grouped.grab_250ml.length} products</span></header>{productRows(grouped.grab_250ml)}</section><section className="grab-section"><header><div><p className="eyebrow">750ml pots</p><h4>Stacking Salads · 750ml</h4></div><span>{grouped.stacking_salad_750ml.length} products</span></header>{productRows(grouped.stacking_salad_750ml)}</section></div><footer className="grab-order-actions"><strong>{itemCount} items</strong><div>{existing?.status === "submitted" && existing.editable && <button className="secondary-button" disabled={busy} onClick={() => onSave("cancel")}>Cancel order</button>}{editable && <button className="primary-button" disabled={busy || itemCount === 0} onClick={() => onSave(existing?.status === "submitted" ? "amend" : "submit")}>{busy ? "Saving…" : existing?.status === "submitted" ? "Amend order" : "Submit order"}</button>}</div></footer></article>;
}
