"use client";

import { useEffect, useMemo, useState } from "react";
import type { ProjectedDay, ProjectedEntry, ProjectedWeek, Site } from "../lib/projection";
import { CANONICAL_ALLERGEN_COLUMNS } from "../lib/allergen-columns";
import { titleCase } from "../lib/text";
import { cacheDeliveredInDays, evictWithdrawnDeliveredInDays } from "./lib/delivered-in-indexeddb";

type Dashboard = { access: { email: string; oplocIds: string[]; permissions: string[] }; sites: Array<Site & { services?: { deliveredIn: boolean; grabAndGo: boolean } }>; selectedOplocId?: string; weeks: ProjectedWeek[] };
type View = "today" | "week" | "allergens";
const todayKey = () => new Date().toISOString().slice(0, 10);
const formatDate = (iso: string, options: Intl.DateTimeFormatOptions) => new Date(`${iso}T00:00:00Z`).toLocaleDateString("en-GB", { ...options, timeZone: "UTC" });
const formatSignedAt = (iso: string) => new Date(iso).toLocaleDateString("en-GB", { day: "numeric", month: "short", timeZone: "UTC" });
const dayTotal = (day: ProjectedDay) => day.entries.reduce((sum, entry) => sum + entry.quantity, 0);
const currentWeek = (weeks: ProjectedWeek[]) => weeks.find(week => week.weekCommencing <= todayKey() && week.weekEnding >= todayKey()) || weeks.find(week => week.weekCommencing >= todayKey()) || weeks[0];
const sectionFor = (entry: ProjectedEntry) => entry.slot || "Uncategorised";

function StatusChip({ children, tone = "neutral" }: { children: React.ReactNode; tone?: "neutral" | "good" | "warning" | "purple" }) { return <span className={`ops-chip ops-chip-${tone}`}>{children}</span>; }
function AllergenChips({ entry }: { entry: ProjectedEntry }) { if (entry.allergensVisible === false) return <div className="ops-chip-list"><span className="ops-muted">Available after CPU sign-off</span></div>; const chips: React.ReactNode[] = []; if (entry.allergens.vegan === "contains") chips.push(<StatusChip key="vegan" tone="good">Vegan</StatusChip>); else if (entry.allergens.vegetarian === "contains") chips.push(<StatusChip key="vegetarian" tone="good">Vegetarian</StatusChip>); for (const [name, value] of Object.entries(entry.allergens)) if (value !== "clear" && !["vegan", "vegetarian"].includes(name)) chips.push(<StatusChip key={name} tone="warning">{value === "may_contain" ? "May contain" : value === "unrecorded" ? "Unknown" : "Contains"} {name.replaceAll("_", " ")}</StatusChip>); return <div className="ops-chip-list">{chips.length ? chips : <span className="ops-muted">No allergen flags</span>}</div>; }
function PdfLink({ day }: { day: ProjectedDay }) { return day.drivePdfUrl ? <a className="ops-link" href={day.drivePdfUrl} target="_blank" rel="noopener noreferrer">View signed matrix PDF <span aria-hidden="true">↗</span></a> : <span className="ops-muted">Matrix PDF unavailable</span>; }

function SiteMenuControls({ day, site, onGenerated }: { day: ProjectedDay; site: Site; onGenerated: () => void }) { const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const state = day.siteMenu || { status: "none" as const }; const artifact = state.artifact; const signed = day.cpuReview?.status === "signed"; const generate = async () => { if (!signed) return; setBusy(true); setError(""); try { const response = await fetch("/api/delivered-in/site-menu", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ oplocId: site.oplocId, publicationDayId: day.publicationDayId, action: state.status === "none" ? "generate" : "regenerate" }) }); if (!response.ok) throw new Error(); onGenerated(); } catch { setError("Site menu could not be generated."); } finally { setBusy(false); } }; return <div className="ops-action-row"><span className={`menu-state menu-state-${state.status}`}>{!signed ? "Waiting for CPU allergen sign-off" : state.status === "current" ? "Site menu current" : state.status === "stale" ? "Site menu needs refresh" : "Site menu not generated"}</span>{signed && artifact && <a className="ops-link" href={artifact.driveUrl} target="_blank" rel="noopener noreferrer">View menu ↗</a>}{signed && <button className="ops-button ops-button-secondary" onClick={() => void generate()} disabled={busy}>{busy ? "Working…" : state.status === "none" ? "Generate site menu" : "Regenerate site menu"}</button>}{error && <span className="ops-error" role="alert">{error}</span>}</div>; }

function OperationalHeader({ site, day }: { site: Site; day?: ProjectedDay }) { const portions = day ? dayTotal(day) : 0; const cpuStatus = day?.cpuReview?.status === "signed" ? "Allergens signed" : day?.cpuReview ? "Needs allergen review" : "Pending CPU handoff"; const handoff = day?.cpuReview ? "Sent to CPU" : "Pending"; return <section className="ops-header-card"><div><p className="ops-eyebrow">Delivered-In · Internal review</p><h1>Delivered-In</h1><p className="ops-date">{day ? `${day.dayName} ${formatDate(day.date, { day: "numeric", month: "long", year: "numeric" })}` : "No published menu for today"}<span>·</span>{site.label}</p></div><div className="ops-header-status"><StatusChip tone={day ? "good" : "neutral"}>{day ? "Published" : "Not published"}</StatusChip>{day?.version && <span className="ops-version">Menu v{day.version}</span>}</div><div className="ops-fact-strip"><div><span>Portions</span><strong>{portions.toLocaleString()}</strong></div><div><span>Dishes</span><strong>{day?.entries.length || 0}</strong></div><div><span>Menu status</span><strong className={day ? "ops-good-text" : "ops-warning-text"}>{day ? "Published" : "Pending"}</strong></div><div><span>Handoff</span><strong className={handoff === "Sent to CPU" ? "ops-good-text" : "ops-warning-text"}>{handoff}</strong></div><div><span>Allergen matrix</span><strong className={cpuStatus === "Allergens signed" ? "ops-good-text" : "ops-warning-text"}>{cpuStatus === "Allergens signed" ? "Signed" : "Needs review"}</strong></div></div></section>; }

function DishTable({ day }: { day: ProjectedDay }) { return <section className="ops-panel"><div className="ops-panel-heading"><div><p className="ops-eyebrow">Published menu</p><h2>Dish allocation and governance</h2></div><span className="ops-muted">{day.entries.length} dishes · {dayTotal(day).toLocaleString()} portions</span></div><div className="ops-table-wrap"><table className="ops-table"><thead><tr><th>Slot</th><th>Dish</th><th className="numeric">Portions</th><th>Dietary / allergens</th><th>Status</th></tr></thead><tbody>{day.entries.map((entry, index) => <tr key={`${entry.sourceEntryId}-${index}`}><td><span className="slot-label">{sectionFor(entry)}</span></td><th>{titleCase(entry.dishName)}{entry.mayContainNotes && <small>{entry.mayContainNotes}</small>}</th><td className="numeric">{entry.quantity.toLocaleString()}</td><td><AllergenChips entry={entry} /></td><td><StatusChip tone="good">Published</StatusChip></td></tr>)}</tbody></table></div></section>; }

function OperationsSidebar({ day }: { day: ProjectedDay }) { const signatures = day.cpuReview?.signatures || []; const chef = signatures.find(item => item.role === "production_chef"); const manager = signatures.find(item => item.role === "head_chef_site_manager"); return <aside className="ops-sidebar"><section className="ops-panel ops-panel-compact"><div className="ops-panel-heading"><div><p className="ops-eyebrow">Publication / handoff</p><h2>Operational status</h2></div></div><dl className="ops-details"><div><dt>Menu version</dt><dd>{day.version}</dd></div><div><dt>Published date</dt><dd>{formatDate(day.date, { day: "numeric", month: "short", year: "numeric" })}</dd></div><div><dt>CPU handoff</dt><dd><StatusChip tone={day.cpuReview ? "good" : "warning"}>{day.cpuReview ? "Sent to CPU" : "Pending CPU handoff"}</StatusChip></dd></div><div><dt>Matrix</dt><dd><StatusChip tone={day.cpuReview?.status === "signed" ? "good" : "warning"}>{day.cpuReview?.status === "signed" ? "Signed" : "Needs review"}</StatusChip></dd></div></dl></section><section className="ops-panel ops-panel-compact"><div className="ops-panel-heading"><div><p className="ops-eyebrow">Allergen governance</p><h2>Sign-off record</h2></div></div><dl className="ops-details"><div><dt>Production chef</dt><dd>{chef ? `${chef.printedName} · ${formatSignedAt(chef.signedAt)}` : "Not signed"}</dd></div><div><dt>Head chef / manager</dt><dd>{manager ? `${manager.printedName} · ${formatSignedAt(manager.signedAt)}` : "Not signed"}</dd></div><div><dt>Matrix artifact</dt><dd><PdfLink day={day} /></dd></div></dl></section></aside>; }

function TodayView({ site, day, onGenerated }: { site: Site; day?: ProjectedDay; onGenerated: () => void }) { if (!day) return <><OperationalHeader site={site} /><div className="ops-empty"><h2>No published Delivered-In menu for today.</h2><p>There is no published operational menu for this service date.</p></div></>; return <><OperationalHeader site={site} day={day} /><div className="ops-layout"><div><DishTable day={day} /><SiteMenuControls day={day} site={site} onGenerated={onGenerated} /></div><OperationsSidebar day={day} /></div></>; }

function WeekView({ week, site, days, onGenerated }: { week?: ProjectedWeek; site: Site; days: ProjectedDay[]; onGenerated: () => void }) { return <><header className="ops-page-heading"><p className="ops-eyebrow">Published delivery schedule · {site.label}</p><h1>Delivered-In Menu Review</h1><p>{week ? `${formatDate(week.weekCommencing, { day: "numeric", month: "long" })} – ${formatDate(week.weekEnding, { day: "numeric", month: "long", year: "numeric" })}` : "No published week"}</p></header><div className="ops-week-grid">{days.map(day => <section className="ops-panel week-review-card" key={day.date}><div className="ops-panel-heading"><div><p className="ops-eyebrow">{day.dayName}</p><h2>{formatDate(day.date, { day: "numeric", month: "long" })}</h2></div><div className="ops-card-summary"><strong>{dayTotal(day).toLocaleString()}</strong><span>portions · {day.entries.length} dishes</span></div></div><div className="week-dish-list">{day.entries.slice(0, 8).map((entry, index) => <div key={`${entry.sourceEntryId}-${index}`}><span>{titleCase(entry.dishName)}</span><strong>{entry.quantity}</strong></div>)}</div><div className="week-review-actions"><StatusChip tone={day.cpuReview?.status === "signed" ? "good" : "warning"}>{day.cpuReview?.status === "signed" ? "Allergens signed" : "Needs allergen review"}</StatusChip><SiteMenuControls day={day} site={site} onGenerated={onGenerated} /></div></section>)}</div></>; }

function AllergenState({ value }: { value?: string }) { if (value === "contains") return <span className="matrix-state matrix-state-contains" aria-label="Contains" />; if (value === "may_contain") return <span className="matrix-state matrix-state-may" aria-label="May contain">MC</span>; if (value === "unrecorded") return <span className="matrix-state matrix-state-may" aria-label="Unknown">?</span>; return <span className="matrix-state matrix-state-clear" aria-label="No declaration" />; }
function AllergenView({ days }: { days: ProjectedDay[] }) { const signedDays = days.filter(day => day.cpuReview?.status === "signed"); return <div className="ops-allergen-view"><header className="ops-page-heading"><p className="ops-eyebrow">CPU-approved allergen information</p><h1>Signed Allergen Matrix</h1><p>{signedDays.length ? "This matrix is locked to the CPU sign-off." : "The allergen matrix will appear here after CPU has recorded both required signatures."}</p></header>{signedDays.map(day => <section className="ops-panel" key={day.publicationDayId}><div className="ops-panel-heading"><div><p className="ops-eyebrow">{day.dayName}</p><h2>{formatDate(day.date, { day: "numeric", month: "long", year: "numeric" })}</h2></div></div><div className="ops-table-wrap"><table className="ops-table ops-allergen-table"><thead><tr><th>Dish</th>{CANONICAL_ALLERGEN_COLUMNS.map(([, label]) => <th key={label}>{label}</th>)}</tr></thead><tbody>{day.entries.map((entry, index) => <tr key={`${entry.sourceEntryId}-${index}`}><th>{titleCase(entry.dishName)}<small>{entry.slot}</small></th>{CANONICAL_ALLERGEN_COLUMNS.map(([key]) => <td key={key}><AllergenState value={entry.allergens[key]} /></td>)}</tr>)}</tbody></table></div></section>)}</div>; }

export default function Page() {
  const [dashboard, setDashboard] = useState<Dashboard>(); const [selectedSiteId, setSelectedSiteId] = useState(""); const [selectedWeekCommencing, setSelectedWeekCommencing] = useState(""); const [selectedDayDate, setSelectedDayDate] = useState(""); const [view, setView] = useState<View>("today"); const [error, setError] = useState("");
  const load = (oplocId?: string) => fetch(`/api/delivered-in${oplocId ? `?oplocId=${encodeURIComponent(oplocId)}` : ""}`, { cache: "no-store" }).then(async response => { const body = await response.json(); if (!response.ok) throw new Error("Unavailable"); setDashboard(body); const nextSite = body.selectedOplocId || oplocId || body.sites[0]?.oplocId || ""; setSelectedSiteId(nextSite); void cacheDeliveredInDays(body.access?.email || "", nextSite, body.weeks.flatMap((week: ProjectedWeek) => week.days)); void evictWithdrawnDeliveredInDays(body.access?.email || "", nextSite, body.withdrawnServiceDates || []); setError(""); }).catch(() => setError("This dashboard is temporarily unavailable. Please check back shortly."));
  useEffect(() => { const params = new URLSearchParams(window.location.search); const requestedSite = params.get("oplocId") || undefined; const requestedView = params.get("view") as View | null; if (requestedView === "today" || requestedView === "week" || requestedView === "allergens") setView(requestedView); if (params.get("week")) setSelectedWeekCommencing(params.get("week")!); if (params.get("day")) setSelectedDayDate(params.get("day")!); void load(requestedSite); }, []);
  useEffect(() => { if (!dashboard?.weeks.length) return; const fallback = currentWeek(dashboard.weeks); if (!selectedWeekCommencing || !dashboard.weeks.some(candidate => candidate.weekCommencing === selectedWeekCommencing)) setSelectedWeekCommencing(fallback?.weekCommencing || dashboard.weeks[0].weekCommencing); }, [dashboard, selectedWeekCommencing]);
  useEffect(() => { if (!selectedSiteId) return; const params = new URLSearchParams(window.location.search); params.set("oplocId", selectedSiteId); window.history.replaceState(null, "", `/?${params.toString()}`); }, [selectedSiteId]);
  const selectedSite = dashboard?.sites.find(site => site.oplocId === selectedSiteId); const week = dashboard?.weeks.find(candidate => candidate.weekCommencing === selectedWeekCommencing) || currentWeek(dashboard?.weeks || []); const selectedDay = week?.days.find(day => day.date === selectedDayDate) || week?.days.find(day => day.entries.length) || week?.days[0]; const weekDays = useMemo(() => week?.days.slice(0, 5).filter((day): day is ProjectedDay => Boolean(day && day.entries.length)) || [], [week]);
  const updatePeriodUrl = (nextWeek: string, nextDay?: string) => { const params = new URLSearchParams(window.location.search); params.set("week", nextWeek); if (nextDay) params.set("day", nextDay); else params.delete("day"); if (selectedSiteId) params.set("oplocId", selectedSiteId); if (view !== "today") params.set("view", view); window.history.replaceState(null, "", `/?${params.toString()}`); };
  const selectWeek = (nextWeek: string) => { const next = dashboard?.weeks.find(candidate => candidate.weekCommencing === nextWeek); const nextDay = next?.days.find(day => day.entries.length)?.date || next?.days[0]?.date || ""; setSelectedWeekCommencing(nextWeek); setSelectedDayDate(nextDay); updatePeriodUrl(nextWeek, nextDay); };
  const selectDay = (nextDay: string) => { setSelectedDayDate(nextDay); if (week) updatePeriodUrl(week.weekCommencing, nextDay); };
  const navigate = (next: View) => { setView(next); const params = new URLSearchParams(window.location.search); if (next === "today") params.delete("view"); else params.set("view", next); if (selectedSiteId) params.set("oplocId", selectedSiteId); if (week) params.set("week", week.weekCommencing); if (selectedDay?.date) params.set("day", selectedDay.date); window.history.replaceState(null, "", `/?${params.toString()}`); };
  const refresh = () => { if (selectedSiteId) void load(selectedSiteId); };
  return <main className="app-shell"><header className="compact-header"><div className="brand-lockup"><strong>FIKA OS</strong><span className="brand-divider" /><b>Delivered-In</b></div><div className="header-actions">{dashboard && dashboard.sites.length > 1 && selectedSite && <label className="site-picker"><span>Site</span><select value={selectedSiteId} onChange={event => { setSelectedSiteId(event.target.value); void load(event.target.value); }}>{dashboard.sites.map(site => <option key={site.oplocId} value={site.oplocId}>{site.label}</option>)}</select></label>}<span className="avatar">OS</span></div></header>{error && <section className="error-banner" role="alert"><strong>Something went wrong</strong><span>{error}</span></section>}{dashboard?.access.oplocIds.length === 0 && <section className="ops-empty"><p className="ops-eyebrow">Access required</p><h2>No Delivered-In site access</h2><p>Your authenticated identity is not assigned to an authorised OPLOC.</p></section>}{dashboard && dashboard.access.oplocIds.length > 0 && <>{week && <section className="period-controls" aria-label="Menu period selector"><label><span>Week commencing</span><select value={week.weekCommencing} onChange={event => selectWeek(event.target.value)}>{dashboard.weeks.map(candidate => <option key={candidate.weekCommencing} value={candidate.weekCommencing}>{formatDate(candidate.weekCommencing, { day: "numeric", month: "short", year: "numeric" })} – {formatDate(candidate.weekEnding, { day: "numeric", month: "short", year: "numeric" })}</option>)}</select></label><div className="day-selector" role="group" aria-label="Service day">{week.days.slice(0, 5).map(day => <button type="button" key={day.date} className={selectedDay?.date === day.date ? "active" : ""} onClick={() => selectDay(day.date)}>{day.dayName.slice(0, 3)} <strong>{formatDate(day.date, { day: "numeric" })}</strong></button>)}</div>{selectedSite?.services?.grabAndGo && <a className="ops-button grab-and-go-link" href="/grab-and-go">Grab &amp; Go ordering</a>}</section>}<section className="content">{selectedSite && view === "today" && <TodayView site={selectedSite} day={selectedDay} onGenerated={refresh} />}{selectedSite && view === "week" && <WeekView week={week} site={selectedSite} days={weekDays} onGenerated={refresh} />}{selectedSite && view === "allergens" && <AllergenView days={weekDays} />}</section></>}{!dashboard && !error && <section className="ops-empty"><p>Loading Delivered-In dashboard…</p></section>}</main>;
}
