"use client";

import { useMemo, useState } from "react";
import type { ProductionOrder } from "@hub/lib/production-domain";
import { CANONICAL_ALLERGEN_COLUMNS, type OperationalAllergenState } from "../../../shared/allergen-contract";
import { buildDeliveredInDishRows, deliveredInTotals, type DeliveredInDishRow } from "../../lib/production-day";
import { cpuAttentionLabel, cpuLifecycle, cpuLifecycleLabels, cpuRequiredTime } from "../../lib/production-presentation";
import "./delivered-in-production-detail.css";
import "./delivered-in-allergen-matrix.css";

function dateLabel(order: ProductionOrder) { return new Date(`${order.serviceDate || order.requiredBy.slice(0, 10)}T12:00:00`).toLocaleDateString("en-GB", { weekday: "long", day: "numeric", month: "long" }); }
function cellState(row: DeliveredInDishRow, key: string): OperationalAllergenState | "none" { const state = row.snapshot?.allergens[key]; return state === "contains" || state === "may_contain" ? state : row.snapshot ? "clear" : "none"; }

export default function DeliveredInProductionDetail({ order, orders, close, onSaved }: { order: ProductionOrder; orders: ProductionOrder[]; close: () => void; onSaved: () => Promise<void> }) {
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [discrepancy, setDiscrepancy] = useState("");
  const totals = deliveredInTotals(orders); const rows = useMemo(() => buildDeliveredInDishRows(orders), [orders]); const lifecycle = cpuLifecycle(order); const allReviewed = rows.length > 0 && rows.every(row => row.reviewed);
  const attention = orders.find(item => cpuAttentionLabel(item));
  const acknowledge = async () => {
    setBusy(true); setMessage("");
    const responses = await Promise.all(orders.map(item => fetch("/api/production", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "update-lines", canonicalId: item.canonicalId, expectedVersion: item.version, lines: item.lines.map(line => ({ canonicalId: line.canonicalId, productionQuantity: line.productionQuantity, productionUnit: line.productionUnit, dietaries: line.dietaries, allergenEvidenceStatus: line.approvedAllergenSnapshot ? "confirmed" : line.allergenEvidenceStatus })) }) })));
    const bodies = await Promise.all(responses.map(response => response.json())); const failed = bodies.find((body, index) => !responses[index].ok);
    if (failed) setMessage(failed.error?.message || "The approved allergen snapshot could not be acknowledged."); else { setMessage("Approved allergen data acknowledged for CPU production."); await onSaved(); } setBusy(false);
  };
  const report = async () => {
    if (!discrepancy.trim()) return; setBusy(true); setMessage("");
    const response = await fetch("/api/production", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "report-allergen-discrepancy", canonicalId: order.canonicalId, expectedVersion: order.version, note: discrepancy }) }); const body = await response.json();
    if (!response.ok) setMessage(body.error?.message || "The discrepancy could not be reported."); else { setDiscrepancy(""); setMessage("Discrepancy reported. The approved allergen snapshot remains unchanged."); await onSaved(); } setBusy(false);
  };
  return <aside className="delivered-in-detail" role="dialog" aria-modal="true" aria-label="Delivered-In production detail">
    <header><div><small>Delivered-In lunch</small><h2>{dateLabel(order)}</h2><p>{totals.portions.toLocaleString()} portions · {totals.dishes} dishes · {totals.destinations} destinations</p></div><button type="button" onClick={close} aria-label="Close production detail">×</button></header>
    <div className="delivered-in-detail-status"><span>{cpuLifecycleLabels[lifecycle]}</span>{attention && <strong>{cpuAttentionLabel(attention)}</strong>}<small>Required ready: {cpuRequiredTime(order)}</small></div>
    <nav className="delivered-in-tabs" aria-label="Delivered-In detail sections"><a href="#delivered-production">Production</a><a href="#delivered-allergens">Allergens</a><a href="#delivered-splits">Destination splits</a><a href="#delivered-notes">Notes</a></nav>
    <section id="delivered-production"><h3>Production</h3><p className="delivered-in-muted">One consolidated production job from the published Menu Planning day. Quantities below are totals to make before packing.</p><div className="delivered-in-lines">{rows.map(row => <div key={row.key}><strong>{row.name}</strong><span>{row.quantity.toLocaleString()} portions</span></div>)}</div></section>
    <section id="delivered-allergens"><div className="delivered-section-heading"><div><h3>Approved allergen data</h3><p>Published by Menu Planning · {rows.filter(row => row.snapshot).length}/{rows.length} dishes approved · {allReviewed ? "CPU reviewed" : "CPU review pending"}</p></div><button type="button" className="delivered-in-ack" disabled={busy || !rows.some(row => row.snapshot)} onClick={() => void acknowledge()}>{allReviewed ? "Reviewed" : "Acknowledge approved data"}</button></div><div className="delivered-in-allergen-legend" aria-label="Allergen matrix legend"><span><i className="allergen-state allergen-state--contains"/>Contains</span><span><i className="allergen-state allergen-state--may_contain"/>May contain</span><span><i className="allergen-state allergen-state--clear"/>No declaration</span><span><i className="allergen-state allergen-state--none"/>Not recorded</span></div><div className="delivered-in-allergen-table-wrap"><table className="delivered-in-allergen-table delivered-in-allergen-matrix"><thead><tr><th>Dish</th>{CANONICAL_ALLERGEN_COLUMNS.map(([key, label]) => <th key={key}>{label}</th>)}<th>Evidence</th><th>CPU review</th></tr></thead><tbody>{rows.map(row => <tr key={row.key}><th>{row.name}</th>{CANONICAL_ALLERGEN_COLUMNS.map(([key]) => { const state = cellState(row, key); return <td key={key} className={`allergen-state allergen-state--${state}`} aria-label={`${row.name}, ${key}: ${state === "may_contain" ? "May contain" : state === "contains" ? "Contains" : state === "none" ? "Not recorded" : "No declaration"}`}>{state === "contains" ? "✓" : state === "may_contain" ? "MC" : state === "none" ? "?" : "—"}</td>; })}<td>{row.snapshot ? "Approved" : "Not recorded"}</td><td>{row.reviewed ? "Reviewed" : "Review"}</td></tr>)}</tbody></table></div><div className="delivered-in-discrepancy"><label htmlFor="allergen-discrepancy">Report allergen discrepancy</label><textarea id="allergen-discrepancy" value={discrepancy} onChange={event => setDiscrepancy(event.target.value)} placeholder="Describe the discrepancy for resolution; the approved snapshot will be retained." /><button type="button" disabled={busy || discrepancy.trim().length < 3} onClick={() => void report()}>Report discrepancy</button></div></section>
    <section id="delivered-splits"><h3>Destination splits</h3><p className="delivered-in-muted">Complete allocation across the destinations in this publication.</p><div className="delivered-in-allocation-table-wrap"><table className="delivered-in-allocation-table"><thead><tr><th>Dish</th><th>Total</th><th>Destination allocations</th></tr></thead><tbody>{rows.map(row => <tr key={row.key}><th>{row.name}</th><td>{row.quantity.toLocaleString()}</td><td>{row.destinations.map(item => `${item.label} ${item.quantity}`).join(" · ")}</td></tr>)}</tbody></table></div></section>
    <section id="delivered-notes"><h3>Notes</h3><p className="delivered-in-muted">{[...new Set(orders.map(item => item.operationalNotes).filter(Boolean))].join(" · ") || "No operational notes recorded."}</p></section>
    <details className="delivered-in-technical"><summary>Details / technical traceability</summary><dl><dt>Source publication day</dt><dd>{order.sourcePublicationDayId || order.sourceEntityId || "Not supplied"}</dd><dt>Source versions</dt><dd>{[...new Set(orders.map(item => item.sourceVersion).filter(value => value !== undefined))].join(", ") || "Not supplied"}</dd><dt>Underlying Production Orders</dt><dd>{orders.map(item => item.canonicalId).join(" · ")}</dd><dt>Destination OPLOCs</dt><dd>{orders.map(item => item.destinationOplocId || "Not supplied").join(" · ")}</dd><dt>Source content hashes</dt><dd>{[...new Set(orders.map(item => item.sourceContentHash).filter(Boolean))].join(" · ") || "Not supplied"}</dd></dl></details>
    {message && <p className="delivered-in-message" role="status">{message}</p>}<footer><button type="button" onClick={close}>Close</button></footer>
  </aside>;
}
