"use client";

import { useEffect, useMemo, useState } from "react";
import type { GrabAndGoProduction } from "../../lib/grab-and-go-read";
import "./production-calendar.css";
import "./grab-and-go-production.css";

type Response = { deliveryDate: string; dates: string[]; production: GrabAndGoProduction };
type ProductionMode = "totals" | "destination";
const dateLabel = (date: string) => new Date(`${date}T00:00:00Z`).toLocaleDateString("en-GB", { weekday: "long", day: "numeric", month: "long", year: "numeric", timeZone: "UTC" });
const categoryLabel = (category: string) => category === "grab_250ml" ? "Grab n Go · 250ml" : "Stacking Salads · 750ml";

export default function GrabAndGoProductionView() {
  const [data, setData] = useState<Response>(); const [selectedDate, setSelectedDate] = useState(""); const [mode, setMode] = useState<ProductionMode>("totals"); const [error, setError] = useState("");
  const load = async (date?: string) => { try { const response = await fetch(`/api/grab-and-go${date ? `?deliveryDate=${encodeURIComponent(date)}` : ""}`, { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message || "Grab & Go production could not be loaded."); setData(body); setSelectedDate(body.deliveryDate); setError(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Grab & Go production could not be loaded."); } };
  useEffect(() => { void load(); }, []);
  const currentIndex = data?.dates.indexOf(selectedDate) ?? -1; const previous = data?.dates[currentIndex - 1]; const next = data?.dates[currentIndex + 1]; const totalsByCategory = useMemo(() => data?.production.totals.reduce<Record<string, typeof data.production.totals>>((groups, item) => { (groups[item.category] ||= []).push(item); return groups; }, {}) || {}, [data]);
  if (!data) return <section className="grab-production-view"><p>Loading Grab &amp; Go production…</p></section>;
  const totalItems = data.production.totals.reduce((sum, item) => sum + item.quantity, 0);
  const renderRows = (items: GrabAndGoProduction["totals"]) => items.map(item => <div className="grab-production-total-row" key={item.productId}><strong>{item.quantity}</strong><span>{item.productName}</span><small>{item.category === "grab_250ml" ? "250ml" : "750ml"}</small></div>);
  return <section className="production-calendar grab-production-view" aria-label="Grab and Go production"><header className="calendar-header grab-production-header"><div><small>CPU production · Read only</small><h2>Grab &amp; Go</h2><p>Production totals and destination packing for submitted site orders.</p></div><nav className="calendar-nav grab-production-nav"><button type="button" onClick={() => previous && void load(previous)} disabled={!previous} aria-label="Previous delivery date">←</button><strong>{dateLabel(selectedDate)}</strong><button type="button" onClick={() => next && void load(next)} disabled={!next} aria-label="Next delivery date">→</button></nav></header>{error && <p className="grab-production-error" role="alert">{error}</p>}{!data.dates.length ? <div className="grab-production-empty">No submitted Grab &amp; Go orders are available.</div> : <><div className="grab-production-date-picker"><label>Delivery date<select value={selectedDate} onChange={event => void load(event.target.value)}>{data.dates.map(date => <option key={date} value={date}>{dateLabel(date)}</option>)}</select></label></div><div className="grab-production-mode-switch" role="tablist" aria-label="Grab and Go production mode"><button type="button" role="tab" aria-selected={mode === "totals"} className={mode === "totals" ? "selected" : ""} onClick={() => setMode("totals")}>Production totals</button><button type="button" role="tab" aria-selected={mode === "destination"} className={mode === "destination" ? "selected" : ""} onClick={() => setMode("destination")}>By destination</button></div><div className="grab-production-summary"><strong>{totalItems} items</strong><span>{data.production.totals.length} products</span><span>{data.production.destinations.length} destination{data.production.destinations.length === 1 ? "" : "s"}</span></div>{mode === "totals" ? <section className="grab-production-panel"><header><h3>Production totals</h3></header>{Object.entries(totalsByCategory).map(([category, items]) => <div className="grab-production-category" key={category}><h4>{categoryLabel(category)}</h4>{renderRows(items)}</div>)}</section> : <section className="grab-production-panel"><header><h3>By destination</h3></header><div className="grab-destination-cards">{data.production.destinations.map(destination => <article className="grab-destination-card" key={destination.oplocId}><header><strong>{destination.siteName}</strong><span>{destination.totalItems} items</span></header>{destination.items.map(item => <div className="grab-destination-row" key={item.productId}><b>{item.quantity}</b><span>{item.productName}<small>{item.category === "grab_250ml" ? "250ml" : "750ml"}</small></span></div>)}</article>)}</div></section>}</>}</section>;
}
