"use client";
import { useEffect, useState } from "react";
type PublishedDay = { publicationDayId: string; sourceDayId: string; date: string; dayName: string; version: number; status: "published" | "superseded"; contentHash: string; entries: Array<{ sourceEntryId: string; slot: string; dishName: string; portions: number; allocations: Array<{ destinationId?: string; destinationLabel: string; quantity: number }>; allergens: Record<string, string>; mayContainNotes?: string }>; allergenSignoff: { productionChef?: { printedName: string; signedAt: string }; headChefSiteManager?: { printedName: string; signedAt: string }; printedName?: string; signedAt?: string } };
type Publication = { publicationId: string; sourceWeekId: string; weekCommencing: string; weekEnding: string; days: PublishedDay[] };
const addDays = (iso: string, amount: number) => { const date = new Date(`${iso}T00:00:00Z`); date.setUTCDate(date.getUTCDate() + amount); return date.toISOString().slice(0, 10); };
const currentDays = (publication?: Publication) => { const latest = new Map<string, PublishedDay>(); for (const day of publication?.days || []) if (day.status === "published") latest.set(day.sourceDayId, day); return latest; };
export default function PublishedMenuView() {
  const [publications, setPublications] = useState<Publication[]>([]); const [selected, setSelected] = useState<Publication>(); const [dayDate, setDayDate] = useState(""); const [error, setError] = useState("");
  useEffect(() => { void fetch("/api/menu-publications", { cache: "no-store" }).then(async response => { const body = await response.json(); if (!response.ok) throw new Error(body.error?.message || "Published menus could not be loaded."); const next = body.publications || []; setPublications(next); if (next[0]) { setSelected(next[0]); setDayDate([...currentDays(next[0]).values()][0]?.date || ""); } }).catch(cause => setError(cause instanceof Error ? cause.message : "Published menus could not be loaded.")); }, []);
  const days = currentDays(selected); const day = [...days.values()].find(value => value.date === dayDate);
  const printMatrix = () => { if (!selected || !day) return; void fetch(`/api/menu-publications?publicationId=${encodeURIComponent(selected.publicationId)}&format=matrix&date=${encodeURIComponent(day.date)}`, { cache: "no-store" }).then(response => response.text()).then(html => { const popup = window.open("", "_blank", "noopener,noreferrer"); if (popup) { popup.document.write(html); popup.document.close(); } }); };
  return <section className="cpu-published-menus"><header><div><p>HEAD CHEF · READ-ONLY</p><h2>Delivered-In Menus</h2><p>Published Menu Planning snapshots. Corrections must originate in Menu Planning.</p></div><button type="button" onClick={printMatrix} disabled={!day}>View / print signed matrix</button></header>{error && <p role="alert">{error}</p>}{!publications.length && !error && <p>No published delivered-in menus are available.</p>}{publications.length > 0 && <div className="cpu-published-layout"><nav aria-label="Published weeks">{publications.map(publication => <button type="button" key={publication.publicationId} className={selected?.publicationId === publication.publicationId ? "selected" : ""} onClick={() => { setSelected(publication); setDayDate([...currentDays(publication).values()][0]?.date || ""); }}>WC {publication.weekCommencing}<small>Published Menu Planning snapshot</small></button>)}</nav>{selected && <article><div className="cpu-published-day-nav">{Array.from({ length: 5 }, (_, index) => { const date = addDays(selected.weekCommencing, index); const published = days.get(date); return <button type="button" key={date} disabled={!published} className={day?.date === date ? "selected" : ""} onClick={() => published && setDayDate(date)}>{published?.dayName || new Date(`${date}T00:00:00Z`).toLocaleDateString("en-GB", { weekday: "long" })} {published ? `Published v${published.version} ✓` : "Not published"}</button>; })}</div>{day ? <><p>{day.entries.length} dishes · {day.entries.reduce((sum, entry) => sum + entry.portions, 0)} portions · signed by {day.allergenSignoff.productionChef?.printedName || day.allergenSignoff.printedName || "—"} and {day.allergenSignoff.headChefSiteManager?.printedName || day.allergenSignoff.printedName || "—"} on {new Date(day.date).toLocaleDateString("en-GB")}</p><table><thead><tr><th>Slot</th><th>Dish</th><th>Destinations</th><th>Portions</th><th>Allergens</th><th>May-contain notes</th></tr></thead><tbody>{day.entries.map(entry => <tr key={entry.sourceEntryId}><td>{entry.slot}</td><td>{entry.dishName}</td><td>{entry.allocations.map(allocation => `${allocation.destinationLabel} ${allocation.quantity}`).join(" · ")}</td><td>{entry.portions}</td><td>{Object.entries(entry.allergens).filter(([, state]) => state !== "clear").map(([key, state]) => `${key} · ${state}`).join(", ") || "No declared allergens"}</td><td>{entry.mayContainNotes || "—"}</td></tr>)}</tbody></table></> : <p>Select a published day to view its immutable menu snapshot.</p>}</article>}</div>}</section>;
}
