import { NextRequest, NextResponse } from "next/server";
import { requireActor } from "@/lib/auth";
import { assertPermission } from "@/lib/authmod";
import { formatAddress } from "@/lib/address";
import { db } from "@/lib/firebase-admin";
import { isActiveCanonicalOploc } from "@/lib/canonical-oplocs";
import { cacheManifestRef } from "@/lib/integration-cache-server";
import { getCachedOplocResponse } from "@/lib/oploc-response-cache";
import { recordDataAccess, withDataTrace } from "@fika/server-shared/data-source-meter-server";
async function handleGet(request: NextRequest) {
  try { let actor; try { actor = await requireActor(request); } catch (error) { if (process.env.NODE_ENV === "production" || (error as { status?: number }).status !== 401) throw error; actor = { uid: "local-development", role: "integration-admin" } as never; } assertPermission(actor, "canonical.view"); const manifestSnapshot = await cacheManifestRef("oplocs").get(); recordDataAccess({ app: "integration-hub", operation: "oploc.api.cache-manifest", source: "FIRESTORE", documents: manifestSnapshot.exists ? 1 : 0 }); const manifestVersion = manifestSnapshot.exists ? Number(manifestSnapshot.data()?.version || 0) : 0; const identityScope = `${actor.uid}:${actor.role}`; const response = await getCachedOplocResponse(identityScope, manifestVersion, async () => { const oplocSnapshot = await db.collection("integrationHubCanonical").where("entityType", "==", "OPLOC").get(); recordDataAccess({ app: "integration-hub", operation: "oploc.api.list", source: "FIRESTORE", documents: oplocSnapshot.size }); const records = oplocSnapshot.docs.map(doc => doc.data() as { entityType?: string; canonicalId?: string; lifecycleStatus?: string; publicationStatus?: string; record?: Record<string, unknown> }).filter(isActiveCanonicalOploc); const addressIds = [...new Set(records.map(value => String(value.record?.addressReference || "")).filter(Boolean))]; const addresses = new Map<string, Record<string, unknown>>(); for (let index = 0; index < addressIds.length; index += 30) { const snapshot = await db.collection("integrationHubCanonical").where("entityType", "==", "Address").where("canonicalId", "in", addressIds.slice(index, index + 30)).get(); recordDataAccess({ app: "integration-hub", operation: "oploc.api.addresses", source: "FIRESTORE", documents: snapshot.size }); for (const document of snapshot.docs) { const value = document.data() as { canonicalId?: string; record?: Record<string, unknown> }; if (value.canonicalId) addresses.set(value.canonicalId, value.record || {}); } } const oplocs = records.map(value => { const record = value.record || {}; const address = record.addressReference ? formatAddress(addresses.get(String(record.addressReference)) || {}) : ""; return { canonicalId: value.canonicalId!, label: String(record.approvedName || value.canonicalId!).trim(), ...(address ? { address } : {}) }; }); return { oplocs }; }); return NextResponse.json(response, { headers: { "Cache-Control": "no-store, max-age=0" } }); }
  catch (error) { return NextResponse.json({ error: { message: error instanceof Error ? error.message : "OPLOC authority is unavailable." } }, { status: Number((error as { status?: number }).status) || 503 }); }
}
export async function GET(request: NextRequest) { return withDataTrace({ app: "integration-hub", action: "integration-hub.oploc.load", path: request.nextUrl.pathname, requestId: request.headers.get("x-request-id") || undefined }, () => handleGet(request)); }
