import { NextRequest, NextResponse } from "next/server";
import { requireActor } from "@/lib/auth";
import { assertPermission } from "@/lib/authmod";
import { formatAddress } from "@/lib/address";
import { db } from "@/lib/firebase-admin";
import { isActiveCanonicalOploc } from "@/lib/canonical-oplocs";
export async function GET(request: NextRequest) {
  try { let actor; try { actor = await requireActor(request); } catch (error) { if (process.env.NODE_ENV === "production" || (error as { status?: number }).status !== 401) throw error; actor = { role: "integration-admin" } as never; } assertPermission(actor, "canonical.view"); const oplocSnapshot = await db.collection("integrationHubCanonical").where("entityType", "==", "OPLOC").get(); const records = oplocSnapshot.docs.map(doc => doc.data() as { entityType?: string; canonicalId?: string; lifecycleStatus?: string; publicationStatus?: string; record?: Record<string, unknown> }).filter(isActiveCanonicalOploc); const addressIds = [...new Set(records.map(value => String(value.record?.addressReference || "")).filter(Boolean))]; const addresses = new Map<string, Record<string, unknown>>(); for (let index = 0; index < addressIds.length; index += 30) { const snapshot = await db.collection("integrationHubCanonical").where("entityType", "==", "Address").where("canonicalId", "in", addressIds.slice(index, index + 30)).get(); for (const document of snapshot.docs) { const value = document.data() as { canonicalId?: string; record?: Record<string, unknown> }; if (value.canonicalId) addresses.set(value.canonicalId, value.record || {}); } } const oplocs = records.map(value => { const record = value.record || {}; const address = record.addressReference ? formatAddress(addresses.get(String(record.addressReference)) || {}) : ""; return { canonicalId: value.canonicalId!, label: String(record.approvedName || value.canonicalId!).trim(), ...(address ? { address } : {}) }; }); return NextResponse.json({ oplocs }, { headers: { "Cache-Control": "no-store, max-age=0" } }); }
  catch (error) { return NextResponse.json({ error: { message: error instanceof Error ? error.message : "OPLOC authority is unavailable." } }, { status: Number((error as { status?: number }).status) || 503 }); }
}
