import { NextRequest, NextResponse } from "next/server";
import { requireActor } from "@/lib/auth";
import { assertPermission } from "@/lib/authmod";
import { db } from "@/lib/firebase-admin";
import { formatAddress } from "@/lib/address";
export async function GET(request: NextRequest) {
  try { let actor; try { actor = await requireActor(request); } catch (error) { if (process.env.NODE_ENV === "production" || (error as { status?: number }).status !== 401) throw error; actor = { role: "integration-admin" } as never; } assertPermission(actor, "canonical.view"); const snapshot = await db.collection("integrationHubCanonical").get(); const records = snapshot.docs.map(doc => doc.data() as { entityType?: string; canonicalId?: string; lifecycleStatus?: string; publicationStatus?: string; record?: Record<string, unknown> }); const addresses = new Map(records.filter(value => value.entityType === "Address" && value.canonicalId).map(value => [value.canonicalId!, value.record || {}])); const oplocs = records.filter(value => value.entityType === "OPLOC" && value.canonicalId && value.lifecycleStatus !== "archived" && value.publicationStatus === "published" && value.record?.lifecycleState === "active").map(value => { const record = value.record || {}; const address = record.addressReference ? formatAddress(addresses.get(String(record.addressReference)) || {}) : ""; return { canonicalId: value.canonicalId!, label: String(record.approvedName || value.canonicalId!).trim(), ...(address ? { address } : {}) }; }); return NextResponse.json({ oplocs }, { headers: { "Cache-Control": "no-store, max-age=0" } }); }
  catch (error) { return NextResponse.json({ error: { message: error instanceof Error ? error.message : "OPLOC authority is unavailable." } }, { status: Number((error as { status?: number }).status) || 503 }); }
}
