import { NextRequest, NextResponse } from "next/server";
import { fetchRequirements } from "@/lib/upstream";
import { listState, saveMovement, saveRun, saveStop } from "@/lib/store";
import { combineStop, orderedTransferStops } from "@/lib/planning";
import type { DeliveryRun, MovementRequest } from "@/lib/types";

export async function GET(request:NextRequest) { try { const date = request.nextUrl.searchParams.get("serviceDate") || undefined; const [requirements,state] = await Promise.all([fetchRequirements(date), listState()]); return NextResponse.json({...state, requirements, fetchedAt:new Date().toISOString()}); } catch (error) { return NextResponse.json({error:error instanceof Error ? error.message : "Logistics could not be loaded."},{status:502}); } }
export async function POST(request:NextRequest) { try { const body = await request.json() as { action:string; by?:string; run?:DeliveryRun; movement?:MovementRequest; requirement?:any; locationLabel?:string; stop?:any; runId?:string; stopIds?:string[] }; const by = body.by || "Franco"; const now = new Date().toISOString();
  if (body.action === "create-run") { const run:DeliveryRun = body.run || {canonicalId:`run:${Date.now()}`,serviceDate:new Date().toISOString().slice(0,10),status:"draft",orderedStopIds:[],version:1,createdAt:now,updatedAt:now,audit:[]}; return NextResponse.json(await saveRun({...run,createdAt:run.createdAt||now,updatedAt:now,audit:[...(run.audit||[]),{action:"run-created",at:now,by,version:run.version||1}]})); }
  if (body.action === "save-movement" && body.movement) return NextResponse.json(await saveMovement(body.movement));
  if (body.action === "update-run" && body.run) { const state=await listState(); const current=state.runs.find(item=>item.canonicalId===body.run!.canonicalId); if (!current) throw new Error("Run not found."); return NextResponse.json(await saveRun({...current,driverId:body.run.driverId,driverLabel:body.run.driverLabel,vehicleLabel:body.run.vehicleLabel,version:current.version+1,updatedAt:now,audit:[...current.audit,{action:"run-updated",at:now,by,version:current.version+1}]})); }
  if (body.action === "assign" && body.runId && (body.requirement || body.movement)) { const state = await listState(); const run = state.runs.find(item=>item.canonicalId===body.runId); if (!run) throw new Error("Run not found."); let newStops=[] as Awaited<ReturnType<typeof combineStop>>[]; if (body.requirement) newStops=[combineStop(state.stops,{locationOplocId:body.requirement.destinationOplocId,locationLabel:body.requirement.destinationLabelSnapshot,requirement:body.requirement,runId:run.canonicalId,by})]; else if (body.movement!.type === "transfer") { const movement=body.movement!; newStops=[combineStop(state.stops,{locationOplocId:movement.fromOplocId || "unknown",locationLabel:movement.fromOplocId || "Collection",movement:{...movement,type:"collection"},runId:run.canonicalId,by}),combineStop(state.stops,{locationOplocId:movement.toOplocId || "unknown",locationLabel:movement.toOplocId || "Delivery",movement:{...movement,type:"delivery"},runId:run.canonicalId,by})]; } else newStops=[combineStop(state.stops,{locationOplocId:body.movement!.toOplocId || body.movement!.fromOplocId || "unknown",locationLabel:body.movement!.toOplocId || body.movement!.fromOplocId || "Movement location",movement:body.movement,runId:run.canonicalId,by})]; await Promise.all(newStops.map(saveStop)); return NextResponse.json(await saveRun({...run,orderedStopIds:Array.from(new Set([...run.orderedStopIds,...newStops.map(stop=>stop.canonicalId)])),status:run.status === "draft" ? "planned" : run.status,version:run.version+1,updatedAt:now,audit:[...run.audit,{action:"work-assigned",at:now,by,version:run.version+1}]})); }
  if (body.action === "update-stop" && body.stop) return NextResponse.json(await saveStop({...body.stop,updatedAt:now,version:body.stop.version+1,audit:[...(body.stop.audit||[]),{action:`stop-${body.stop.status}`,at:now,by,version:body.stop.version+1}]}));
  if (body.action === "reorder" && body.runId && Array.isArray(body.stopIds)) { const state = await listState(); const run=state.runs.find(item=>item.canonicalId===body.runId); if (!run) throw new Error("Run not found."); const saved=await saveRun({...run,orderedStopIds:body.stopIds,version:run.version+1,updatedAt:now,audit:[...run.audit,{action:"stops-reordered",at:now,by,version:run.version+1}]}); return NextResponse.json(saved); }
  return NextResponse.json({error:"Unknown Logistics action."},{status:400});
 } catch(error) { return NextResponse.json({error:error instanceof Error ? error.message : "Logistics action failed."},{status:400}); } }
