import { NextRequest, NextResponse } from "next/server";
import { fetchOplocs, fetchRequirements } from "@/lib/upstream";
import { listState, saveMovement, saveRun, saveStop } from "@/lib/store";
import { assignMovementStops, combineStop, orderedTransferStops } from "@/lib/planning";
import { operationalDate } from "@/lib/date";
import type { DeliveryRun, DeliveryStop, MovementRequest } from "@/lib/types";

function labelFor(oplocs: Awaited<ReturnType<typeof fetchOplocs>>, id: string) { const match = oplocs.find(oploc => oploc.id === id); if (!match) throw new Error(`OPLOC ${id} is not an active governed Integration Hub location.`); return match.label; }
export async function GET(request:NextRequest) { try { const requestedRunId = request.nextUrl.searchParams.get("runId") || undefined; const requestedDate = request.nextUrl.searchParams.get("serviceDate") || undefined; const cookie = request.headers.get("cookie") || undefined; const state = await listState(); const runDate = requestedRunId ? state.runs.find(run => run.canonicalId === requestedRunId)?.serviceDate : undefined; const date = requestedDate || runDate || operationalDate(); const [requirements,oplocs] = await Promise.all([fetchRequirements(date,cookie), fetchOplocs(cookie)]); return NextResponse.json({...state, requirements, oplocs, serviceDate:date, fetchedAt:new Date().toISOString()}); } catch (error) { return NextResponse.json({error:error instanceof Error ? error.message : "Logistics could not be loaded."},{status:502}); } }

export async function POST(request:NextRequest) { try { const body = await request.json() as { action:string; by?:string; run?:DeliveryRun; movement?:MovementRequest; requirement?:any; stop?:DeliveryStop; runId?:string; stopIds?:string[] }; const by = body.by || "Franco"; const now = new Date().toISOString();
  if (body.action === "create-run") { const run:DeliveryRun = body.run || {canonicalId:`run:${operationalDate()}:${Date.now()}`,serviceDate:operationalDate(),status:"draft",orderedStopIds:[],version:1,createdAt:now,updatedAt:now,audit:[]}; return NextResponse.json(await saveRun({...run,createdAt:run.createdAt||now,updatedAt:now,audit:[...(run.audit||[]),{action:"run-created",at:now,by,version:run.version||1}]})); }
  if (body.action === "save-movement" && body.movement) { const oplocs=await fetchOplocs(request.headers.get("cookie") || undefined); for (const id of [body.movement.fromOplocId,body.movement.toOplocId].filter(Boolean) as string[]) labelFor(oplocs,id); return NextResponse.json(await saveMovement(body.movement)); }
  if (body.action === "update-run" && body.run) { const state=await listState(); const current=state.runs.find(item=>item.canonicalId===body.run!.canonicalId); if (!current) throw new Error("Run not found."); return NextResponse.json(await saveRun({...current,driverId:body.run.driverId,driverLabel:body.run.driverLabel,vehicleLabel:body.run.vehicleLabel,version:current.version+1,updatedAt:now,audit:[...current.audit,{action:"run-updated",at:now,by,version:current.version+1}]})); }
  if (body.action === "assign" && body.runId && (body.requirement || body.movement)) { const [state,oplocs]=await Promise.all([listState(),fetchOplocs(request.headers.get("cookie") || undefined)]); const run=state.runs.find(item=>item.canonicalId===body.runId); if (!run) throw new Error("Run not found."); let newStops:DeliveryStop[]=[];
    if (body.requirement) newStops=[combineStop(state.stops,{locationOplocId:body.requirement.destinationOplocId,locationLabel:body.requirement.destinationLabelSnapshot,requirement:body.requirement,runId:run.canonicalId,by})];
    else { const movement=body.movement!; const ordered=assignMovementStops(state.stops,run.canonicalId,movement,{from:movement.fromOplocId?labelFor(oplocs,movement.fromOplocId):undefined,to:movement.toOplocId?labelFor(oplocs,movement.toOplocId):undefined},by); newStops=ordered; await Promise.all(ordered.map(saveStop)); const nextVersion=run.version+1; return NextResponse.json(await saveRun({...run,orderedStopIds:ordered.map(stop=>stop.canonicalId),status:run.status === "draft" ? "planned" : run.status,version:nextVersion,updatedAt:now,audit:[...run.audit,{action:"work-assigned",at:now,by,version:nextVersion}]})); }
    const byId=new Map(state.stops.filter(stop=>stop.runId===run.canonicalId).map(stop=>[stop.canonicalId,stop])); newStops.forEach(stop=>byId.set(stop.canonicalId,stop)); const ordered=[...byId.values()].sort((a,b)=>a.sequence-b.sequence).map((stop,index)=>({...stop,sequence:index+1})); await Promise.all(ordered.map(saveStop)); const nextVersion=run.version+1; return NextResponse.json(await saveRun({...run,orderedStopIds:ordered.map(stop=>stop.canonicalId),status:run.status === "draft" ? "planned" : run.status,version:nextVersion,updatedAt:now,audit:[...run.audit,{action:"work-assigned",at:now,by,version:nextVersion}]})); }
  if (body.action === "update-stop" && body.stop) { const next={...body.stop,movementRequestIds:body.stop.movementRequestIds || (body.stop.movementRequestId ? [body.stop.movementRequestId] : []),updatedAt:now,version:body.stop.version+1,audit:[...(body.stop.audit||[]),{action:`stop-${body.stop.status}`,at:now,by,version:body.stop.version+1}]}; return NextResponse.json(await saveStop(next)); }
  if (body.action === "reorder" && body.runId && Array.isArray(body.stopIds)) { const state=await listState(); const run=state.runs.find(item=>item.canonicalId===body.runId); if (!run) throw new Error("Run not found."); const selected=body.stopIds.map(id=>state.stops.find(stop=>stop.canonicalId===id)).filter(Boolean) as DeliveryStop[]; const ordered=orderedTransferStops(selected); await Promise.all(ordered.map(saveStop)); const nextVersion=run.version+1; return NextResponse.json(await saveRun({...run,orderedStopIds:ordered.map(stop=>stop.canonicalId),version:nextVersion,updatedAt:now,audit:[...run.audit,{action:"stops-reordered",at:now,by,version:nextVersion}]})); }
  return NextResponse.json({error:"Unknown Logistics action."},{status:400});
 } catch(error) { return NextResponse.json({error:error instanceof Error ? error.message : "Logistics action failed."},{status:400}); } }
